Soletta: src/modules/flow/am2315/am2315.c File Reference
am2315.c File Reference
#include <sol-i2c.h>
#include <sol-log.h>
#include <sol-mainloop.h>
#include <sol-vector.h>
#include <errno.h>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>
#include "am2315.h"
Data Structures
struct am2315
Macros
#define AM2315_BUFFER_LEN 8
#define AM2315_HUMIDITY_HIGH 0x00
#define AM2315_INTERVAL_BETWEEN_READINGS 2
#define AM2315_READ_LEN 4
#define AM2315_READ_REG 0x03
#define AM2315_WRITE_MSG_LEN 3
#define READING_SCALE 10.0
#define STEP_TIME 1
Functions
void am2315_close (struct am2315 *device)
void am2315_humidity_callback_set (struct am2315 *device, void(*cb)(float temperature, bool success, void *data), void *data)
struct am2315 * am2315_open (uint8_t bus, uint8_t slave)
void am2315_read_humidity (struct am2315 *device)
void am2315_read_temperature (struct am2315 *device)
void am2315_temperature_callback_set (struct am2315 *device, void(*cb)(float temperature, bool success, void *data), void *data)
Macro Definition Documentation
#define AM2315_BUFFER_LEN 8
#define AM2315_HUMIDITY_HIGH 0x00
#define AM2315_INTERVAL_BETWEEN_READINGS 2
#define AM2315_READ_LEN 4
#define AM2315_READ_REG 0x03
#define AM2315_WRITE_MSG_LEN 3
#define READING_SCALE 10.0
#define STEP_TIME 1
Function Documentation
void am2315_close (struct am2315 * device)
References am2315::i2c, am2315::i2c_pending, am2315::refcount, sol_i2c_close(), sol_i2c_pending_cancel(), SOL_PTR_VECTOR_FOREACH_IDX, sol_timeout_del(), and am2315::timer.
void am2315_humidity_callback_set (struct am2315 * device, void(*)(float temperature, bool success, void *data) cb, void * data)
References am2315::humidity_callback, and am2315::humidity_callback_data.
struct am2315* am2315_open (uint8_t bus, uint8_t slave)
References am2315::i2c, am2315::refcount, am2315::slave, sol_i2c_bus_get(), sol_i2c_close(), sol_i2c_open(), SOL_I2C_SPEED_10KBIT, sol_ptr_vector_append(), SOL_PTR_VECTOR_FOREACH_IDX, and SOL_WRN.
void am2315_read_humidity (struct am2315 * device)
References am2315::pending_humidity.
void am2315_read_temperature (struct am2315 * device)
References am2315::pending_temperature.
void am2315_temperature_callback_set (struct am2315 * device, void(*)(float temperature, bool success, void *data) cb, void * data)
References am2315::temperature_callback, and am2315::temperature_callback_data.