Soletta: src/modules/flow/am2315/am2315.h File Reference
am2315.h File Reference
Functions
void am2315_close (struct am2315 *device)
void am2315_humidity_callback_set (struct am2315 *device, void(*cb)(float humidity, bool success, void *data), void *data)
struct am2315 * am2315_open (uint8_t bus, uint8_t slave)
void am2315_read_humidity (struct am2315 *device)
void am2315_read_temperature (struct am2315 *device)
void am2315_temperature_callback_set (struct am2315 *device, void(*cb)(float temperature, bool success, void *data), void *data)
Function Documentation
void am2315_close (struct am2315 * device)
References am2315::i2c, am2315::i2c_pending, am2315::refcount, sol_i2c_close(), sol_i2c_pending_cancel(), SOL_PTR_VECTOR_FOREACH_IDX, sol_timeout_del(), and am2315::timer.
void am2315_humidity_callback_set (struct am2315 * device, void(*)(float humidity, bool success, void *data) cb, void * data)
struct am2315* am2315_open (uint8_t bus, uint8_t slave)
References am2315::i2c, am2315::refcount, am2315::slave, sol_i2c_bus_get(), sol_i2c_close(), sol_i2c_open(), SOL_I2C_SPEED_10KBIT, sol_ptr_vector_append(), SOL_PTR_VECTOR_FOREACH_IDX, and SOL_WRN.
void am2315_read_humidity (struct am2315 * device)
References am2315::pending_humidity.
void am2315_read_temperature (struct am2315 * device)
References am2315::pending_temperature.
void am2315_temperature_callback_set (struct am2315 * device, void(*)(float temperature, bool success, void *data) cb, void * data)
References am2315::temperature_callback, and am2315::temperature_callback_data.