Soletta: src/modules/flow/test/blob-validator.c File Reference
blob-validator.c File Reference
#include <errno.h>
#include <string.h>
#include "sol-flow.h"
#include "sol-log-internal.h"
#include "sol-mainloop.h"
#include "sol-util.h"
#include "blob-validator.h"
#include "sol-flow/test.h"
Functions
void blob_validator_close (struct sol_flow_node *node, void *data)
int blob_validator_open (struct sol_flow_node *node, void *data, const struct sol_flow_node_options *options)
int blob_validator_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
Function Documentation
void blob_validator_close (struct sol_flow_node * node, void * data)
References blob_validator_data::expected, and sol_blob::mem.
int blob_validator_open (struct sol_flow_node * node, void * data, const struct sol_flow_node_options * options)
References blob_validator_data::done, blob_validator_data::expected, sol_blob::mem, sol_blob::size, SOL_ERR, and SOL_NULL_CHECK.
int blob_validator_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References blob_validator_data::done, blob_validator_data::expected, sol_blob::mem, sol_blob::size, sol_flow_packet_get_blob(), sol_flow_send_boolean_packet(), sol_flow_send_error_packet(), and SOL_INT_CHECK.