Soletta: src/modules/flow/test/boolean-validator.c File Reference
boolean-validator.c File Reference
#include <errno.h>
#include <string.h>
#include "sol-flow.h"
#include "sol-log-internal.h"
#include "sol-mainloop.h"
#include "sol-util.h"
#include "boolean-validator.h"
#include "sol-flow/test.h"
Functions
void boolean_validator_close (struct sol_flow_node *node, void *data)
int boolean_validator_open (struct sol_flow_node *node, void *data, const struct sol_flow_node_options *options)
int sequence_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
Function Documentation
void boolean_validator_close (struct sol_flow_node * node, void * data)
References boolean_validator_data::sequence.
int boolean_validator_open (struct sol_flow_node * node, void * data, const struct sol_flow_node_options * options)
References boolean_validator_data::done, boolean_validator_data::it, boolean_validator_data::sequence, SOL_ERR, and SOL_NULL_CHECK.
int sequence_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References boolean_validator_data::done, boolean_validator_data::it, sol_flow_packet_get_boolean(), sol_flow_send_boolean_packet(), sol_flow_send_error_packet(), and SOL_INT_CHECK.