Soletta: src/modules/flow/test/byte-validator.c File Reference
byte-validator.c File Reference
#include <ctype.h>
#include <errno.h>
#include <string.h>
#include "sol-flow.h"
#include "sol-log-internal.h"
#include "sol-mainloop.h"
#include "sol-util.h"
#include "byte-validator.h"
#include "sol-flow/test.h"
Functions
void byte_validator_close (struct sol_flow_node *node, void *data)
int byte_validator_open (struct sol_flow_node *node, void *data, const struct sol_flow_node_options *options)
int byte_validator_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
Function Documentation
void byte_validator_close (struct sol_flow_node * node, void * data)
References sol_vector_clear(), and byte_validator_data::values.
int byte_validator_open (struct sol_flow_node * node, void * data, const struct sol_flow_node_options * options)
References byte_validator_data::done, and SOL_ERR.
int byte_validator_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References byte_validator_data::done, sol_vector::len, byte_validator_data::next_index, sol_flow_packet_get_byte(), sol_flow_send_boolean_packet(), sol_flow_send_error_packet(), SOL_INT_CHECK, and byte_validator_data::values.