Soletta™ Framework: src/samples/http/client.c File Reference
client.c File Reference
HTTP Client sample.
#include <getopt.h>
#include <stdio.h>
#include <string.h>
#include "soletta.h"
#include "sol-http.h"
#include "sol-http-client.h"
Macros
#define CREATE_PARAM(_key, _filename, _value)
Functions
static int create_header_params (struct sol_http_params *params, const char *value)
static int create_post_data_params (struct sol_http_params *params, const char *query)
static int create_post_field_params (struct sol_http_params *params, const char *value)
static void response_cb (void *userdata, struct sol_http_client_connection *connection, struct sol_http_response *response)
static void shutdown (void)
SOL_MAIN_DEFAULT (startup, shutdown)
static void startup (void)
Variables
static bool verbose = false
Detailed Description
HTTP Client sample.
A command-line application that allows one make GET and POST. It intends to replicate some curl functionalities, such as, set post fields and headers.
Macro Definition Documentation
#define CREATE_PARAM (_key, _filename, _value)
Value:
(struct sol_http_param_value) { \
        .type = SOL_HTTP_PARAM_POST_DATA, \
        .value.data.filename = _filename, \
        .value.data.key = _key, \
        .value.data.value = _value \
    }
Examples:
/src/samples/http/client.c.
Referenced by create_post_data_params().
Function Documentation
static int create_header_params (struct sol_http_params * params, const char * value) static
Examples:
/src/samples/http/client.c.
References sol_str_slice::data, key, sol_str_slice::len, SOL_HTTP_PARAM_HEADER, sol_http_params_add_copy(), SOL_STR_SLICE_PRINT, sol_http_param_value::type, value, and sol_http_param_value::value.
Referenced by startup().
static int create_post_data_params (struct sol_http_params * params, const char * query) static
Examples:
/src/samples/http/client.c.
References CREATE_PARAM, sol_str_slice::data, sol_str_slice::len, sol_http_params_add_copy(), SOL_STR_SLICE_EMPTY, sol_str_slice_from_str(), SOL_STR_SLICE_PRINT, sol_str_slice_split(), sol_vector_clear(), and SOL_VECTOR_FOREACH_IDX.
Referenced by startup().
static int create_post_field_params (struct sol_http_params * params, const char * value) static
Examples:
/src/samples/http/client.c.
References sol_http_split_post_field().
Referenced by startup().
static void response_cb (void * userdata, struct sol_http_client_connection * connection, struct sol_http_response * response) static
Examples:
/src/samples/http/client.c.
References sol_http_response::content, sol_buffer::data, sol_http_response::param, sol_http_response::response_code, SOL_HTTP_PARAM_COOKIE, SOL_HTTP_PARAM_HEADER, SOL_HTTP_PARAMS_FOREACH_IDX, SOL_HTTP_STATUS_OK, sol_quit_with_code(), SOL_STR_SLICE_PRINT, sol_http_param_value::type, sol_buffer::used, value, sol_http_param_value::value, and verbose.
Referenced by startup().
static void shutdown (void) static
SOL_MAIN_DEFAULT (startup , shutdown)
static void startup (void) static
References create_header_params(), create_post_data_params(), create_post_field_params(), pending, response_cb(), sol_argc(), sol_argv(), sol_http_client_request(), SOL_HTTP_METHOD_GET, SOL_HTTP_METHOD_POST, sol_http_params_clear(), SOL_HTTP_REQUEST_PARAMS_INIT, sol_quit_with_code(), and verbose.
Variable Documentation
bool verbose = false static
Examples:
/src/samples/http/client.c.
Referenced by response_cb(), and startup().