Soletta™ Framework: src/samples/bluetooth/connect-paired.c File Reference
connect-paired.c File Reference
#include <errno.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "soletta.h"
#include "sol-log.h"
#include "sol-mainloop.h"
#include "sol-bluetooth.h"
Functions
static void enabled (void *data, bool powered)
static void found_device (void *user_data, const struct sol_bt_device_info *device)
static bool on_connect (void *user_data, struct sol_bt_conn *conn)
static void on_disconnect (void *user_data, struct sol_bt_conn *conn)
static void on_error (void *user_data, int error)
static void shutdown (void)
SOL_MAIN_DEFAULT (startup, shutdown)
static void startup (void)
Variables
static struct sol_network_link_addr paired_device_addr
static struct sol_bt_conn * paired_device_conn
static struct sol_bt_scan_pending * scan
static struct sol_bt_session * session
Function Documentation
static void enabled (void * data, bool powered) static
References found_device(), scan, sol_bt_start_scan(), SOL_BT_TRANSPORT_ALL, SOL_INF, and SOL_NULL_CHECK.
Referenced by startup().
static void found_device (void * user_data, const struct sol_bt_device_info * device) static
References sol_bt_device_info::addr, sol_bt_device_info::in_range, on_connect(), on_disconnect(), on_error(), sol_bt_device_info::paired, paired_device_addr, paired_device_conn, scan, sol_bt_connect(), sol_bt_stop_scan(), and SOL_NULL_CHECK.
Referenced by enabled().
static bool on_connect (void * user_data, struct sol_bt_conn * conn) static
References SOL_BLUETOOTH_ADDR_STRLEN, sol_bt_conn_get_addr(), SOL_BUFFER_DECLARE_STATIC, SOL_INF, and sol_network_link_addr_to_str().
Referenced by found_device().
static void on_disconnect (void * user_data, struct sol_bt_conn * conn) static
References SOL_BLUETOOTH_ADDR_STRLEN, sol_bt_conn_get_addr(), SOL_BUFFER_DECLARE_STATIC, SOL_INF, and sol_network_link_addr_to_str().
Referenced by found_device().
static void on_error (void * user_data, int error) static
References paired_device_conn.
Referenced by found_device().
static void shutdown (void) static
References paired_device_conn, scan, session, sol_bt_disable(), sol_bt_disconnect(), and sol_bt_stop_scan().
SOL_MAIN_DEFAULT (startup , shutdown)
static void startup (void) static
References enabled(), session, sol_bt_enable(), sol_quit_with_code(), and SOL_WRN.
Variable Documentation
struct sol_network_link_addr paired_device_addr static
Examples:
/src/samples/bluetooth/connect-paired.c.
Referenced by found_device().
struct sol_bt_conn* paired_device_conn static
Examples:
/src/samples/bluetooth/connect-paired.c.
Referenced by found_device(), on_error(), and shutdown().
struct sol_bt_scan_pending* scan static
Referenced by enabled(), found_device(), and shutdown().
struct sol_bt_session* session static
Referenced by shutdown(), and startup().