Soletta™ Framework: src/samples/http/download.c File Reference
download.c File Reference
#include <errno.h>
#include <getopt.h>
#include <stdio.h>
#include <string.h>
#include "soletta.h"
#include "sol-http.h"
#include "sol-http-client.h"
Functions
static ssize_t on_data_func (void *userdata, struct sol_http_client_connection *connection, const struct sol_buffer *buffer)
static void response_func (void *userdata, struct sol_http_client_connection *connection, struct sol_http_response *response)
static void shutdown (void)
SOL_MAIN_DEFAULT (startup, shutdown)
static void startup (void)
Variables
static FILE * fd
static const struct
sol_http_request_interface iface
struct sol_http_client_connection * pending
Function Documentation
static ssize_t on_data_func (void * userdata, struct sol_http_client_connection * connection, const struct sol_buffer * buffer) static
Examples:
/src/samples/http/download.c.
References sol_buffer::data, fd, and sol_buffer::used.
static void response_func (void * userdata, struct sol_http_client_connection * connection, struct sol_http_response * response) static
Examples:
/src/samples/http/download.c.
References fd, pending, sol_http_response::response_code, SOL_HTTP_STATUS_OK, and sol_quit_with_code().
static void shutdown (void) static
References fd, pending, and sol_http_client_connection_cancel().
SOL_MAIN_DEFAULT (startup , shutdown)
static void startup (void) static
References fd, pending, sol_argc(), sol_argv(), sol_http_client_request_with_interface(), SOL_HTTP_METHOD_GET, and sol_quit_with_code().
Variable Documentation
FILE* fd static
Examples:
/src/samples/crypto/sha256sum.c, /src/samples/design_patterns/stream_sample.c, /src/samples/http/download.c, /src/samples/http/server-sse.c, and /src/samples/http/server.c.
Referenced by on_data_func(), response_func(), shutdown(), and startup().
const struct sol_http_request_interface iface static
Initial value:
= {
    .on_data = on_data_func,
    .on_response = response_func
}
Examples:
/src/samples/http/download.c.
struct sol_http_client_connection* pending
Examples:
/src/samples/crypto/message-digest.c, /src/samples/crypto/sha256sum.c, /src/samples/http/client.c, and /src/samples/http/download.c.
Referenced by response_func(), shutdown(), and startup().