Soletta™ Framework: src/samples/network/echo-client.c File Reference
echo-client.c File Reference
Basic echo client.
#include <errno.h>
#include <getopt.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include "soletta.h"
#include "sol-buffer.h"
#include "sol-socket.h"
#include "sol-network.h"
#include "sol-vector.h"
#include "sol-util.h"
Functions
static bool on_can_read (void *data, struct sol_socket *s)
static bool on_can_write (void *data, struct sol_socket *s)
static void shutdown_client (void)
SOL_MAIN_DEFAULT (startup_client, shutdown_client)
static void startup_client (void)
Variables
static struct sol_network_link_addr address
static struct sol_socket * sock
Detailed Description
Basic echo client.
This is echo client, the value given to the program is sent to the echo server and the response is printed out. To see the usage help, -h or –help.
Function Documentation
static bool on_can_read (void * data, struct sol_socket * s) static
Examples:
/src/samples/network/echo-client.c, and /src/samples/network/echo-server.c.
References sol_buffer_fini(), sol_buffer_get_slice(), SOL_BUFFER_INIT_EMPTY, sol_quit_with_code(), sol_socket_recvmsg(), and SOL_STR_SLICE_PRINT.
Referenced by startup_client().
static bool on_can_write (void * data, struct sol_socket * s) static
Examples:
/src/samples/network/echo-client.c, and /src/samples/network/echo-server.c.
References sol_buffer_fini(), SOL_BUFFER_INIT_CONST, sol_quit_with_code(), and sol_socket_sendmsg().
Referenced by startup_client().
static void shutdown_client (void) static
Examples:
/src/samples/network/echo-client.c.
References sol_socket_del().
SOL_MAIN_DEFAULT (startup_client , shutdown_client)
static void startup_client (void) static
Examples:
/src/samples/network/echo-client.c.
References sol_socket_ip_options::base, sol_socket_options::data, on_can_read(), on_can_write(), sol_network_link_addr::port, sol_argc(), sol_argv(), SOL_NETWORK_FAMILY_INET6, sol_network_link_addr_from_str(), sol_quit_with_code(), SOL_SET_API_VERSION, sol_socket_ip_new(), SOL_SOCKET_OPTIONS_API_VERSION, sol_socket_set_read_monitor(), and sol_socket_set_write_monitor().
Variable Documentation
struct sol_network_link_addr address static
Initial value:
= {
    .port = 7,
    .family = SOL_NETWORK_FAMILY_INET6,
}
Examples:
/src/samples/network/echo-client.c.
struct sol_socket* sock static
Examples:
/src/samples/network/echo-client.c, and /src/samples/network/echo-server.c.