Soletta™ Framework: src/samples/flow/c-api/find-type.c File Reference
find-type.c File Reference
Example how to find a node type given its name, then print its description such as ports and options.
#include <getopt.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <inttypes.h>
#include <limits.h>
#include <dlfcn.h>
#include "sol-flow.h"
#include "sol-flow-resolver.h"
#include "sol-util-file.h"
#include "soletta.h"
Macros
#define CHECK_TYPE_API_VERSION(type,...)
#define CHECK_TYPE_DESC_API_VERSION(type,...)
#define FLOWMODULESDIR MODULESDIR "/flow"
#define MODULESDIR "/usr/lib/soletta/modules"
Functions
static bool cb_print_type_name (void *data, const struct sol_flow_node_type *type)
static void print_type (const struct sol_flow_node_type *type)
static void show_builtins (void)
static void show_help (void)
static void show_module_types (const char *modname)
static void show_resolved_type (const char *name)
static void shutdown (void)
SOL_MAIN_DEFAULT (startup, shutdown)
static void startup (void)
Detailed Description
Example how to find a node type given its name, then print its description such as ports and options.
Macro Definition Documentation
#define CHECK_TYPE_API_VERSION (type, ...)
Value:
do { \
        if (type->api_version != SOL_FLOW_NODE_TYPE_API_VERSION) { \
            fprintf(stderr, "ERROR: type=%p has api_version=%" PRIu16 \
                " while %" PRIu16 " was expected.\n", \
                type, type->api_version, SOL_FLOW_NODE_TYPE_API_VERSION); \
            return __VA_ARGS__; \
        } \
    } while (0)
Examples:
/src/samples/flow/c-api/find-type.c.
Referenced by cb_print_type_name(), and print_type().
#define CHECK_TYPE_DESC_API_VERSION (type, ...)
Value:
do { \
        if (!type->description) { \
            fprintf(stderr, "ERROR: type=%p has no description.\n", type); \
            return __VA_ARGS__; \
        } \
        if (type->description->api_version != SOL_FLOW_NODE_TYPE_DESCRIPTION_API_VERSION) { \
            fprintf(stderr, "ERROR: type=%p description->api_version=%" PRIu16 \
                " while %" PRIu16 " was expected.\n", \
                type, type->description->api_version, SOL_FLOW_NODE_TYPE_DESCRIPTION_API_VERSION); \
            return __VA_ARGS__; \
        } \
    } while (0)
Examples:
/src/samples/flow/c-api/find-type.c.
Referenced by cb_print_type_name(), and print_type().
#define FLOWMODULESDIR MODULESDIR "/flow"
Examples:
/src/samples/flow/c-api/find-type.c.
Referenced by show_module_types().
#define MODULESDIR "/usr/lib/soletta/modules"
Function Documentation
static bool cb_print_type_name (void * data, const struct sol_flow_node_type * type) static
Examples:
/src/samples/flow/c-api/find-type.c.
References CHECK_TYPE_API_VERSION, and CHECK_TYPE_DESC_API_VERSION.
Referenced by show_builtins(), and show_module_types().
static void print_type (const struct sol_flow_node_type * type) static
Examples:
/src/samples/flow/c-api/find-type.c.
References CHECK_TYPE_API_VERSION, and CHECK_TYPE_DESC_API_VERSION.
Referenced by show_resolved_type().
static void show_builtins (void) static
Examples:
/src/samples/flow/c-api/find-type.c.
References cb_print_type_name().
Referenced by startup().
static void show_help (void) static
Examples:
/src/samples/flow/c-api/find-type.c.
References sol_argv().
Referenced by startup().
static void show_module_types (const char * modname) static
Examples:
/src/samples/flow/c-api/find-type.c.
References cb_print_type_name(), FLOWMODULESDIR, and sol_util_get_rootdir().
Referenced by startup().
static void show_resolved_type (const char * name) static
Examples:
/src/samples/flow/c-api/find-type.c.
References sol_rgb::blue, sol_rgb::blue_max, sol_flow_node_named_options_member::boolean, sol_flow_node_named_options_member::byte, sol_flow_node_named_options::count, sol_flow_node_named_options_member::direction_vector, sol_flow_node_named_options_member::drange_spec, sol_flow_node_named_options_member::f, sol_rgb::green, sol_rgb::green_max, sol_flow_node_named_options_member::i, sol_flow_node_named_options_member::irange_spec, sol_direction_vector::max, sol_drange_spec::max, sol_irange_spec::max, sol_flow_node_named_options::members, sol_direction_vector::min, sol_drange_spec::min, sol_irange_spec::min, sol_flow_node_named_options_member::name, print_type(), sol_rgb::red, sol_rgb::red_max, sol_flow_node_named_options_member::rgb, sol_flow_get_builtins_resolver(), sol_flow_node_named_options_fini(), SOL_FLOW_NODE_OPTIONS_MEMBER_BOOL, SOL_FLOW_NODE_OPTIONS_MEMBER_BYTE, SOL_FLOW_NODE_OPTIONS_MEMBER_DIRECTION_VECTOR, SOL_FLOW_NODE_OPTIONS_MEMBER_DRANGE_SPEC, SOL_FLOW_NODE_OPTIONS_MEMBER_FLOAT, SOL_FLOW_NODE_OPTIONS_MEMBER_INT, SOL_FLOW_NODE_OPTIONS_MEMBER_IRANGE_SPEC, SOL_FLOW_NODE_OPTIONS_MEMBER_RGB, SOL_FLOW_NODE_OPTIONS_MEMBER_STRING, sol_flow_resolve(), sol_drange_spec::step, sol_irange_spec::step, sol_flow_node_named_options_member::string, sol_flow_node_named_options_member::type, sol_direction_vector::x, sol_direction_vector::y, and sol_direction_vector::z.
Referenced by startup().
static void shutdown (void) static
SOL_MAIN_DEFAULT (startup , shutdown)
static void startup (void) static
References show_builtins(), show_help(), show_module_types(), show_resolved_type(), sol_argc(), sol_argv(), sol_quit(), and sol_quit_with_code().