Soletta: src/modules/flow/flower-power/flower-power.c File Reference
flower-power.c File Reference
#include "sol-flower-power.h"
#include "sol-flow/flower-power.h"
#include "sol-flow-internal.h"
#include <sol-http-client.h>
#include <sol-json.h>
#include <sol-util.h>
#include <errno.h>
#include <float.h>
#include <math.h>
#include <time.h>
#include "flower-power-gen.c"
Data Structures
struct filter_data
struct http_get_data
Macros
#define AUTH_START "Bearer "
#define AUTH_URL BASE_URL "user/v1/authenticate"
#define BASE_URL "https://apiflowerpower.parrot.com/"
#define INIT_FERTILIZER(_fertilizer)
#define INIT_LIGHT(_light)
#define INIT_TEMPERATURE(_temperature)
#define INIT_WATER(_water)
#define PACKET_TYPE_FLOWER_POWER_PACKET_TYPE_API_VERSION (1)
#define PACKET_TYPE_FLOWER_POWER_SENSOR_PACKET_TYPE_API_VERSION (1)
#define STATUS_URL BASE_URL "sensor_data/v4/garden_locations_status"
Functions
SOL_API int sol_flower_power_get_packet (const struct sol_flow_packet *packet, struct sol_flower_power_data *fpd)
SOL_API struct sol_flow_packet * sol_flower_power_new_packet (const struct sol_flower_power_data *fpd)
SOL_API int sol_flower_power_send_packet (struct sol_flow_node *src, uint16_t src_port, const struct sol_flower_power_data *fpd)
SOL_API int sol_flower_power_sensor_get_packet (const struct sol_flow_packet *packet, struct sol_flower_power_sensor_data *fpsd)
SOL_API int sol_flower_power_sensor_get_packet_components (const struct sol_flow_packet *packet, const char **id, struct timespec *timestamp, struct timespec *battery_end_of_life, struct sol_drange *battery_level)
SOL_API struct sol_flow_packet * sol_flower_power_sensor_new_packet (const struct sol_flower_power_sensor_data *fpsd)
SOL_API struct sol_flow_packet * sol_flower_power_sensor_new_packet_components (const char *id, const struct timespec *timestamp, const struct timespec *battery_end_of_life, struct sol_drange *battery_level)
SOL_API int sol_flower_power_sensor_send_packet (struct sol_flow_node *src, uint16_t src_port, const struct sol_flower_power_sensor_data *fpsd)
SOL_API int sol_flower_power_sensor_send_packet_components (struct sol_flow_node *src, uint16_t src_port, char *id, struct timespec *timestamp, struct timespec *battery_end_of_life, struct sol_drange *battery_level)
Variables
SOL_API const struct
sol_flow_packet_type * PACKET_TYPE_FLOWER_POWER
SOL_API const struct
sol_flow_packet_type * PACKET_TYPE_FLOWER_POWER_SENSOR
Macro Definition Documentation
#define AUTH_START "Bearer "
#define AUTH_URL BASE_URL "user/v1/authenticate"
#define BASE_URL "https://apiflowerpower.parrot.com/"
#define INIT_FERTILIZER (_fertilizer)
Value:
_fertilizer.min = 0; \
    _fertilizer.max = 10;
#define INIT_LIGHT (_light)
Value:
_light.min = 0.13; \
    _light.max = 104;
#define INIT_TEMPERATURE (_temperature)
Value:
_temperature.min = 268.15; \
    _temperature.max = 328.15;
#define INIT_WATER (_water)
Value:
_water.min = 0; \
    _water.max = 50;
#define PACKET_TYPE_FLOWER_POWER_PACKET_TYPE_API_VERSION (1)
#define PACKET_TYPE_FLOWER_POWER_SENSOR_PACKET_TYPE_API_VERSION (1)
#define STATUS_URL BASE_URL "sensor_data/v4/garden_locations_status"
Function Documentation
SOL_API int sol_flower_power_get_packet (const struct sol_flow_packet * packet, struct sol_flower_power_data * fpd)
References sol_flow_packet_get(), sol_flow_packet_get_type(), and SOL_NULL_CHECK.
SOL_API struct sol_flow_packet* sol_flower_power_new_packet (const struct sol_flower_power_data * fpd)
References sol_flow_packet_new(), and SOL_NULL_CHECK.
Referenced by sol_flower_power_send_packet().
SOL_API int sol_flower_power_send_packet (struct sol_flow_node * src, uint16_t src_port, const struct sol_flower_power_data * fpd)
References sol_flow_send_packet(), sol_flower_power_new_packet(), and SOL_NULL_CHECK.
SOL_API int sol_flower_power_sensor_get_packet (const struct sol_flow_packet * packet, struct sol_flower_power_sensor_data * fpsd)
References sol_flow_packet_get(), sol_flow_packet_get_type(), and SOL_NULL_CHECK.
SOL_API int sol_flower_power_sensor_get_packet_components (const struct sol_flow_packet * packet, const char ** id, struct timespec * timestamp, struct timespec * battery_end_of_life, struct sol_drange * battery_level)
References sol_flower_power_sensor_data::battery_end_of_life, sol_flower_power_sensor_data::battery_level, sol_flower_power_sensor_data::id, sol_flow_packet_get(), sol_flow_packet_get_type(), SOL_INT_CHECK, SOL_NULL_CHECK, and sol_flower_power_sensor_data::timestamp.
SOL_API struct sol_flow_packet* sol_flower_power_sensor_new_packet (const struct sol_flower_power_sensor_data * fpsd)
References sol_flow_packet_new(), and SOL_NULL_CHECK.
Referenced by sol_flower_power_sensor_send_packet().
SOL_API struct sol_flow_packet* sol_flower_power_sensor_new_packet_components (const char * id, const struct timespec * timestamp, const struct timespec * battery_end_of_life, struct sol_drange * battery_level)
References sol_flower_power_sensor_data::battery_end_of_life, sol_flower_power_sensor_data::battery_level, sol_flower_power_sensor_data::id, sol_flow_packet_new(), SOL_NULL_CHECK, and sol_flower_power_sensor_data::timestamp.
Referenced by sol_flower_power_sensor_send_packet_components().
SOL_API int sol_flower_power_sensor_send_packet (struct sol_flow_node * src, uint16_t src_port, const struct sol_flower_power_sensor_data * fpsd)
References sol_flow_send_packet(), sol_flower_power_sensor_new_packet(), and SOL_NULL_CHECK.
SOL_API int sol_flower_power_sensor_send_packet_components (struct sol_flow_node * src, uint16_t src_port, char * id, struct timespec * timestamp, struct timespec * battery_end_of_life, struct sol_drange * battery_level)
References sol_flow_send_packet(), sol_flower_power_sensor_new_packet_components(), and SOL_NULL_CHECK.
Variable Documentation
SOL_API const struct sol_flow_packet_type* PACKET_TYPE_FLOWER_POWER
Initial value:
=
    &_PACKET_TYPE_FLOWER_POWER
SOL_API const struct sol_flow_packet_type* PACKET_TYPE_FLOWER_POWER_SENSOR
Initial value:
=
    &_PACKET_TYPE_FLOWER_POWER_SENSOR