Soletta: SPI
SPI
I/O
Data Structures
struct sol_spi_config
Macros
#define SOL_SPI_DATA_BITS_DEFAULT 8
Enumerations
enum sol_spi_mode { SOL_SPI_MODE_0 = 0, SOL_SPI_MODE_1, SOL_SPI_MODE_2, SOL_SPI_MODE_3 }
Functions
void sol_spi_close (struct sol_spi *spi)
struct sol_spi * sol_spi_open (unsigned int bus, const struct sol_spi_config *config)
bool sol_spi_transfer (struct sol_spi *spi, const uint8_t *tx, uint8_t *rx, size_t count, void(*transfer_cb)(void *cb_data, struct sol_spi *spi, const uint8_t *tx, uint8_t *rx, ssize_t status), const void *cb_data)
Detailed Description
SPI (Serial Peripheral Interface) API for Soletta.
Macro Definition Documentation
#define SOL_SPI_DATA_BITS_DEFAULT 8
Enumeration Type Documentation
enum sol_spi_mode
Enumerator
SOL_SPI_MODE_0
SOL_SPI_MODE_1
CPOL = 0 and CPHA = 0
SOL_SPI_MODE_2
CPOL = 0 and CPHA = 1
SOL_SPI_MODE_3
CPOL = 1 and CPHA = 0 CPOL = 1 and CPHA = 1
Function Documentation
void sol_spi_close (struct sol_spi * spi)
Close an SPI bus.
Parameters
spi The SPI bus handle
References sol_spi::bus, sol_spi::fd, SOL_NULL_CHECK, sol_timeout_del(), sol_worker_thread_cancel(), sol_spi::timeout, and sol_spi::transfer.
struct sol_spi* sol_spi_open (unsigned int bus, const struct sol_spi_config * config)
Open an SPI bus.
Parameters
bus The SPI bus number to open
config The SPI bus configuration
Returns
A new SPI bus handle
Note
For now it only supports one user of the bus at time, 2 or mode devices with different chip select on the same bus will cause concurrency errors.
References sol_spi_config::api_version, sol_spi::bits_per_word, sol_spi_config::bits_per_word, sol_spi::bus, sol_spi::chip_select, sol_spi_config::chip_select, sol_spi::cs_pin, sol_spi::fd, sol_spi_config::frequency, sol_spi_config::mode, SOL_EXP_CHECK, SOL_LOG_INTERNAL_INIT_ONCE, SOL_NULL_CHECK, SOL_SPI_CONFIG_API_VERSION, sol_util_strerrora, SOL_WRN, sol_spi::timeout, sol_spi::transfer, and unlikely.
bool sol_spi_transfer (struct sol_spi * spi, const uint8_t * tx, uint8_t * rx, size_t count, void(*)(void *cb_data, struct sol_spi *spi, const uint8_t *tx, uint8_t *rx, ssize_t status) transfer_cb, const void * cb_data)
Perform a SPI asynchronous transfer.
Parameters
spi The SPI bus handle
tx The output buffer
rx The input buffer
count number of bytes to be transfer
transfer_cb callback to be called when transmission finish, in case of success the status parameters on callback should be the same value as count, otherwise a error happen.
cb_data user data, first parameter of transfer_cb
Returns
true if transfer was started.
As SPI works in full-duplex, data are going in and out at same time, so both buffers must have the count size. Caller should guarantee that both buffers will not be freed until callback is called. Also there is no transfer queue, calling this function when there is transfer happening would return false.
References sol_worker_thread_spec::api_version, sol_spi::cb, sol_spi::cb_data, sol_spi::count, sol_spi::intern_allocated_buffer_flags, INTERN_ALLOCATED_RX_BUFFER, INTERN_ALLOCATED_TX_BUFFER, sol_spi::rx, SOL_EXP_CHECK, SOL_INT_CHECK, SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, sol_timeout_add(), sol_worker_thread_new(), SOL_WORKER_THREAD_SPEC_API_VERSION, sol_spi::status, sol_spi::timeout, sol_spi::transfer, and sol_spi::tx.