Soletta: Parsers
Parsers
Data Structures
struct sol_json_scanner
struct sol_json_token
Macros
#define SOL_JSON_ESCAPE_STRING(s)
#define SOL_JSON_SCANNER_ARRAY_LOOP(scanner_, token_, element_type_, end_reason_)
#define SOL_JSON_SCANNER_ARRAY_LOOP_ALL(scanner_, token_, end_reason_)
#define SOL_JSON_SCANNER_ARRAY_LOOP_ALL_NEST(scanner_, token_, end_reason_)
#define SOL_JSON_SCANNER_ARRAY_LOOP_NEST(scanner_, token_, element_type_, end_reason_)
#define SOL_JSON_SCANNER_OBJECT_LOOP(scanner_, token_, key_, value_, end_reason_)
#define SOL_JSON_SCANNER_OBJECT_LOOP_NEST(scanner_, token_, key_, value_, end_reason_)
#define SOL_JSON_TOKEN_STR_LITERAL_EQ(token_, str_) sol_json_token_str_eq(token_, str_, sizeof(str_) - 1)
Enumerations
enum sol_json_loop_reason { SOL_JSON_LOOP_REASON_OK = 0, SOL_JSON_LOOP_REASON_INVALID }
enum sol_json_type {
SOL_JSON_TYPE_UNKNOWN = 0, SOL_JSON_TYPE_OBJECT_START = '{', SOL_JSON_TYPE_OBJECT_END = '}', SOL_JSON_TYPE_ARRAY_START = '[',
SOL_JSON_TYPE_ARRAY_END = ']', SOL_JSON_TYPE_ELEMENT_SEP = ',', SOL_JSON_TYPE_PAIR_SEP = ':', SOL_JSON_TYPE_TRUE = 't',
SOL_JSON_TYPE_FALSE = 'f', SOL_JSON_TYPE_NULL = 'n', SOL_JSON_TYPE_STRING = '"', SOL_JSON_TYPE_NUMBER = '1'
}
Functions
size_t sol_json_calculate_escaped_string_len (const char *str) SOL_ATTR_NONNULL(1)
int sol_json_double_to_str (const double value, char *buf, size_t buf_len)
char * sol_json_escape_string (const char *str, char *buf, size_t len) SOL_ATTR_NONNULL(1
bool sol_json_is_valid_type (struct sol_json_scanner *scanner, enum sol_json_type start_type) SOL_ATTR_NONNULL(1)
bool bool bool sol_json_scanner_get_dict_pair (struct sol_json_scanner *scanner, struct sol_json_token *key, struct sol_json_token *value) SOL_ATTR_WARN_UNUSED_RESULT SOL_ATTR_NONNULL(1
bool sol_json_scanner_next (struct sol_json_scanner *scanner, struct sol_json_token *token) SOL_ATTR_WARN_UNUSED_RESULT SOL_ATTR_NONNULL(1
bool bool sol_json_scanner_skip_over (struct sol_json_scanner *scanner, struct sol_json_token *token) SOL_ATTR_WARN_UNUSED_RESULT SOL_ATTR_NONNULL(1
int sol_json_serialize_boolean (struct sol_buffer *buffer, bool val) SOL_ATTR_NONNULL(1)
int int sol_json_serialize_double (struct sol_buffer *buffer, double val) SOL_ATTR_NONNULL(1)
int sol_json_serialize_int32 (struct sol_buffer *buffer, int32_t val) SOL_ATTR_NONNULL(1)
int sol_json_serialize_int64 (struct sol_buffer *buffer, int64_t val) SOL_ATTR_NONNULL(1)
int sol_json_serialize_string (struct sol_buffer *buffer, const char *str) SOL_ATTR_NONNULL(1
int sol_json_serialize_uint32 (struct sol_buffer *buffer, uint32_t val) SOL_ATTR_NONNULL(1)
int sol_json_serialize_uint64 (struct sol_buffer *buffer, uint64_t val) SOL_ATTR_NONNULL(1)
int sol_json_token_get_double (const struct sol_json_token *token, double *value) SOL_ATTR_WARN_UNUSED_RESULT SOL_ATTR_NONNULL(1
int int sol_json_token_get_int64 (const struct sol_json_token *token, int64_t *value) SOL_ATTR_WARN_UNUSED_RESULT SOL_ATTR_NONNULL(1
int sol_json_token_get_uint64 (const struct sol_json_token *token, uint64_t *value) SOL_ATTR_WARN_UNUSED_RESULT SOL_ATTR_NONNULL(1
int sol_json_token_get_unescaped_string (const struct sol_json_token *token, struct sol_buffer *buffer)
char * sol_json_token_get_unescaped_string_copy (const struct sol_json_token *value)
Detailed Description
These are the parsers that Soletta provides (JSON only, for now)
Macro Definition Documentation
#define SOL_JSON_ESCAPE_STRING (s)
Value:
({ \
        size_t str_len ## __COUNT__  = sol_json_calculate_escaped_string_len(s); \
        sol_json_escape_string(s, alloca(str_len ## __COUNT__), str_len ## __COUNT__); \
    })
#define SOL_JSON_SCANNER_ARRAY_LOOP (scanner_, token_, element_type_, end_reason_)
Value:
for (end_reason_ = _sol_json_loop_helper_init(scanner_, token_, SOL_JSON_TYPE_ARRAY_START); \
        _sol_json_loop_helper_array(scanner_, token_, &end_reason_, element_type_);)
Referenced by sol_board_detect().
#define SOL_JSON_SCANNER_ARRAY_LOOP_ALL (scanner_, token_, end_reason_)
Value:
for (end_reason_ = _sol_json_loop_helper_init(scanner_, token_, SOL_JSON_TYPE_ARRAY_START); \
        _sol_json_loop_helper_generic(scanner_, token_, SOL_JSON_TYPE_ARRAY_END, &end_reason_);)
#define SOL_JSON_SCANNER_ARRAY_LOOP_ALL_NEST (scanner_, token_, end_reason_)
Value:
for (end_reason_ = SOL_JSON_LOOP_REASON_OK;  \
        _sol_json_loop_helper_generic(scanner_, token_, SOL_JSON_TYPE_ARRAY_END, &end_reason_);)
#define SOL_JSON_SCANNER_ARRAY_LOOP_NEST (scanner_, token_, element_type_, end_reason_)
Value:
for (end_reason_ = SOL_JSON_LOOP_REASON_OK;  \
        _sol_json_loop_helper_array(scanner_, token_, &end_reason_, element_type_);)
#define SOL_JSON_SCANNER_OBJECT_LOOP (scanner_, token_, key_, value_, end_reason_)
Value:
for (end_reason_ = _sol_json_loop_helper_init(scanner_, token_, SOL_JSON_TYPE_OBJECT_START); \
        _sol_json_loop_helper_object(scanner_, token_, key_, value_, &end_reason_);)
Referenced by sol_board_detect().
#define SOL_JSON_SCANNER_OBJECT_LOOP_NEST (scanner_, token_, key_, value_, end_reason_)
Value:
for (end_reason_ = SOL_JSON_LOOP_REASON_OK; \
        _sol_json_loop_helper_object(scanner_, token_, key_, value_, &end_reason_);)
Referenced by sol_board_detect().
#define SOL_JSON_TOKEN_STR_LITERAL_EQ (token_, str_) sol_json_token_str_eq(token_, str_, sizeof(str_) - 1)
Referenced by sol_board_detect().
Enumeration Type Documentation
enum sol_json_loop_reason
Enumerator
SOL_JSON_LOOP_REASON_OK
SOL_JSON_LOOP_REASON_INVALID
enum sol_json_type
Enumerator
SOL_JSON_TYPE_UNKNOWN
SOL_JSON_TYPE_OBJECT_START
SOL_JSON_TYPE_OBJECT_END
SOL_JSON_TYPE_ARRAY_START
SOL_JSON_TYPE_ARRAY_END
SOL_JSON_TYPE_ELEMENT_SEP
SOL_JSON_TYPE_PAIR_SEP
SOL_JSON_TYPE_TRUE
SOL_JSON_TYPE_FALSE
SOL_JSON_TYPE_NULL
SOL_JSON_TYPE_STRING
SOL_JSON_TYPE_NUMBER
Function Documentation
size_t sol_json_calculate_escaped_string_len (const char * str)
References SOL_NULL_CHECK.
Referenced by sol_json_serialize_string().
int sol_json_double_to_str (const double value, char * buf, size_t buf_len)
References SOL_NULL_CHECK, and streq.
Referenced by sol_json_serialize_double().
char* sol_json_escape_string (const char * str, char * buf, size_t len)
bool sol_json_is_valid_type (struct sol_json_scanner * scanner, enum sol_json_type start_type)
References sol_json_token::end, sol_json_scanner::mem_end, sol_json_scanner_next(), sol_json_scanner_skip_over(), and SOL_NULL_CHECK.
bool bool bool sol_json_scanner_get_dict_pair (struct sol_json_scanner * scanner, struct sol_json_token * key, struct sol_json_token * value)
bool sol_json_scanner_next (struct sol_json_scanner * scanner, struct sol_json_token * token)
bool bool sol_json_scanner_skip_over (struct sol_json_scanner * scanner, struct sol_json_token * token)
int sol_json_serialize_boolean (struct sol_buffer * buffer, bool val)
References sol_buffer_append_slice(), SOL_INT_CHECK, SOL_NULL_CHECK, and SOL_STR_SLICE_LITERAL.
int int sol_json_serialize_double (struct sol_buffer * buffer, double val)
References sol_buffer_ensure(), SOL_INT_CHECK, sol_json_double_to_str(), SOL_NULL_CHECK, STR_DOUBLE_LEN, and sol_buffer::used.
int sol_json_serialize_int32 (struct sol_buffer * buffer, int32_t val)
References SOL_INT_CHECK, and SOL_NULL_CHECK.
int sol_json_serialize_int64 (struct sol_buffer * buffer, int64_t val)
References SOL_INT_CHECK, and SOL_NULL_CHECK.
int sol_json_serialize_string (struct sol_buffer * buffer, const char * str)
int sol_json_serialize_uint32 (struct sol_buffer * buffer, uint32_t val)
References SOL_INT_CHECK, and SOL_NULL_CHECK.
int sol_json_serialize_uint64 (struct sol_buffer * buffer, uint64_t val)
References SOL_INT_CHECK, and SOL_NULL_CHECK.
int sol_json_token_get_double (const struct sol_json_token * token, double * value)
Get the numeric value of the given token as double-precision floating point.
Parameters
token the token to convert to number.
value where to return the converted number.
Returns
0 on success, -errno on failure (EINVAL or ERANGE). On errors value will be set to a best-match, such as 0.0 if EINVAL, DBL_MAX or -DBL_MAX if ERANGE.
See Also
sol_json_token_get_uint64()
sol_json_token_get_int64()
sol_json_token_get_uint32()
sol_json_token_get_int32()
int int sol_json_token_get_int64 (const struct sol_json_token * token, int64_t * value)
Get the numeric value of the given token as an 64 bits signed integer.
Parameters
token the token to convert to number.
value where to return the converted number.
Returns
0 on success, -errno on failure (EINVAL or ERANGE). On errors value will be set to a best-match, such as 0 if EINVAL, INT64_MAX or INT64_MIN if ERANGE.
See Also
sol_json_token_get_uint64()
sol_json_token_get_int32()
sol_json_token_get_double()
int sol_json_token_get_uint64 (const struct sol_json_token * token, uint64_t * value)
Get the numeric value of the given token as an 64 bits unsigned integer.
Parameters
token the token to convert to number.
value where to return the converted number.
Returns
0 on success, -errno on failure (EINVAL or ERANGE). On errors value will be set to a best-match, such as 0 if EINVAL or UINT64_MAX if ERANGE.
See Also
sol_json_token_get_int64()
sol_json_token_get_uint32()
sol_json_token_get_double()
int sol_json_token_get_unescaped_string (const struct sol_json_token * token, struct sol_buffer * buffer)
Get in a sol_buffer the string value of informed token. If token type is a JSON string, quotes are removed and string is unescaped. If not full token value is returned as a string.
If necessary memory will be allocated to place unescaped string, so caller is responsable to call sol_buffer_fini after using the buffer content.
Parameters
token A token to get string from
buf An unitialized buffer. sol_buffer_init will be called internally
Returns
0 on sucess, a negative error code on failure.
References sol_buffer::capacity, sol_str_slice::data, sol_json_token::end, MAX_BYTES_UNICODE, sol_buffer_append_char(), sol_buffer_append_slice(), sol_buffer_ensure(), SOL_BUFFER_FLAGS_MEMORY_NOT_OWNED, SOL_BUFFER_FLAGS_NO_NUL_BYTE, SOL_DECODE_BOTH, SOL_INT_CHECK, SOL_INT_CHECK_GOTO, SOL_NULL_CHECK, SOL_STR_SLICE_STR, sol_util_base16_decode(), sol_util_utf8_from_unicode_code(), SOL_WRN, sol_json_token::start, start, and sol_buffer::used.
Referenced by sol_json_token_get_unescaped_string_copy().
char* sol_json_token_get_unescaped_string_copy (const struct sol_json_token * value)
Helper function to get a copy of the unescaped and no-quotes string produced by sol_json_token_get_unescaped_string.
Caller is responsable to free string memory.
Parameters
token A string type token
Returns
A a copy of the unescaped string on sucess, NULL on failure.
References sol_buffer::data, sol_buffer::flags, sol_buffer_ensure_nul_byte(), SOL_BUFFER_FLAGS_DEFAULT, SOL_BUFFER_FLAGS_NO_FREE, sol_buffer_steal(), SOL_INT_CHECK_GOTO, sol_json_token_get_unescaped_string(), and sol_buffer::used.