Soletta™ Framework: GPIO
GPIO
I/O
GPIO (General Purpose Input/Output) API for Soletta.
Data Structures
struct sol_gpio_config
Structure to hold the configuration of a GPIO device.
Typedefs
typedef struct sol_gpio sol_gpio
A handle to a GPIO.
typedef struct sol_gpio_config sol_gpio_config
Structure to hold the configuration of a GPIO device.
Enumerations
enum sol_gpio_direction { SOL_GPIO_DIR_OUT = 0, SOL_GPIO_DIR_IN = 1 }
Possible values for the direction of a GPIO.
enum sol_gpio_drive { SOL_GPIO_DRIVE_NONE = 0, SOL_GPIO_DRIVE_PULL_UP, SOL_GPIO_DRIVE_PULL_DOWN }
Possible values for pull-up or pull-down resistor of a GPIO.
enum sol_gpio_edge { SOL_GPIO_EDGE_NONE = 0, SOL_GPIO_EDGE_RISING, SOL_GPIO_EDGE_FALLING, SOL_GPIO_EDGE_BOTH }
Possible values for the edge mode of a GPIO.
Functions
void sol_gpio_close (struct sol_gpio *gpio)
Closes a given GPIO pin.
enum sol_gpio_direction sol_gpio_direction_from_str (const char *direction)
Converts a string GPIO direction to sol_gpio_direction.
const char * sol_gpio_direction_to_str (enum sol_gpio_direction direction)
Converts sol_gpio_direction to a string name.
enum sol_gpio_drive sol_gpio_drive_from_str (const char *drive)
Converts a string GPIO drive to sol_gpio_drive.
const char * sol_gpio_drive_to_str (enum sol_gpio_drive drive)
Converts sol_gpio_drive to a string name.
enum sol_gpio_edge sol_gpio_edge_from_str (const char *edge)
Converts a string GPIO edge to sol_gpio_edge.
const char * sol_gpio_edge_to_str (enum sol_gpio_edge edge)
Converts sol_gpio_edge to a string name.
struct sol_gpio * sol_gpio_open (uint32_t pin, const struct sol_gpio_config *config)
Opens a given pin as general purpose input or output.
struct sol_gpio * sol_gpio_open_by_label (const char *label, const struct sol_gpio_config *config)
Opens a given pin by its board label as general purpose input or output.
struct sol_gpio * sol_gpio_open_raw (uint32_t pin, const struct sol_gpio_config *config)
Opens a given pin as general purpose input or output.
int sol_gpio_read (struct sol_gpio *gpio)
Get the current value set to pin.
bool sol_gpio_write (struct sol_gpio *gpio, bool value)
Set an arbitrary value to pin.
Detailed Description
GPIO (General Purpose Input/Output) API for Soletta.
Typedef Documentation
sol_gpio
A handle to a GPIO.
See Also
sol_gpio_open_by_label()
sol_gpio_open()
sol_gpio_open_raw()
sol_gpio_close()
sol_gpio_read()
sol_gpio_write()
typedef struct sol_gpio_config sol_gpio_config
Structure to hold the configuration of a GPIO device.
When opening a GPIO with sol_gpio_open_by_label(), sol_gpio_open() or sol_gpio_open_raw(), the parameters with which the GPIO is configured are those defined in this structure.
If there's a need to change any of these parameters, the GPIO must be closed and opened again with a new configuration.
Enumeration Type Documentation
enum sol_gpio_direction
Possible values for the direction of a GPIO.
Enumerator
SOL_GPIO_DIR_OUT
The GPIO is an output.
For things like LEDs.
SOL_GPIO_DIR_IN
The GPIO is an input.
For buttons or similar devices.
enum sol_gpio_drive
Possible values for pull-up or pull-down resistor of a GPIO.
It will avoid values to float when this pin isn't connected. It'll define output value if nothing else is defined by software.
Enumerator
SOL_GPIO_DRIVE_NONE
Do not set any state.
SOL_GPIO_DRIVE_PULL_UP
When set as pull-up, resistor will be connected to VCC.
Logic value of output will be true while unset.
SOL_GPIO_DRIVE_PULL_DOWN
When set as pull-down, resistor will be connected to ground.
Logic value of output will be false while unset.
enum sol_gpio_edge
Possible values for the edge mode of a GPIO.
This indicate when an interrupt event should be generated.
Enumerator
SOL_GPIO_EDGE_NONE
Don't generate events.
When using this mode, no interrupt handler will be registered and it's up to the user to read the GPIO manually.
SOL_GPIO_EDGE_RISING
Events will be triggered on a rising edge.
That is, when the state of the GPIO goes from low to high.
SOL_GPIO_EDGE_FALLING
Events will be triggered onf a falling edge.
That is, when the state of the GPIO goes from high to low.
SOL_GPIO_EDGE_BOTH
Events will be triggered for both edge levels.
Both rising and falling edges will trigger events.
Function Documentation
void sol_gpio_close (struct sol_gpio * gpio)
Closes a given GPIO pin.
See Also
sol_gpio_open(), sol_gpio_open_raw().
Parameters
gpio The open sol_gpio representing the pin to be closed.
Examples:
/src/samples/common/linux-micro-init.c.
Referenced by shutdown().
enum sol_gpio_direction sol_gpio_direction_from_str (const char * direction)
Converts a string GPIO direction to sol_gpio_direction.
This function converts a string GPIO direction to enumeration sol_gpio_direction.
See Also
sol_gpio_direction_to_str().
Parameters
direction Valid values are "in", "out".
Returns
enumeration sol_gpio_direction.
const char* sol_gpio_direction_to_str (enum sol_gpio_direction direction)
Converts sol_gpio_direction to a string name.
This function converts sol_gpio_direction enumeration to a string GPIO direction name.
See Also
sol_gpio_direction_from_str().
Parameters
direction sol_gpio_direction.
Returns
String representation of the sol_gpio_direction.
enum sol_gpio_drive sol_gpio_drive_from_str (const char * drive)
Converts a string GPIO drive to sol_gpio_drive.
This function converts a string GPIO drive to enumeration sol_gpio_drive.
See Also
sol_gpio_drive_to_str().
Parameters
drive Valid values are "none", "up", "down".
Returns
enumeration sol_gpio_drive.
const char* sol_gpio_drive_to_str (enum sol_gpio_drive drive)
Converts sol_gpio_drive to a string name.
This function converts sol_gpio_drive enumeration to a string GPIO drive name.
See Also
sol_gpio_drive_from_str().
Parameters
drive sol_gpio_drive.
Returns
String representation of the sol_gpio_drive.
enum sol_gpio_edge sol_gpio_edge_from_str (const char * edge)
Converts a string GPIO edge to sol_gpio_edge.
This function converts a string GPIO edge to enumeration sol_gpio_edge
See Also
sol_gpio_edge_to_str().
Parameters
edge Valid values are "none", "rising", "falling", "any".
Returns
enumeration sol_gpio_edge
const char* sol_gpio_edge_to_str (enum sol_gpio_edge edge)
Converts sol_gpio_edge to a string name.
This function converts sol_gpio_edge enumeration to a string GPIO edge name
See Also
sol_gpio_edge_from_str().
Parameters
edge sol_gpio_edge
Returns
String representation of the sol_gpio_edge
struct sol_gpio* sol_gpio_open (uint32_t pin, const struct sol_gpio_config * config)
Opens a given pin as general purpose input or output.
A pin should be opened just once, calling this function more than once for the same pin results in undefined behaviour - per platform basis.
See Also
sol_gpio_open_raw(), sol_gpio_close().
Parameters
pin The pin to be opened.
config Contains the pin configuration.
Returns
A new sol_gpio instance on success, NULL otherwise.
Examples:
/src/samples/common/linux-micro-init.c.
Referenced by startup().
struct sol_gpio* sol_gpio_open_by_label (const char * label, const struct sol_gpio_config * config)
Opens a given pin by its board label as general purpose input or output.
This function only works when the board was successfully detected by Soletta and a corresponding pin multiplexer module was found.
A pin should be opened just once, calling this function more than once for the same pin results in undefined behavior - per platform basis.
See Also
sol_gpio_open_raw(), sol_gpio_close().
Parameters
label The pin to be opened.
config Contains the pin configuration.
Returns
A new sol_gpio instance on success, NULL otherwise.
struct sol_gpio* sol_gpio_open_raw (uint32_t pin, const struct sol_gpio_config * config)
Opens a given pin as general purpose input or output.
A pin should be opened just once, calling this function more than once for the same pin results in undefined behaviour - per platform basis.
See Also
sol_gpio_open(), sol_gpio_close().
Parameters
pin The pin to be opened.
config Contains the pin configuration.
Returns
A new sol_gpio instance on success, NULL otherwise.
int sol_gpio_read (struct sol_gpio * gpio)
Get the current value set to pin.
Parameters
gpio The opened sol_gpio that contains the pin that will be read.
Returns
The value of the pin on success, otherwise a negative errno value.
bool sol_gpio_write (struct sol_gpio * gpio, bool value)
Set an arbitrary value to pin.
Parameters
gpio The opened sol_gpio that contains the pin that will be used.
value The value that will be set to the pin.
Returns
true on success, otherwise false.
Examples:
/src/samples/common/linux-micro-init.c.
Referenced by on_timeout().