Soletta: AIO
AIO
I/O
Functions
void sol_aio_close (struct sol_aio *aio)
int32_t sol_aio_get_value (const struct sol_aio *aio)
struct sol_aio * sol_aio_open (const int device, const int pin, const unsigned int precision)
struct sol_aio * sol_aio_open_by_label (const char *label, const unsigned int precision)
struct sol_aio * sol_aio_open_raw (const int device, const int pin, const unsigned int precision)
Detailed Description
Analog I/O API for Soletta.
Function Documentation
void sol_aio_close (struct sol_aio * aio)
Close the given AIO handler.
Parameters
aio AIO handler to be closed.
References sol_aio::device, sol_aio::fp, and SOL_NULL_CHECK.
Referenced by sol_aio_open().
int32_t sol_aio_get_value (const struct sol_aio * aio)
Read the value of AIO 'pin' on 'device'.
Parameters
aio A valid AIO handler for the desired 'device'/'pin' pair.
Returns
The value read. -1 in case of error.
References sol_aio::device, sol_aio::fp, sol_aio::mask, sol_aio::pin, SOL_NULL_CHECK, and SOL_WRN.
struct sol_aio* sol_aio_open (const int device, const int pin, const unsigned int precision)
Open the given Analog I/O 'pin' on 'device' to be used.
This function also applies any Pin Multiplexer rules needed if a multiplexer for the current board was previously loaded.
Parameters
device The AIO device number.
pin The AIO pin on device.
precision The number of valid bits on the data received from the analog to digital converter.
Returns
A new AIO handler
See Also
sol_aio_open_raw
References sol_aio_close(), sol_aio_open_raw(), sol_pin_mux_setup_aio(), and SOL_WRN.
Referenced by sol_aio_open_by_label().
struct sol_aio* sol_aio_open_by_label (const char * label, const unsigned int precision)
Structure of the AIO handler Open the given board 'pin' by its label to be used as Analog I/O.
This function only works when the board was successfully detect by Soletta and a corresponding pin multiplexer module was found.
This function also applies any Pin Multiplexer rules needed if a multiplexer for the current board was previously loaded.
Parameters
label Label of the pin on the board.
precision The number of valid bits on the data received from the analog to digital converter.
Returns
A new AIO handler
See Also
sol_aio_open_raw
References sol_aio::device, sol_aio::pin, sol_aio_open(), SOL_INF, SOL_IO_AIO, sol_pin_mux_map(), and SOL_WRN.
struct sol_aio* sol_aio_open_raw (const int device, const int pin, const unsigned int precision)
Open the given Analog I/O 'pin' on 'device' to be used.
'precision' is used to filter the valid bits from the data received from hardware (which is manufacturer dependent), therefore should not be used as a way to change the output range because is applied to the least significant bits.
Parameters
device The AIO device number
pin The AIO pin on device
precision The number of valid bits on the data received from the analog to digital converter.
Returns
A new AIO handler
References AIO_DEV_PATH, sol_aio::device, sol_aio::mask, sol_aio::pin, SOL_LOG_INTERNAL_INIT_ONCE, and SOL_WRN.
Referenced by sol_aio_open().