Soletta™ Framework: Socket
Socket
Communication Modules
API to create a communication endpoint using sockets.
Data Structures
struct sol_socket
Structure to represent a socket.
struct sol_socket_ip_options
Defines specific IP layer related behaviour of a socket instance.
struct sol_socket_options
Defines the behaviour of a socket instance.
struct sol_socket_type
Structure to represent a socket class.
Typedefs
typedef struct sol_socket sol_socket
Structure to represent a socket.
typedef struct
sol_socket_ip_options sol_socket_ip_options
Defines specific IP layer related behaviour of a socket instance.
typedef struct sol_socket_options sol_socket_options
Defines the behaviour of a socket instance.
typedef struct sol_socket_type sol_socket_type
Structure to represent a socket class.
Enumerations
enum sol_socket_dtls_cipher { SOL_SOCKET_DTLS_CIPHER_ECDH_ANON_AES128_CBC_SHA256, SOL_SOCKET_DTLS_CIPHER_PSK_AES128_CCM8, SOL_SOCKET_DTLS_CIPHER_ECDHE_ECDSA_AES128_CCM8 }
Represents supported Cipher Suites for use with DTLS.
Functions
int sol_socket_bind (struct sol_socket *s, const struct sol_network_link_addr *addr)
Binds the socket to a specific address.
void sol_socket_del (struct sol_socket *s)
Destroy the socket instance.
struct sol_socket * sol_socket_ip_new (const struct sol_socket_options *options)
Creates an endpoint for communication.
int sol_socket_join_group (struct sol_socket *s, int ifindex, const struct sol_network_link_addr *group)
Joins a multicast group.
ssize_t sol_socket_recvmsg (struct sol_socket *s, struct sol_buffer *buffer, struct sol_network_link_addr *cliaddr)
Receive a message from a socket.
ssize_t sol_socket_sendmsg (struct sol_socket *s, const struct sol_buffer *buffer, const struct sol_network_link_addr *cliaddr)
Transmits a message using the socket.
int sol_socket_set_read_monitor (struct sol_socket *s, bool on)
Adds a function to be called when the socket had data to be read.
int sol_socket_set_write_monitor (struct sol_socket *s, bool on)
Adds a function to be called when the socket is able to send data.
Detailed Description
API to create a communication endpoint using sockets.
Typedef Documentation
typedef struct sol_socket sol_socket
Structure to represent a socket.
Opaque handler for a socket.
See Also
sol_socket_type
typedef struct sol_socket_ip_options sol_socket_ip_options
Defines specific IP layer related behaviour of a socket instance.
typedef struct sol_socket_options sol_socket_options
Defines the behaviour of a socket instance.
typedef struct sol_socket_type sol_socket_type
Structure to represent a socket class.
This struct contains the necessary information do deal with a socket. This contains the methods necessary to create a new socket type.
Enumeration Type Documentation
enum sol_socket_dtls_cipher
Represents supported Cipher Suites for use with DTLS.
Enumerator
SOL_SOCKET_DTLS_CIPHER_ECDH_ANON_AES128_CBC_SHA256
SOL_SOCKET_DTLS_CIPHER_PSK_AES128_CCM8
SOL_SOCKET_DTLS_CIPHER_ECDHE_ECDSA_AES128_CCM8
Function Documentation
int sol_socket_bind (struct sol_socket * s, const struct sol_network_link_addr * addr)
Binds the socket to a specific address.
Assigns the address specified by addr to the socket referred to s
Parameters
s The value got with sol_socket_ip_new()
addr The address to associate.
Returns
0 on success, error code (always negative) otherwise.
See Also
sol_socket_join_group()
sol_network_link_addr
Examples:
/src/samples/network/echo-server.c.
Referenced by startup_server().
void sol_socket_del (struct sol_socket * s)
Destroy the socket instance.
Destroy and release all the socket resources
Parameters
s The value got with sol_socket_ip_new()
See Also
sol_socket_ip_new()
Examples:
/src/samples/network/echo-client.c, and /src/samples/network/echo-server.c.
Referenced by shutdown_client(), and shutdown_server().
struct sol_socket* sol_socket_ip_new (const struct sol_socket_options * options)
Creates an endpoint for communication.
This function creates a socket using the system's default implementation.
Parameters
options The socket's options.
Returns
a handle to the socket on success, otherwise NULL is returned.
See Also
sol_socket_del()
sol_socket_options
Examples:
/src/samples/network/echo-client.c, and /src/samples/network/echo-server.c.
Referenced by startup_client(), and startup_server().
int sol_socket_join_group (struct sol_socket * s, int ifindex, const struct sol_network_link_addr * group)
Joins a multicast group.
Both IPv4 and IPv6 addresses are possible.
Parameters
s The value got with sol_socket_ip_new()
ifindex The index of the interface to be used. Interface index is available in sol_network_link.
group The address of the group to join.
Returns
0 on success, error code (always negative) otherwise.
See Also
sol_socket_bind()
sol_network_link_addr
sol_network_link
ssize_t sol_socket_recvmsg (struct sol_socket * s, struct sol_buffer * buffer, struct sol_network_link_addr * cliaddr)
Receive a message from a socket.
If it's a datagram socket, buf may be NULL, and in this case the function will only peek the incoming packet queue (not removing data from it), returning the number of bytes needed to store the next datagram and ignoring the cliaddr argument. This way, the user may allocate the exact number of bytes to hold the message contents.
Parameters
s The value got with sol_socket_ip_new()
buffer the data buffer that will be used to receive the data. If buffer does not has the flags SOL_BUFFER_FLAGS_FIXED_CAPACITY or SOL_BUFFER_FLAGS_MEMORY_NOT_OWNED this functions will allocate/re-allocate. The buffer must be initialized.
cliaddr The source address of the message.
Returns
The number of bytes read in case of success, error code (always negative) otherwise.
See Also
sol_socket_sendmsg()
sol_buffer_flags
Examples:
/src/samples/network/echo-client.c, and /src/samples/network/echo-server.c.
Referenced by on_can_read().
ssize_t sol_socket_sendmsg (struct sol_socket * s, const struct sol_buffer * buffer, const struct sol_network_link_addr * cliaddr)
Transmits a message using the socket.
Parameters
s The value got with sol_socket_ip_new()
buffer The data to be transmitted.
cliaddr The address which the data will be sent.
Returns
0 on success, error code (always negative) otherwise.
See Also
sol_socket_recvmsg()
Examples:
/src/samples/network/echo-client.c, and /src/samples/network/echo-server.c.
Referenced by on_can_write().
int sol_socket_set_read_monitor (struct sol_socket * s, bool on)
Adds a function to be called when the socket had data to be read.
Parameters
s The value got with sol_socket_ip_new()
on true to start to monitor the socket. When the socket is available to read the callback set on sol_socket_options will be called, if false it stops monitoring the socket to read.
Returns
0 on success, error code (always negative) otherwise.
See Also
sol_socket_ip_new()
Examples:
/src/samples/network/echo-client.c, and /src/samples/network/echo-server.c.
Referenced by startup_client(), and startup_server().
int sol_socket_set_write_monitor (struct sol_socket * s, bool on)
Adds a function to be called when the socket is able to send data.
Parameters
s The value got with sol_socket_ip_new()
on true to start to monitor the socket. When the socket is available to write the callback set on sol_socket_options will be called, if false it stops monitoring the socket to write.
Returns
0 on success, error code (always negative) otherwise.
See Also
sol_socket_ip_new()
Examples:
/src/samples/network/echo-client.c, and /src/samples/network/echo-server.c.
Referenced by on_can_read(), on_can_write(), and startup_client().