Soletta: Arena
Arena
Data types
Data Structures
struct sol_arena
Functions
void sol_arena_del (struct sol_arena *arena)
struct sol_arena * sol_arena_new (void)
int sol_arena_slice_dup (struct sol_arena *arena, struct sol_str_slice *dst, struct sol_str_slice slice)
int sol_arena_slice_dup_str (struct sol_arena *arena, struct sol_str_slice *dst, const char *str)
int sol_arena_slice_dup_str_n (struct sol_arena *arena, struct sol_str_slice *dst, const char *str, size_t n)
int sol_arena_slice_sprintf (struct sol_arena *arena, struct sol_str_slice *dst, const char *fmt,...)
char * sol_arena_strdup (struct sol_arena *arena, const char *str)
char * sol_arena_strdup_slice (struct sol_arena *arena, const struct sol_str_slice slice)
char * sol_arena_strndup (struct sol_arena *arena, const char *str, size_t n)
Detailed Description
An arena is an object that does allocation on user behalf and can deallocate all at once.
Function Documentation
void sol_arena_del (struct sol_arena * arena)
References SOL_NULL_CHECK, SOL_PTR_VECTOR_FOREACH_IDX, and sol_arena::str_vector.
Referenced by main(), sol_fbp_graph_fini(), sol_flow_builder_del(), and sol_http_client_request().
struct sol_arena* sol_arena_new (void)
References SOL_NULL_CHECK, and sol_arena::str_vector.
Referenced by main(), sol_fbp_graph_init(), and sol_http_client_request().
int sol_arena_slice_dup (struct sol_arena * arena, struct sol_str_slice * dst, struct sol_str_slice slice)
References sol_str_slice::data, sol_str_slice::len, and sol_arena_slice_dup_str_n().
int sol_arena_slice_dup_str (struct sol_arena * arena, struct sol_str_slice * dst, const char * str)
References sol_arena_slice_dup_str_n(), and SOL_NULL_CHECK.
int sol_arena_slice_dup_str_n (struct sol_arena * arena, struct sol_str_slice * dst, const char * str, size_t n)
References sol_str_slice::data, sol_str_slice::len, SOL_INT_CHECK, SOL_NULL_CHECK, sol_ptr_vector_append(), and sol_arena::str_vector.
Referenced by sol_arena_slice_dup(), and sol_arena_slice_dup_str().
int sol_arena_slice_sprintf (struct sol_arena * arena, struct sol_str_slice * dst, const char * fmt, ...)
References sol_str_slice::data, sol_str_slice::len, SOL_INT_CHECK, sol_ptr_vector_append(), and sol_arena::str_vector.
Referenced by sol_fbp_graph_add_node().
char* sol_arena_strdup (struct sol_arena * arena, const char * str)
References sol_arena_strndup(), and SOL_NULL_CHECK.
Referenced by sol_flow_builder_add_node(), sol_flow_builder_export_option(), and sol_flow_builder_set_type_description().
char* sol_arena_strdup_slice (struct sol_arena * arena, const struct sol_str_slice slice)
References sol_str_slice::data, sol_str_slice::len, and sol_arena_strndup().
char* sol_arena_strndup (struct sol_arena * arena, const char * str, size_t n)
References SOL_INT_CHECK, SOL_NULL_CHECK, sol_ptr_vector_append(), and sol_arena::str_vector.
Referenced by sol_arena_strdup(), and sol_arena_strdup_slice().