Soletta: Open Interconnect Consortium
Open Interconnect Consortium
Communication Modules
Data Structures
struct sol_oic_client
struct sol_oic_resource
Functions
bool sol_oic_client_find_resource (struct sol_oic_client *client, struct sol_network_link_addr *cliaddr, const char *resource_type, void(*resource_found_cb)(struct sol_oic_client *cli, struct sol_oic_resource *res, void *data), void *data)
bool sol_oic_client_get_server_info (struct sol_oic_client *client, struct sol_oic_resource *resource, void(*info_received_cb)(struct sol_oic_client *cli, const struct sol_oic_server_information *info, void *data), void *data)
bool sol_oic_client_resource_request (struct sol_oic_client *client, struct sol_oic_resource *res, sol_coap_method_t method, const struct sol_vector *reprs, void(*callback)(struct sol_oic_client *cli, const struct sol_network_link_addr *addr, const struct sol_str_slice *href, const struct sol_vector *reprs, void *data), void *data)
bool sol_oic_client_resource_set_observable (struct sol_oic_client *client, struct sol_oic_resource *res, void(*callback)(struct sol_oic_client *cli, const struct sol_network_link_addr *addr, const struct sol_str_slice *href, const struct sol_vector *reprs, void *data), void *data, bool observe)
struct sol_oic_resource * sol_oic_resource_ref (struct sol_oic_resource *r)
void sol_oic_resource_unref (struct sol_oic_resource *r)
int sol_oic_server_init (int port)
void sol_oic_server_release (void)
struct sol_oic_server_resource * sol_oic_server_add_resource (const struct sol_oic_resource_type *rt, const void *handler_data, enum sol_oic_resource_flag flags)
void sol_oic_server_del_resource (struct sol_oic_server_resource *resource)
bool sol_oic_notify_observers (struct sol_oic_server_resource *resource, const struct sol_vector *repr)
#define OIC_MANUFACTURER_NAME "Soletta"
#define OIC_MANUFACTURER_URL "https://soletta-project.org"
#define OIC_MODEL_NUMBER "Unknown"
#define OIC_MANUFACTURE_DATE "2015-01-01"
#define OIC_PLATFORM_VERSION "Unknown"
#define OIC_HARDWARE_VERSION "Unknown"
#define OIC_FIRMWARE_VERSION "Unknown"
#define OIC_SUPPORT_URL "Unknown"
Detailed Description
Implementation of protocol defined by Open Interconnect Consortium (OIC - http://openinterconnect.org/)
It's a common communication framework based on industry standard technologies to wirelessly connect and intelligently manage the flow of information among devices, regardless of form factor, operating system or service provider.
Both client and server sides are covered by this module.
Macro Definition Documentation
#define OIC_FIRMWARE_VERSION "Unknown"
#define OIC_HARDWARE_VERSION "Unknown"
#define OIC_MANUFACTURE_DATE "2015-01-01"
#define OIC_MANUFACTURER_NAME "Soletta"
#define OIC_MANUFACTURER_URL "https://soletta-project.org"
#define OIC_MODEL_NUMBER "Unknown"
#define OIC_PLATFORM_VERSION "Unknown"
#define OIC_SUPPORT_URL "Unknown"
Function Documentation
bool sol_oic_client_find_resource (struct sol_oic_client * client, struct sol_network_link_addr * cliaddr, const char * resource_type, void(*)(struct sol_oic_client *cli, struct sol_oic_resource *res, void *data) resource_found_cb, void * data)
References find_resource_ctx::client, find_resource_ctx::data, DISCOVERY_RESPONSE_TIMEOUT_MS, OIC_CLIENT_CHECK_API, sol_oic_client::server, sol_coap_add_option(), SOL_COAP_METHOD_GET, SOL_COAP_OPTION_URI_QUERY, sol_coap_packet_add_uri_path_option(), sol_coap_packet_request_new(), sol_coap_packet_unref(), sol_coap_send_packet_with_reply(), SOL_COAP_TYPE_NONCON, SOL_LOG_INTERNAL_INIT_ONCE, SOL_NULL_CHECK, sol_ptr_vector_append(), sol_ptr_vector_remove(), sol_timeout_add(), sol_util_memdup(), SOL_WRN, and find_resource_ctx::token.
Referenced by main().
bool sol_oic_client_get_server_info (struct sol_oic_client * client, struct sol_oic_resource * resource, void(*)(struct sol_oic_client *cli, const struct sol_oic_server_information *info, void *data) info_received_cb, void * data)
References sol_oic_resource::addr, server_info_ctx::client, server_info_ctx::data, OIC_CLIENT_CHECK_API, OIC_RESOURCE_CHECK_API, sol_oic_client::server, SOL_COAP_METHOD_GET, sol_coap_packet_add_uri_path_option(), sol_coap_packet_request_new(), sol_coap_packet_unref(), sol_coap_send_packet_with_reply(), SOL_COAP_TYPE_CON, SOL_LOG_INTERNAL_INIT_ONCE, SOL_NULL_CHECK, sol_util_memdup(), SOL_WRN, and server_info_ctx::token.
bool sol_oic_client_resource_request (struct sol_oic_client * client, struct sol_oic_resource * res, sol_coap_method_t method, const struct sol_vector * reprs, void(*)(struct sol_oic_client *cli, const struct sol_network_link_addr *addr, const struct sol_str_slice *href, const struct sol_vector *reprs, void *data) callback, void * data)
References OIC_CLIENT_CHECK_API, OIC_RESOURCE_CHECK_API, and SOL_NULL_CHECK.
bool sol_oic_client_resource_set_observable (struct sol_oic_client * client, struct sol_oic_resource * res, void(*)(struct sol_oic_client *cli, const struct sol_network_link_addr *addr, const struct sol_str_slice *href, const struct sol_vector *reprs, void *data) callback, void * data, bool observe)
References sol_oic_resource::observable, sol_oic_resource::observe, OIC_CLIENT_CHECK_API, OIC_RESOURCE_CHECK_API, SOL_COAP_METHOD_GET, SOL_NULL_CHECK, SOL_WRN, and sol_oic_resource::timeout.
bool sol_oic_notify_observers (struct sol_oic_server_resource * resource, const struct sol_vector * repr)
References sol_oic_server_resource::coap, sol_oic_server_resource::href, sol_oic_server::server, sol_coap_add_option(), SOL_COAP_CONTENTTYPE_APPLICATION_CBOR, sol_coap_header_set_code(), sol_coap_header_set_type(), SOL_COAP_OPTION_CONTENT_FORMAT, sol_coap_packet_notification_new(), sol_coap_packet_send_notification(), SOL_COAP_RSPCODE_INTERNAL_ERROR, SOL_COAP_RSPCODE_OK, SOL_COAP_TYPE_ACK, SOL_NULL_CHECK, and sol_oic_encode_cbor_repr().
struct sol_oic_resource* sol_oic_resource_ref (struct sol_oic_resource * r)
References OIC_RESOURCE_CHECK_API, sol_oic_resource::refcnt, and SOL_NULL_CHECK.
void sol_oic_resource_unref (struct sol_oic_resource * r)
References sol_str_slice::data, sol_oic_resource::device_id, sol_oic_resource::href, sol_oic_resource::interfaces, OIC_RESOURCE_CHECK_API, sol_oic_resource::refcnt, SOL_NULL_CHECK, sol_vector_clear(), SOL_VECTOR_FOREACH_IDX, and sol_oic_resource::types.
struct sol_oic_server_resource* sol_oic_server_add_resource (const struct sol_oic_resource_type * rt, const void * handler_data, enum sol_oic_resource_flag flags)
References sol_oic_resource_type::api_version, sol_oic_server_resource::callback, sol_oic_server_resource::coap, sol_oic_server_resource::data, sol_str_slice::data, sol_oic_server_resource::delete, sol_oic_resource_type::delete, sol_oic_server_resource::flags, sol_oic_server_resource::get, sol_oic_resource_type::get, sol_oic_resource_type::handle, sol_oic_server_resource::href, sol_oic_server_resource::iface, sol_oic_resource_type::interface, sol_vector::len, sol_str_slice::len, OIC_SERVER_CHECK, sol_oic_server_resource::post, sol_oic_resource_type::post, sol_oic_server_resource::put, sol_oic_resource_type::put, sol_oic_resource_type::resource_type, sol_oic_server::resources, sol_oic_server_resource::rt, sol_oic_server::server, sol_coap_server_register_resource(), SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, SOL_OIC_RESOURCE_TYPE_API_VERSION, sol_vector_append(), sol_vector_del(), SOL_WRN, and unlikely.
void sol_oic_server_del_resource (struct sol_oic_server_resource * resource)
References sol_oic_server_resource::coap, sol_oic_server_resource::href, sol_oic_server_resource::iface, OIC_SERVER_CHECK, sol_oic_server::resources, sol_oic_server_resource::rt, sol_oic_server::server, sol_coap_server_unregister_resource(), SOL_ERR, SOL_NULL_CHECK, sol_vector_del(), and SOL_VECTOR_FOREACH_REVERSE_IDX.
Referenced by main().
int sol_oic_server_init (int port)
References sol_oic_server::information, sol_oic_server::refcnt, sol_oic_server::resources, sol_oic_server::server, sol_coap_server_new(), sol_coap_server_register_resource(), sol_coap_server_unregister_resource(), SOL_LOG_INTERNAL_INIT_ONCE, SOL_NULL_CHECK, and sol_vector_init().
Referenced by main().
void sol_oic_server_release (void)
References sol_oic_server_resource::coap, sol_oic_server::information, OIC_SERVER_CHECK, sol_oic_server::refcnt, sol_oic_server::resources, sol_oic_server::server, sol_coap_server_unref(), sol_coap_server_unregister_resource(), sol_vector_clear(), and SOL_VECTOR_FOREACH_REVERSE_IDX.
Referenced by main().