Soletta: Message Digest (Hash)
Message Digest (Hash)
Cryptography And Signatures
Data Structures
struct sol_message_digest_config
Macros
#define SOL_MESSAGE_DIGEST_CONFIG_API_VERSION (1)
Functions
void sol_message_digest_del (struct sol_message_digest *handle)
int sol_message_digest_feed (struct sol_message_digest *handle, struct sol_blob *input, bool is_last)
struct sol_message_digest * sol_message_digest_new (const struct sol_message_digest_config *config)
Variables
const char * sol_message_digest_config::algorithm
uint16_t sol_message_digest_config::api_version
const void * sol_message_digest_config::data
struct sol_str_slice sol_message_digest_config::key
void(* sol_message_digest_config::on_digest_ready)(void *data, struct sol_message_digest *handle, struct sol_blob *output)
void(* sol_message_digest_config::on_feed_done)(void *data, struct sol_message_digest *handle, struct sol_blob *input)
Detailed Description
Message Digest algorithms will take a byte stream and compute a hash that may be used to later validate the identity. Even the smallest variation of the input data will have an avalanche effect that drastically change the output data.
Wikipedia says (https://en.wikipedia.org/wiki/Cryptographic_hash_function): The ideal cryptographic hash function has four main properties:
it is easy to compute the hash value for any given message
it is infeasible to generate a message from its hash
it is infeasible to modify a message without changing the hash
it is infeasible to find two different messages with the same hash.
Common Message Digest algorithms are CRC32, MD5, SHA1, SHA256 and SHA512. Most of these are already broken, such as CRC32 and nowadays MD5 and even SHA1, then before picking one for your application, check the one that is more secure and hard to break, such as SHA512.
Macro Definition Documentation
#define SOL_MESSAGE_DIGEST_CONFIG_API_VERSION (1)
Referenced by sol_message_digest_new().
Function Documentation
void sol_message_digest_del (struct sol_message_digest * handle)
Delete a message digest handle.
Parameters
handle the handle previously created with sol_message_digest_new().
References sol_message_digest::deleted, sol_message_digest::digest, sol_vector::len, sol_message_digest::pending_feed, sol_message_digest::refcnt, SOL_DBG, SOL_EXP_CHECK, SOL_INT_CHECK, SOL_NULL_CHECK, and SOL_WRN.
Referenced by sol_message_digest_new().
int sol_message_digest_feed (struct sol_message_digest * handle, struct sol_blob * input, bool is_last)
Feed message (data) to be digested (hashed).
This is the core of the message digest as it will take chunks of data (message) to process and then produce the final hash (digest) at the end.
The message digest implementation is asynchronous to allow to offload computation to another unit such as hardware acceleration or a thread, not blocking the main thread while it happens. Thus the lifetime of input and output data must be clear, and struct sol_blob is used to manage that.
After a chunk is fed with this function, it is queued for processing. Once that chunk is done, on_feed_done() is called with that information. This may be used to feed more data.
Once the last chunk is fed (is_last=true), then the final digest is calculated and delivered by calling () function provided via sol_message_digest_config.
Parameters
handle the handle previously created with sol_message_digest_new().
input the input data to be consumed. The blob will be referenced until data is processed and automatically unreferenced after the user callback config->on_feed_done() returns.
is_last indicates whenever this is the last input data chunk to be processed. Some algorithms operates on block size and must use padding if there is remaining data that is not of that size. After the last blob is processed, config->on_digest_ready() is called with the resulting digest as a blob.
Returns
0 on success, -errno otherwise. If error, then the input reference is not taken.
References sol_message_digest_pending_feed::blob, sol_message_digest::deleted, sol_message_digest::finished, sol_message_digest_pending_feed::is_last, sol_vector::len, sol_message_digest_pending_feed::offset, sol_message_digest::pending_feed, sol_message_digest::refcnt, sol_blob::size, sol_blob_ref(), sol_blob_unref(), SOL_DBG, SOL_EXP_CHECK, SOL_INT_CHECK, SOL_INT_CHECK_GOTO, SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, sol_vector_append(), sol_vector_del(), and SOL_WRN.
struct sol_message_digest* sol_message_digest_new (const struct sol_message_digest_config * config)
Create a new handle to feed the message to digest.
Parameters
config the configuration (algorithm, callbacks) to use.
Returns
a newly allocated handle on success or NULL on failure and errno is set. For instance if the algorithm is not supported, ENOTSUP if the algorithm is not supported.
See Also
sol_message_digest_del()
sol_message_digest_feed()
References AF_ALG, sol_message_digest_config::algorithm, sol_message_digest_config::api_version, config, sol_message_digest_common_new_params::config, sol_message_digest_info::context_size, sol_message_digest_common_new_params::context_size, sol_message_digest_common_new_params::context_template, sol_str_slice::data, sol_message_digest_info::digest_size, sol_message_digest_algorithm_info::digest_size, sol_message_digest_common_new_params::digest_size, sol_message_digest_info::init, sol_message_digest_config::key, sol_str_slice::len, sol_message_digest_config::on_digest_ready, sol_message_digest_info::ops, sol_message_digest_common_new_params::ops, SOL_ALG, SOL_DBG, sol_message_digest_common_new(), SOL_MESSAGE_DIGEST_CONFIG_API_VERSION, sol_message_digest_del(), SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, SOL_STR_SLICE_PRINT, sol_str_table_ptr_lookup, sol_util_strerrora, SOL_WRN, streqn, and strndupa.
Variable Documentation
const char* sol_message_digest_config::algorithm
Algorithm name.
The name should match Linux kernel's names, such as:
md5
sha1
hmac(sha1)
crc32
This pointer must NOT be NULL.
Referenced by sol_message_digest_common_new(), and sol_message_digest_new().
uint16_t sol_message_digest_config::api_version
api_version must match SOL_MESSAGE_DIGEST_CONFIG_API_VERSION at runtime.
Referenced by sol_message_digest_new().
const void* sol_message_digest_config::data
The context data to give to all callbacks.
Referenced by sol_message_digest_common_new().
struct sol_str_slice sol_message_digest_config::key
If provided (length > 0), then is used by the message digest hash function.
A slice is used so the key may contain null-bytes inside, the whole slice length will be used.
Referenced by sol_message_digest_new().
void(* sol_message_digest_config::on_digest_ready)(void *data, struct sol_message_digest *handle, struct sol_blob *output)
The mandatory callback function to report digest is ready.
This pointer must NOT be NULL.
The parameters are:
data the context data given with this configuration.
handle the handle used to push data.
output the resulting digest (hash). It is binary and can be encoded with tools such as sol_buffer_append_as_base16(). The blob is valid while the callback happens, if one wants it to live further increase its reference with sol_blob_ref().
Note
it is safe to delete the message digest handle from inside this callback.
Referenced by sol_message_digest_common_new(), and sol_message_digest_new().
void(* sol_message_digest_config::on_feed_done)(void *data, struct sol_message_digest *handle, struct sol_blob *input)
The optional callback function to report digest consumed given data.
This pointer may be NULL.
This function may be used to report progress of the whole process or to control a possibly lengthy and costly feed pipeline, this way the pipeline will only feed data once its needed.
The parameters are:
data the context data given with this configuration.
handle the handle used to push data.
input the input data originally pushed/fed. There is no need to sol_blob_unref() it is done automatically.
Note
it is safe to delete the message digest handle from inside this callback.
Referenced by sol_message_digest_common_new().