Soletta™ Framework: src/samples/bluetooth/heartbeat.c File Reference
heartbeat.c File Reference
#include <errno.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "soletta.h"
#include "sol-log.h"
#include "sol-mainloop.h"
#include "sol-bluetooth.h"
#include "sol-gatt.h"
Macros
#define UUID_HRS 0x180d
#define UUID_HRS_MEASUREMENT 0x2a37
Functions
static void enabled (void *data, bool powered)
static int hrs_measurement_read (struct sol_gatt_pending *op, uint16_t offset)
static void shutdown (void)
SOL_MAIN_DEFAULT (startup, shutdown)
static void startup (void)
static bool timeout_cb (void *data)
Variables
static struct sol_gatt_attr attrs []
static struct sol_bt_session * session
static struct sol_timeout * timeout
Macro Definition Documentation
#define UUID_HRS 0x180d
Examples:
/src/samples/bluetooth/heartbeat.c.
#define UUID_HRS_MEASUREMENT 0x2a37
Examples:
/src/samples/bluetooth/heartbeat.c.
Function Documentation
static void enabled (void * data, bool powered) static
References sol_gatt_register_attributes(), SOL_INF, SOL_INT_CHECK, SOL_NULL_CHECK, sol_timeout_add(), timeout, and timeout_cb().
Referenced by startup().
static int hrs_measurement_read (struct sol_gatt_pending * op, uint16_t offset) static
Examples:
/src/samples/bluetooth/heartbeat.c.
References SOL_BUFFER_FLAGS_MEMORY_NOT_OWNED, SOL_BUFFER_FLAGS_NO_NUL_BYTE, sol_buffer_init_flags(), sol_gatt_pending_reply(), SOL_INT_CHECK, and sol_buffer::used.
static void shutdown (void) static
References session, sol_bt_disable(), and sol_gatt_unregister_attributes().
SOL_MAIN_DEFAULT (startup , shutdown)
static void startup (void) static
References enabled(), session, sol_bt_enable(), sol_quit_with_code(), and SOL_WRN.
static bool timeout_cb (void * data) static
References sol_gatt_notify(), and SOL_INT_CHECK.
Referenced by enabled().
Variable Documentation
struct sol_gatt_attr attrs[] static
Initial value:
= {
    SOL_GATT_SERVICE_UUID_16(UUID_HRS),
    SOL_GATT_CHARACTERISTIC_UUID_16(UUID_HRS_MEASUREMENT,
        SOL_GATT_CHR_FLAGS_READ | SOL_GATT_CHR_FLAGS_INDICATE,
        .read = hrs_measurement_read),
    SOL_GATT_ATTR_INVALID,
}
Examples:
/src/samples/bluetooth/heartbeat.c.
struct sol_bt_session* session static
Referenced by shutdown(), and startup().
struct sol_timeout* timeout static
Referenced by enabled().