Soletta™ Framework: src/samples/flow/c-api/highlevel.c File Reference
highlevel.c File Reference
Example of soletta's flow in C using high-level API.
#include <stdlib.h>
#include "sol-macros.h"
#include "soletta.h"
#include "sol-flow-builder.h"
#include "custom-node-types-gen.h"
Functions
static void shutdown (void)
SOL_MAIN_DEFAULT (startup, shutdown)
static void startup (void)
Variables
static struct sol_flow_node * flow
static struct sol_flow_node_type * flow_node_type
Detailed Description
Example of soletta's flow in C using high-level API.
It will manipulate the nodes and connections using easy to use and human readable strings.
There is a runtime penalty as this requires node type descriptions to be available, consuming disk and memory space, thus it is not recommended for very constrained systems.
See lowlevel.c on how to use the lowlevel API that does not rely on node type descriptions.
Function Documentation
static void shutdown (void) static
References flow, sol_flow_node_del(), and sol_flow_node_type_del().
SOL_MAIN_DEFAULT (startup , shutdown)
static void startup (void) static
References builder, flow, sol_flow_builder_add_node(), sol_flow_builder_add_node_by_type(), sol_flow_builder_connect(), sol_flow_builder_del(), sol_flow_builder_get_node_type(), sol_flow_builder_new(), and sol_flow_node_new().
Variable Documentation
struct sol_flow_node* flow static
Examples:
/src/samples/flow/c-api/highlevel.c, /src/samples/flow/c-api/lowlevel.c, and /src/samples/flow/c-api/simple-c-type.c.
Referenced by shutdown(), and startup().
struct sol_flow_node_type* flow_node_type static
Examples:
/src/samples/flow/c-api/highlevel.c, and /src/samples/flow/c-api/simple-c-type.c.