Soletta: src/modules/flow/gtk/label.c File Reference
label.c File Reference
#include "label.h"
#include "sol-flow/gtk.h"
Functions
DEFINE_DEFAULT_OPEN_CLOSE (label)
int gtk_label_in_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
Function Documentation
DEFINE_DEFAULT_OPEN_CLOSE (label)
int gtk_label_in_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References gtk_label_data::empty_count, name, sol_flow_packet_get_boolean(), sol_flow_packet_get_byte(), sol_flow_packet_get_irange_value(), sol_flow_packet_get_string(), sol_flow_packet_get_type(), SOL_FLOW_PACKET_TYPE_BOOLEAN, SOL_FLOW_PACKET_TYPE_BYTE, SOL_FLOW_PACKET_TYPE_EMPTY, SOL_FLOW_PACKET_TYPE_IRANGE, SOL_FLOW_PACKET_TYPE_STRING, SOL_INT_CHECK, SOL_WRN, and gtk_common_data::widget.