Soletta™ Framework: src/samples/common/linux-micro-init.c File Reference
linux-micro-init.c File Reference
#include <ctype.h>
#include <stdio.h>
#include <string.h>
#include "soletta.h"
#include "sol-platform.h"
#include "sol-gpio.h"
#include "sol-util.h"
#include "sol-util-file.h"
Macros
#define _GNU_SOURCE
Functions
static void on_platform_state_change (void *data, enum sol_platform_state state)
static void on_service_change (void *data, const char *service, enum sol_platform_service_state state)
static bool on_timeout (void *data)
static int parse_cmdline_pin (void)
static int parse_kcmdline_pin (void)
static int parse_kcmdline_pin_entry (const char *start, size_t len)
static void shutdown (void)
SOL_MAIN_DEFAULT (startup, shutdown)
static void startup (void)
Variables
static struct sol_gpio * gpio
static bool gpio_state = false
static const char * services []
static struct sol_timeout * timeout
Macro Definition Documentation
#define _GNU_SOURCE
Function Documentation
static void on_platform_state_change (void * data, enum sol_platform_state state) static
Examples:
/src/samples/common/linux-micro-init.c.
Referenced by shutdown(), and startup().
static void on_service_change (void * data, const char * service, enum sol_platform_service_state state) static
Examples:
/src/samples/common/linux-micro-init.c.
Referenced by shutdown(), and startup().
static bool on_timeout (void * data) static
Examples:
/src/samples/common/linux-micro-init.c, and /src/samples/flow/c-api/simple-c-type.c.
References gpio, gpio_state, and sol_gpio_write().
Referenced by startup().
static int parse_cmdline_pin (void) static
Examples:
/src/samples/common/linux-micro-init.c.
References sol_argc(), sol_argv(), and value.
Referenced by startup().
static int parse_kcmdline_pin (void) static
Examples:
/src/samples/common/linux-micro-init.c.
References parse_kcmdline_pin_entry(), and sol_util_read_file().
Referenced by startup().
static int parse_kcmdline_pin_entry (const char * start, size_t len) static
Examples:
/src/samples/common/linux-micro-init.c.
Referenced by parse_kcmdline_pin().
static void shutdown (void) static
References gpio, on_platform_state_change(), on_service_change(), services, sol_gpio_close(), sol_platform_del_service_monitor(), sol_platform_del_state_monitor(), sol_timeout_del(), and timeout.
SOL_MAIN_DEFAULT (startup , shutdown)
static void startup (void) static
References sol_gpio_config::api_version, gpio, on_platform_state_change(), on_service_change(), on_timeout(), parse_cmdline_pin(), parse_kcmdline_pin(), services, SOL_GPIO_CONFIG_API_VERSION, SOL_GPIO_DIR_OUT, sol_gpio_open(), sol_platform_add_service_monitor(), sol_platform_add_state_monitor(), sol_platform_get_service_state(), sol_platform_get_state(), SOL_SET_API_VERSION, sol_timeout_add(), and timeout.
Variable Documentation
struct sol_gpio* gpio static
Examples:
/src/samples/common/linux-micro-init.c.
Referenced by on_timeout(), shutdown(), and startup().
bool gpio_state = false static
Examples:
/src/samples/common/linux-micro-init.c.
Referenced by on_timeout().
const char* services[] static
Initial value:
= {
    "console",
    "hostname",
    "network-up",
    "sysctl",
    "watchdog",
    NULL
}
Examples:
/src/samples/common/linux-micro-init.c.
Referenced by shutdown(), and startup().
struct sol_timeout* timeout static
Referenced by shutdown(), and startup().