Soletta™ Framework: src/samples/coap/lwm2m-bs-server.c File Reference
lwm2m-bs-server.c File Reference
#include "sol-lwm2m-bs-server.h"
#include "sol-mainloop.h"
#include "sol-vector.h"
#include "sol-util.h"
#include <stdio.h>
#include <stdbool.h>
#include <errno.h>
#include <unistd.h>
Macros
#define ACCESS_CONTROL_OBJ_ACL_RES_ID (2)
#define ACCESS_CONTROL_OBJ_ID (2)
#define ACCESS_CONTROL_OBJ_INSTANCE_RES_ID (1)
#define ACCESS_CONTROL_OBJ_OBJECT_RES_ID (0)
#define ACCESS_CONTROL_OBJ_OWNER_RES_ID (3)
#define BS_SERVER_PRIVATE_KEY ("9b7dfec20e49fe2cacf23fb21d06a8dc496530c695ec24cdf6c002ce44afa5fb")
#define BS_SERVER_PUBLIC_KEY
#define CLIENT_BS_PSK_ID ("cli1-bs")
#define CLIENT_BS_PSK_KEY ("FEDCBA9876543210")
#define CLIENT_PUBLIC_KEY
#define CLIENT_SERVER_PSK_ID ("cli1")
#define CLIENT_SERVER_PSK_KEY ("0123456789ABCDEF")
#define LIFETIME (60)
#define PSK_KEY_LEN 16
#define RPK_PRIVATE_KEY_LEN 32
#define RPK_PUBLIC_KEY_LEN (2 * RPK_PRIVATE_KEY_LEN)
#define SECURITY_BOOTSTRAP_SERVER_ACCOUNT_TIMEOUT_RES_ID (12)
#define SECURITY_CLIENT_HOLD_OFF_TIME_RES_ID (11)
#define SECURITY_IS_BOOTSTRAP_RES_ID (1)
#define SECURITY_OBJ_ID (0)
#define SECURITY_PUBLIC_KEY_OR_IDENTITY_RES_ID (3)
#define SECURITY_SECRET_KEY_RES_ID (5)
#define SECURITY_SECURITY_MODE_RES_ID (2)
#define SECURITY_SERVER_ID_RES_ID (10)
#define SECURITY_SERVER_PUBLIC_KEY_RES_ID (4)
#define SECURITY_SERVER_URI_RES_ID (0)
#define SERVER_OBJ_BINDING_RES_ID (7)
#define SERVER_OBJ_ID (1)
#define SERVER_OBJ_LIFETIME_RES_ID (1)
#define SERVER_OBJ_REGISTRATION_UPDATE_RES_ID (8)
#define SERVER_OBJ_SHORT_RES_ID (0)
Functions
static void bootstrap_cb (void *data, struct sol_lwm2m_bootstrap_server *server, struct sol_lwm2m_bootstrap_client_info *bs_cinfo)
static void delete_all_cb (void *data, struct sol_lwm2m_bootstrap_server *server, struct sol_lwm2m_bootstrap_client_info *bs_cinfo, const char *path, enum sol_coap_response_code response_code)
int main (int argc, char *argv[])
static void write_resource_cb (void *data, struct sol_lwm2m_bootstrap_server *server, struct sol_lwm2m_bootstrap_client_info *bs_cinfo, const char *path, enum sol_coap_response_code response_code)
static void write_sec_one_cb (void *data, struct sol_lwm2m_bootstrap_server *server, struct sol_lwm2m_bootstrap_client_info *bs_cinfo, const char *path, enum sol_coap_response_code response_code)
static void write_server_one_cb (void *data, struct sol_lwm2m_bootstrap_server *server, struct sol_lwm2m_bootstrap_client_info *bs_cinfo, const char *path, enum sol_coap_response_code response_code)
static void write_servers_cb (void *data, struct sol_lwm2m_bootstrap_server *server, struct sol_lwm2m_bootstrap_client_info *bs_cinfo, const char *path, enum sol_coap_response_code response_code)
Variables
static struct sol_blob binding
const char * known_clients [] = { "cli1", "cli2", NULL }
static struct sol_blob psk_id_0
static struct sol_blob psk_key_0
static struct sol_blob server_one_addr
Macro Definition Documentation
#define ACCESS_CONTROL_OBJ_ACL_RES_ID (2)
Examples:
/src/samples/coap/lwm2m-client.c.
#define ACCESS_CONTROL_OBJ_ID (2)
Examples:
/src/samples/coap/lwm2m-client.c.
#define ACCESS_CONTROL_OBJ_INSTANCE_RES_ID (1)
Examples:
/src/samples/coap/lwm2m-client.c.
#define ACCESS_CONTROL_OBJ_OBJECT_RES_ID (0)
Examples:
/src/samples/coap/lwm2m-client.c.
#define ACCESS_CONTROL_OBJ_OWNER_RES_ID (3)
Examples:
/src/samples/coap/lwm2m-client.c.
#define BS_SERVER_PRIVATE_KEY ("9b7dfec20e49fe2cacf23fb21d06a8dc496530c695ec24cdf6c002ce44afa5fb")
Examples:
/src/samples/coap/lwm2m-bs-server.c.
Referenced by main().
#define BS_SERVER_PUBLIC_KEY
Value:
("cd4110e97bbd6e7e5a800028079d02915c70b915ea4596402098deea585eb7ad" \
    "f3e080487327f70758b13bc0583f4293d13288a0164a8e324779aa4f7ada26c1")
Examples:
/src/samples/coap/lwm2m-bs-server.c, and /src/samples/coap/lwm2m-client.c.
Referenced by main().
#define CLIENT_BS_PSK_ID ("cli1-bs")
Examples:
/src/samples/coap/lwm2m-bs-server.c, and /src/samples/coap/lwm2m-client.c.
Referenced by main().
#define CLIENT_BS_PSK_KEY ("FEDCBA9876543210")
Examples:
/src/samples/coap/lwm2m-bs-server.c, and /src/samples/coap/lwm2m-client.c.
Referenced by main().
#define CLIENT_PUBLIC_KEY
Value:
("D055EE14084D6E0615599DB583913E4A3E4526A2704D61F27A4CCFBA9758EF9A" \
    "B418B64AFE8030DA1DDCF4F42E2F2631D043B1FB03E22F4D17DE43F9F9ADEE70")
Examples:
/src/samples/coap/lwm2m-bs-server.c, /src/samples/coap/lwm2m-client.c, and /src/samples/coap/lwm2m-server.c.
Referenced by main().
#define CLIENT_SERVER_PSK_ID ("cli1")
Examples:
/src/samples/coap/lwm2m-bs-server.c, /src/samples/coap/lwm2m-client.c, and /src/samples/coap/lwm2m-server.c.
#define CLIENT_SERVER_PSK_KEY ("0123456789ABCDEF")
Examples:
/src/samples/coap/lwm2m-bs-server.c, /src/samples/coap/lwm2m-client.c, and /src/samples/coap/lwm2m-server.c.
#define LIFETIME (60)
Examples:
/src/samples/coap/lwm2m-bs-server.c, and /src/samples/coap/lwm2m-client.c.
Referenced by write_sec_one_cb(), write_server_one_cb(), and write_servers_cb().
#define PSK_KEY_LEN 16
Examples:
/src/samples/coap/lwm2m-bs-server.c, /src/samples/coap/lwm2m-client.c, and /src/samples/coap/lwm2m-server.c.
Referenced by main().
#define RPK_PRIVATE_KEY_LEN 32
Examples:
/src/samples/coap/lwm2m-bs-server.c, /src/samples/coap/lwm2m-client.c, and /src/samples/coap/lwm2m-server.c.
Referenced by main().
#define RPK_PUBLIC_KEY_LEN (2 * RPK_PRIVATE_KEY_LEN)
Examples:
/src/samples/coap/lwm2m-bs-server.c, /src/samples/coap/lwm2m-client.c, and /src/samples/coap/lwm2m-server.c.
Referenced by main().
#define SECURITY_BOOTSTRAP_SERVER_ACCOUNT_TIMEOUT_RES_ID (12)
Examples:
/src/samples/coap/lwm2m-client.c.
#define SECURITY_CLIENT_HOLD_OFF_TIME_RES_ID (11)
Examples:
/src/samples/coap/lwm2m-client.c.
#define SECURITY_IS_BOOTSTRAP_RES_ID (1)
Examples:
/src/samples/coap/lwm2m-bs-server.c, and /src/samples/coap/lwm2m-client.c.
Referenced by delete_all_cb().
#define SECURITY_OBJ_ID (0)
Examples:
/src/samples/coap/lwm2m-client.c.
#define SECURITY_PUBLIC_KEY_OR_IDENTITY_RES_ID (3)
Examples:
/src/samples/coap/lwm2m-bs-server.c, and /src/samples/coap/lwm2m-client.c.
Referenced by delete_all_cb().
#define SECURITY_SECRET_KEY_RES_ID (5)
Examples:
/src/samples/coap/lwm2m-bs-server.c, and /src/samples/coap/lwm2m-client.c.
Referenced by delete_all_cb().
#define SECURITY_SECURITY_MODE_RES_ID (2)
Examples:
/src/samples/coap/lwm2m-bs-server.c, and /src/samples/coap/lwm2m-client.c.
Referenced by delete_all_cb().
#define SECURITY_SERVER_ID_RES_ID (10)
Examples:
/src/samples/coap/lwm2m-bs-server.c, and /src/samples/coap/lwm2m-client.c.
Referenced by delete_all_cb().
#define SECURITY_SERVER_PUBLIC_KEY_RES_ID (4)
Examples:
/src/samples/coap/lwm2m-client.c.
#define SECURITY_SERVER_URI_RES_ID (0)
Examples:
/src/samples/coap/lwm2m-bs-server.c, and /src/samples/coap/lwm2m-client.c.
Referenced by delete_all_cb().
#define SERVER_OBJ_BINDING_RES_ID (7)
Examples:
/src/samples/coap/lwm2m-bs-server.c, and /src/samples/coap/lwm2m-client.c.
Referenced by write_sec_one_cb(), and write_server_one_cb().
#define SERVER_OBJ_ID (1)
Examples:
/src/samples/coap/lwm2m-client.c.
#define SERVER_OBJ_LIFETIME_RES_ID (1)
Examples:
/src/samples/coap/lwm2m-bs-server.c, and /src/samples/coap/lwm2m-client.c.
Referenced by write_sec_one_cb(), write_server_one_cb(), and write_servers_cb().
#define SERVER_OBJ_REGISTRATION_UPDATE_RES_ID (8)
Examples:
/src/samples/coap/lwm2m-client.c.
#define SERVER_OBJ_SHORT_RES_ID (0)
Examples:
/src/samples/coap/lwm2m-bs-server.c, and /src/samples/coap/lwm2m-client.c.
Referenced by write_sec_one_cb(), and write_server_one_cb().
Function Documentation
static void bootstrap_cb (void * data, struct sol_lwm2m_bootstrap_server * server, struct sol_lwm2m_bootstrap_client_info * bs_cinfo) static
Examples:
/src/samples/coap/lwm2m-bs-server.c, and /src/samples/coap/lwm2m-client.c.
References delete_all_cb(), sol_lwm2m_bootstrap_client_info_get_name(), and sol_lwm2m_bootstrap_server_delete_object_instance().
Referenced by main().
static void delete_all_cb (void * data, struct sol_lwm2m_bootstrap_server * server, struct sol_lwm2m_bootstrap_client_info * bs_cinfo, const char * path, enum sol_coap_response_code response_code) static
Examples:
/src/samples/coap/lwm2m-bs-server.c.
References SECURITY_IS_BOOTSTRAP_RES_ID, SECURITY_PUBLIC_KEY_OR_IDENTITY_RES_ID, SECURITY_SECRET_KEY_RES_ID, SECURITY_SECURITY_MODE_RES_ID, SECURITY_SERVER_ID_RES_ID, SECURITY_SERVER_URI_RES_ID, SOL_COAP_RESPONSE_CODE_DELETED, sol_lwm2m_bootstrap_client_info_get_name(), sol_lwm2m_bootstrap_server_write(), sol_lwm2m_resource_clear(), SOL_LWM2M_RESOURCE_DATA_TYPE_BOOL, SOL_LWM2M_RESOURCE_DATA_TYPE_STRING, SOL_LWM2M_RESOURCE_SINGLE_INIT, SOL_LWM2M_RESOURCE_SINGLE_INT_INIT, SOL_LWM2M_SECURITY_MODE_PRE_SHARED_KEY, sol_util_array_size, and write_sec_one_cb().
Referenced by bootstrap_cb().
int main (int argc, char * argv[])
References bootstrap_cb(), BS_SERVER_PRIVATE_KEY, BS_SERVER_PUBLIC_KEY, CLIENT_BS_PSK_ID, CLIENT_BS_PSK_KEY, CLIENT_PUBLIC_KEY, sol_lwm2m_security_psk::id, key, sol_lwm2m_security_psk::key, known_clients, port, sol_lwm2m_security_rpk::private_key, PSK_KEY_LEN, sol_lwm2m_security_rpk::public_key, RPK_PRIVATE_KEY_LEN, RPK_PUBLIC_KEY_LEN, server, sol_blob_new_dup(), sol_blob_unref(), SOL_DECODE_BOTH, sol_init(), sol_lwm2m_bootstrap_server_add_request_monitor(), sol_lwm2m_bootstrap_server_del(), sol_lwm2m_bootstrap_server_new(), SOL_LWM2M_SECURITY_MODE_CERTIFICATE, SOL_LWM2M_SECURITY_MODE_PRE_SHARED_KEY, SOL_LWM2M_SECURITY_MODE_RAW_PUBLIC_KEY, sol_run(), sol_shutdown(), sol_str_slice_from_str(), sol_util_base16_decode(), and usage().
static void write_resource_cb (void * data, struct sol_lwm2m_bootstrap_server * server, struct sol_lwm2m_bootstrap_client_info * bs_cinfo, const char * path, enum sol_coap_response_code response_code) static
Examples:
/src/samples/coap/lwm2m-bs-server.c.
References SOL_COAP_RESPONSE_CODE_CHANGED, sol_lwm2m_bootstrap_client_info_get_name(), and sol_lwm2m_bootstrap_server_send_finish().
Referenced by write_servers_cb().
static void write_sec_one_cb (void * data, struct sol_lwm2m_bootstrap_server * server, struct sol_lwm2m_bootstrap_client_info * bs_cinfo, const char * path, enum sol_coap_response_code response_code) static
Examples:
/src/samples/coap/lwm2m-bs-server.c.
References LIFETIME, SERVER_OBJ_BINDING_RES_ID, SERVER_OBJ_LIFETIME_RES_ID, SERVER_OBJ_SHORT_RES_ID, SOL_COAP_RESPONSE_CODE_CHANGED, sol_lwm2m_bootstrap_client_info_get_name(), sol_lwm2m_bootstrap_server_write(), sol_lwm2m_resource_clear(), SOL_LWM2M_RESOURCE_DATA_TYPE_STRING, SOL_LWM2M_RESOURCE_SINGLE_INIT, SOL_LWM2M_RESOURCE_SINGLE_INT_INIT, sol_util_array_size, and write_server_one_cb().
Referenced by delete_all_cb().
static void write_server_one_cb (void * data, struct sol_lwm2m_bootstrap_server * server, struct sol_lwm2m_bootstrap_client_info * bs_cinfo, const char * path, enum sol_coap_response_code response_code) static
Examples:
/src/samples/coap/lwm2m-bs-server.c.
References LIFETIME, SERVER_OBJ_BINDING_RES_ID, SERVER_OBJ_LIFETIME_RES_ID, SERVER_OBJ_SHORT_RES_ID, SOL_COAP_RESPONSE_CODE_CHANGED, sol_lwm2m_bootstrap_client_info_get_name(), sol_lwm2m_bootstrap_server_write_object(), sol_lwm2m_resource_clear(), SOL_LWM2M_RESOURCE_DATA_TYPE_STRING, SOL_LWM2M_RESOURCE_SINGLE_INIT, SOL_LWM2M_RESOURCE_SINGLE_INT_INIT, sol_util_array_size, and write_servers_cb().
Referenced by write_sec_one_cb().
static void write_servers_cb (void * data, struct sol_lwm2m_bootstrap_server * server, struct sol_lwm2m_bootstrap_client_info * bs_cinfo, const char * path, enum sol_coap_response_code response_code) static
Examples:
/src/samples/coap/lwm2m-bs-server.c.
References LIFETIME, SERVER_OBJ_LIFETIME_RES_ID, SOL_COAP_RESPONSE_CODE_CHANGED, sol_lwm2m_bootstrap_client_info_get_name(), sol_lwm2m_bootstrap_server_write(), sol_lwm2m_resource_clear(), SOL_LWM2M_RESOURCE_SINGLE_INT_INIT, and write_resource_cb().
Referenced by write_server_one_cb().
Variable Documentation
struct sol_blob binding static
Initial value:
= {
    .type = &SOL_BLOB_TYPE_NO_FREE,
    .parent = NULL,
    .mem = (void *)"U",
    .size = sizeof("U") - 1,
    .refcnt = 1
}
Examples:
/src/samples/coap/lwm2m-bs-server.c, and /src/samples/coap/lwm2m-client.c.
const char* known_clients[] = { "cli1", "cli2", NULL }
Examples:
/src/samples/coap/lwm2m-bs-server.c.
Referenced by main().
struct sol_blob psk_id_0 static
Initial value:
= {
    .type = &SOL_BLOB_TYPE_NO_FREE,
    .parent = NULL,
    .mem = (void *)CLIENT_SERVER_PSK_ID,
    .size = sizeof(CLIENT_SERVER_PSK_ID) - 1,
    .refcnt = 1
}
Examples:
/src/samples/coap/lwm2m-bs-server.c.
struct sol_blob psk_key_0 static
Initial value:
= {
    .type = &SOL_BLOB_TYPE_NO_FREE,
    .parent = NULL,
    .mem = (void *)CLIENT_SERVER_PSK_KEY,
    .size = sizeof(CLIENT_SERVER_PSK_KEY) - 1,
    .refcnt = 1
}
Examples:
/src/samples/coap/lwm2m-bs-server.c.
struct sol_blob server_one_addr static
Initial value:
= {
    .type = &SOL_BLOB_TYPE_NO_FREE,
    .parent = NULL,
    .mem = (void *)"coaps://localhost:5684",
    .size = sizeof("coaps://localhost:5684") - 1,
    .refcnt = 1
}
Examples:
/src/samples/coap/lwm2m-bs-server.c.