Soletta™ Framework: src/samples/coap/lwm2m-client.c File Reference
lwm2m-client.c File Reference
#include "sol-lwm2m-client.h"
#include "sol-mainloop.h"
#include "sol-vector.h"
#include "sol-util.h"
#include <stdio.h>
#include <stdbool.h>
#include <errno.h>
#include <time.h>
#include <unistd.h>
Data Structures
struct access_control_obj_instance_ctx
struct acl_instance
struct client_data_ctx
struct location_obj_instance_ctx
struct security_obj_instance_ctx
struct server_obj_instance_ctx
Macros
#define ACCESS_CONTROL_OBJ_ACL_RES_ID (2)
#define ACCESS_CONTROL_OBJ_ID (2)
#define ACCESS_CONTROL_OBJ_INSTANCE_RES_ID (1)
#define ACCESS_CONTROL_OBJ_OBJECT_RES_ID (0)
#define ACCESS_CONTROL_OBJ_OWNER_RES_ID (3)
#define BS_SERVER_PUBLIC_KEY
#define CLIENT_BS_PSK_ID ("cli1-bs")
#define CLIENT_BS_PSK_KEY ("FEDCBA9876543210")
#define CLIENT_PRIVATE_KEY ("D9E2707A72DA6A0504995C86EDDBE3EFC7F1CD74838F7570C8072D0A76261BD4")
#define CLIENT_PUBLIC_KEY
#define CLIENT_SERVER_PSK_ID ("cli1")
#define CLIENT_SERVER_PSK_KEY ("0123456789ABCDEF")
#define LIFETIME (60)
#define LOCATION_OBJ_ID (6)
#define LOCATION_OBJ_LATITUDE_RES_ID (0)
#define LOCATION_OBJ_LONGITUDE_RES_ID (1)
#define LOCATION_OBJ_TIMESTAMP_RES_ID (5)
#define ONE_SECOND (1000)
#define PSK_KEY_LEN 16
#define RPK_PRIVATE_KEY_LEN 32
#define RPK_PUBLIC_KEY_LEN (2 * RPK_PRIVATE_KEY_LEN)
#define SECURITY_BOOTSTRAP_SERVER_ACCOUNT_TIMEOUT_RES_ID (12)
#define SECURITY_CLIENT_HOLD_OFF_TIME_RES_ID (11)
#define SECURITY_IS_BOOTSTRAP_RES_ID (1)
#define SECURITY_OBJ_ID (0)
#define SECURITY_PUBLIC_KEY_OR_IDENTITY_RES_ID (3)
#define SECURITY_SECRET_KEY_RES_ID (5)
#define SECURITY_SECURITY_MODE_RES_ID (2)
#define SECURITY_SERVER_ID_RES_ID (10)
#define SECURITY_SERVER_PUBLIC_KEY_RES_ID (4)
#define SECURITY_SERVER_URI_RES_ID (0)
#define SERVER_OBJ_BINDING_RES_ID (7)
#define SERVER_OBJ_ID (1)
#define SERVER_OBJ_LIFETIME_RES_ID (1)
#define SERVER_OBJ_REGISTRATION_UPDATE_RES_ID (8)
#define SERVER_OBJ_SHORT_RES_ID (0)
#define SERVER_PUBLIC_KEY
Functions
static void bootstrap_cb (void *data, struct sol_lwm2m_client *client, enum sol_lwm2m_bootstrap_event event)
static bool change_location (void *data)
static struct sol_blob * coord_to_str (double d)
static int create_access_control_obj (void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id, void **instance_data, struct sol_lwm2m_payload payload)
static int create_location_obj (void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id, void **instance_data, struct sol_lwm2m_payload payload)
static int create_security_obj (void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id, void **instance_data, struct sol_lwm2m_payload payload)
static int create_server_obj (void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id, void **instance_data, struct sol_lwm2m_payload payload)
static int del_access_control_obj (void *instance_data, void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id)
static int del_location_obj (void *instance_data, void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id)
static int del_security_obj (void *instance_data, void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id)
static int del_server_obj (void *instance_data, void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id)
static int execute_server_obj (void *instance_data, void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id, uint16_t res_id, const struct sol_str_slice args)
int main (int argc, char *argv[])
static int read_access_control_obj (void *instance_data, void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id, uint16_t res_id, struct sol_lwm2m_resource *res)
static int read_location_obj (void *instance_data, void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id, uint16_t res_id, struct sol_lwm2m_resource *res)
static int read_security_obj (void *instance_data, void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id, uint16_t res_id, struct sol_lwm2m_resource *res)
static int read_server_obj (void *instance_data, void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id, uint16_t res_id, struct sol_lwm2m_resource *res)
static int write_access_control_res (void *instance_data, void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id, uint16_t res_id, const struct sol_lwm2m_resource *res)
static int write_access_control_tlv (void *instance_data, void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id, struct sol_vector *tlvs)
static int write_or_create_acl (struct sol_vector *acl, struct sol_vector *tlvs, uint16_t *j, bool is_create)
static int write_security_res (void *instance_data, void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id, uint16_t res_id, const struct sol_lwm2m_resource *res)
static int write_security_tlv (void *instance_data, void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id, struct sol_vector *tlvs)
static int write_server_res (void *instance_data, void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id, uint16_t res_id, const struct sol_lwm2m_resource *res)
static int write_server_tlv (void *instance_data, void *user_data, struct sol_lwm2m_client *client, uint16_t instance_id, struct sol_vector *tlvs)
Variables
static const struct
sol_lwm2m_object access_control_object
static struct sol_blob binding
static struct sol_blob bootstrap_server_addr
static const struct
sol_lwm2m_object location_object
static const struct
sol_lwm2m_object security_object
static struct sol_blob server_addr_coap
static struct sol_blob server_addr_dtls
static const struct
sol_lwm2m_object server_object
Macro Definition Documentation
#define ACCESS_CONTROL_OBJ_ACL_RES_ID (2)
Referenced by create_access_control_obj(), read_access_control_obj(), write_access_control_res(), and write_access_control_tlv().
#define ACCESS_CONTROL_OBJ_ID (2)
#define ACCESS_CONTROL_OBJ_INSTANCE_RES_ID (1)
Referenced by create_access_control_obj(), read_access_control_obj(), write_access_control_res(), and write_access_control_tlv().
#define ACCESS_CONTROL_OBJ_OBJECT_RES_ID (0)
Referenced by create_access_control_obj(), read_access_control_obj(), write_access_control_res(), and write_access_control_tlv().
#define ACCESS_CONTROL_OBJ_OWNER_RES_ID (3)
Referenced by create_access_control_obj(), read_access_control_obj(), write_access_control_res(), and write_access_control_tlv().
#define BS_SERVER_PUBLIC_KEY
Value:
("cd4110e97bbd6e7e5a800028079d02915c70b915ea4596402098deea585eb7ad" \
    "f3e080487327f70758b13bc0583f4293d13288a0164a8e324779aa4f7ada26c1")
Referenced by main().
#define CLIENT_BS_PSK_ID ("cli1-bs")
Referenced by main().
#define CLIENT_BS_PSK_KEY ("FEDCBA9876543210")
Referenced by main().
#define CLIENT_PRIVATE_KEY ("D9E2707A72DA6A0504995C86EDDBE3EFC7F1CD74838F7570C8072D0A76261BD4")
Examples:
/src/samples/coap/lwm2m-client.c.
Referenced by main().
#define CLIENT_PUBLIC_KEY
Value:
("D055EE14084D6E0615599DB583913E4A3E4526A2704D61F27A4CCFBA9758EF9A" \
    "B418B64AFE8030DA1DDCF4F42E2F2631D043B1FB03E22F4D17DE43F9F9ADEE70")
Referenced by main().
#define CLIENT_SERVER_PSK_ID ("cli1")
Referenced by main().
#define CLIENT_SERVER_PSK_KEY ("0123456789ABCDEF")
Referenced by main().
#define LIFETIME (60)
Referenced by main().
#define LOCATION_OBJ_ID (6)
Examples:
/src/samples/coap/lwm2m-client.c, and /src/samples/coap/lwm2m-server.c.
#define LOCATION_OBJ_LATITUDE_RES_ID (0)
Examples:
/src/samples/coap/lwm2m-client.c.
Referenced by create_location_obj(), and read_location_obj().
#define LOCATION_OBJ_LONGITUDE_RES_ID (1)
Examples:
/src/samples/coap/lwm2m-client.c.
Referenced by create_location_obj(), and read_location_obj().
#define LOCATION_OBJ_TIMESTAMP_RES_ID (5)
Examples:
/src/samples/coap/lwm2m-client.c.
Referenced by read_location_obj().
#define ONE_SECOND (1000)
Examples:
/src/samples/coap/lwm2m-client.c.
Referenced by create_location_obj().
#define PSK_KEY_LEN 16
Referenced by main().
#define RPK_PRIVATE_KEY_LEN 32
Referenced by main().
#define RPK_PUBLIC_KEY_LEN (2 * RPK_PRIVATE_KEY_LEN)
Referenced by main().
#define SECURITY_BOOTSTRAP_SERVER_ACCOUNT_TIMEOUT_RES_ID (12)
Referenced by create_security_obj(), read_security_obj(), write_security_res(), and write_security_tlv().
#define SECURITY_CLIENT_HOLD_OFF_TIME_RES_ID (11)
Referenced by create_security_obj(), read_security_obj(), write_security_res(), and write_security_tlv().
#define SECURITY_IS_BOOTSTRAP_RES_ID (1)
Referenced by create_security_obj(), read_security_obj(), write_security_res(), and write_security_tlv().
#define SECURITY_OBJ_ID (0)
#define SECURITY_PUBLIC_KEY_OR_IDENTITY_RES_ID (3)
Referenced by create_security_obj(), read_security_obj(), write_security_res(), and write_security_tlv().
#define SECURITY_SECRET_KEY_RES_ID (5)
Referenced by create_security_obj(), read_security_obj(), write_security_res(), and write_security_tlv().
#define SECURITY_SECURITY_MODE_RES_ID (2)
Referenced by create_security_obj(), read_security_obj(), write_security_res(), and write_security_tlv().
#define SECURITY_SERVER_ID_RES_ID (10)
Referenced by create_security_obj(), read_security_obj(), write_security_res(), and write_security_tlv().
#define SECURITY_SERVER_PUBLIC_KEY_RES_ID (4)
Referenced by create_security_obj(), read_security_obj(), write_security_res(), and write_security_tlv().
#define SECURITY_SERVER_URI_RES_ID (0)
Referenced by create_security_obj(), read_security_obj(), write_security_res(), and write_security_tlv().
#define SERVER_OBJ_BINDING_RES_ID (7)
Referenced by create_server_obj(), read_server_obj(), write_server_res(), and write_server_tlv().
#define SERVER_OBJ_ID (1)
#define SERVER_OBJ_LIFETIME_RES_ID (1)
Referenced by create_server_obj(), read_server_obj(), write_server_res(), and write_server_tlv().
#define SERVER_OBJ_REGISTRATION_UPDATE_RES_ID (8)
Referenced by execute_server_obj().
#define SERVER_OBJ_SHORT_RES_ID (0)
Referenced by create_server_obj(), read_server_obj(), write_server_res(), and write_server_tlv().
#define SERVER_PUBLIC_KEY
Value:
("3b88c213ca5ccfd9c5a7f73715760d7d9a5220768f2992d2628ae1389cbca4c6" \
    "d1b73cc6d61ae58783135749fb03eaaa64a7a1adab8062ed5fc0d7b86ba2d5ca")
Examples:
/src/samples/coap/lwm2m-client.c, and /src/samples/coap/lwm2m-server.c.
Referenced by main().
Function Documentation
static void bootstrap_cb (void * data, struct sol_lwm2m_client * client, enum sol_lwm2m_bootstrap_event event) static
References SOL_LWM2M_BOOTSTRAP_EVENT_ERROR, SOL_LWM2M_BOOTSTRAP_EVENT_FINISHED, and sol_lwm2m_client_start().
Referenced by main().
static bool change_location (void * data) static
Examples:
/src/samples/coap/lwm2m-client.c.
References location_obj_instance_ctx::client, location_obj_instance_ctx::latitude, location_obj_instance_ctx::longitude, sol_lwm2m_client_notify(), and location_obj_instance_ctx::timestamp.
Referenced by create_location_obj().
static struct sol_blob* coord_to_str (double d) static
Examples:
/src/samples/coap/lwm2m-client.c.
References sol_blob_new(), and SOL_BLOB_TYPE_DEFAULT.
Referenced by read_location_obj().
static int create_access_control_obj (void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id, void ** instance_data, struct sol_lwm2m_payload payload) static
Examples:
/src/samples/coap/lwm2m-client.c.
References ACCESS_CONTROL_OBJ_ACL_RES_ID, ACCESS_CONTROL_OBJ_INSTANCE_RES_ID, ACCESS_CONTROL_OBJ_OBJECT_RES_ID, ACCESS_CONTROL_OBJ_OWNER_RES_ID, access_control_obj_instance_ctx::acl, access_control_obj_instance_ctx::client, sol_lwm2m_tlv::id, access_control_obj_instance_ctx::instance_id, access_control_obj_instance_ctx::object_id, access_control_obj_instance_ctx::owner_id, sol_lwm2m_payload::payload, SOL_LWM2M_CONTENT_TYPE_TLV, sol_lwm2m_tlv_get_int(), SOL_LWM2M_TLV_TYPE_MULTIPLE_RESOURCES, SOL_LWM2M_TLV_TYPE_RESOURCE_WITH_VALUE, sol_vector_clear(), SOL_VECTOR_FOREACH_IDX, sol_vector_init(), sol_lwm2m_payload::sol_lwm2m_payload_data::tlv_content, sol_lwm2m_tlv::type, sol_lwm2m_payload::type, and write_or_create_acl().
static int create_location_obj (void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id, void ** instance_data, struct sol_lwm2m_payload payload) static
Examples:
/src/samples/coap/lwm2m-client.c, and /src/samples/coap/lwm2m-server.c.
References change_location(), location_obj_instance_ctx::client, client_data_ctx::has_location_instance, sol_lwm2m_tlv::id, location_obj_instance_ctx::latitude, sol_vector::len, LOCATION_OBJ_LATITUDE_RES_ID, LOCATION_OBJ_LONGITUDE_RES_ID, location_obj_instance_ctx::longitude, ONE_SECOND, sol_lwm2m_payload::payload, SOL_BUFFER_DECLARE_STATIC, sol_buffer_fini(), SOL_LWM2M_CONTENT_TYPE_TLV, sol_lwm2m_tlv_get_bytes(), sol_lwm2m_tlv_get_int(), sol_timeout_add(), sol_timeout_del(), sol_util_strtod_n(), SOL_VECTOR_FOREACH_IDX, location_obj_instance_ctx::timeout, location_obj_instance_ctx::timestamp, sol_lwm2m_payload::sol_lwm2m_payload_data::tlv_content, and sol_lwm2m_payload::type.
static int create_security_obj (void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id, void ** instance_data, struct sol_lwm2m_payload payload) static
Examples:
/src/samples/coap/lwm2m-client.c.
References security_obj_instance_ctx::bootstrap_server_account_timeout, security_obj_instance_ctx::client, security_obj_instance_ctx::client_hold_off_time, sol_lwm2m_tlv::id, security_obj_instance_ctx::is_bootstrap, sol_lwm2m_payload::payload, security_obj_instance_ctx::public_key_or_id, security_obj_instance_ctx::secret_key, SECURITY_BOOTSTRAP_SERVER_ACCOUNT_TIMEOUT_RES_ID, SECURITY_CLIENT_HOLD_OFF_TIME_RES_ID, SECURITY_IS_BOOTSTRAP_RES_ID, security_obj_instance_ctx::security_mode, SECURITY_PUBLIC_KEY_OR_IDENTITY_RES_ID, SECURITY_SECRET_KEY_RES_ID, SECURITY_SECURITY_MODE_RES_ID, SECURITY_SERVER_ID_RES_ID, SECURITY_SERVER_PUBLIC_KEY_RES_ID, SECURITY_SERVER_URI_RES_ID, security_obj_instance_ctx::server_id, security_obj_instance_ctx::server_public_key, security_obj_instance_ctx::server_uri, sol_blob_unref(), SOL_BUFFER_DECLARE_STATIC, sol_buffer_to_blob(), SOL_LWM2M_CONTENT_TYPE_TLV, sol_lwm2m_tlv_get_bool(), sol_lwm2m_tlv_get_bytes(), sol_lwm2m_tlv_get_int(), SOL_VECTOR_FOREACH_IDX, sol_lwm2m_payload::sol_lwm2m_payload_data::tlv_content, and sol_lwm2m_payload::type.
static int create_server_obj (void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id, void ** instance_data, struct sol_lwm2m_payload payload) static
Examples:
/src/samples/coap/lwm2m-client.c.
References server_obj_instance_ctx::binding, server_obj_instance_ctx::client, sol_lwm2m_tlv::id, server_obj_instance_ctx::lifetime, sol_lwm2m_payload::payload, server_obj_instance_ctx::server_id, SERVER_OBJ_BINDING_RES_ID, SERVER_OBJ_LIFETIME_RES_ID, SERVER_OBJ_SHORT_RES_ID, SOL_BUFFER_DECLARE_STATIC, sol_buffer_to_blob(), SOL_LWM2M_CONTENT_TYPE_TLV, sol_lwm2m_tlv_get_bytes(), sol_lwm2m_tlv_get_int(), SOL_VECTOR_FOREACH_IDX, sol_lwm2m_payload::sol_lwm2m_payload_data::tlv_content, and sol_lwm2m_payload::type.
static int del_access_control_obj (void * instance_data, void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id) static
Examples:
/src/samples/coap/lwm2m-client.c.
References access_control_obj_instance_ctx::acl, and sol_vector_clear().
static int del_location_obj (void * instance_data, void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id) static
Examples:
/src/samples/coap/lwm2m-client.c.
References client_data_ctx::has_location_instance, sol_timeout_del(), and location_obj_instance_ctx::timeout.
static int del_security_obj (void * instance_data, void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id) static
Examples:
/src/samples/coap/lwm2m-client.c.
References security_obj_instance_ctx::public_key_or_id, security_obj_instance_ctx::secret_key, security_obj_instance_ctx::server_public_key, security_obj_instance_ctx::server_uri, and sol_blob_unref().
static int del_server_obj (void * instance_data, void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id) static
Examples:
/src/samples/coap/lwm2m-client.c.
References server_obj_instance_ctx::binding, and sol_blob_unref().
static int execute_server_obj (void * instance_data, void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id, uint16_t res_id, const struct sol_str_slice args) static
Examples:
/src/samples/coap/lwm2m-client.c.
References SERVER_OBJ_REGISTRATION_UPDATE_RES_ID, and sol_lwm2m_client_send_update().
int main (int argc, char * argv[])
References access_control_object, server_obj_instance_ctx::binding, binding, bootstrap_cb(), security_obj_instance_ctx::bootstrap_server_account_timeout, bootstrap_server_addr, BS_SERVER_PUBLIC_KEY, security_obj_instance_ctx::client, server_obj_instance_ctx::client, CLIENT_BS_PSK_ID, CLIENT_BS_PSK_KEY, security_obj_instance_ctx::client_hold_off_time, CLIENT_PRIVATE_KEY, CLIENT_PUBLIC_KEY, CLIENT_SERVER_PSK_ID, CLIENT_SERVER_PSK_KEY, client_data_ctx::is_bootstrap, security_obj_instance_ctx::is_bootstrap, LIFETIME, server_obj_instance_ctx::lifetime, location_object, PSK_KEY_LEN, security_obj_instance_ctx::public_key_or_id, RPK_PRIVATE_KEY_LEN, RPK_PUBLIC_KEY_LEN, security_obj_instance_ctx::secret_key, security_obj_instance_ctx::security_mode, security_object, server_data, security_obj_instance_ctx::server_id, server_obj_instance_ctx::server_id, server_object, SERVER_PUBLIC_KEY, security_obj_instance_ctx::server_public_key, security_obj_instance_ctx::server_uri, sol_blob_new_dup(), SOL_DECODE_BOTH, sol_init(), sol_lwm2m_client_add_bootstrap_finish_monitor(), sol_lwm2m_client_add_object_instance(), sol_lwm2m_client_del(), sol_lwm2m_client_new(), sol_lwm2m_client_start(), sol_lwm2m_client_stop(), SOL_LWM2M_SECURITY_MODE_CERTIFICATE, SOL_LWM2M_SECURITY_MODE_NO_SEC, SOL_LWM2M_SECURITY_MODE_PRE_SHARED_KEY, SOL_LWM2M_SECURITY_MODE_RAW_PUBLIC_KEY, sol_run(), sol_shutdown(), sol_str_slice_from_str(), sol_util_base16_decode(), and usage().
static int read_access_control_obj (void * instance_data, void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id, uint16_t res_id, struct sol_lwm2m_resource * res) static
Examples:
/src/samples/coap/lwm2m-client.c.
References ACCESS_CONTROL_OBJ_ACL_RES_ID, ACCESS_CONTROL_OBJ_INSTANCE_RES_ID, ACCESS_CONTROL_OBJ_OBJECT_RES_ID, ACCESS_CONTROL_OBJ_OWNER_RES_ID, access_control_obj_instance_ctx::acl, sol_lwm2m_resource::api_version, access_control_obj_instance_ctx::instance_id, acl_instance::key, sol_vector::len, access_control_obj_instance_ctx::object_id, access_control_obj_instance_ctx::owner_id, SOL_LWM2M_RESOURCE_API_VERSION, SOL_LWM2M_RESOURCE_DATA_TYPE_INT, sol_lwm2m_resource_init_vector(), SOL_LWM2M_RESOURCE_SINGLE_INT_INIT, SOL_SET_API_VERSION, sol_vector_append(), sol_vector_clear(), SOL_VECTOR_FOREACH_IDX, sol_vector_init(), and acl_instance::value.
static int read_location_obj (void * instance_data, void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id, uint16_t res_id, struct sol_lwm2m_resource * res) static
Examples:
/src/samples/coap/lwm2m-client.c.
References coord_to_str(), location_obj_instance_ctx::latitude, LOCATION_OBJ_LATITUDE_RES_ID, LOCATION_OBJ_LONGITUDE_RES_ID, LOCATION_OBJ_TIMESTAMP_RES_ID, location_obj_instance_ctx::longitude, sol_blob_unref(), SOL_LWM2M_RESOURCE_DATA_TYPE_STRING, SOL_LWM2M_RESOURCE_DATA_TYPE_TIME, SOL_LWM2M_RESOURCE_SINGLE_INIT, and location_obj_instance_ctx::timestamp.
static int read_security_obj (void * instance_data, void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id, uint16_t res_id, struct sol_lwm2m_resource * res) static
Examples:
/src/samples/coap/lwm2m-client.c.
References security_obj_instance_ctx::bootstrap_server_account_timeout, security_obj_instance_ctx::client_hold_off_time, security_obj_instance_ctx::is_bootstrap, security_obj_instance_ctx::public_key_or_id, security_obj_instance_ctx::secret_key, SECURITY_BOOTSTRAP_SERVER_ACCOUNT_TIMEOUT_RES_ID, SECURITY_CLIENT_HOLD_OFF_TIME_RES_ID, SECURITY_IS_BOOTSTRAP_RES_ID, security_obj_instance_ctx::security_mode, SECURITY_PUBLIC_KEY_OR_IDENTITY_RES_ID, SECURITY_SECRET_KEY_RES_ID, SECURITY_SECURITY_MODE_RES_ID, SECURITY_SERVER_ID_RES_ID, SECURITY_SERVER_PUBLIC_KEY_RES_ID, SECURITY_SERVER_URI_RES_ID, security_obj_instance_ctx::server_id, security_obj_instance_ctx::server_public_key, security_obj_instance_ctx::server_uri, SOL_LWM2M_RESOURCE_DATA_TYPE_BOOL, SOL_LWM2M_RESOURCE_DATA_TYPE_STRING, SOL_LWM2M_RESOURCE_SINGLE_INIT, and SOL_LWM2M_RESOURCE_SINGLE_INT_INIT.
static int read_server_obj (void * instance_data, void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id, uint16_t res_id, struct sol_lwm2m_resource * res) static
Examples:
/src/samples/coap/lwm2m-client.c.
References server_obj_instance_ctx::binding, server_obj_instance_ctx::lifetime, server_obj_instance_ctx::server_id, SERVER_OBJ_BINDING_RES_ID, SERVER_OBJ_LIFETIME_RES_ID, SERVER_OBJ_SHORT_RES_ID, SOL_LWM2M_RESOURCE_DATA_TYPE_STRING, SOL_LWM2M_RESOURCE_SINGLE_INIT, and SOL_LWM2M_RESOURCE_SINGLE_INT_INIT.
static int write_access_control_res (void * instance_data, void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id, uint16_t res_id, const struct sol_lwm2m_resource * res) static
Examples:
/src/samples/coap/lwm2m-client.c.
References ACCESS_CONTROL_OBJ_ACL_RES_ID, ACCESS_CONTROL_OBJ_INSTANCE_RES_ID, ACCESS_CONTROL_OBJ_OBJECT_RES_ID, ACCESS_CONTROL_OBJ_OWNER_RES_ID, access_control_obj_instance_ctx::acl, sol_lwm2m_resource::sol_lwm2m_resource_data::content, sol_lwm2m_resource::data, sol_lwm2m_resource::data_len, sol_lwm2m_resource::id, sol_lwm2m_resource::sol_lwm2m_resource_data::id, access_control_obj_instance_ctx::instance_id, sol_lwm2m_resource::sol_lwm2m_resource_data::integer, acl_instance::key, access_control_obj_instance_ctx::object_id, access_control_obj_instance_ctx::owner_id, SOL_LWM2M_RESOURCE_TYPE_MULTIPLE, sol_vector_append(), sol_vector_clear(), sol_lwm2m_resource::type, and acl_instance::value.
static int write_access_control_tlv (void * instance_data, void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id, struct sol_vector * tlvs) static
Examples:
/src/samples/coap/lwm2m-client.c.
References ACCESS_CONTROL_OBJ_ACL_RES_ID, ACCESS_CONTROL_OBJ_INSTANCE_RES_ID, ACCESS_CONTROL_OBJ_OBJECT_RES_ID, ACCESS_CONTROL_OBJ_OWNER_RES_ID, access_control_obj_instance_ctx::acl, sol_lwm2m_tlv::content, sol_lwm2m_tlv::id, access_control_obj_instance_ctx::instance_id, sol_vector::len, access_control_obj_instance_ctx::object_id, access_control_obj_instance_ctx::owner_id, sol_buffer_get_slice(), sol_lwm2m_tlv_get_int(), SOL_LWM2M_TLV_TYPE_MULTIPLE_RESOURCES, SOL_LWM2M_TLV_TYPE_RESOURCE_WITH_VALUE, SOL_STR_SLICE_PRINT, sol_vector_clear(), SOL_VECTOR_FOREACH_IDX, sol_lwm2m_tlv::type, sol_buffer::used, and write_or_create_acl().
static int write_or_create_acl (struct sol_vector * acl, struct sol_vector * tlvs, uint16_t * j, bool is_create) static
Examples:
/src/samples/coap/lwm2m-client.c.
References sol_lwm2m_tlv::id, acl_instance::key, sol_lwm2m_tlv_get_int(), SOL_LWM2M_TLV_TYPE_RESOURCE_INSTANCE, sol_vector_append(), sol_vector_get(), sol_lwm2m_tlv::type, and acl_instance::value.
Referenced by create_access_control_obj(), and write_access_control_tlv().
static int write_security_res (void * instance_data, void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id, uint16_t res_id, const struct sol_lwm2m_resource * res) static
Examples:
/src/samples/coap/lwm2m-client.c.
References sol_lwm2m_resource::sol_lwm2m_resource_data::b, sol_lwm2m_resource::sol_lwm2m_resource_data::blob, security_obj_instance_ctx::bootstrap_server_account_timeout, security_obj_instance_ctx::client_hold_off_time, sol_lwm2m_resource::sol_lwm2m_resource_data::content, sol_lwm2m_resource::data, sol_lwm2m_resource::id, sol_lwm2m_resource::sol_lwm2m_resource_data::integer, security_obj_instance_ctx::is_bootstrap, security_obj_instance_ctx::public_key_or_id, security_obj_instance_ctx::secret_key, SECURITY_BOOTSTRAP_SERVER_ACCOUNT_TIMEOUT_RES_ID, SECURITY_CLIENT_HOLD_OFF_TIME_RES_ID, SECURITY_IS_BOOTSTRAP_RES_ID, security_obj_instance_ctx::security_mode, SECURITY_PUBLIC_KEY_OR_IDENTITY_RES_ID, SECURITY_SECRET_KEY_RES_ID, SECURITY_SECURITY_MODE_RES_ID, SECURITY_SERVER_ID_RES_ID, SECURITY_SERVER_PUBLIC_KEY_RES_ID, SECURITY_SERVER_URI_RES_ID, security_obj_instance_ctx::server_id, security_obj_instance_ctx::server_public_key, security_obj_instance_ctx::server_uri, sol_blob_ref(), and sol_blob_unref().
static int write_security_tlv (void * instance_data, void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id, struct sol_vector * tlvs) static
Examples:
/src/samples/coap/lwm2m-client.c.
References security_obj_instance_ctx::bootstrap_server_account_timeout, security_obj_instance_ctx::client_hold_off_time, sol_lwm2m_tlv::content, sol_lwm2m_tlv::id, security_obj_instance_ctx::is_bootstrap, sol_vector::len, security_obj_instance_ctx::public_key_or_id, security_obj_instance_ctx::secret_key, SECURITY_BOOTSTRAP_SERVER_ACCOUNT_TIMEOUT_RES_ID, SECURITY_CLIENT_HOLD_OFF_TIME_RES_ID, SECURITY_IS_BOOTSTRAP_RES_ID, security_obj_instance_ctx::security_mode, SECURITY_PUBLIC_KEY_OR_IDENTITY_RES_ID, SECURITY_SECRET_KEY_RES_ID, SECURITY_SECURITY_MODE_RES_ID, SECURITY_SERVER_ID_RES_ID, SECURITY_SERVER_PUBLIC_KEY_RES_ID, SECURITY_SERVER_URI_RES_ID, security_obj_instance_ctx::server_id, security_obj_instance_ctx::server_public_key, security_obj_instance_ctx::server_uri, sol_blob_unref(), SOL_BUFFER_DECLARE_STATIC, sol_buffer_get_slice(), sol_buffer_to_blob(), sol_lwm2m_tlv_get_bool(), sol_lwm2m_tlv_get_bytes(), sol_lwm2m_tlv_get_int(), SOL_STR_SLICE_PRINT, SOL_VECTOR_FOREACH_IDX, sol_lwm2m_tlv::type, and sol_buffer::used.
static int write_server_res (void * instance_data, void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id, uint16_t res_id, const struct sol_lwm2m_resource * res) static
Examples:
/src/samples/coap/lwm2m-client.c.
References server_obj_instance_ctx::binding, sol_lwm2m_resource::sol_lwm2m_resource_data::blob, sol_lwm2m_resource::sol_lwm2m_resource_data::content, sol_lwm2m_resource::data, sol_lwm2m_resource::id, sol_lwm2m_resource::sol_lwm2m_resource_data::integer, server_obj_instance_ctx::lifetime, server_obj_instance_ctx::server_id, SERVER_OBJ_BINDING_RES_ID, SERVER_OBJ_LIFETIME_RES_ID, SERVER_OBJ_SHORT_RES_ID, sol_blob_ref(), and sol_blob_unref().
static int write_server_tlv (void * instance_data, void * user_data, struct sol_lwm2m_client * client, uint16_t instance_id, struct sol_vector * tlvs) static
Examples:
/src/samples/coap/lwm2m-client.c.
References server_obj_instance_ctx::binding, sol_lwm2m_tlv::content, sol_lwm2m_tlv::id, sol_vector::len, server_obj_instance_ctx::lifetime, server_obj_instance_ctx::server_id, SERVER_OBJ_BINDING_RES_ID, SERVER_OBJ_LIFETIME_RES_ID, SERVER_OBJ_SHORT_RES_ID, sol_blob_unref(), SOL_BUFFER_DECLARE_STATIC, sol_buffer_get_slice(), sol_buffer_to_blob(), sol_lwm2m_tlv_get_bytes(), sol_lwm2m_tlv_get_int(), SOL_STR_SLICE_PRINT, SOL_VECTOR_FOREACH_IDX, sol_lwm2m_tlv::type, and sol_buffer::used.
Variable Documentation
const struct sol_lwm2m_object access_control_object static
Initial value:
= {
    .id = ACCESS_CONTROL_OBJ_ID,
    .resources_count = 4,
    .read = read_access_control_obj,
    .create = create_access_control_obj,
    .del = del_access_control_obj,
    .write_resource = write_access_control_res,
    .write_tlv = write_access_control_tlv,
}
Examples:
/src/samples/coap/lwm2m-client.c.
Referenced by main().
struct sol_blob binding static
Initial value:
= {
    .type = &SOL_BLOB_TYPE_NO_FREE,
    .parent = NULL,
    .mem = (void *)"U",
    .size = sizeof("U") - 1,
    .refcnt = 1
}
Referenced by main().
struct sol_blob bootstrap_server_addr static
Initial value:
= {
    .type = &SOL_BLOB_TYPE_NO_FREE,
    .parent = NULL,
    .mem = (void *)"coaps://localhost:5783",
    .size = sizeof("coaps://localhost:5783") - 1,
    .refcnt = 1
}
Examples:
/src/samples/coap/lwm2m-client.c.
Referenced by main().
const struct sol_lwm2m_object location_object static
Initial value:
= {
    .id = LOCATION_OBJ_ID,
    .create = create_location_obj,
    .read = read_location_obj,
    .del = del_location_obj,
    .resources_count = 6
}
Examples:
/src/samples/coap/lwm2m-client.c.
Referenced by main().
const struct sol_lwm2m_object security_object static
Initial value:
= {
    .id = SECURITY_OBJ_ID,
    .resources_count = 12,
    .read = read_security_obj,
    .create = create_security_obj,
    .del = del_security_obj,
    .write_resource = write_security_res,
    .write_tlv = write_security_tlv
}
Examples:
/src/samples/coap/lwm2m-client.c.
Referenced by main().
struct sol_blob server_addr_coap static
Initial value:
= {
    .type = &SOL_BLOB_TYPE_NO_FREE,
    .parent = NULL,
    .mem = (void *)"coap://localhost:5683",
    .size = sizeof("coap://localhost:5683") - 1,
    .refcnt = 1
}
Examples:
/src/samples/coap/lwm2m-client.c.
struct sol_blob server_addr_dtls static
Initial value:
= {
    .type = &SOL_BLOB_TYPE_NO_FREE,
    .parent = NULL,
    .mem = (void *)"coaps://localhost:5684",
    .size = sizeof("coaps://localhost:5684") - 1,
    .refcnt = 1
}
Examples:
/src/samples/coap/lwm2m-client.c.
const struct sol_lwm2m_object server_object static
Initial value:
= {
    .id = SERVER_OBJ_ID,
    .resources_count = 9,
    .read = read_server_obj,
    .create = create_server_obj,
    .del = del_server_obj,
    .write_resource = write_server_res,
    .write_tlv = write_server_tlv,
    .execute = execute_server_obj
}
Examples:
/src/samples/coap/lwm2m-client.c.
Referenced by main().