Soletta™ Framework: src/samples/crypto/message-digest.c File Reference
message-digest.c File Reference
#include <stdio.h>
#include <errno.h>
#include "soletta.h"
#include "sol-buffer.h"
#include "sol-file-reader.h"
#include "sol-message-digest.h"
#include "sol-util.h"
Data Structures
struct feed_ctx
Functions
static void on_digest_ready (void *data, struct sol_message_digest *handle, struct sol_blob *digest)
static void on_feed_done (void *data, struct sol_message_digest *handle, struct sol_blob *input, int status)
static void print_time (const struct feed_ctx *ctx, size_t amount, const char *prefix)
static void shutdown (void)
SOL_MAIN_DEFAULT (startup, shutdown)
static void startup (void)
Variables
static uint32_t pending
Function Documentation
static void on_digest_ready (void * data, struct sol_message_digest * handle, struct sol_blob * digest) static
Examples:
/src/samples/crypto/message-digest.c.
References sol_buffer::data, feed_ctx::done, feed_ctx::file, pending, print_time(), sol_buffer_append_as_base16(), sol_buffer_fini(), sol_buffer_init(), sol_message_digest_del(), sol_quit(), and sol_str_slice_from_blob().
Referenced by startup().
static void on_feed_done (void * data, struct sol_message_digest * handle, struct sol_blob * input, int status) static
Examples:
/src/samples/crypto/message-digest.c, and /src/samples/design_patterns/stream_sample.c.
References feed_ctx::done, feed_ctx::idx, print_time(), and sol_blob::size.
Referenced by startup().
static void print_time (const struct feed_ctx * ctx, size_t amount, const char * prefix) static
Examples:
/src/samples/crypto/message-digest.c.
References feed_ctx::chunk_size, feed_ctx::idx, seconds, SOL_UTIL_NSEC_PER_SEC, sol_util_timespec_get_current(), sol_util_timespec_sub(), and feed_ctx::start.
Referenced by on_digest_ready(), and on_feed_done().
static void shutdown (void) static
SOL_MAIN_DEFAULT (startup , shutdown)
static void startup (void) static
References algorithm, sol_message_digest_config::api_version, feed_ctx::chunk_size, sol_message_digest_config::data, feed_ctx::done, feed_ctx::file, key, sol_message_digest_config::key, sol_blob::mem, on_digest_ready(), on_feed_done(), pending, sol_blob::size, sol_argc(), sol_argv(), sol_blob_new(), SOL_BLOB_TYPE_NO_FREE_DATA, sol_blob_unref(), sol_file_reader_open(), sol_file_reader_to_blob(), SOL_MESSAGE_DIGEST_CONFIG_API_VERSION, sol_message_digest_del(), sol_message_digest_feed(), sol_message_digest_new(), sol_quit_with_code(), SOL_SET_API_VERSION, sol_str_slice_from_str(), sol_util_strerrora, sol_util_timespec_get_current(), and feed_ctx::start.
Variable Documentation
uint32_t pending static
Referenced by on_digest_ready(), and startup().