Soletta: src/samples/mqtt/mqtt-publish.c File Reference
mqtt-publish.c File Reference
MQTT Publish client.
#include <string.h>
#include <sol-log.h>
#include <sol-mainloop.h>
#include <sol-mqtt.h>
Functions
int main (int argc, char *argv[])
static void on_connect (void *data, struct sol_mqtt *mqtt)
static void on_disconnect (void *data, struct sol_mqtt *mqtt)
static bool publish_callback (void *data)
static bool try_reconnect (void *data)
Variables
const struct sol_mqtt_config config
static struct sol_mqtt_message message
static struct sol_timeout * timeout
static char * topic
Detailed Description
MQTT Publish client.
Sample client that connects a broker at host:port and publishes the provided message once every 1 second.
Function Documentation
int main (int argc, char * argv[])
References message, sol_mqtt_message::payload, SOL_BUFFER_INIT_CONST, SOL_INF, sol_init(), sol_mqtt_connect(), sol_mqtt_disconnect(), SOL_MQTT_QOS_EXACTLY_ONCE, sol_run(), sol_shutdown(), sol_timeout_del(), SOL_WRN, timeout, topic, and sol_mqtt_message::topic.
static void on_connect (void * data, struct sol_mqtt * mqtt) static
References publish_callback(), SOL_MQTT_CONNECTED, sol_mqtt_get_connection_status(), sol_timeout_add(), SOL_WRN, timeout, and try_reconnect().
static void on_disconnect (void * data, struct sol_mqtt * mqtt) static
References SOL_INF, sol_timeout_add(), and try_reconnect().
static bool publish_callback (void * data) static
References message, SOL_INF, sol_mqtt_publish(), SOL_NULL_CHECK, and SOL_WRN.
Referenced by on_connect().
static bool try_reconnect (void * data) static
References sol_mqtt_reconnect().
Referenced by on_connect(), and on_disconnect().
Variable Documentation
const struct sol_mqtt_config config
Initial value:
= {
    .clean_session = true,
    .keepalive = 60,
    .handlers = {
        .connect = on_connect,
        .disconnect = on_disconnect,
    },
}
struct sol_mqtt_message message static
Referenced by main(), and publish_callback().
struct sol_timeout* timeout static
Referenced by main(), and on_connect().
char* topic static
Referenced by main().