Soletta: src/samples/mqtt/mqtt-subscribe.c File Reference
mqtt-subscribe.c File Reference
MQTT Publish client.
#include <string.h>
#include <sol-log.h>
#include <sol-mainloop.h>
#include <sol-mqtt.h>
Functions
int main (int argc, char *argv[])
static void on_connect (void *data, struct sol_mqtt *mqtt)
static void on_disconnect (void *data, struct sol_mqtt *mqtt)
static void on_message (void *data, struct sol_mqtt *mqtt, const struct sol_mqtt_message *message)
static bool try_reconnect (void *data)
Variables
const struct sol_mqtt_config config
static char * topic
Detailed Description
MQTT Publish client.
Sample client that connects a broker at host:port and subscribes to the provided topic. Whenever a new message is published to that topic, it is printed in the console.
Function Documentation
int main (int argc, char * argv[])
References SOL_INF, sol_init(), sol_mqtt_connect(), sol_mqtt_disconnect(), sol_run(), sol_shutdown(), SOL_WRN, and topic.
static void on_connect (void * data, struct sol_mqtt * mqtt) static
References SOL_ERR, SOL_MQTT_CONNECTED, sol_mqtt_get_connection_status(), SOL_MQTT_QOS_AT_MOST_ONCE, sol_mqtt_subscribe(), sol_timeout_add(), SOL_WRN, topic, and try_reconnect().
static void on_disconnect (void * data, struct sol_mqtt * mqtt) static
References SOL_INF, sol_timeout_add(), and try_reconnect().
static void on_message (void * data, struct sol_mqtt * mqtt, const struct sol_mqtt_message * message) static
References sol_buffer::data, sol_mqtt_message::payload, SOL_INF, SOL_NULL_CHECK, and sol_buffer::used.
static bool try_reconnect (void * data) static
References sol_mqtt_reconnect().
Referenced by on_connect(), and on_disconnect().
Variable Documentation
const struct sol_mqtt_config config
Initial value:
= {
    .clean_session = true,
    .keepalive = 60,
    .handlers = {
        .connect = on_connect,
        .disconnect = on_disconnect,
        .message = on_message,
    },
}
char* topic static
Referenced by main(), and on_connect().