Soletta™ Framework: src/samples/network/netctl.c File Reference
netctl.c File Reference
#include <stdbool.h>
#include <inttypes.h>
#include <stdio.h>
#include <errno.h>
#include "soletta.h"
#include "sol-netctl.h"
#include "sol-util.h"
#include "sol-log.h"
Macros
#define CONN_AP "Guest"
#define INPUT "12345678"
Functions
static void cancel (void *data)
static void error_cb (void *data, const struct sol_netctl_service *service, unsigned int error)
static void manager_cb (void *data)
static void release (void *data)
static void report_error (void *data, const struct sol_netctl_service *service, const char *error)
static void request_input (void *data, const struct sol_netctl_service *service, const struct sol_ptr_vector *vector)
static void service_cb (void *data, const struct sol_netctl_service *service)
static void shutdown (void)
SOL_MAIN_DEFAULT (startup, shutdown)
static void startup (void)
Variables
struct sol_netctl_agent agent
Macro Definition Documentation
#define CONN_AP "Guest"
Examples:
/src/samples/network/netctl.c.
Referenced by service_cb().
#define INPUT "12345678"
Examples:
/src/samples/network/netctl.c.
Referenced by request_input().
Function Documentation
static void cancel (void * data) static
Examples:
/src/samples/network/netctl.c.
Referenced by startup().
static void error_cb (void * data, const struct sol_netctl_service * service, unsigned int error) static
Examples:
/src/samples/network/netctl.c.
References sol_netctl_service_get_name().
Referenced by shutdown(), and startup().
static void manager_cb (void * data) static
Examples:
/src/samples/network/netctl.c.
References sol_netctl_get_radios_offline(), and sol_netctl_get_state().
Referenced by shutdown(), and startup().
static void release (void * data) static
Examples:
/src/samples/network/netctl.c.
Referenced by startup().
static void report_error (void * data, const struct sol_netctl_service * service, const char * error) static
Examples:
/src/samples/network/netctl.c.
References sol_netctl_request_retry().
Referenced by startup().
static void request_input (void * data, const struct sol_netctl_service * service, const struct sol_ptr_vector * vector) static
Examples:
/src/samples/network/netctl.c.
References sol_netctl_agent_input::api_version, INPUT, sol_netctl_agent_input::input, SOL_NETCTL_AGENT_INPUT_API_VERSION, sol_netctl_request_input(), sol_ptr_vector_append(), sol_ptr_vector_clear(), SOL_PTR_VECTOR_FOREACH_IDX, sol_ptr_vector_init(), SOL_SET_API_VERSION, sol_netctl_agent_input::type, and value.
Referenced by startup().
static void service_cb (void * data, const struct sol_netctl_service * service) static
Examples:
/src/samples/network/netctl.c.
References CONN_AP, sol_netctl_service_connect(), sol_netctl_service_disconnect(), sol_netctl_service_get_name(), sol_netctl_service_get_state(), sol_netctl_service_get_strength(), sol_netctl_service_get_type(), SOL_NETCTL_SERVICE_STATE_IDLE, and SOL_NETCTL_SERVICE_STATE_READY.
Referenced by shutdown(), and startup().
static void shutdown (void) static
References error_cb(), manager_cb(), service_cb(), sol_netctl_del_error_monitor(), sol_netctl_del_manager_monitor(), sol_netctl_del_service_monitor(), and sol_netctl_unregister_agent().
SOL_MAIN_DEFAULT (startup , shutdown)
static void startup (void) static
References agent, sol_netctl_agent::api_version, cancel(), sol_netctl_agent::cancel, error_cb(), manager_cb(), release(), sol_netctl_agent::release, report_error(), sol_netctl_agent::report_error, request_input(), sol_netctl_agent::request_input, service_cb(), sol_netctl_add_error_monitor(), sol_netctl_add_manager_monitor(), sol_netctl_add_service_monitor(), SOL_NETCTL_AGENT_API_VERSION, sol_netctl_register_agent(), sol_netctl_scan(), and SOL_SET_API_VERSION.
Variable Documentation
struct sol_netctl_agent agent
Examples:
/src/samples/network/netctl.c.
Referenced by startup().