Soletta: src/samples/coap/oic-server.c File Reference
oic-server.c File Reference
#include <errno.h>
#include <fcntl.h>
#include <linux/kd.h>
#include <netinet/in.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include "sol-log.h"
#include "sol-mainloop.h"
#include "sol-str-slice.h"
#include "sol-util.h"
#include "sol-vector.h"
#include "sol-coap.h"
#include "sol-oic-server.h"
Functions
static bool get_scrolllock_led (void)
int main (int argc, char *argv[])
static struct sol_oic_server_resource * register_light_resource_type (sol_coap_responsecode_t(*handle_get)(const struct sol_network_link_addr *cliaddr, const void *data, const struct sol_oic_map_reader *input, struct sol_oic_map_writer *output), sol_coap_responsecode_t(*handle_put)(const struct sol_network_link_addr *cliaddr, const void *data, const struct sol_oic_map_reader *input, struct sol_oic_map_writer *output), const char *resource_type)
static int set_scrolllock_led (bool on)
static sol_coap_responsecode_t user_handle_get (const struct sol_network_link_addr *cliaddr, const void *data, const struct sol_oic_map_reader *input, struct sol_oic_map_writer *output)
static sol_coap_responsecode_t user_handle_put (const struct sol_network_link_addr *cliaddr, const void *data, const struct sol_oic_map_reader *input, struct sol_oic_map_writer *output)
Variables
static int console_fd
static bool led_state
Function Documentation
static bool get_scrolllock_led (void) static
References console_fd, led_state, and value.
Referenced by user_handle_get().
int main (int argc, char * argv[])
References console_fd, register_light_resource_type(), SOL_ERR, sol_init(), sol_oic_server_del_resource(), sol_oic_server_init(), sol_oic_server_release(), sol_run(), SOL_WRN, user_handle_get(), and user_handle_put().
static struct sol_oic_server_resource* register_light_resource_type (sol_coap_responsecode_t(*)(const struct sol_network_link_addr *cliaddr, const void *data, const struct sol_oic_map_reader *input, struct sol_oic_map_writer *output) handle_get, sol_coap_responsecode_t(*)(const struct sol_network_link_addr *cliaddr, const void *data, const struct sol_oic_map_reader *input, struct sol_oic_map_writer *output) handle_put, const char * resource_type) static
References sol_oic_resource_type::api_version, sol_oic_resource_type::resource_type, SOL_OIC_FLAG_ACTIVE, SOL_OIC_FLAG_DISCOVERABLE, SOL_OIC_FLAG_OBSERVABLE, SOL_OIC_RESOURCE_TYPE_API_VERSION, sol_oic_server_add_resource(), and SOL_STR_SLICE_LITERAL.
Referenced by main().
static int set_scrolllock_led (bool on) static
References console_fd, and led_state.
Referenced by user_handle_put().
static sol_coap_responsecode_t user_handle_get (const struct sol_network_link_addr * cliaddr, const void * data, const struct sol_oic_map_reader * input, struct sol_oic_map_writer * output) static
References get_scrolllock_led(), SOL_COAP_RSPCODE_CONTENT, SOL_COAP_RSPCODE_INTERNAL_ERROR, SOL_EXP_CHECK, sol_oic_map_append(), SOL_OIC_REPR_BOOLEAN, and SOL_OIC_REPR_INT.
Referenced by main().
static sol_coap_responsecode_t user_handle_put (const struct sol_network_link_addr * cliaddr, const void * data, const struct sol_oic_map_reader * input, struct sol_oic_map_writer * output) static
References sol_oic_repr_field::key, set_scrolllock_led(), SOL_COAP_RSPCODE_BAD_REQUEST, SOL_COAP_RSPCODE_INTERNAL_ERROR, SOL_COAP_RSPCODE_OK, SOL_OIC_MAP_LOOP, SOL_OIC_REPR_TYPE_BOOLEAN, sol_oic_repr_field::type, and sol_oic_repr_field::v_boolean.
Referenced by main().
Variable Documentation
int console_fd static
Referenced by get_scrolllock_led(), main(), and set_scrolllock_led().
bool led_state static
Referenced by get_scrolllock_led(), and set_scrolllock_led().