Soletta™ Framework: src/samples/coap/oic-client.c File Reference
oic-client.c File Reference
#include <stdio.h>
#include "sol-log.h"
#include "sol-mainloop.h"
#include "sol-oic-client.h"
Functions
static bool found_resource (void *data, struct sol_oic_client *cli, struct sol_oic_resource *res)
static void got_get_response (void *data, enum sol_coap_response_code response_code, struct sol_oic_client *cli, const struct sol_network_link_addr *srv_addr, const struct sol_oic_map_reader *map_reader)
int main (int argc, char *argv[])
Function Documentation
static bool found_resource (void * data, struct sol_oic_client * cli, struct sol_oic_resource * res) static
References sol_oic_resource::addr, sol_str_slice::data, sol_oic_resource::device_id, got_get_response(), sol_oic_resource::interfaces, sol_oic_resource::observable, sol_oic_resource::path, sol_oic_resource::secure, SOL_BUFFER_DECLARE_STATIC, sol_buffer_get_slice(), SOL_COAP_METHOD_GET, SOL_NETWORK_INET_ADDR_STR_LEN, sol_network_link_addr_to_str(), sol_oic_client_request(), sol_oic_client_request_new(), SOL_STR_SLICE_PRINT, SOL_VECTOR_FOREACH_IDX, SOL_WRN, and sol_oic_resource::types.
Referenced by main().
static void got_get_response (void * data, enum sol_coap_response_code response_code, struct sol_oic_client * cli, const struct sol_network_link_addr * srv_addr, const struct sol_oic_map_reader * map_reader) static
Examples:
/src/samples/coap/oic-client.c.
References sol_str_slice::data, sol_oic_repr_field::key, sol_str_slice::len, SOL_BUFFER_DECLARE_STATIC, sol_buffer_get_slice(), SOL_NETWORK_INET_ADDR_STR_LEN, sol_network_link_addr_to_str(), SOL_OIC_MAP_LOOP, SOL_OIC_REPR_TYPE_BOOL, SOL_OIC_REPR_TYPE_BYTE_STRING, SOL_OIC_REPR_TYPE_DOUBLE, SOL_OIC_REPR_TYPE_FLOAT, SOL_OIC_REPR_TYPE_HALF_FLOAT, SOL_OIC_REPR_TYPE_INT, SOL_OIC_REPR_TYPE_SIMPLE, SOL_OIC_REPR_TYPE_TEXT_STRING, SOL_OIC_REPR_TYPE_UINT, SOL_OIC_REPR_TYPE_UNSUPPORTED, SOL_STR_SLICE_PRINT, SOL_WRN, sol_oic_repr_field::type, sol_oic_repr_field::v_boolean, sol_oic_repr_field::v_double, sol_oic_repr_field::v_float, sol_oic_repr_field::v_int, sol_oic_repr_field::v_simple, sol_oic_repr_field::v_slice, sol_oic_repr_field::v_uint, and sol_oic_repr_field::v_voidptr.
Referenced by found_resource().
int main (int argc, char * argv[])
References sol_network_link_addr::family, found_resource(), sol_init(), SOL_NETWORK_FAMILY_INET, SOL_NETWORK_FAMILY_INET6, sol_network_link_addr_from_str(), sol_oic_client_del(), sol_oic_client_find_resources(), sol_oic_client_new(), and sol_run().