Soletta™ Framework: src/samples/common/platform-simple.c File Reference
platform-simple.c File Reference
#include <errno.h>
#include <stdlib.h>
#include <stdio.h>
#include "sol-mainloop.h"
#include "sol-platform.h"
#include "sol-util.h"
Macros
#define CMD_TICK 2000
Functions
int main (int argc, char *argv[])
static void on_service_changed (void *data, const char *service, enum sol_platform_service_state state)
static void on_state_change (void *data, enum sol_platform_state state)
static bool on_timeout_cmd (void *data)
Variables
static char ** cmds
static int cur_cmd
static int n_cmds
static struct sol_timeout * timeout_handle
Macro Definition Documentation
#define CMD_TICK 2000
Examples:
/src/samples/common/platform-simple.c.
Referenced by main().
Function Documentation
int main (int argc, char * argv[])
References CMD_TICK, cmds, n_cmds, on_state_change(), on_timeout_cmd(), sol_init(), sol_platform_add_state_monitor(), sol_platform_del_state_monitor(), sol_platform_get_state(), sol_run(), sol_shutdown(), sol_timeout_add(), sol_timeout_del(), and timeout_handle.
static void on_service_changed (void * data, const char * service, enum sol_platform_service_state state) static
Examples:
/src/samples/common/platform-simple.c.
Referenced by on_timeout_cmd().
static void on_state_change (void * data, enum sol_platform_state state) static
Examples:
/src/samples/common/platform-simple.c.
Referenced by main().
static bool on_timeout_cmd (void * data) static
Examples:
/src/samples/common/platform-simple.c.
References cmds, cur_cmd, n_cmds, on_service_changed(), sol_platform_add_service_monitor(), sol_platform_del_service_monitor(), sol_platform_restart_service(), sol_platform_set_target(), sol_platform_start_service(), sol_platform_stop_service(), and timeout_handle.
Referenced by main().
Variable Documentation
char** cmds static
Examples:
/src/samples/common/platform-simple.c.
Referenced by main(), and on_timeout_cmd().
int cur_cmd static
Examples:
/src/samples/common/platform-simple.c.
Referenced by on_timeout_cmd().
int n_cmds static
Examples:
/src/samples/common/platform-simple.c.
Referenced by main(), and on_timeout_cmd().
struct sol_timeout* timeout_handle static
Examples:
/src/samples/common/platform-simple.c.
Referenced by main(), and on_timeout_cmd().