Soletta: src/modules/flow/gtk/pwm-viewer.c File Reference
pwm-viewer.c File Reference
#include "pwm-viewer.h"
#include "sol-flow/gtk.h"
Macros
#define CHART_HEIGHT 42
#define CHART_WIDTH 340
#define CHART_X 30
#define CHART_Y 8
#define N_WAVES 5
#define WAVE_OFFSET (CHART_WIDTH - CHART_X) / N_WAVES
Functions
DEFINE_DEFAULT_OPEN_CLOSE (pwm_viewer)
int gtk_pwm_viewer_duty_cycle_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int gtk_pwm_viewer_enable_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int gtk_pwm_viewer_period_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
Macro Definition Documentation
#define CHART_HEIGHT 42
#define CHART_WIDTH 340
#define CHART_X 30
#define CHART_Y 8
#define N_WAVES 5
#define WAVE_OFFSET (CHART_WIDTH - CHART_X) / N_WAVES
Function Documentation
DEFINE_DEFAULT_OPEN_CLOSE (pwm_viewer)
int gtk_pwm_viewer_duty_cycle_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References gtk_pwm_viewer_data::base, gtk_pwm_viewer_data::duty_cycle, name, sol_flow_packet_get_irange_value(), sol_flow_packet_get_type(), SOL_FLOW_PACKET_TYPE_IRANGE, SOL_INT_CHECK, SOL_WRN, and gtk_common_data::widget.
int gtk_pwm_viewer_enable_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References gtk_pwm_viewer_data::base, gtk_pwm_viewer_data::enabled, name, sol_flow_packet_get_boolean(), sol_flow_packet_get_type(), SOL_FLOW_PACKET_TYPE_BOOLEAN, SOL_INT_CHECK, SOL_WRN, and gtk_common_data::widget.
int gtk_pwm_viewer_period_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References gtk_pwm_viewer_data::base, name, gtk_pwm_viewer_data::period, sol_flow_packet_get_irange_value(), sol_flow_packet_get_type(), SOL_FLOW_PACKET_TYPE_IRANGE, SOL_INT_CHECK, SOL_WRN, and gtk_common_data::widget.