Soletta: src/modules/flow/gtk/pwm-viewer.h File Reference
pwm-viewer.h File Reference
#include "common.h"
Data Structures
struct gtk_pwm_viewer_data
Functions
DEFINE_DEFAULT_HEADER (pwm_viewer)
int gtk_pwm_viewer_duty_cycle_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int gtk_pwm_viewer_enable_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int gtk_pwm_viewer_period_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
Function Documentation
DEFINE_DEFAULT_HEADER (pwm_viewer)
int gtk_pwm_viewer_duty_cycle_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References gtk_pwm_viewer_data::base, gtk_pwm_viewer_data::duty_cycle, name, sol_flow_packet_get_irange_value(), sol_flow_packet_get_type(), SOL_FLOW_PACKET_TYPE_IRANGE, SOL_INT_CHECK, SOL_WRN, and gtk_common_data::widget.
int gtk_pwm_viewer_enable_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References gtk_pwm_viewer_data::base, gtk_pwm_viewer_data::enabled, name, sol_flow_packet_get_boolean(), sol_flow_packet_get_type(), SOL_FLOW_PACKET_TYPE_BOOLEAN, SOL_INT_CHECK, SOL_WRN, and gtk_common_data::widget.
int gtk_pwm_viewer_period_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References gtk_pwm_viewer_data::base, name, gtk_pwm_viewer_data::period, sol_flow_packet_get_irange_value(), sol_flow_packet_get_type(), SOL_FLOW_PACKET_TYPE_IRANGE, SOL_INT_CHECK, SOL_WRN, and gtk_common_data::widget.