Soletta: src/modules/flow/test/result.c File Reference
result.c File Reference
#include <errno.h>
#include "sol-flow.h"
#include "sol-mainloop.h"
#include "sol-util.h"
#include "test-module.h"
#include "result.h"
#include "sol-flow/test.h"
Functions
int test_fail_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int test_pass_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
void test_result_close (struct sol_flow_node *node, void *data)
int test_result_open (struct sol_flow_node *node, void *data, const struct sol_flow_node_options *options)
int test_result_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
Function Documentation
int test_fail_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
int test_pass_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
void test_result_close (struct sol_flow_node * node, void * data)
References sol_timeout_del(), and test_result_data::timer.
int test_result_open (struct sol_flow_node * node, void * data, const struct sol_flow_node_options * options)
References test_result_data::done, SOL_NULL_CHECK_GOTO, sol_timeout_add(), and test_result_data::timer.
int test_result_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References sol_flow_packet_get_boolean(), and SOL_INT_CHECK.