Soletta: src/bin/sol-fbp-runner/runner.c File Reference
runner.c File Reference
#include <errno.h>
#include <libgen.h>
#include <sys/stat.h>
#include "sol-file-reader.h"
#include "sol-flow-parser.h"
#include "sol-flow-builder.h"
#include "sol-log.h"
#include "sol-str-slice.h"
#include "sol-util.h"
#include "sol-vector.h"
#include "runner.h"
Data Structures
struct map
struct runner
Functions
int runner_attach_simulation (struct runner *r)
void runner_del (struct runner *r)
struct runner * runner_new_from_file (const char *filename, const char **options_strv, struct sol_ptr_vector *fbps)
struct runner * runner_new_from_type (const char *typename, const char **options_strv)
int runner_run (struct runner *r)
Function Documentation
int runner_attach_simulation (struct runner * r)
References ARRAY_SIZE, runner::builder, sol_flow_packet_type::name, map::packet_type, sol_flow_port_type_out::packet_type, sol_flow_port_type_in::packet_type, sol_flow_node_type::ports_in_count, sol_flow_node_type::ports_out_count, runner::root_options, runner::root_type, runner::sim_type, sol_flow_builder_add_node(), sol_flow_builder_del(), sol_flow_builder_get_node_type(), sol_flow_builder_new(), sol_flow_node_type_get_port_in(), sol_flow_node_type_get_port_out(), SOL_INT_CHECK_GOTO, SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, and SOL_WRN.
void runner_del (struct runner * r)
References runner::basename, runner::builder, runner::dir, runner::parser, runner::root, runner::root_options, runner::root_type, runner::sim_type, sol_flow_builder_del(), sol_flow_node_del(), sol_flow_node_options_del(), sol_flow_node_type_del(), and sol_flow_parser_del().
Referenced by runner_new_from_file(), and runner_new_from_type().
struct runner* runner_new_from_file (const char * filename, const char ** options_strv, struct sol_ptr_vector * fbps)
References sol_flow_parser_client::api_version, runner::basename, sol_flow_parser_client::data, runner::dir, runner::fbp_paths, runner::file_readers, runner::filename, runner::parser, runner::parser_client, sol_flow_parser_client::read_file, runner::root_type, runner_del(), sol_flow_parse_buffer(), SOL_FLOW_PARSER_CLIENT_API_VERSION, sol_flow_parser_new(), SOL_NULL_CHECK, and SOL_NULL_CHECK_GOTO.
struct runner* runner_new_from_type (const char * typename, const char ** options_strv)
References runner::filename, runner::root_type, runner_del(), sol_flow_get_builtins_resolver(), sol_flow_resolve(), and SOL_NULL_CHECK.
int runner_run (struct runner * r)
References runner::filename, runner::root, runner::root_options, runner::root_type, runner::sim_type, and sol_flow_node_new().