Soletta™ Framework: src/samples/http/server-https.c File Reference
server-https.c File Reference
HTTPS sample.
#include <getopt.h>
#include <stdio.h>
#include <string.h>
#include "soletta.h"
#include "sol-http.h"
#include "sol-http-server.h"
Functions
static int request_cb (void *data, struct sol_http_request *request)
static void shutdown_server (void)
SOL_MAIN_DEFAULT (startup_server, shutdown_server)
static void startup_server (void)
Variables
static struct sol_cert * cert
static struct sol_cert * key
static struct sol_http_server * server
static char * server_data
Detailed Description
HTTPS sample.
Basic HTTPS server. It uses a given certificate to crypto its contents.
How to generate a certificate:
openssl req -new > new.cert.csr openssl rsa -in privkey.pem -out new.cert.key openssl x509 -in new.cert.csr -out new.cert.cert -req -signkey new.cert.key -days 3652 -sha1
To test it:
run ./server-https -p 8080 -d "Hello HTTPS" -c new.cert.cert -k new,.cert.key
open the browser and go to address https://your-ip:the-given-port The browser will complaint about the certificate, it's ok add it as exception.
To see the usage help, -h or –help.
Function Documentation
static int request_cb (void * data, struct sol_http_request * request) static
Examples:
/src/samples/http/server-https.c, /src/samples/http/server-sse.c, and /src/samples/http/server.c.
References sol_http_response::api_version, sol_http_response::content, server_data, sol_buffer_fini(), SOL_BUFFER_INIT_CONST, SOL_HTTP_REQUEST_PARAMS_INIT, SOL_HTTP_RESPONSE_API_VERSION, sol_http_server_send_response(), SOL_HTTP_STATUS_OK, and SOL_SET_API_VERSION.
Referenced by startup_server().
static void shutdown_server (void) static
Examples:
/src/samples/http/server-https.c, /src/samples/http/server-sse.c, /src/samples/http/server.c, /src/samples/http/static-files.c, and /src/samples/network/echo-server.c.
References server, and sol_http_server_del().
SOL_MAIN_DEFAULT (startup_server , shutdown_server)
static void startup_server (void) static
Examples:
/src/samples/http/server-https.c, /src/samples/http/server-sse.c, /src/samples/http/server.c, /src/samples/http/static-files.c, and /src/samples/network/echo-server.c.
References cert, key, port, request_cb(), server, server_data, sol_argc(), sol_argv(), sol_cert_load_from_id(), sol_cert_unref(), SOL_HTTP_SERVER_CONFIG_API_VERSION, sol_http_server_new(), sol_http_server_register_handler(), sol_quit_with_code(), and SOL_SET_API_VERSION.
Variable Documentation
struct sol_cert* cert static
Examples:
/src/samples/http/server-https.c.
Referenced by startup_server().
struct sol_cert * key static
Examples:
/src/samples/coap/lwm2m-bs-server.c, /src/samples/coap/lwm2m-server.c, /src/samples/crypto/message-digest.c, /src/samples/http/client.c, and /src/samples/http/server-https.c.
Referenced by create_header_params(), main(), startup(), and startup_server().
struct sol_http_server* server static
Examples:
/src/samples/coap/lwm2m-bs-server.c, /src/samples/coap/lwm2m-server.c, /src/samples/coap/simple-client.c, /src/samples/coap/simple-server.c, /src/samples/http/server-https.c, /src/samples/http/server-sse.c, /src/samples/http/server.c, and /src/samples/http/static-files.c.
Referenced by main(), shutdown_server(), startup_server(), and update_light().
char* server_data static
Examples:
/src/samples/coap/lwm2m-client.c, and /src/samples/http/server-https.c.
Referenced by main(), request_cb(), and startup_server().