Soletta: src/lib/flow/sol-flow-static.c File Reference
sol-flow-static.c File Reference
#include <assert.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "sol-buffer.h"
#include "sol-flow-internal.h"
#include "sol-flow-static.h"
#include "sol-list.h"
#include "sol-mainloop.h"
#include "sol-util.h"
Data Structures
struct conn_info
struct delayed_packet
struct flow_static_data
struct flow_static_type
struct node_info
Macros
#define CONNECT_NODES_WRN(spec, src_id, dst_id, reason,...)
#define INVALID_SPEC_WRN(spec, reason,...)
#define SOL_FLOW_STATIC_TYPE_CHECK(type,...)
Functions
SOL_API struct sol_flow_node * sol_flow_static_get_node (struct sol_flow_node *flow, uint16_t index)
SOL_API struct sol_flow_node * sol_flow_static_new (struct sol_flow_node *parent, const struct sol_flow_static_node_spec nodes[], const struct sol_flow_static_conn_spec conns[])
SOL_API struct sol_flow_node_type * sol_flow_static_new_type (const struct sol_flow_static_spec *spec)
Macro Definition Documentation
#define CONNECT_NODES_WRN (spec, src_id, dst_id, reason, ...)
Value:
SOL_WRN("Invalid connection specification: "                         \
    "{ .src_id=%s, .src=%hu, .src_port=%hu, .dst_id=%s .dst=%hu, .dst_port=%hu }: " # reason, \
    src_id, spec->src, spec->src_port,                           \
    dst_id, spec->dst, spec->dst_port, ## __VA_ARGS__)
#define INVALID_SPEC_WRN (spec, reason, ...)
Value:
SOL_WRN("Invalid connection specification "                          \
    "{ .src=%hu, .src_port=%hu, .dst=%hu, .dst_port=%hu }: " # reason, \
    spec->src, spec->src_port, spec->dst, spec->dst_port, ## __VA_ARGS__)
#define SOL_FLOW_STATIC_TYPE_CHECK (type, ...)
Value:
do {                                                                \
        if (!(type)) {                                                  \
            SOL_WRN("" # type " == NULL");                               \
            return __VA_ARGS__;                                         \
        }                                                               \
        if (((type)->flags & SOL_FLOW_NODE_TYPE_FLAGS_CONTAINER) == 0    \
            || ((type)->open != flow_node_open)) { \
            SOL_WRN("" # type " isn't a static flow type!");             \
            return __VA_ARGS__;                                         \
        }                                                               \
    } while (0)
Referenced by sol_flow_static_get_node().
Function Documentation
SOL_API struct sol_flow_node* sol_flow_static_get_node (struct sol_flow_node * node, uint16_t index)
Get a container node's children node by index
Parameters
node The node to get the child node from
index The index of the child node in node (position in the sol_flow_static_node_spec array)
Returns
The child node of node with the given index or NULL, on errors.
References flow_static_type::node_count, flow_static_data::nodes, sol_flow_node_get_private_data(), SOL_FLOW_STATIC_TYPE_CHECK, SOL_NULL_CHECK, and sol_flow_node::type.
SOL_API struct sol_flow_node* sol_flow_static_new (struct sol_flow_node * parent, const struct sol_flow_static_node_spec nodes[], const struct sol_flow_static_conn_spec conns[])
Creates a new "static flow" node.
Nodes should be created in the sol_main_callbacks::startup function, and at least the root one must be a "static flow" node. This function will create one of those "by hand", if all the child nodes and connections are provided.
Parameters
parent The parent node. Pass NULL if you're creating the root node of the flow.
nodes A SOL_FLOW_STATIC_PORT_SPEC_GUARD terminated array of node specification structs
conns A SOL_FLOW_STATIC_CONN_SPEC_GUARD terminated array of port connections of the nodes declared in nodes. This array must be sorted by node index and port indexes.
For a higher level construct to get your root static flow node, consider using sol_flow_builder_new() family of functions.
See Also
sol_flow_new(), sol_flow_builder_get_node_type() and sol_flow_static_new_type().
Returns
A new node instance on success, otherwise NULL.
References sol_flow_static_spec::api_version, flow_static_type::base, sol_flow_node_container_type::base, sol_flow_static_spec::conns, sol_flow_static_spec::nodes, flow_static_type::owned_by_node, sol_flow_node_new(), sol_flow_node_type_del(), SOL_FLOW_STATIC_API_VERSION, and sol_flow_static_new_type().
SOL_API struct sol_flow_node_type* sol_flow_static_new_type (const struct sol_flow_static_spec * spec)
Creates a new "static flow" (container) type.
This allows one to create a static flow type "by hand" and fine- tune it. Exported input/output ports may be declared, as well as options forwarding.
Parameters
spec A specification of the type to be created. The data inside the spec is assumed to still be valid until the type is deleted.
Returns
A new container node type on success, otherwise NULL.
References sol_flow_static_spec::api_version, flow_static_type::base, sol_flow_node_container_type::base, SOL_FLOW_STATIC_API_VERSION, SOL_NULL_CHECK, and SOL_WRN.
Referenced by sol_flow_builder_get_node_type(), and sol_flow_static_new().