Soletta: src/lib/common/sol-platform-linux.h File Reference
sol-platform-linux.h File Reference
#include "sol-platform.h"
#include "sol-macros.h"
#include <stdbool.h>
#include <stdint.h>
Functions
struct
sol_platform_linux_fork_run * sol_platform_linux_fork_run (void(*on_fork)(void *data), void(*on_child_exit)(void *data, uint64_t pid, int status), const void *data)
void sol_platform_linux_fork_run_exit (int status) SOL_ATTR_NORETURN
uint64_t sol_platform_linux_fork_run_get_pid (const struct sol_platform_linux_fork_run *handle)
int sol_platform_linux_fork_run_send_signal (struct sol_platform_linux_fork_run *handle, int sig)
int sol_platform_linux_fork_run_stop (struct sol_platform_linux_fork_run *handle)
Function Documentation
struct sol_platform_linux_fork_run* sol_platform_linux_fork_run (void(*)(void *data) on_fork, void(*)(void *data, uint64_t pid, int status) on_child_exit, const void * data)
Fork a new process and run the given on_fork callback on that process.
This call will execute fork(), then wait for children to be ready (internally uses a pipe() to synchronize), reset all signal handlers to their default values and then call on_fork. This user-provided function may then do whatever it wants and when it returns the process will exit with EXIT_SUCCESS. The other way to exit is to call sol_platform_linux_fork_run_exit().
Note
whenever the user wants to exit with a different code or prematurely, never call exit() directly, instead call sol_platform_linux_fork_run_exit() (or _exit()). The reason is that functions registered with atexit() or on_exit() shouldn't be executed in the children processes.
When the child exits, the user-provided on_child_exit is called and after this point the handle returned by sol_platform_linux_fork_run() is invalidated (freed), thus shouldn't be used any further.
The main process may force the child process to stop using sol_platform_linux_fork_run_stop(), that blocking call will send SIGTERM and wait the child to exit using waitpid(), calling on_child_exit before it returns.
Parameters
on_fork the function to call back after the child process is ready. The given data is the same pointer given as data.
on_child_exit the function to call back on the main (original) process when the child exits. The given data is the same pointer given as data, pid is the process identifier (as returned by sol_platform_linux_fork_run_get_pid()) and the status is the one returned by libc waitpid(), that means the macros such as WIFEXITED(), WEXITSTATUS(), WIFSIGNALED(), WTERMSIG() and similar from sys/wait.h should be used to interpret it.
data the context data to give to the callbacks on_fork and on_child_exit. It is not modified in any way by sol_platform_linux_fork_run functions.
Returns
the handle to the child process or NULL on errors (and errno is set to the actual reason). The handle may be used to query the process identifier, to stop the process.
See Also
sol_platform_linux_fork_run_stop()
sol_platform_linux_fork_run_get_pid()
sol_platform_linux_fork_run_exit()
References sol_platform_linux_fork_run::data, sol_platform_linux_fork_run::on_child_exit, sol_platform_linux_fork_run::pid, SOL_INT_CHECK_GOTO, SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, sol_platform_linux_fork_run_exit(), sol_ptr_vector_append(), sol_util_strerrora, SOL_WRN, and sol_platform_linux_fork_run::watch.
Referenced by process_subprocess_open(), and process_subprocess_start_process().
void sol_platform_linux_fork_run_exit (int status)
Exit from a child process.
This function is to be called from inside on_fork to exit the child process using a specific status, such as EXIT_FAILURE or EXIT_SUCCESS.
Children process should never call exit() directly, rather use this function or _exit().
Parameters
status the value to use to exit this process, it will be available to the main process via the on_child_exit status parameter, in that case use the sys/wait.h macros to get the actual value, such as WEXITSTATUS().
Referenced by sol_platform_linux_fork_run().
uint64_t sol_platform_linux_fork_run_get_pid (const struct sol_platform_linux_fork_run * handle)
The process identifier of this child.
Parameters
handle a valid (non-NULL and alive) handle returned by sol_platform_linux_fork_run().
Returns
the processes identifier (PID) that can be used with syscalls such as kill(). On errors, UINT64_MAX is returned and errno is set to ENOENT.
References sol_platform_linux_fork_run::pid, and SOL_INT_CHECK.
int sol_platform_linux_fork_run_send_signal (struct sol_platform_linux_fork_run * handle, int sig)
Send a signal to the child process.
This is a helper using sol_platform_linux_fork_run_get_pid() and kill(). It may be useful to send control signals such as SIGUSR1 and SIGUSR2.
Parameters
handle a valid (non-NULL and alive) handle returned by sol_platform_linux_fork_run().
sig the signal number, such as SIGUSR1.
Returns
0 on success or -errno on failure.
References sol_platform_linux_fork_run::pid, and SOL_INT_CHECK.
Referenced by process_subprocess_signal_process(), and process_subprocess_stop_process().
int sol_platform_linux_fork_run_stop (struct sol_platform_linux_fork_run * handle)
Force the child process to stop running and wait for it.
This is a blocking function that will kill the child process using SIGTERM, then waiting the process to exit using waitpid().
After the process exit, the on_child_exit is called and the given handle is invalidated (freed) before this function returns.
If the user doesn't want the blocking behavior he may use sol_platform_linux_fork_run_send_signal() using SIGTERM and wait on_child_exit to be called when the process exits.
Parameters
handle a valid (non-NULL and alive) handle returned by sol_platform_linux_fork_run() to be terminated. After this function return, the handle is then invalidated.
Returns
0 on success or -errno on failure.
See Also
sol_platform_linux_fork_run_send_signal()
References sol_platform_linux_fork_run::data, sol_platform_linux_fork_run::on_child_exit, sol_platform_linux_fork_run::pid, SOL_INT_CHECK, sol_util_strerrora, SOL_WRN, and sol_platform_linux_fork_run::watch.
Referenced by process_subprocess_close().