Soletta: src/lib/common/sol-platform-impl-systemd.c File Reference
sol-platform-impl-systemd.c File Reference
#include <errno.h>
#include <limits.h>
#include <inttypes.h>
#include <stdlib.h>
#include <stdio.h>
#include <systemd/sd-bus.h>
#include "sol-platform-impl.h"
#include "sol-bus.h"
#include "sol-platform.h"
#include "sol-str-table.h"
#include "sol-util.h"
#include "sol-vector.h"
Data Structures
struct ctx
struct service
Enumerations
enum { MANAGER_PROPERTY_SYSTEM_STATE }
enum { SERVICE_PROPERTY_STATE }
enum { TARGET_PARAM_ISOLATE = 0, TARGET_PARAM_REPLACE_IRREVERSIBLY }
Functions
int sol_platform_impl_add_service_monitor (const char *service)
int sol_platform_impl_del_service_monitor (const char *service)
int sol_platform_impl_get_machine_id (char id[static 33])
int sol_platform_impl_get_serial_number (char **number)
int sol_platform_impl_get_state (void)
int sol_platform_impl_init (void)
int sol_platform_impl_restart_service (const char *service)
int sol_platform_impl_set_target (const char *target)
void sol_platform_impl_shutdown (void)
int sol_platform_impl_start_service (const char *service)
int sol_platform_impl_stop_service (const char *service)
Enumeration Type Documentation
anonymous enum
Enumerator
MANAGER_PROPERTY_SYSTEM_STATE
anonymous enum
Enumerator
SERVICE_PROPERTY_STATE
anonymous enum
Enumerator
TARGET_PARAM_ISOLATE
TARGET_PARAM_REPLACE_IRREVERSIBLY
Function Documentation
int sol_platform_impl_add_service_monitor (const char * service)
References service::properties, service::service, ctx::services, service::slot, sol_bus_get(), SOL_INT_CHECK_GOTO, SOL_NULL_CHECK, SOL_PLATFORM_SERVICE_STATE_UNKNOWN, sol_ptr_vector_append(), SOL_WRN, and service::state.
int sol_platform_impl_del_service_monitor (const char * service)
References service::service, ctx::services, service::slot, sol_bus_unmap_cached_properties(), SOL_NULL_CHECK, SOL_PTR_VECTOR_FOREACH_IDX, SOL_WRN, and streq.
int sol_platform_impl_get_machine_id (char id[static 33])
References sol_util_read_file(), and SOL_WRN.
int sol_platform_impl_get_serial_number (char ** number)
References SOL_INT_CHECK, sol_util_read_file(), and SOL_WRN.
int sol_platform_impl_get_state (void)
References ctx::properties, sol_bus_get(), SOL_NULL_CHECK, SOL_WRN, and ctx::system_state.
int sol_platform_impl_init (void)
References ctx::services.
int sol_platform_impl_restart_service (const char * service)
References SOL_WRN.
int sol_platform_impl_set_target (const char * target)
References SOL_PLATFORM_TARGET_DEFAULT, SOL_PLATFORM_TARGET_EMERGENCY, SOL_PLATFORM_TARGET_POWEROFF, SOL_PLATFORM_TARGET_REBOOT, SOL_PLATFORM_TARGET_RESCUE, SOL_PLATFORM_TARGET_SUSPEND, SOL_STR_TABLE_ITEM, sol_str_table_lookup_fallback(), SOL_WRN, TARGET_PARAM_ISOLATE, and TARGET_PARAM_REPLACE_IRREVERSIBLY.
void sol_platform_impl_shutdown (void)
References ctx::services, and sol_bus_close().
int sol_platform_impl_start_service (const char * service)
References SOL_WRN.
int sol_platform_impl_stop_service (const char * service)
References SOL_WRN.