Soletta: src/shared/sol-fbp.h File Reference
sol-fbp.h File Reference
#include "sol-arena.h"
#include "sol-str-slice.h"
#include "sol-vector.h"
Data Structures
struct sol_fbp_conn
struct sol_fbp_declaration
struct sol_fbp_error
struct sol_fbp_exported_port
struct sol_fbp_graph
struct sol_fbp_meta
struct sol_fbp_node
struct sol_fbp_option
struct sol_fbp_port
struct sol_fbp_position
Functions
void sol_fbp_error_free (struct sol_fbp_error *e)
int sol_fbp_graph_add_conn (struct sol_fbp_graph *g, int src, struct sol_str_slice src_port, int src_port_idx, int dst, struct sol_str_slice dst_port, int dst_port_idx, struct sol_fbp_position position)
int sol_fbp_graph_add_exported_in_port (struct sol_fbp_graph *g, int node, struct sol_str_slice port, int port_idx, struct sol_str_slice exported_name, struct sol_fbp_position position, struct sol_fbp_exported_port **out_ep)
int sol_fbp_graph_add_exported_out_port (struct sol_fbp_graph *g, int node, struct sol_str_slice port, int port_idx, struct sol_str_slice exported_name, struct sol_fbp_position position, struct sol_fbp_exported_port **out_ep)
int sol_fbp_graph_add_in_port (struct sol_fbp_graph *g, int node, struct sol_str_slice name, struct sol_fbp_position position)
int sol_fbp_graph_add_meta (struct sol_fbp_graph *g, int node, struct sol_str_slice key, struct sol_str_slice value, struct sol_fbp_position position)
int sol_fbp_graph_add_node (struct sol_fbp_graph *g, struct sol_str_slice name, struct sol_str_slice component, struct sol_fbp_position position, struct sol_fbp_node **out_node)
int sol_fbp_graph_add_out_port (struct sol_fbp_graph *g, int node, struct sol_str_slice name, struct sol_fbp_position position)
int sol_fbp_graph_declare (struct sol_fbp_graph *g, struct sol_str_slice name, struct sol_str_slice metatype, struct sol_str_slice contents, struct sol_fbp_position)
int sol_fbp_graph_fini (struct sol_fbp_graph *g)
int sol_fbp_graph_init (struct sol_fbp_graph *g)
int sol_fbp_graph_option (struct sol_fbp_graph *g, int node, struct sol_str_slice name, struct sol_str_slice node_opt, struct sol_fbp_position position)
void sol_fbp_log_print (const char *file, unsigned int line, unsigned int column, const char *format,...)
struct sol_fbp_error * sol_fbp_parse (struct sol_str_slice input, struct sol_fbp_graph *g)
Function Documentation
void sol_fbp_error_free (struct sol_fbp_error * e)
References sol_fbp_error::msg, and SOL_NULL_CHECK.
int sol_fbp_graph_add_conn (struct sol_fbp_graph * g, int src, struct sol_str_slice src_port, int src_port_idx, int dst, struct sol_str_slice dst_port, int dst_port_idx, struct sol_fbp_position position)
References sol_fbp_graph::conns, sol_fbp_conn::dst, sol_fbp_conn::dst_port, sol_fbp_conn::dst_port_idx, sol_str_slice::len, sol_fbp_conn::position, SOL_INT_CHECK, SOL_NULL_CHECK, sol_vector_append(), SOL_VECTOR_FOREACH_IDX, sol_fbp_conn::src, and sol_fbp_conn::src_port_idx.
int sol_fbp_graph_add_exported_in_port (struct sol_fbp_graph * g, int node, struct sol_str_slice port, int port_idx, struct sol_str_slice exported_name, struct sol_fbp_position position, struct sol_fbp_exported_port ** out_ep)
References sol_fbp_graph::exported_in_ports, sol_fbp_exported_port::exported_name, sol_fbp_exported_port::node, sol_fbp_exported_port::port_idx, sol_fbp_exported_port::position, SOL_NULL_CHECK, sol_vector_append(), and SOL_VECTOR_FOREACH_IDX.
int sol_fbp_graph_add_exported_out_port (struct sol_fbp_graph * g, int node, struct sol_str_slice port, int port_idx, struct sol_str_slice exported_name, struct sol_fbp_position position, struct sol_fbp_exported_port ** out_ep)
References sol_fbp_exported_port::exported_name, sol_fbp_graph::exported_out_ports, sol_fbp_exported_port::node, sol_fbp_exported_port::port_idx, sol_fbp_exported_port::position, SOL_NULL_CHECK, sol_vector_append(), and SOL_VECTOR_FOREACH_IDX.
int sol_fbp_graph_add_in_port (struct sol_fbp_graph * g, int node, struct sol_str_slice name, struct sol_fbp_position position)
References sol_fbp_node::in_ports, sol_fbp_port::name, name, sol_fbp_graph::nodes, sol_fbp_port::position, SOL_INT_CHECK, SOL_NULL_CHECK, sol_vector_append(), and SOL_VECTOR_FOREACH_IDX.
int sol_fbp_graph_add_meta (struct sol_fbp_graph * g, int node, struct sol_str_slice key, struct sol_str_slice value, struct sol_fbp_position position)
References sol_fbp_meta::key, sol_fbp_node::meta, sol_fbp_graph::nodes, sol_fbp_meta::position, SOL_INT_CHECK, SOL_NULL_CHECK, sol_vector_append(), SOL_VECTOR_FOREACH_IDX, and sol_fbp_meta::value.
int sol_fbp_graph_add_node (struct sol_fbp_graph * g, struct sol_str_slice name, struct sol_str_slice component, struct sol_fbp_position position, struct sol_fbp_node ** out_node)
References sol_fbp_graph::arena, sol_fbp_position::column, sol_fbp_node::component, sol_str_slice::data, sol_fbp_node::in_ports, sol_vector::len, sol_str_slice::len, sol_fbp_position::line, sol_fbp_node::meta, sol_fbp_node::name, name, sol_fbp_graph::nodes, sol_fbp_node::out_ports, sol_fbp_node::position, sol_arena_slice_sprintf(), SOL_INT_CHECK, SOL_NULL_CHECK, sol_vector_append(), SOL_VECTOR_FOREACH_IDX, sol_vector_init(), and sol_fbp_node::user_data.
int sol_fbp_graph_add_out_port (struct sol_fbp_graph * g, int node, struct sol_str_slice name, struct sol_fbp_position position)
References sol_fbp_port::name, name, sol_fbp_graph::nodes, sol_fbp_node::out_ports, sol_fbp_port::position, SOL_INT_CHECK, SOL_NULL_CHECK, sol_vector_append(), and SOL_VECTOR_FOREACH_IDX.
int sol_fbp_graph_declare (struct sol_fbp_graph * g, struct sol_str_slice name, struct sol_str_slice metatype, struct sol_str_slice contents, struct sol_fbp_position)
References sol_fbp_declaration::contents, sol_fbp_graph::declarations, sol_str_slice::len, sol_fbp_declaration::metatype, name, sol_fbp_declaration::name, sol_fbp_declaration::position, SOL_NULL_CHECK, sol_vector_append(), and SOL_VECTOR_FOREACH_IDX.
int sol_fbp_graph_fini (struct sol_fbp_graph * g)
References sol_fbp_graph::arena, sol_fbp_graph::conns, sol_fbp_graph::declarations, sol_fbp_graph::exported_in_ports, sol_fbp_graph::exported_out_ports, sol_fbp_node::in_ports, sol_fbp_node::meta, sol_fbp_graph::nodes, sol_fbp_graph::options, sol_fbp_node::out_ports, sol_arena_del(), SOL_NULL_CHECK, sol_vector_clear(), and SOL_VECTOR_FOREACH_IDX.
Referenced by main().
int sol_fbp_graph_init (struct sol_fbp_graph * g)
References sol_fbp_graph::arena, sol_fbp_graph::conns, sol_fbp_graph::declarations, sol_fbp_graph::exported_in_ports, sol_fbp_graph::exported_out_ports, sol_fbp_graph::nodes, sol_fbp_graph::options, sol_arena_new(), sol_fbp_init_log_domain(), SOL_NULL_CHECK, and sol_vector_init().
int sol_fbp_graph_option (struct sol_fbp_graph * g, int node, struct sol_str_slice name, struct sol_str_slice node_opt, struct sol_fbp_position position)
References sol_str_slice::len, name, sol_fbp_option::name, sol_fbp_option::node, sol_fbp_option::node_option, sol_fbp_graph::options, sol_fbp_option::position, SOL_NULL_CHECK, sol_vector_append(), and SOL_VECTOR_FOREACH_IDX.
void sol_fbp_log_print (const char * file, unsigned int line, unsigned int column, const char * format, ...)
References sol_util_strerrora, and SOL_WRN.
struct sol_fbp_error* sol_fbp_parse (struct sol_str_slice input, struct sol_fbp_graph * g)
References sol_fbp_parser::current_token, sol_fbp_parser::error_msg, sol_fbp_parser::error_pos, sol_fbp_parser::graph, sol_fbp_error::msg, sol_fbp_parser::pending_token, sol_fbp_error::position, sol_fbp_parser::scanner, sol_fbp_init_log_domain(), sol_fbp_scanner_init(), and sol_fbp_token::type.