Soletta: src/lib/common/sol-log.c File Reference
sol-log.c File Reference
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include "sol-util.h"
#include "sol-log.h"
#include "sol-log-impl.h"
Macros
#define SOL_LOG_INIT_CHECK(fmt,...)
Functions
SOL_API void sol_log_domain_init_level (struct sol_log_domain *domain)
SOL_API uint8_t sol_log_get_abort_level (void)
SOL_API uint8_t sol_log_get_level (void)
SOL_API const char * sol_log_get_level_color (uint8_t level)
SOL_API bool sol_log_get_show_colors (void)
SOL_API bool sol_log_get_show_file (void)
SOL_API bool sol_log_get_show_function (void)
SOL_API bool sol_log_get_show_line (void)
int sol_log_init (void)
SOL_API void sol_log_level_to_str (uint8_t level, char *buf, size_t buflen)
SOL_API void sol_log_print (const struct sol_log_domain *domain, uint8_t message_level, const char *file, const char *function, int line, const char *format,...)
SOL_API void sol_log_print_function_stderr (void *data, const struct sol_log_domain *domain, uint8_t message_level, const char *file, const char *function, int line, const char *format, va_list args)
SOL_API void sol_log_set_abort_level (uint8_t level)
SOL_API void sol_log_set_level (uint8_t level)
SOL_API void sol_log_set_print_function (void(*cb)(void *data, const struct sol_log_domain *domain, uint8_t message_level, const char *file, const char *function, int line, const char *format, va_list args), const void *data)
SOL_API void sol_log_set_show_colors (bool enabled)
SOL_API void sol_log_set_show_file (bool enabled)
SOL_API void sol_log_set_show_function (bool enabled)
SOL_API void sol_log_set_show_line (bool enabled)
void sol_log_shutdown (void)
SOL_API void sol_log_vprint (const struct sol_log_domain *domain, uint8_t message_level, const char *file, const char *function, int line, const char *format, va_list args)
Variables
uint8_t _abort_level = SOL_LOG_LEVEL_CRITICAL
struct sol_log_domain _global_domain
void(* _print_function)(void *data, const struct sol_log_domain *domain, uint8_t message_level, const char *file, const char *function, int line, const char *format, va_list args) = sol_log_print_function_stderr
const void * _print_function_data = NULL
bool _show_colors = false
bool _show_file = true
bool _show_function = true
bool _show_line = true
SOL_API struct sol_log_domain * sol_log_global_domain = &_global_domain
Macro Definition Documentation
#define SOL_LOG_INIT_CHECK (fmt, ...)
Value:
do {                                                                \
        if (unlikely(!_inited)) {                                       \
            fprintf(stderr, "CRITICAL:%s:%d:%s() "                      \
                "SOL_LOG used before initialization. "fmt "\n",       \
                __FILE__, __LINE__, __PRETTY_FUNCTION__, ## __VA_ARGS__); \
            abort();                                                    \
        }                                                               \
    } while (0)
Referenced by sol_log_domain_init_level(), sol_log_get_abort_level(), sol_log_get_level(), sol_log_get_level_color(), sol_log_get_show_colors(), sol_log_get_show_file(), sol_log_get_show_function(), sol_log_get_show_line(), sol_log_level_to_str(), sol_log_set_abort_level(), sol_log_set_level(), sol_log_set_print_function(), sol_log_set_show_colors(), sol_log_set_show_file(), sol_log_set_show_function(), sol_log_set_show_line(), and sol_log_vprint().
Function Documentation
SOL_API void sol_log_domain_init_level (struct sol_log_domain * domain)
References sol_log_domain::name, sol_log_impl_domain_init_level(), and SOL_LOG_INIT_CHECK.
Referenced by sol_blob_init(), sol_flow_init(), sol_init(), sol_pin_mux_init(), and sol_platform_init().
SOL_API uint8_t sol_log_get_abort_level (void)
References _abort_level, and SOL_LOG_INIT_CHECK.
SOL_API uint8_t sol_log_get_level (void)
References sol_log_domain::level, and SOL_LOG_INIT_CHECK.
SOL_API const char* sol_log_get_level_color (uint8_t level)
References ARRAY_SIZE, sol_log_domain::level, SOL_LOG_COLOR_CYAN, SOL_LOG_COLOR_LIGHTBLUE, SOL_LOG_COLOR_LIGHTRED, SOL_LOG_COLOR_MAGENTA, SOL_LOG_COLOR_ORANGE, SOL_LOG_COLOR_RED, SOL_LOG_INIT_CHECK, SOL_LOG_LEVEL_CRITICAL, SOL_LOG_LEVEL_DEBUG, SOL_LOG_LEVEL_ERROR, SOL_LOG_LEVEL_INFO, and SOL_LOG_LEVEL_WARNING.
Referenced by sol_log_impl_print_function_stderr().
SOL_API bool sol_log_get_show_colors (void)
References _show_colors, and SOL_LOG_INIT_CHECK.
SOL_API bool sol_log_get_show_file (void)
References _show_file, and SOL_LOG_INIT_CHECK.
SOL_API bool sol_log_get_show_function (void)
References _show_function, and SOL_LOG_INIT_CHECK.
SOL_API bool sol_log_get_show_line (void)
References _show_line, and SOL_LOG_INIT_CHECK.
int sol_log_init (void)
References sol_log_impl_init().
Referenced by sol_init().
SOL_API void sol_log_level_to_str (uint8_t level, char * buf, size_t buflen)
References ARRAY_SIZE, SOL_LOG_INIT_CHECK, SOL_LOG_LEVEL_CRITICAL, SOL_LOG_LEVEL_DEBUG, SOL_LOG_LEVEL_ERROR, SOL_LOG_LEVEL_INFO, and SOL_LOG_LEVEL_WARNING.
Referenced by sol_log_impl_print_function_stderr(), and sol_log_print_function_file().
SOL_API void sol_log_print (const struct sol_log_domain * domain, uint8_t message_level, const char * file, const char * function, int line, const char * format, ...)
References sol_log_vprint().
SOL_API void sol_log_print_function_stderr (void * data, const struct sol_log_domain * domain, uint8_t message_level, const char * file, const char * function, int line, const char * format, va_list args)
References sol_log_impl_print_function_stderr().
Referenced by sol_log_impl_init(), and sol_log_set_print_function().
SOL_API void sol_log_set_abort_level (uint8_t level)
References _abort_level, sol_log_domain::level, and SOL_LOG_INIT_CHECK.
SOL_API void sol_log_set_level (uint8_t level)
References sol_log_domain::level, and SOL_LOG_INIT_CHECK.
SOL_API void sol_log_set_print_function (void(*)(void *data, const struct sol_log_domain *domain, uint8_t message_level, const char *file, const char *function, int line, const char *format, va_list args) cb, const void * data)
References _print_function, _print_function_data, SOL_LOG_INIT_CHECK, and sol_log_print_function_stderr().
SOL_API void sol_log_set_show_colors (bool enabled)
References _show_colors, and SOL_LOG_INIT_CHECK.
SOL_API void sol_log_set_show_file (bool enabled)
References _show_file, and SOL_LOG_INIT_CHECK.
SOL_API void sol_log_set_show_function (bool enabled)
References _show_function, and SOL_LOG_INIT_CHECK.
SOL_API void sol_log_set_show_line (bool enabled)
References _show_line, and SOL_LOG_INIT_CHECK.
void sol_log_shutdown (void)
References sol_log_impl_shutdown().
Referenced by sol_init(), and sol_shutdown().
SOL_API void sol_log_vprint (const struct sol_log_domain * domain, uint8_t message_level, const char * file, const char * function, int line, const char * format, va_list args)
References _abort_level, _global_domain, _print_function, _print_function_data, sol_log_domain::level, sol_log_impl_lock(), sol_log_impl_unlock(), and SOL_LOG_INIT_CHECK.
Referenced by sol_log_print().
Variable Documentation
uint8_t _abort_level = SOL_LOG_LEVEL_CRITICAL
Referenced by sol_log_get_abort_level(), sol_log_impl_init(), sol_log_set_abort_level(), and sol_log_vprint().
struct sol_log_domain _global_domain
Initial value:
= {
    .color = SOL_LOG_COLOR_WHITE,
    .name = "",
    .level = SOL_LOG_LEVEL_WARNING
}
Referenced by sol_log_impl_domain_init_level(), sol_log_impl_init(), and sol_log_vprint().
void(* _print_function)(void *data, const struct sol_log_domain *domain, uint8_t message_level, const char *file, const char *function, int line, const char *format, va_list args) = sol_log_print_function_stderr
Referenced by sol_log_impl_init(), sol_log_set_print_function(), and sol_log_vprint().
const void* _print_function_data = NULL
Referenced by sol_log_impl_init(), sol_log_set_print_function(), and sol_log_vprint().
bool _show_colors = false
Referenced by sol_log_get_show_colors(), sol_log_impl_init(), sol_log_impl_print_function_stderr(), and sol_log_set_show_colors().
bool _show_file = true
Referenced by sol_log_get_show_file(), sol_log_impl_init(), sol_log_impl_print_function_stderr(), sol_log_print_function_file(), and sol_log_set_show_file().
bool _show_function = true
Referenced by sol_log_get_show_function(), sol_log_impl_init(), sol_log_impl_print_function_stderr(), sol_log_print_function_file(), and sol_log_set_show_function().
bool _show_line = true
Referenced by sol_log_get_show_line(), sol_log_impl_init(), sol_log_impl_print_function_stderr(), sol_log_print_function_file(), and sol_log_set_show_line().