Soletta: src/lib/comms/sol-socket-impl-riot.c File Reference
sol-socket-impl-riot.c File Reference
#include "sol-interrupt_scheduler_riot.h"
#include "sol-log.h"
#include "sol-mainloop.h"
#include "sol-socket.h"
#include "sol-vector.h"
#include "sol-util.h"
#include "net/gnrc/ipv6.h"
#include "net/gnrc/udp.h"
Data Structures
struct sol_socket
struct sol_socket_class
Macros
#define IPV6_MULTICAST_PREFIX_LEN 16
Functions
void sol_network_msg_dispatch (msg_t *msg)
SOL_API int sol_socket_bind (struct sol_socket *s, const struct sol_network_link_addr *addr)
SOL_API void sol_socket_del (struct sol_socket *s)
SOL_API int sol_socket_join_group (struct sol_socket *s, int ifindex, const struct sol_network_link_addr *group)
SOL_API struct sol_socket * sol_socket_new (int domain, enum sol_socket_type type, int protocol)
SOL_API int sol_socket_recvmsg (struct sol_socket *s, void *buf, size_t len, struct sol_network_link_addr *cliaddr)
SOL_API int sol_socket_sendmsg (struct sol_socket *s, const void *buf, size_t len, const struct sol_network_link_addr *cliaddr)
SOL_API int sol_socket_set_on_read (struct sol_socket *s, bool(*cb)(void *data, struct sol_socket *s), void *data)
SOL_API int sol_socket_set_on_write (struct sol_socket *s, bool(*cb)(void *data, struct sol_socket *s), void *data)
Macro Definition Documentation
#define IPV6_MULTICAST_PREFIX_LEN 16
Function Documentation
void sol_network_msg_dispatch (msg_t * msg)
Referenced by sol_interrupt_scheduler_process().
SOL_API int sol_socket_bind (struct sol_socket * s, const struct sol_network_link_addr * addr)
References sol_socket_class::bind, sol_socket::class, sol_socket::entry, sol_socket::fd, SOL_INT_CHECK, sol_interrupt_scheduler_get_pid(), SOL_NULL_CHECK, and sol_socket_class::type.
SOL_API void sol_socket_del (struct sol_socket * s)
References sol_socket::class, sol_socket_class::delete, sol_socket::entry, sol_socket::fd, sol_socket::read, sol_socket_class::type, sol_socket::watch, and sol_socket::write.
SOL_API int sol_socket_join_group (struct sol_socket * s, int ifindex, const struct sol_network_link_addr * group)
References sol_network_link_addr::addr, sol_socket::class, sol_network_link_addr::family, sol_socket::fd, sol_network_link_addr::in, sol_network_link_addr::in6, sol_socket_class::join_group, and SOL_NULL_CHECK.
SOL_API struct sol_socket* sol_socket_new (int domain, enum sol_socket_type type, int protocol)
References sol_socket::class, sol_socket::entry, sol_socket::fd, SOL_INT_CHECK, SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, SOL_SOCKET_UDP, and SOL_WRN.
SOL_API int sol_socket_recvmsg (struct sol_socket * s, void * buf, size_t len, struct sol_network_link_addr * cliaddr)
References sol_network_link_addr::addr, sol_network_link::addrs, sol_socket::class, sol_network_link_addr::family, sol_socket::fd, sol_network_link::flags, sol_network_link::index, sol_vector::len, sol_socket_class::recvmsg, SOL_API, SOL_DBG, sol_network_get_available_links(), SOL_NETWORK_LINK_MULTICAST, SOL_NETWORK_LINK_RUNNING, SOL_NULL_CHECK, sol_util_strerrora, SOL_VECTOR_FOREACH_IDX, and SOL_WRN.
SOL_API int sol_socket_sendmsg (struct sol_socket * s, const void * buf, size_t len, const struct sol_network_link_addr * cliaddr)
References sol_socket::class, sol_network_link_addr::family, sol_socket::fd, sol_socket_class::sendmsg, SOL_API, SOL_NULL_CHECK, and sol_socket_class::type.
SOL_API int sol_socket_set_on_read (struct sol_socket * s, bool(*)(void *data, struct sol_socket *s) cb, void * data)
References sol_socket::cb, sol_socket::data, sol_socket::fd, sol_socket::read, SOL_NULL_CHECK, and sol_socket::watch.
SOL_API int sol_socket_set_on_write (struct sol_socket * s, bool(*)(void *data, struct sol_socket *s) cb, void * data)
References sol_socket::cb, sol_socket::data, sol_socket::fd, SOL_NULL_CHECK, sol_timeout_add(), sol_timeout_del(), sol_socket::watch, sol_socket::write, and sol_socket::write_timeout.