Soletta: src/lib/common/sol-platform-impl-linux-micro.c File Reference
sol-platform-impl-linux-micro.c File Reference
#include <ctype.h>
#include <dlfcn.h>
#include <errno.h>
#include <limits.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/ioctl.h>
#include <sys/mount.h>
#include <sys/reboot.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>
#include "sol-file-reader.h"
#include "sol-mainloop.h"
#include "sol-platform-impl.h"
#include "sol-platform-linux-micro.h"
#include "sol-platform.h"
#include "sol-util.h"
#include "sol-vector.h"
#include "sol-platform-linux-micro-builtins-gen.h"
Data Structures
struct mount_table
Macros
#define SOL_DEBUG_ARG "sol-debug=1"
#define SOL_DEBUG_COMM_ARG "sol-debug-comm="
Functions
int sol_platform_impl_add_service_monitor (const char *service)
int sol_platform_impl_del_service_monitor (const char *service)
int sol_platform_impl_get_machine_id (char id[static 33])
int sol_platform_impl_get_serial_number (char **number)
int sol_platform_impl_get_state (void)
int sol_platform_impl_init (void)
int sol_platform_impl_restart_service (const char *service)
int sol_platform_impl_set_target (const char *target)
void sol_platform_impl_shutdown (void)
int sol_platform_impl_start_service (const char *service)
int sol_platform_impl_stop_service (const char *service)
SOL_API void sol_platform_linux_micro_inform_service_state (const char *service, enum sol_platform_service_state state)
Macro Definition Documentation
#define SOL_DEBUG_ARG "sol-debug=1"
#define SOL_DEBUG_COMM_ARG "sol-debug-comm="
Function Documentation
int sol_platform_impl_add_service_monitor (const char * service)
References SOL_PLATFORM_STATE_STOPPING, and SOL_WRN.
int sol_platform_impl_del_service_monitor (const char * service)
References SOL_PLATFORM_STATE_STOPPING, and SOL_WRN.
int sol_platform_impl_get_machine_id (char id[static 33])
References sol_util_read_file().
int sol_platform_impl_get_serial_number (char ** number)
References SOL_INT_CHECK, and sol_util_read_file().
int sol_platform_impl_get_state (void)
int sol_platform_impl_init (void)
References SOL_INT_CHECK, SOL_PLATFORM_STATE_INITIALIZING, SOL_PLATFORM_STATE_RUNNING, and streq.
int sol_platform_impl_restart_service (const char * service)
References SOL_DBG, SOL_INT_CHECK, SOL_PLATFORM_SERVICE_STATE_ACTIVATING, SOL_PLATFORM_SERVICE_STATE_DEACTIVATING, SOL_PLATFORM_SERVICE_STATE_RELOADING, SOL_PLATFORM_STATE_STOPPING, and SOL_WRN.
int sol_platform_impl_set_target (const char * target)
References SOL_PLATFORM_STATE_STOPPING, SOL_PLATFORM_TARGET_DEFAULT, SOL_PLATFORM_TARGET_EMERGENCY, SOL_PLATFORM_TARGET_POWEROFF, SOL_PLATFORM_TARGET_REBOOT, SOL_PLATFORM_TARGET_RESCUE, SOL_PLATFORM_TARGET_SUSPEND, sol_quit(), SOL_WRN, and streq.
void sol_platform_impl_shutdown (void)
References SOL_PLATFORM_STATE_STOPPING.
int sol_platform_impl_start_service (const char * service)
References SOL_DBG, SOL_PLATFORM_SERVICE_STATE_ACTIVATING, SOL_PLATFORM_STATE_STOPPING, and SOL_WRN.
int sol_platform_impl_stop_service (const char * service)
References SOL_DBG, SOL_PLATFORM_SERVICE_STATE_DEACTIVATING, SOL_PLATFORM_STATE_STOPPING, and SOL_WRN.
SOL_API void sol_platform_linux_micro_inform_service_state (const char * service, enum sol_platform_service_state state)
References sol_platform_inform_service_monitors(), SOL_PLATFORM_STATE_STOPPING, and SOL_WRN.