Soletta: src/lib/common/sol-interrupt_scheduler_riot.c File Reference
sol-interrupt_scheduler_riot.c File Reference
#include "sol-interrupt_scheduler_riot.h"
#include <stdbool.h>
#include <stdlib.h>
#include <thread.h>
Data Structures
struct interrupt_data
struct interrupt_data_base
Enumerations
enum interrupt_type { GPIO }
Functions
kernel_pid_t sol_interrupt_scheduler_get_pid (void)
int sol_interrupt_scheduler_gpio_init_int (gpio_t dev, gpio_pp_t pullup, gpio_flank_t flank, gpio_cb_t cb, void *arg, void **handler)
void sol_interrupt_scheduler_gpio_stop (gpio_t dev, void *handler)
void sol_interrupt_scheduler_process (msg_t *msg)
void sol_interrupt_scheduler_set_pid (kernel_pid_t p)
Enumeration Type Documentation
enum interrupt_type
Enumerator
GPIO
Function Documentation
kernel_pid_t sol_interrupt_scheduler_get_pid (void)
Referenced by sol_socket_bind().
int sol_interrupt_scheduler_gpio_init_int (gpio_t dev, gpio_pp_t pullup, gpio_flank_t flank, gpio_cb_t cb, void * arg, void ** handler)
References interrupt_data::base, interrupt_data::cb, interrupt_data::data, interrupt_data_base::deleted, and interrupt_data_base::refcount.
Referenced by sol_gpio_open_raw().
void sol_interrupt_scheduler_gpio_stop (gpio_t dev, void * handler)
Referenced by sol_gpio_close().
void sol_interrupt_scheduler_process (msg_t * msg)
References interrupt_data::base, interrupt_data::cb, interrupt_data::data, interrupt_data_base::deleted, GPIO, and sol_network_msg_dispatch().
Referenced by sol_mainloop_impl_iter().
void sol_interrupt_scheduler_set_pid (kernel_pid_t p)
Referenced by sol_mainloop_impl_platform_init().