Soletta: src/lib/common/sol-blob.c File Reference
sol-blob.c File Reference
#include <stdlib.h>
#include <errno.h>
#include "sol-log-internal.h"
#include "sol-macros.h"
#include "sol-util.h"
#include "sol-types.h"
Macros
#define SOL_BLOB_CHECK(blob,...)
#define SOL_LOG_DOMAIN &_sol_blob_log_domain
Functions
int sol_blob_init (void)
SOL_API struct sol_blob * sol_blob_new (const struct sol_blob_type *type, struct sol_blob *parent, const void *mem, size_t size)
SOL_API struct sol_blob * sol_blob_ref (struct sol_blob *blob)
SOL_API void sol_blob_set_parent (struct sol_blob *blob, struct sol_blob *parent)
SOL_API int sol_blob_setup (struct sol_blob *blob, const struct sol_blob_type *type, const void *mem, size_t size)
void sol_blob_shutdown (void)
SOL_API void sol_blob_unref (struct sol_blob *blob)
SOL_LOG_INTERNAL_DECLARE_STATIC (_sol_blob_log_domain,"blob")
Variables
SOL_API const struct
sol_blob_type * SOL_BLOB_TYPE_DEFAULT = &_SOL_BLOB_TYPE_DEFAULT
SOL_API const struct
sol_blob_type * SOL_BLOB_TYPE_NOFREE = &_SOL_BLOB_TYPE_NOFREE
Macro Definition Documentation
#define SOL_BLOB_CHECK (blob, ...)
Value:
do {                                                \
        if (!(blob)) {                                  \
            SOL_WRN("" # blob " == NULL");               \
            return __VA_ARGS__;                         \
        }                                               \
        if (!(blob)->type) {                            \
            SOL_WRN("" # blob "(%p)->type == NULL",      \
                (blob));                             \
            return __VA_ARGS__;                         \
        }                                               \
        if (!(blob)->type->api_version) {               \
            SOL_WRN("" # blob                            \
                "(%p)->type->api_version(%hu) != "   \
                "SOL_BLOB_TYPE_API_VERSION(%hu)",     \
                (blob), (blob)->type->api_version,   \
                SOL_BLOB_TYPE_API_VERSION);           \
            return __VA_ARGS__;                         \
        }                                               \
        if ((blob)->refcnt == 0) {                      \
            SOL_WRN("" # blob "(%p)->refcnt == 0",       \
                (blob));                             \
            return __VA_ARGS__;                         \
        }                                               \
    } while (0)
Referenced by sol_blob_ref(), sol_blob_set_parent(), and sol_blob_unref().
#define SOL_LOG_DOMAIN &_sol_blob_log_domain
Referenced by sol_blob_init().
Function Documentation
int sol_blob_init (void)
References SOL_LOG_DOMAIN, and sol_log_domain_init_level().
Referenced by sol_init().
void sol_blob_shutdown (void)
Referenced by sol_init(), and sol_shutdown().
SOL_LOG_INTERNAL_DECLARE_STATIC (_sol_blob_log_domain , "blob")