Soletta: src/lib/comms/sol-oic-cbor.c File Reference
sol-oic-cbor.c File Reference
#include "sol-log.h"
#include "sol-oic-cbor.h"
#include "sol-oic-common.h"
Functions
CborError sol_oic_decode_cbor_repr (struct sol_coap_packet *pkt, struct sol_vector *reprs)
CborError sol_oic_decode_cbor_repr_map (CborValue *map, struct sol_vector *reprs)
CborError sol_oic_encode_cbor_repr (struct sol_coap_packet *pkt, const char *href, const struct sol_vector *repr_vec)
bool sol_oic_pkt_has_cbor_content (const struct sol_coap_packet *pkt)
Function Documentation
CborError sol_oic_decode_cbor_repr (struct sol_coap_packet * pkt, struct sol_vector * reprs)
References sol_coap_packet_get_payload(), sol_oic_decode_cbor_repr_map(), SOL_OIC_KEY_REPRESENTATION, and SOL_OIC_PAYLOAD_REPRESENTATION.
CborError sol_oic_decode_cbor_repr_map (CborValue * map, struct sol_vector * reprs)
References sol_str_slice::data, sol_oic_repr_field::key, sol_str_slice::len, SOL_ERR, SOL_OIC_REPR_TYPE_BOOLEAN, SOL_OIC_REPR_TYPE_BYTE_STRING, SOL_OIC_REPR_TYPE_DOUBLE, SOL_OIC_REPR_TYPE_FLOAT, SOL_OIC_REPR_TYPE_HALF_FLOAT, SOL_OIC_REPR_TYPE_INT, SOL_OIC_REPR_TYPE_TEXT_STRING, sol_vector_append(), sol_oic_repr_field::type, sol_oic_repr_field::v_boolean, sol_oic_repr_field::v_double, sol_oic_repr_field::v_float, sol_oic_repr_field::v_int, sol_oic_repr_field::v_slice, and sol_oic_repr_field::v_voidptr.
Referenced by sol_oic_decode_cbor_repr().
CborError sol_oic_encode_cbor_repr (struct sol_coap_packet * pkt, const char * href, const struct sol_vector * repr_vec)
References sol_str_slice::data, sol_oic_repr_field::key, sol_str_slice::len, sol_coap_packet_get_payload(), sol_coap_packet_set_payload_used(), SOL_OIC_KEY_HREF, SOL_OIC_KEY_REPRESENTATION, SOL_OIC_PAYLOAD_REPRESENTATION, SOL_OIC_REPR_TYPE_BOOLEAN, SOL_OIC_REPR_TYPE_BYTE_STRING, SOL_OIC_REPR_TYPE_DOUBLE, SOL_OIC_REPR_TYPE_FLOAT, SOL_OIC_REPR_TYPE_HALF_FLOAT, SOL_OIC_REPR_TYPE_INT, SOL_OIC_REPR_TYPE_SIMPLE, SOL_OIC_REPR_TYPE_TEXT_STRING, SOL_OIC_REPR_TYPE_UINT, SOL_VECTOR_FOREACH_IDX, SOL_WRN, sol_oic_repr_field::type, sol_oic_repr_field::v_boolean, sol_oic_repr_field::v_double, sol_oic_repr_field::v_float, sol_oic_repr_field::v_int, sol_oic_repr_field::v_simple, sol_oic_repr_field::v_slice, sol_oic_repr_field::v_uint, and sol_oic_repr_field::v_voidptr.
Referenced by sol_oic_notify_observers().
bool sol_oic_pkt_has_cbor_content (const struct sol_coap_packet * pkt)
References SOL_COAP_CONTENTTYPE_APPLICATION_CBOR, sol_coap_find_first_option(), and SOL_COAP_OPTION_CONTENT_FORMAT.