Soletta: src/shared/sol-file-reader.c File Reference
sol-file-reader.c File Reference
#include <errno.h>
#include <fcntl.h>
#include <stdlib.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include "sol-log.h"
#include "sol-buffer.h"
#include "sol-util.h"
#include "sol-file-reader.h"
Data Structures
struct sol_blob_file_reader
struct sol_file_reader
Functions
void sol_file_reader_close (struct sol_file_reader *fr)
struct sol_str_slice sol_file_reader_get_all (const struct sol_file_reader *fr)
const struct stat * sol_file_reader_get_stat (const struct sol_file_reader *fr)
struct sol_file_reader * sol_file_reader_open (const char *filename)
SOL_API struct sol_blob * sol_file_reader_to_blob (struct sol_file_reader *fr)
Function Documentation
void sol_file_reader_close (struct sol_file_reader * fr)
References sol_file_reader::contents, sol_file_reader::mmapped, and sol_file_reader::st.
Referenced by main(), sol_board_detect(), and sol_file_reader_to_blob().
struct sol_str_slice sol_file_reader_get_all (const struct sol_file_reader * fr)
References sol_str_slice::len.
Referenced by sol_file_reader_to_blob().
const struct stat* sol_file_reader_get_stat (const struct sol_file_reader * fr)
References sol_file_reader::st.
struct sol_file_reader* sol_file_reader_open (const char * filename)
References sol_file_reader::contents, sol_file_reader::mmapped, sol_buffer_steal(), sol_util_load_file_raw(), and sol_file_reader::st.
Referenced by main().
SOL_API struct sol_blob* sol_file_reader_to_blob (struct sol_file_reader * fr)
convert an open file reader to a blob.
This will convert a valid and opened file reader to a blob, thus no further explicit calls to sol_file_reader_close() should be done as the blob will automatically close once its last reference is gone.
Parameters
fr valid opened file reader.
Returns
NULL on error (and fr is closed) or new blob instance that should be sol_blob_unref() once it's not needed.
References sol_blob_file_reader::base, sol_str_slice::data, sol_blob_file_reader::fr, sol_str_slice::len, sol_blob_setup(), sol_file_reader_close(), sol_file_reader_get_all(), and SOL_NULL_CHECK_GOTO.