Soletta: src/lib/common/sol-worker-thread-impl-glib.c File Reference
sol-worker-thread-impl-glib.c File Reference
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <glib.h>
#include "sol-mainloop.h"
#include "sol-worker-thread-impl.h"
Data Structures
struct sol_worker_thread_glib
Functions
void sol_worker_thread_impl_cancel (void *handle)
bool sol_worker_thread_impl_cancel_check (const void *handle)
void sol_worker_thread_impl_feedback (void *handle)
void * sol_worker_thread_impl_new (const struct sol_worker_thread_spec *spec)
Function Documentation
void sol_worker_thread_impl_cancel (void * handle)
Referenced by sol_worker_thread_cancel().
bool sol_worker_thread_impl_cancel_check (const void * handle)
Referenced by sol_worker_thread_cancel_check(), sol_worker_thread_impl_cancel(), and sol_worker_thread_impl_feedback().
void sol_worker_thread_impl_feedback (void * handle)
Referenced by sol_worker_thread_feedback().
void* sol_worker_thread_impl_new (const struct sol_worker_thread_spec * spec)
Referenced by sol_worker_thread_new().