Soletta: src/lib/flow/sol-flow-builder.c File Reference
sol-flow-builder.c File Reference
#include <ctype.h>
#include <stdlib.h>
#include <string.h>
#include "sol-arena.h"
#include "sol-buffer.h"
#include "sol-flow-builder.h"
#include "sol-flow-internal.h"
#include "sol-flow-resolver.h"
#include "sol-flow-static.h"
#include "sol-str-table.h"
Data Structures
struct builder_type_data
struct node_extra
struct sol_flow_builder
struct sol_flow_builder_node_exported_option
struct sol_flow_builder_options
Macros
#define SOL_FLOW_BUILDER_OPTIONS_API_VERSION 1
Functions
SOL_API int sol_flow_builder_add_node (struct sol_flow_builder *builder, const char *name, const struct sol_flow_node_type *type, const struct sol_flow_node_options *option)
SOL_API int sol_flow_builder_add_node_by_type (struct sol_flow_builder *builder, const char *name, const char *type_name, const char *const *options_strv)
int sol_flow_builder_add_node_taking_options (struct sol_flow_builder *builder, const char *name, const struct sol_flow_node_type *type, const struct sol_flow_node_options *options)
SOL_API int sol_flow_builder_connect (struct sol_flow_builder *builder, const char *src_name, const char *src_port_name, int src_port_idx, const char *dst_name, const char *dst_port_name, int dst_port_idx)
SOL_API int sol_flow_builder_connect_by_index (struct sol_flow_builder *builder, const char *src_name, uint16_t src_port_index, const char *dst_name, uint16_t dst_port_index)
SOL_API int sol_flow_builder_del (struct sol_flow_builder *builder)
SOL_API int sol_flow_builder_export_in_port (struct sol_flow_builder *builder, const char *node_name, const char *port_name, int port_idx, const char *exported_name)
SOL_API int sol_flow_builder_export_option (struct sol_flow_builder *builder, const char *node_name, const char *option_name, const char *exported_name)
SOL_API int sol_flow_builder_export_out_port (struct sol_flow_builder *builder, const char *node_name, const char *port_name, int port_idx, const char *exported_name)
SOL_API struct sol_flow_node_type * sol_flow_builder_get_node_type (struct sol_flow_builder *builder)
SOL_API struct sol_flow_builder * sol_flow_builder_new (void)
SOL_API void sol_flow_builder_set_resolver (struct sol_flow_builder *builder, const struct sol_flow_resolver *resolver)
SOL_API int sol_flow_builder_set_type_description (struct sol_flow_builder *builder, const char *name, const char *category, const char *description, const char *author, const char *url, const char *license, const char *version)
Macro Definition Documentation
#define SOL_FLOW_BUILDER_OPTIONS_API_VERSION 1
Function Documentation
SOL_API int sol_flow_builder_add_node (struct sol_flow_builder * builder, const char * name, const struct sol_flow_node_type * type, const struct sol_flow_node_options * option)
References node_extra::exported_options, sol_vector::len, sol_flow_static_node_spec::name, sol_flow_builder::node_extras, sol_flow_builder::node_type, sol_flow_builder::nodes, sol_flow_static_node_spec::opts, node_extra::owns_opts, sol_arena_strdup(), SOL_DBG, SOL_FLOW_NODE_TYPE_API_CHECK, SOL_FLOW_NODE_TYPE_API_VERSION, SOL_NULL_CHECK, sol_vector_append(), sol_vector_del(), SOL_VECTOR_FOREACH_IDX, sol_vector_init(), SOL_WRN, and sol_flow_static_node_spec::type.
Referenced by runner_attach_simulation(), and sol_flow_builder_add_node_taking_options().
SOL_API int sol_flow_builder_add_node_by_type (struct sol_flow_builder * builder, const char * name, const char * type_name, const char *const * options_strv)
References sol_flow_node_named_options::count, sol_flow_node_named_options_member::i, sol_flow_node_named_options::members, sol_flow_builder::resolver, sol_flow_builder_add_node_taking_options(), sol_flow_get_builtins_resolver(), sol_flow_node_named_options_fini(), sol_flow_node_named_options_init_from_strv(), SOL_FLOW_NODE_OPTIONS_MEMBER_STRING, sol_flow_node_options_new(), sol_flow_resolve(), SOL_NULL_CHECK, sol_flow_node_named_options_member::string, and sol_flow_node_named_options_member::type.
int sol_flow_builder_add_node_taking_options (struct sol_flow_builder * builder, const char * name, const struct sol_flow_node_type * type, const struct sol_flow_node_options * options)
References sol_vector::len, sol_flow_builder::nodes, sol_flow_builder_add_node(), and sol_flow_node_options_del().
Referenced by sol_flow_builder_add_node_by_type().
SOL_API int sol_flow_builder_connect (struct sol_flow_builder * builder, const char * src_name, const char * src_port_name, int src_port_idx, const char * dst_name, const char * dst_port_name, int dst_port_idx)
References sol_flow_builder::node_type, SOL_DBG, SOL_ERR, SOL_NULL_CHECK, and sol_flow_static_node_spec::type.
SOL_API int sol_flow_builder_connect_by_index (struct sol_flow_builder * builder, const char * src_name, uint16_t src_port_index, const char * dst_name, uint16_t dst_port_index)
References sol_flow_builder::node_type, sol_flow_node_type::ports_in_count, sol_flow_node_type::ports_out_count, SOL_NULL_CHECK, SOL_WRN, and sol_flow_static_node_spec::type.
SOL_API int sol_flow_builder_del (struct sol_flow_builder * builder)
References builder_type_data::arena, sol_flow_builder::conns, builder_type_data::default_opts_buf, sol_flow_builder::exported_in, node_extra::exported_options, sol_flow_builder::exported_out, sol_flow_builder::node_extras, sol_flow_builder::node_type, sol_flow_builder::nodes, sol_flow_builder::options_description, sol_flow_static_node_spec::opts, node_extra::owns_opts, sol_flow_builder::ports_in_desc, sol_flow_builder::ports_out_desc, sol_arena_del(), sol_flow_node_options_del(), SOL_NULL_CHECK, SOL_PTR_VECTOR_FOREACH_IDX, sol_vector_clear(), SOL_VECTOR_FOREACH_IDX, sol_flow_static_node_spec::type, and sol_flow_builder::type_data.
Referenced by runner_attach_simulation(), and runner_del().
SOL_API int sol_flow_builder_export_in_port (struct sol_flow_builder * builder, const char * node_name, const char * port_name, int port_idx, const char * exported_name)
References sol_flow_builder::exported_in, sol_flow_builder::node_type, sol_flow_builder::ports_in_desc, SOL_ERR, SOL_NULL_CHECK, sol_util_strerrora, and sol_flow_static_node_spec::type.
SOL_API int sol_flow_builder_export_option (struct sol_flow_builder * builder, const char * node_name, const char * option_name, const char * exported_name)
References builder_type_data::default_opts_buf, sol_vector::len, sol_flow_builder::node_type, sol_flow_builder::options_description, builder_type_data::options_size, sol_flow_static_node_spec::opts, sol_arena_strdup(), sol_buffer_ensure(), SOL_ERR, SOL_NULL_CHECK, sol_vector_append(), sol_vector_del(), streq, sol_flow_static_node_spec::type, and sol_flow_builder::type_data.
SOL_API int sol_flow_builder_export_out_port (struct sol_flow_builder * builder, const char * node_name, const char * port_name, int port_idx, const char * exported_name)
References sol_flow_builder::exported_out, sol_flow_builder::node_type, sol_flow_builder::ports_out_desc, SOL_ERR, SOL_NULL_CHECK, sol_util_strerrora, and sol_flow_static_node_spec::type.
SOL_API struct sol_flow_node_type* sol_flow_builder_get_node_type (struct sol_flow_builder * builder)
References sol_ptr_vector::base, sol_flow_static_spec::child_opts_set, sol_flow_builder::conns, sol_flow_static_spec::conns, sol_vector::data, sol_buffer::data, sol_flow_node_type::default_options, builder_type_data::default_opts_buf, builder_type_data::desc, sol_flow_static_spec::dispose, sol_flow_builder::exported_in, sol_flow_static_spec::exported_in, sol_flow_builder::exported_out, sol_flow_static_spec::exported_out, sol_vector::len, builder_type_data::node_extras, sol_flow_builder::node_extras, sol_flow_builder::node_type, sol_flow_builder::nodes, sol_flow_static_spec::nodes, sol_flow_builder::options_description, builder_type_data::options_size, sol_flow_node_type::options_size, sol_flow_builder::ports_in_desc, sol_flow_builder::ports_out_desc, SOL_DBG, sol_flow_static_new_type(), SOL_NULL_CHECK, SOL_WRN, builder_type_data::spec, sol_flow_builder::type_data, and sol_flow_node_type::type_data.
Referenced by runner_attach_simulation().
SOL_API struct sol_flow_builder* sol_flow_builder_new (void)
References SOL_INT_CHECK_GOTO, and SOL_NULL_CHECK.
Referenced by runner_attach_simulation().
SOL_API void sol_flow_builder_set_resolver (struct sol_flow_builder * builder, const struct sol_flow_resolver * resolver)
References sol_flow_builder::resolver, sol_flow_get_default_resolver(), and SOL_NULL_CHECK.
SOL_API int sol_flow_builder_set_type_description (struct sol_flow_builder * builder, const char * name, const char * category, const char * description, const char * author, const char * url, const char * license, const char * version)
References builder_type_data::desc, sol_flow_builder::node_type, sol_arena_strdup(), SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, SOL_WRN, and sol_flow_builder::type_data.