Soletta: src/lib/flow/include/sol-flow-parser.h File Reference
sol-flow-parser.h File Reference
These routines are used for Soletta flow language (flow based programming) parsing.
#include <stdbool.h>
#include "sol-flow.h"
#include "sol-flow-resolver.h"
Data Structures
struct sol_flow_parser_client
Macros
#define SOL_FLOW_PARSER_CLIENT_API_VERSION (1UL)
Functions
struct sol_flow_parser * sol_flow_parser_new (const struct sol_flow_parser_client *client, const struct sol_flow_resolver *resolver)
int sol_flow_parser_del (struct sol_flow_parser *parser)
struct sol_flow_node_type * sol_flow_parse_buffer (struct sol_flow_parser *parser, const char *buf, size_t len, const char *filename)
struct sol_flow_node_type * sol_flow_parse_string (struct sol_flow_parser *parser, const char *str, const char *filename)
struct sol_flow_node_type * sol_flow_parse_buffer_metatype (struct sol_flow_parser *parser, const char *metatype, const char *buf, size_t len, const char *filename)
struct sol_flow_node_type * sol_flow_parse_string_metatype (struct sol_flow_parser *parser, const char *metatype, const char *str, const char *filename)
Detailed Description
These routines are used for Soletta flow language (flow based programming) parsing.
Macro Definition Documentation
#define SOL_FLOW_PARSER_CLIENT_API_VERSION (1UL)
Referenced by runner_new_from_file(), and sol_flow_parser_new().
Function Documentation
struct sol_flow_node_type* sol_flow_parse_buffer (struct sol_flow_parser * parser, const char * buf, size_t len, const char * filename)
References sol_str_slice::data, sol_flow_node_type_del(), SOL_INT_CHECK, SOL_NULL_CHECK, sol_ptr_vector_append(), and sol_flow_parser::types.
Referenced by runner_new_from_file(), sol_flow_parse_buffer_metatype(), and sol_flow_parse_string().
struct sol_flow_node_type* sol_flow_parse_buffer_metatype (struct sol_flow_parser * parser, const char * metatype, const char * buf, size_t len, const char * filename)
References metatype_context_internal::base, metatype_context_with_buf::base, metatype_context_with_buf::buf, sol_flow_metatype_context::contents, metatype_context_with_buf::filename, metatype_context_with_buf::len, sol_flow_metatype_context::name, sol_flow_metatype_context::read_file, SOL_ERR, sol_flow_parse_buffer(), SOL_INT_CHECK, SOL_NULL_CHECK, and streq.
Referenced by sol_flow_parse_string_metatype().
struct sol_flow_node_type* sol_flow_parse_string (struct sol_flow_parser * parser, const char * str, const char * filename)
References sol_flow_parse_buffer().
struct sol_flow_node_type* sol_flow_parse_string_metatype (struct sol_flow_parser * parser, const char * metatype, const char * str, const char * filename)
References sol_flow_parse_buffer_metatype(), and SOL_NULL_CHECK.
int sol_flow_parser_del (struct sol_flow_parser * parser)
References sol_flow_node_type_del(), SOL_NULL_CHECK, SOL_PTR_VECTOR_FOREACH_REVERSE_IDX, and sol_flow_parser::types.
Referenced by runner_del().
struct sol_flow_parser* sol_flow_parser_new (const struct sol_flow_parser_client * client, const struct sol_flow_resolver * resolver)
References sol_flow_parser::builtins_resolver, sol_flow_parser::client, sol_flow_parser::resolver, sol_flow_get_builtins_resolver(), sol_flow_get_default_resolver(), SOL_FLOW_PARSER_CLIENT_API_CHECK, SOL_FLOW_PARSER_CLIENT_API_VERSION, and sol_flow_parser::types.
Referenced by runner_new_from_file().