Soletta: src/lib/flow/include/sol-flow-resolver.h File Reference
sol-flow-resolver.h File Reference
These routines are used for Soletta flow language's .conf file entries resolving.
#include <stdio.h>
#include "sol-flow.h"
Data Structures
struct sol_flow_resolver
Macros
#define SOL_FLOW_RESOLVER_API_VERSION (1UL)
Functions
const struct sol_flow_resolver * sol_flow_get_default_resolver (void)
int sol_flow_resolve (const struct sol_flow_resolver *resolver, const char *id, const struct sol_flow_node_type **type, struct sol_flow_node_named_options *named_opts)
const struct sol_flow_resolver * sol_flow_get_builtins_resolver (void)
Detailed Description
These routines are used for Soletta flow language's .conf file entries resolving.
Macro Definition Documentation
#define SOL_FLOW_RESOLVER_API_VERSION (1UL)
Function Documentation
const struct sol_flow_resolver* sol_flow_get_builtins_resolver (void)
Referenced by runner_new_from_type(), sol_flow_builder_add_node_by_type(), and sol_flow_parser_new().
const struct sol_flow_resolver* sol_flow_get_default_resolver (void)
Referenced by sol_flow_builder_set_resolver(), sol_flow_parser_new(), and sol_flow_resolve().
int sol_flow_resolve (const struct sol_flow_resolver * resolver, const char * id, const struct sol_flow_node_type ** type, struct sol_flow_node_named_options * named_opts)
References sol_flow_resolver::data, sol_flow_resolver::name, sol_flow_resolver::resolve, SOL_DBG, sol_flow_get_default_resolver(), and SOL_NULL_CHECK.
Referenced by runner_new_from_type(), and sol_flow_builder_add_node_by_type().