Soletta: src/shared/sol-lib-loader.c File Reference
sol-lib-loader.c File Reference
#include <dlfcn.h>
#include <errno.h>
#include <limits.h>
#include <string.h>
#include <stdio.h>
#include "sol-lib-loader.h"
#include "sol-log.h"
#include "sol-util.h"
#include "sol-vector.h"
Data Structures
struct sol_lib_entry
struct sol_lib_loader
Functions
void * sol_lib_load (struct sol_lib_loader *loader, const char *name)
void sol_lib_loader_del (struct sol_lib_loader *loader)
struct sol_lib_loader * sol_lib_loader_new (const char *dir, const char *symbol_name, bool(*check_func)(const char *path, const char *symbol_name, void *symbol))
struct sol_lib_loader * sol_lib_loader_new_in_rootdir (const char *dir, const char *symbol_name, bool(*check_func)(const char *path, const char *symbol_name, void *symbol))
Function Documentation
void* sol_lib_load (struct sol_lib_loader * loader, const char * name)
References sol_lib_loader::check_func, sol_lib_loader::dir, sol_lib_entry::handle, sol_lib_loader::loaded_cache, sol_lib_entry::name, SOL_DBG, SOL_INF, sol_vector_append(), SOL_VECTOR_FOREACH_IDX, SOL_WRN, streq, sol_lib_entry::symbol, and sol_lib_loader::symbol_name.
Referenced by get_dynamic_metatype().
void sol_lib_loader_del (struct sol_lib_loader * loader)
References sol_lib_loader::dir, sol_lib_entry::handle, sol_lib_loader::loaded_cache, sol_lib_entry::name, sol_vector_clear(), SOL_VECTOR_FOREACH_REVERSE_IDX, and sol_lib_loader::symbol_name.
Referenced by loaded_metatype_cache_shutdown().
struct sol_lib_loader* sol_lib_loader_new (const char * dir, const char * symbol_name, bool(*)(const char *path, const char *symbol_name, void *symbol) check_func)
References sol_lib_loader::check_func, sol_lib_loader::dir, sol_lib_loader::loaded_cache, SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, sol_vector_init(), and sol_lib_loader::symbol_name.
Referenced by sol_lib_loader_new_in_rootdir().
struct sol_lib_loader* sol_lib_loader_new_in_rootdir (const char * dir, const char * symbol_name, bool(*)(const char *path, const char *symbol_name, void *symbol) check_func)
References sol_lib_loader::check_func, SOL_INT_CHECK, sol_lib_loader_new(), and sol_util_get_rootdir().
Referenced by get_dynamic_metatype().