Soletta: src/modules/flow/flower-power/include/sol-flower-power.h File Reference
sol-flower-power.h File Reference
#include <time.h>
#include "sol-flow.h"
#include "sol-flow-packet.h"
#include "sol-types.h"
Data Structures
struct sol_flower_power_data
struct sol_flower_power_sensor_data
Macros
#define SOL_FLOWER_POWER_DATA_INIT_VALUE(value_)
Functions
int sol_flower_power_get_packet (const struct sol_flow_packet *packet, struct sol_flower_power_data *fpd)
struct sol_flow_packet * sol_flower_power_new_packet (const struct sol_flower_power_data *fpd)
int sol_flower_power_send_packet (struct sol_flow_node *src, uint16_t src_port, const struct sol_flower_power_data *fpd)
int sol_flower_power_sensor_get_packet (const struct sol_flow_packet *packet, struct sol_flower_power_sensor_data *fpsd)
int sol_flower_power_sensor_get_packet_components (const struct sol_flow_packet *packet, const char **id, struct timespec *timestamp, struct timespec *battery_end_of_life, struct sol_drange *battery_level)
struct sol_flow_packet * sol_flower_power_sensor_new_packet (const struct sol_flower_power_sensor_data *fpsd)
struct sol_flow_packet * sol_flower_power_sensor_new_packet_components (const char *id, const struct timespec *timestamp, const struct timespec *battery_end_of_life, struct sol_drange *battery_level)
int sol_flower_power_sensor_send_packet (struct sol_flow_node *src, uint16_t src_port, const struct sol_flower_power_sensor_data *fpsd)
int sol_flower_power_sensor_send_packet_components (struct sol_flow_node *src, uint16_t src_port, char *id, struct timespec *timestamp, struct timespec *battery_end_of_life, struct sol_drange *battery_level)
Variables
const struct sol_flow_packet_type * PACKET_TYPE_FLOWER_POWER
const struct sol_flow_packet_type * PACKET_TYPE_FLOWER_POWER_SENSOR
Macro Definition Documentation
#define SOL_FLOWER_POWER_DATA_INIT_VALUE (value_)
Value:
{ \
        .fertilizer = SOL_DRANGE_INIT_VALUE(value_), \
        .fertilizer_max = SOL_DRANGE_INIT_VALUE(value_), \
        .fertilizer_min = SOL_DRANGE_INIT_VALUE(value_), \
        .light = SOL_DRANGE_INIT_VALUE(value_), \
        .light_max = SOL_DRANGE_INIT_VALUE(value_), \
        .light_min = SOL_DRANGE_INIT_VALUE(value_), \
        .temperature = SOL_DRANGE_INIT_VALUE(value_), \
        .temperature_max = SOL_DRANGE_INIT_VALUE(value_), \
        .temperature_min = SOL_DRANGE_INIT_VALUE(value_), \
        .water = SOL_DRANGE_INIT_VALUE(value_), \
        .water_max = SOL_DRANGE_INIT_VALUE(value_), \
        .water_min = SOL_DRANGE_INIT_VALUE(value_), \
        .timestamp = { 0 }, \
        .id = NULL \
    }
Function Documentation
int sol_flower_power_get_packet (const struct sol_flow_packet * packet, struct sol_flower_power_data * fpd)
References sol_flow_packet_get(), sol_flow_packet_get_type(), and SOL_NULL_CHECK.
struct sol_flow_packet* sol_flower_power_new_packet (const struct sol_flower_power_data * fpd)
References sol_flow_packet_new(), and SOL_NULL_CHECK.
Referenced by sol_flower_power_send_packet().
int sol_flower_power_send_packet (struct sol_flow_node * src, uint16_t src_port, const struct sol_flower_power_data * fpd)
References sol_flow_send_packet(), sol_flower_power_new_packet(), and SOL_NULL_CHECK.
int sol_flower_power_sensor_get_packet (const struct sol_flow_packet * packet, struct sol_flower_power_sensor_data * fpsd)
References sol_flow_packet_get(), sol_flow_packet_get_type(), and SOL_NULL_CHECK.
int sol_flower_power_sensor_get_packet_components (const struct sol_flow_packet * packet, const char ** id, struct timespec * timestamp, struct timespec * battery_end_of_life, struct sol_drange * battery_level)
References sol_flower_power_sensor_data::battery_end_of_life, sol_flower_power_sensor_data::battery_level, sol_flower_power_sensor_data::id, sol_flow_packet_get(), sol_flow_packet_get_type(), SOL_INT_CHECK, SOL_NULL_CHECK, and sol_flower_power_sensor_data::timestamp.
struct sol_flow_packet* sol_flower_power_sensor_new_packet (const struct sol_flower_power_sensor_data * fpsd)
References sol_flow_packet_new(), and SOL_NULL_CHECK.
Referenced by sol_flower_power_sensor_send_packet().
struct sol_flow_packet* sol_flower_power_sensor_new_packet_components (const char * id, const struct timespec * timestamp, const struct timespec * battery_end_of_life, struct sol_drange * battery_level)
References sol_flower_power_sensor_data::battery_end_of_life, sol_flower_power_sensor_data::battery_level, sol_flower_power_sensor_data::id, sol_flow_packet_new(), SOL_NULL_CHECK, and sol_flower_power_sensor_data::timestamp.
Referenced by sol_flower_power_sensor_send_packet_components().
int sol_flower_power_sensor_send_packet (struct sol_flow_node * src, uint16_t src_port, const struct sol_flower_power_sensor_data * fpsd)
References sol_flow_send_packet(), sol_flower_power_sensor_new_packet(), and SOL_NULL_CHECK.
int sol_flower_power_sensor_send_packet_components (struct sol_flow_node * src, uint16_t src_port, char * id, struct timespec * timestamp, struct timespec * battery_end_of_life, struct sol_drange * battery_level)
References sol_flow_send_packet(), sol_flower_power_sensor_new_packet_components(), and SOL_NULL_CHECK.
Variable Documentation
const struct sol_flow_packet_type* PACKET_TYPE_FLOWER_POWER
const struct sol_flow_packet_type* PACKET_TYPE_FLOWER_POWER_SENSOR