Soletta: src/lib/flow/include/sol-flow-packet.h File Reference
sol-flow-packet.h File Reference
These routines are used for Soletta flow packets manipulation.
#include <stdbool.h>
#include <stddef.h>
#include <time.h>
#include "sol-str-slice.h"
#include "sol-types.h"
Data Structures
struct sol_flow_packet_type
Macros
#define SOL_FLOW_PACKET_TYPE_API_VERSION (1)
const struct sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_EMPTY
const struct sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_BOOLEAN
const struct sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_BYTE
const struct sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_IRANGE
const struct sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_STRING
const struct sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_BLOB
const struct sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_JSON_OBJECT
const struct sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_JSON_ARRAY
const struct sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_DRANGE
const struct sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_ANY
const struct sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_ERROR
const struct sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_RGB
const struct sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_DIRECTION_VECTOR
const struct sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_LOCATION
const struct sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_TIMESTAMP
const struct sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_HTTP_RESPONSE
struct sol_flow_packet * sol_flow_packet_new (const struct sol_flow_packet_type *type, const void *value)
void sol_flow_packet_del (struct sol_flow_packet *packet)
const struct sol_flow_packet_type * sol_flow_packet_get_type (const struct sol_flow_packet *packet)
int sol_flow_packet_get (const struct sol_flow_packet *packet, void *output)
struct sol_flow_packet * sol_flow_packet_new_empty (void)
struct sol_flow_packet * sol_flow_packet_new_boolean (bool boolean)
int sol_flow_packet_get_boolean (const struct sol_flow_packet *packet, bool *boolean)
struct sol_flow_packet * sol_flow_packet_new_byte (unsigned char byte)
int sol_flow_packet_get_byte (const struct sol_flow_packet *packet, unsigned char *byte)
struct sol_flow_packet * sol_flow_packet_new_irange (const struct sol_irange *irange)
struct sol_flow_packet * sol_flow_packet_new_irange_value (int32_t value)
int sol_flow_packet_get_irange (const struct sol_flow_packet *packet, struct sol_irange *irange)
int sol_flow_packet_get_irange_value (const struct sol_flow_packet *packet, int32_t *value)
struct sol_flow_packet * sol_flow_packet_new_string (const char *value)
struct sol_flow_packet * sol_flow_packet_new_string_slice (struct sol_str_slice slice)
int sol_flow_packet_get_string (const struct sol_flow_packet *packet, const char **value)
struct sol_flow_packet * sol_flow_packet_new_string_take (char *value)
struct sol_flow_packet * sol_flow_packet_new_blob (const struct sol_blob *value)
int sol_flow_packet_get_blob (const struct sol_flow_packet *packet, struct sol_blob **value)
struct sol_flow_packet * sol_flow_packet_new_json_object (const struct sol_blob *value)
int sol_flow_packet_get_json_object (const struct sol_flow_packet *packet, struct sol_blob **value)
struct sol_flow_packet * sol_flow_packet_new_json_array (const struct sol_blob *value)
int sol_flow_packet_get_json_array (const struct sol_flow_packet *packet, struct sol_blob **value)
struct sol_flow_packet * sol_flow_packet_new_drange (const struct sol_drange *drange)
struct sol_flow_packet * sol_flow_packet_new_drange_value (double value)
int sol_flow_packet_get_drange (const struct sol_flow_packet *packet, struct sol_drange *drange)
int sol_flow_packet_get_drange_value (const struct sol_flow_packet *packet, double *value)
struct sol_flow_packet * sol_flow_packet_new_error (int code, const char *msg)
int sol_flow_packet_get_error (const struct sol_flow_packet *packet, int *code, const char **msg)
struct sol_flow_packet * sol_flow_packet_new_rgb (const struct sol_rgb *rgb)
struct sol_flow_packet * sol_flow_packet_new_rgb_components (uint32_t red, uint32_t green, uint32_t blue)
int sol_flow_packet_get_rgb (const struct sol_flow_packet *packet, struct sol_rgb *rgb)
int sol_flow_packet_get_rgb_components (const struct sol_flow_packet *packet, uint32_t *red, uint32_t *green, uint32_t *blue)
struct sol_flow_packet * sol_flow_packet_new_direction_vector (const struct sol_direction_vector *direction_vector)
struct sol_flow_packet * sol_flow_packet_new_direction_vector_components (double x, double y, double z)
int sol_flow_packet_get_direction_vector (const struct sol_flow_packet *packet, struct sol_direction_vector *direction_vector)
int sol_flow_packet_get_direction_vector_components (const struct sol_flow_packet *packet, double *x, double *y, double *z)
struct sol_flow_packet * sol_flow_packet_new_location (const struct sol_location *location)
int sol_flow_packet_get_location (const struct sol_flow_packet *packet, struct sol_location *location)
struct sol_flow_packet * sol_flow_packet_new_timestamp (const struct timespec *timestamp)
int sol_flow_packet_get_timestamp (const struct sol_flow_packet *packet, struct timespec *timestamp)
const struct sol_flow_packet_type * sol_flow_packet_type_composed_new (const struct sol_flow_packet_type **types)
bool sol_flow_packet_is_composed_type (const struct sol_flow_packet_type *type)
int sol_flow_packet_get_composed_members_len (const struct sol_flow_packet_type *type, uint16_t *len)
int sol_flow_packet_get_composed_members (const struct sol_flow_packet *packet, struct sol_flow_packet ***children, uint16_t *len)
struct sol_flow_packet * sol_flow_packet_dup (const struct sol_flow_packet *packet)
struct sol_flow_packet * sol_flow_packet_new_http_response (int response_code, const char *url, const char *content_type, const struct sol_blob *content, const struct sol_vector *cookies, const struct sol_vector *headers)
int sol_flow_packet_get_http_response (const struct sol_flow_packet *packet, int *response_code, const char **url, const char **content_type, const struct sol_blob **content, struct sol_vector *cookies, struct sol_vector *headers)
Detailed Description
These routines are used for Soletta flow packets manipulation.
Macro Definition Documentation
#define SOL_FLOW_PACKET_TYPE_API_VERSION (1)
Referenced by sol_flow_packet_new(), and sol_flow_packet_type_composed_new().
Function Documentation
void sol_flow_packet_del (struct sol_flow_packet * packet)
References sol_flow_packet_type::dispose, sol_flow_packet_type::get_constant, SOL_NULL_CHECK, and sol_flow_packet::type.
Referenced by sol_flow_packet_new(), sol_flow_packet_new_string_take(), and sol_flow_send_packet().
struct sol_flow_packet* sol_flow_packet_dup (const struct sol_flow_packet * packet)
References sol_flow_packet::data, sol_flow_packet_type::data_size, sol_flow_packet_get(), sol_flow_packet_get_type(), sol_flow_packet_new(), SOL_INT_CHECK_GOTO, and SOL_NULL_CHECK.
int sol_flow_packet_get (const struct sol_flow_packet * packet, void * output)
References sol_flow_packet_type::get, SOL_NULL_CHECK, and sol_flow_packet::type.
Referenced by sol_flow_packet_dup(), sol_flow_packet_get_blob(), sol_flow_packet_get_boolean(), sol_flow_packet_get_byte(), sol_flow_packet_get_composed_members(), sol_flow_packet_get_direction_vector(), sol_flow_packet_get_direction_vector_components(), sol_flow_packet_get_drange(), sol_flow_packet_get_drange_value(), sol_flow_packet_get_error(), sol_flow_packet_get_http_response(), sol_flow_packet_get_irange(), sol_flow_packet_get_irange_value(), sol_flow_packet_get_json_array(), sol_flow_packet_get_json_object(), sol_flow_packet_get_location(), sol_flow_packet_get_rgb(), sol_flow_packet_get_rgb_components(), sol_flow_packet_get_string(), sol_flow_packet_get_timestamp(), sol_flower_power_get_packet(), sol_flower_power_sensor_get_packet(), and sol_flower_power_sensor_get_packet_components().
int sol_flow_packet_get_blob (const struct sol_flow_packet * packet, struct sol_blob ** value)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
Referenced by blob_validator_process(), process_subprocess_in_process(), string_b16encode_blob(), and string_b64encode_blob().
int sol_flow_packet_get_boolean (const struct sol_flow_packet * packet, bool * boolean)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
Referenced by gtk_label_in_process(), gtk_led_in_process(), gtk_pwm_viewer_enable_process(), sequence_process(), and test_result_process().
int sol_flow_packet_get_byte (const struct sol_flow_packet * packet, unsigned char * byte)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
Referenced by byte_validator_process(), gtk_label_in_process(), and gtk_led_7seg_segments_process().
int sol_flow_packet_get_composed_members (const struct sol_flow_packet * packet, struct sol_flow_packet *** children, uint16_t * len)
References sol_flow_packet_type::name, sol_flow_packet_get(), sol_flow_packet_is_composed_type(), SOL_NULL_CHECK, SOL_WRN, and sol_flow_packet::type.
int sol_flow_packet_get_composed_members_len (const struct sol_flow_packet_type * type, uint16_t * len)
References sol_flow_packet_type::name, SOL_ERR, sol_flow_packet_is_composed_type(), and SOL_NULL_CHECK.
int sol_flow_packet_get_direction_vector (const struct sol_flow_packet * packet, struct sol_direction_vector * direction_vector)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
int sol_flow_packet_get_direction_vector_components (const struct sol_flow_packet * packet, double * x, double * y, double * z)
References SOL_FLOW_PACKET_CHECK, sol_flow_packet_get(), sol_direction_vector::x, sol_direction_vector::y, and sol_direction_vector::z.
int sol_flow_packet_get_drange (const struct sol_flow_packet * packet, struct sol_drange * drange)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
Referenced by float_validator_process().
int sol_flow_packet_get_drange_value (const struct sol_flow_packet * packet, double * value)
References SOL_FLOW_PACKET_CHECK, sol_flow_packet_get(), SOL_NULL_CHECK, and sol_drange::val.
int sol_flow_packet_get_error (const struct sol_flow_packet * packet, int * code, const char ** msg)
References error_data::code, error_data::msg, SOL_FLOW_PACKET_CHECK, sol_flow_packet_get(), and SOL_INT_CHECK.
int sol_flow_packet_get_http_response (const struct sol_flow_packet * packet, int * response_code, const char ** url, const char ** content_type, const struct sol_blob ** content, struct sol_vector * cookies, struct sol_vector * headers)
References http_response::code, http_response::content, http_response::content_type, http_response::cookies, http_response::headers, SOL_FLOW_PACKET_CHECK, sol_flow_packet_get(), SOL_FLOW_PACKET_TYPE_HTTP_RESPONSE, SOL_INT_CHECK, and http_response::url.
int sol_flow_packet_get_irange (const struct sol_flow_packet * packet, struct sol_irange * irange)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
Referenced by int_validator_process().
int sol_flow_packet_get_irange_value (const struct sol_flow_packet * packet, int32_t * value)
References SOL_FLOW_PACKET_CHECK, sol_flow_packet_get(), SOL_NULL_CHECK, and sol_irange::val.
Referenced by gtk_label_in_process(), gtk_led_7seg_value_process(), gtk_led_in_process(), gtk_pwm_viewer_duty_cycle_process(), gtk_pwm_viewer_period_process(), process_subprocess_signal_process(), set_string_regexp_index(), and set_string_regexp_max_match().
int sol_flow_packet_get_json_array (const struct sol_flow_packet * packet, struct sol_blob ** value)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
int sol_flow_packet_get_json_object (const struct sol_flow_packet * packet, struct sol_blob ** value)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
int sol_flow_packet_get_location (const struct sol_flow_packet * packet, struct sol_location * location)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
int sol_flow_packet_get_rgb (const struct sol_flow_packet * packet, struct sol_rgb * rgb)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
Referenced by gtk_led_in_process().
int sol_flow_packet_get_rgb_components (const struct sol_flow_packet * packet, uint32_t * red, uint32_t * green, uint32_t * blue)
References sol_rgb::blue, sol_rgb::green, sol_rgb::red, SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
int sol_flow_packet_get_string (const struct sol_flow_packet * packet, const char ** value)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
Referenced by gtk_label_in_process(), set_string_regexp_pattern(), string_b16decode(), string_b16encode_string(), string_b64decode(), string_b64encode_string(), string_is_empty(), string_regexp_replace(), string_regexp_search(), and string_validator_process().
int sol_flow_packet_get_timestamp (const struct sol_flow_packet * packet, struct timespec * timestamp)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
const struct sol_flow_packet_type* sol_flow_packet_get_type (const struct sol_flow_packet * packet)
References SOL_NULL_CHECK, and sol_flow_packet::type.
Referenced by gtk_label_in_process(), gtk_led_in_process(), gtk_pwm_viewer_duty_cycle_process(), gtk_pwm_viewer_enable_process(), gtk_pwm_viewer_period_process(), sol_flow_packet_dup(), sol_flower_power_get_packet(), sol_flower_power_sensor_get_packet(), and sol_flower_power_sensor_get_packet_components().
bool sol_flow_packet_is_composed_type (const struct sol_flow_packet_type * type)
References sol_flow_packet_type::init, and SOL_NULL_CHECK.
Referenced by sol_flow_packet_get_composed_members(), and sol_flow_packet_get_composed_members_len().
struct sol_flow_packet* sol_flow_packet_new (const struct sol_flow_packet_type * type, const void * value)
References sol_flow_packet_type::api_version, sol_flow_packet_type::get_constant, sol_flow_packet_type::name, sol_flow_packet_del(), SOL_FLOW_PACKET_TYPE_ANY, SOL_FLOW_PACKET_TYPE_API_VERSION, SOL_NULL_CHECK, SOL_WRN, and unlikely.
Referenced by sol_flow_packet_dup(), sol_flow_packet_new_blob(), sol_flow_packet_new_boolean(), sol_flow_packet_new_byte(), sol_flow_packet_new_direction_vector(), sol_flow_packet_new_direction_vector_components(), sol_flow_packet_new_drange(), sol_flow_packet_new_drange_value(), sol_flow_packet_new_empty(), sol_flow_packet_new_error(), sol_flow_packet_new_http_response(), sol_flow_packet_new_irange(), sol_flow_packet_new_irange_value(), sol_flow_packet_new_json_array(), sol_flow_packet_new_json_object(), sol_flow_packet_new_location(), sol_flow_packet_new_rgb(), sol_flow_packet_new_rgb_components(), sol_flow_packet_new_string(), sol_flow_packet_new_timestamp(), sol_flow_send_composed_packet(), sol_flower_power_new_packet(), sol_flower_power_sensor_new_packet(), and sol_flower_power_sensor_new_packet_components().
struct sol_flow_packet* sol_flow_packet_new_blob (const struct sol_blob * value)
References sol_flow_packet_new(), and SOL_NULL_CHECK.
struct sol_flow_packet* sol_flow_packet_new_boolean (bool boolean)
References sol_flow_packet_new().
struct sol_flow_packet* sol_flow_packet_new_byte (unsigned char byte)
References sol_flow_packet_new().
struct sol_flow_packet* sol_flow_packet_new_direction_vector (const struct sol_direction_vector * direction_vector)
References sol_flow_packet_new().
struct sol_flow_packet* sol_flow_packet_new_direction_vector_components (double x, double y, double z)
References sol_flow_packet_new(), sol_direction_vector::x, sol_direction_vector::y, and sol_direction_vector::z.
Referenced by sol_flow_send_direction_vector_components_packet().
struct sol_flow_packet* sol_flow_packet_new_drange (const struct sol_drange * drange)
References sol_flow_packet_new().
struct sol_flow_packet* sol_flow_packet_new_drange_value (double value)
References SOL_DRANGE_INIT_VALUE, and sol_flow_packet_new().
struct sol_flow_packet* sol_flow_packet_new_empty (void)
References sol_flow_packet_new().
Referenced by sol_flow_send_empty_packet().
struct sol_flow_packet* sol_flow_packet_new_error (int code, const char * msg)
References error_data::code, error_data::msg, and sol_flow_packet_new().
Referenced by sol_flow_send_error_packet().
struct sol_flow_packet* sol_flow_packet_new_http_response (int response_code, const char * url, const char * content_type, const struct sol_blob * content, const struct sol_vector * cookies, const struct sol_vector * headers)
References http_response::code, http_response::content, http_response::content_type, http_response::cookies, http_response::headers, sol_flow_packet_new(), SOL_FLOW_PACKET_TYPE_HTTP_RESPONSE, and http_response::url.
Referenced by sol_flow_send_http_response_packet().
struct sol_flow_packet* sol_flow_packet_new_irange (const struct sol_irange * irange)
References sol_flow_packet_new().
struct sol_flow_packet* sol_flow_packet_new_irange_value (int32_t value)
References sol_flow_packet_new(), and SOL_IRANGE_INIT_VALUE.
struct sol_flow_packet* sol_flow_packet_new_json_array (const struct sol_blob * value)
References sol_flow_packet_new(), and SOL_NULL_CHECK.
struct sol_flow_packet* sol_flow_packet_new_json_object (const struct sol_blob * value)
References sol_flow_packet_new(), and SOL_NULL_CHECK.
struct sol_flow_packet* sol_flow_packet_new_location (const struct sol_location * location)
References sol_flow_packet_new().
struct sol_flow_packet* sol_flow_packet_new_rgb (const struct sol_rgb * rgb)
References sol_flow_packet_new().
struct sol_flow_packet* sol_flow_packet_new_rgb_components (uint32_t red, uint32_t green, uint32_t blue)
References sol_rgb::blue, sol_rgb::green, sol_rgb::red, sol_rgb::red_max, and sol_flow_packet_new().
Referenced by sol_flow_send_rgb_components_packet().
struct sol_flow_packet* sol_flow_packet_new_string (const char * value)
References sol_flow_packet_new().
struct sol_flow_packet* sol_flow_packet_new_string_slice (struct sol_str_slice slice)
References sol_str_slice::data, sol_str_slice::len, and sol_flow_packet_new_string_take().
struct sol_flow_packet* sol_flow_packet_new_string_take (char * value)
References sol_flow_packet_del(), and SOL_WRN.
Referenced by sol_flow_packet_new_string_slice(), and sol_flow_send_string_take_packet().
struct sol_flow_packet* sol_flow_packet_new_timestamp (const struct timespec * timestamp)
References sol_flow_packet_new().
const struct sol_flow_packet_type* sol_flow_packet_type_composed_new (const struct sol_flow_packet_type ** types)
References sol_flow_packet_type::api_version, sol_flow_packet_type::data_size, sol_flow_packet_type::dispose, sol_flow_packet_type::init, sol_flow_packet_composed_type::members, sol_flow_packet_composed_type::members_len, sol_flow_packet_type::name, sol_flow_packet_composed_type::self, sol_buffer_append_slice(), sol_buffer_steal(), SOL_FLOW_PACKET_TYPE_API_VERSION, SOL_INT_CHECK_GOTO, SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, sol_ptr_vector_append(), and SOL_PTR_VECTOR_FOREACH_IDX.
Variable Documentation
const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_ANY
Referenced by sol_flow_packet_new().
const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_BLOB
const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_BOOLEAN
Referenced by gtk_label_in_process(), gtk_led_in_process(), and gtk_pwm_viewer_enable_process().
const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_BYTE
Referenced by gtk_label_in_process().
const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_DIRECTION_VECTOR
const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_DRANGE
const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_EMPTY
Referenced by gtk_label_in_process().
const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_ERROR
Referenced by sol_flow_node_type_get_port_out().
const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_HTTP_RESPONSE
Referenced by sol_flow_packet_get_http_response(), and sol_flow_packet_new_http_response().
const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_IRANGE
Referenced by gtk_label_in_process(), gtk_led_in_process(), gtk_pwm_viewer_duty_cycle_process(), and gtk_pwm_viewer_period_process().
const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_JSON_ARRAY
const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_JSON_OBJECT
const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_LOCATION
const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_RGB
Referenced by gtk_led_in_process().
const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_STRING
Referenced by gtk_label_in_process().
const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_TIMESTAMP