Soletta: src/lib/common/sol-mainloop-impl-posix.c File Reference
sol-mainloop-impl-posix.c File Reference
#include <stdbool.h>
#include <stdlib.h>
#include <unistd.h>
#include <poll.h>
#include <signal.h>
#include <sys/wait.h>
#include "sol-mainloop-common.h"
#include "sol-mainloop-impl.h"
#include "sol-vector.h"
Data Structures
struct child_exit_status
struct siginfo_handler
struct sol_child_watch_posix
struct sol_fd_posix
Macros
#define CHILD_WATCH_ACUM child_watch_vector
#define CHILD_WATCH_PROCESS child_watch_vector
#define FD_ACUM fd_vector
#define FD_PROCESS fd_vector
#define MAP(a, b) if (flags & a) events |= b
#define MAP(a, b) if (events & b) flags |= a
#define POLLFDS_COUNT_BLOCKSIZE (32)
#define SIG(num, handler) { .sig = num, .cb = handler }
#define SIGINFO_HANDLER_COUNT ARRAY_SIZE(siginfo_handler)
#define SIGINFO_HANDLER_FOREACH(ptr) for (ptr = siginfo_handler; ptr < siginfo_handler + SIGINFO_HANDLER_COUNT; ptr++) if (ptr->sig)
#define SIGINFO_STORAGE_CAPACITY 64
#define SIGPROCMASK sigprocmask
#define threads_init() do { } while (0)
#define threads_shutdown() do { } while (0)
Functions
int ppoll (struct pollfd *fds, nfds_t nfds, const struct timespec *timeout_ts, const sigset_t *sigmask)
void * sol_mainloop_impl_child_watch_add (uint64_t pid, void(*cb)(void *data, uint64_t pid, int status), const void *data)
bool sol_mainloop_impl_child_watch_del (void *handle)
void * sol_mainloop_impl_fd_add (int fd, unsigned int flags, bool(*cb)(void *data, int fd, unsigned int active_flags), const void *data)
bool sol_mainloop_impl_fd_del (void *handle)
unsigned int sol_mainloop_impl_fd_get_flags (const void *handle)
bool sol_mainloop_impl_fd_set_flags (void *handle, unsigned int flags)
void sol_mainloop_impl_iter (void)
void sol_mainloop_impl_lock (void)
bool sol_mainloop_impl_main_thread_check (void)
void sol_mainloop_impl_main_thread_notify (void)
int sol_mainloop_impl_platform_init (void)
void sol_mainloop_impl_platform_shutdown (void)
void sol_mainloop_impl_unlock (void)
Macro Definition Documentation
#define CHILD_WATCH_ACUM child_watch_vector
#define CHILD_WATCH_PROCESS child_watch_vector
#define FD_ACUM fd_vector
#define FD_PROCESS fd_vector
#define MAP (a, b) if (flags & a) events |= b
#define MAP (a, b) if (events & b) flags |= a
#define POLLFDS_COUNT_BLOCKSIZE (32)
#define SIG (num, handler) { .sig = num, .cb = handler }
#define SIGINFO_HANDLER_COUNT ARRAY_SIZE(siginfo_handler)
#define SIGINFO_HANDLER_FOREACH (ptr) for (ptr = siginfo_handler; ptr < siginfo_handler + SIGINFO_HANDLER_COUNT; ptr++) if (ptr->sig)
Referenced by sol_mainloop_impl_platform_init(), and sol_mainloop_impl_platform_shutdown().
#define SIGINFO_STORAGE_CAPACITY 64
#define SIGPROCMASK sigprocmask
Referenced by sol_mainloop_impl_platform_init(), and sol_mainloop_impl_platform_shutdown().
#define threads_init () do { } while (0)
Referenced by sol_mainloop_impl_platform_init().
#define threads_shutdown () do { } while (0)
Referenced by sol_mainloop_impl_platform_shutdown().
Function Documentation
int ppoll (struct pollfd * fds, nfds_t nfds, const struct timespec * timeout_ts, const sigset_t * sigmask)
References timeout_ms.
void* sol_mainloop_impl_child_watch_add (uint64_t pid, void(*)(void *data, uint64_t pid, int status) cb, const void * data)
References sol_child_watch_posix::cb, sol_child_watch_posix::data, sol_child_watch_posix::pid, sol_child_watch_posix::remove_me, SOL_INT_CHECK_GOTO, sol_mainloop_impl_lock(), sol_mainloop_impl_unlock(), SOL_NULL_CHECK, and sol_ptr_vector_append().
bool sol_mainloop_impl_child_watch_del (void * handle)
References sol_child_watch_posix::remove_me, sol_mainloop_impl_lock(), and sol_mainloop_impl_unlock().
void* sol_mainloop_impl_fd_add (int fd, unsigned int flags, bool(*)(void *data, int fd, unsigned int active_flags) cb, const void * data)
References sol_fd_posix::cb, sol_fd_posix::data, sol_fd_posix::fd, sol_fd_posix::flags, sol_fd_posix::invalid, sol_fd_posix::remove_me, SOL_INT_CHECK_GOTO, sol_mainloop_impl_lock(), sol_mainloop_impl_unlock(), SOL_NULL_CHECK, and sol_ptr_vector_append().
bool sol_mainloop_impl_fd_del (void * handle)
References sol_fd_posix::remove_me, sol_mainloop_impl_lock(), and sol_mainloop_impl_unlock().
unsigned int sol_mainloop_impl_fd_get_flags (const void * handle)
References sol_fd_posix::flags, and SOL_NULL_CHECK.
bool sol_mainloop_impl_fd_set_flags (void * handle, unsigned int flags)
References sol_fd_posix::flags, sol_mainloop_impl_lock(), sol_mainloop_impl_unlock(), and SOL_NULL_CHECK.
void sol_mainloop_impl_iter (void)
References sol_mainloop_common_idler_process(), and sol_mainloop_common_timeout_process().
void sol_mainloop_impl_lock (void)
Referenced by sol_mainloop_impl_child_watch_add(), sol_mainloop_impl_child_watch_del(), sol_mainloop_impl_fd_add(), sol_mainloop_impl_fd_del(), and sol_mainloop_impl_fd_set_flags().
bool sol_mainloop_impl_main_thread_check (void)
void sol_mainloop_impl_main_thread_notify (void)
int sol_mainloop_impl_platform_init (void)
References siginfo_handler::sig, SIGINFO_HANDLER_FOREACH, SIGPROCMASK, and threads_init.
void sol_mainloop_impl_platform_shutdown (void)
References siginfo_handler::sig, SIGINFO_HANDLER_FOREACH, SIGPROCMASK, sol_mainloop_common_source_shutdown(), SOL_PTR_VECTOR_FOREACH_IDX, and threads_shutdown.
void sol_mainloop_impl_unlock (void)
Referenced by sol_mainloop_impl_child_watch_add(), sol_mainloop_impl_child_watch_del(), sol_mainloop_impl_fd_add(), sol_mainloop_impl_fd_del(), and sol_mainloop_impl_fd_set_flags().