Soletta: src/lib/common/sol-mainloop-impl-glib.c File Reference
sol-mainloop-impl-glib.c File Reference
#include <stdbool.h>
#include <glib-unix.h>
#include "sol-mainloop-impl.h"
#include "sol-util.h"
Data Structures
struct child_wrap_data
struct gsourcefunc_wrap_data
struct sol_fd_glib
struct source_wrap_data
Functions
void * sol_mainloop_impl_child_watch_add (uint64_t pid, void(*cb)(void *data, uint64_t pid, int status), const void *data)
bool sol_mainloop_impl_child_watch_del (void *handle)
void * sol_mainloop_impl_fd_add (int fd, unsigned int flags, bool(*cb)(void *data, int fd, unsigned int active_flags), const void *data)
bool sol_mainloop_impl_fd_del (void *handle)
unsigned int sol_mainloop_impl_fd_get_flags (const void *handle)
bool sol_mainloop_impl_fd_set_flags (void *handle, unsigned int flags)
void * sol_mainloop_impl_idle_add (bool(*cb)(void *data), const void *data)
bool sol_mainloop_impl_idle_del (void *handle)
int sol_mainloop_impl_init (void)
void sol_mainloop_impl_quit (void)
void sol_mainloop_impl_run (void)
void sol_mainloop_impl_shutdown (void)
void sol_mainloop_impl_source_del (void *handle)
void * sol_mainloop_impl_source_get_data (const void *handle)
void * sol_mainloop_impl_source_new (const struct sol_mainloop_source_type *type, const void *data)
void * sol_mainloop_impl_timeout_add (unsigned int timeout_ms, bool(*cb)(void *data), const void *data)
bool sol_mainloop_impl_timeout_del (void *handle)
Function Documentation
void* sol_mainloop_impl_child_watch_add (uint64_t pid, void(*)(void *data, uint64_t pid, int status) cb, const void * data)
References child_wrap_data::cb, child_wrap_data::data, and SOL_NULL_CHECK.
bool sol_mainloop_impl_child_watch_del (void * handle)
void* sol_mainloop_impl_fd_add (int fd, unsigned int flags, bool(*)(void *data, int fd, unsigned int active_flags) cb, const void * data)
References sol_fd_glib::cb, sol_fd_glib::data, sol_fd_glib::fd, sol_fd_glib::flags, sol_fd_glib::id, sol_fd_glib::refcnt, and SOL_NULL_CHECK.
bool sol_mainloop_impl_fd_del (void * handle)
References sol_fd_glib::id, and SOL_NULL_CHECK.
unsigned int sol_mainloop_impl_fd_get_flags (const void * handle)
References sol_fd_glib::flags, and SOL_NULL_CHECK.
bool sol_mainloop_impl_fd_set_flags (void * handle, unsigned int flags)
References sol_fd_glib::fd, sol_fd_glib::flags, sol_fd_glib::id, sol_fd_glib::refcnt, SOL_NULL_CHECK, and SOL_WRN.
void* sol_mainloop_impl_idle_add (bool(*)(void *data) cb, const void * data)
References sol_idler_common::cb, gsourcefunc_wrap_data::cb, sol_idler_common::data, gsourcefunc_wrap_data::data, sol_idler_common::idler_ready, sol_idler_common::idler_ready_on_next_iteration, SOL_INT_CHECK_GOTO, sol_mainloop_impl_lock(), sol_mainloop_impl_unlock(), SOL_NULL_CHECK, sol_ptr_vector_append(), and sol_idler_common::status.
bool sol_mainloop_impl_idle_del (void * handle)
References sol_idler_common::idler_deleted, SOL_INT_CHECK, sol_mainloop_impl_lock(), sol_mainloop_impl_unlock(), and sol_idler_common::status.
int sol_mainloop_impl_init (void)
References SOL_CRI, and sol_mainloop_impl_platform_init().
void sol_mainloop_impl_quit (void)
References sol_mainloop_common_loop_set(), and sol_mainloop_impl_main_thread_notify().
void sol_mainloop_impl_run (void)
References SOL_ERR, sol_mainloop_common_loop_check(), sol_mainloop_common_loop_set(), sol_mainloop_impl_iter(), and sol_mainloop_impl_main_thread_check().
void sol_mainloop_impl_shutdown (void)
References sol_mainloop_impl_platform_shutdown(), and SOL_PTR_VECTOR_FOREACH_IDX.
void sol_mainloop_impl_source_del (void * handle)
References source_wrap_data::base, sol_mainloop_source_common::remove_me, SOL_EXP_CHECK, sol_mainloop_impl_lock(), and sol_mainloop_impl_unlock().
void* sol_mainloop_impl_source_get_data (const void * handle)
References sol_mainloop_source_common::data, and source_wrap_data::data.
void* sol_mainloop_impl_source_new (const struct sol_mainloop_source_type * type, const void * data)
References source_wrap_data::base, sol_mainloop_source_common::data, source_wrap_data::data, sol_mainloop_source_common::ready, sol_mainloop_source_common::remove_me, SOL_INT_CHECK_GOTO, sol_mainloop_impl_lock(), sol_mainloop_impl_unlock(), SOL_NULL_CHECK, sol_ptr_vector_append(), sol_mainloop_source_common::type, and source_wrap_data::type.
void* sol_mainloop_impl_timeout_add (unsigned int timeout_ms, bool(*)(void *data) cb, const void * data)
References sol_timeout_common::cb, gsourcefunc_wrap_data::cb, sol_timeout_common::data, gsourcefunc_wrap_data::data, sol_timeout_common::expire, MSEC_PER_SEC, NSEC_PER_MSEC, sol_timeout_common::remove_me, SOL_INT_CHECK_GOTO, sol_mainloop_impl_lock(), sol_mainloop_impl_unlock(), SOL_NULL_CHECK, sol_ptr_vector_insert_sorted(), sol_util_timespec_get_current(), and sol_timeout_common::timeout.
bool sol_mainloop_impl_timeout_del (void * handle)
References sol_timeout_common::remove_me, SOL_EXP_CHECK, sol_mainloop_impl_lock(), and sol_mainloop_impl_unlock().