Soletta: src/lib/flow/sol-flow-packet.c File Reference
sol-flow-packet.c File Reference
#include <errno.h>
#include <string.h>
#include <stdlib.h>
#include <float.h>
#include <time.h>
#include "sol-flow-internal.h"
#include "sol-flow-packet.h"
#include "sol-util.h"
#include "sol-vector.h"
#include "sol-buffer.h"
Data Structures
struct error_data
struct http_response
struct sol_flow_packet
struct sol_flow_packet_composed_type
Macros
#define SOL_FLOW_PACKET_CHECK(packet, _type,...)
Functions
SOL_API void sol_flow_packet_del (struct sol_flow_packet *packet)
SOL_API struct sol_flow_packet * sol_flow_packet_dup (const struct sol_flow_packet *packet)
SOL_API int sol_flow_packet_get (const struct sol_flow_packet *packet, void *output)
SOL_API int sol_flow_packet_get_blob (const struct sol_flow_packet *packet, struct sol_blob **value)
SOL_API int sol_flow_packet_get_boolean (const struct sol_flow_packet *packet, bool *boolean)
SOL_API int sol_flow_packet_get_byte (const struct sol_flow_packet *packet, unsigned char *byte)
SOL_API int sol_flow_packet_get_composed_members (const struct sol_flow_packet *packet, struct sol_flow_packet ***children, uint16_t *len)
SOL_API int sol_flow_packet_get_composed_members_len (const struct sol_flow_packet_type *type, uint16_t *len)
SOL_API int sol_flow_packet_get_direction_vector (const struct sol_flow_packet *packet, struct sol_direction_vector *direction_vector)
SOL_API int sol_flow_packet_get_direction_vector_components (const struct sol_flow_packet *packet, double *x, double *y, double *z)
SOL_API int sol_flow_packet_get_drange (const struct sol_flow_packet *packet, struct sol_drange *drange)
SOL_API int sol_flow_packet_get_drange_value (const struct sol_flow_packet *packet, double *value)
SOL_API int sol_flow_packet_get_error (const struct sol_flow_packet *packet, int *code, const char **msg)
SOL_API int sol_flow_packet_get_http_response (const struct sol_flow_packet *packet, int *response_code, const char **url, const char **content_type, const struct sol_blob **content, struct sol_vector *cookies, struct sol_vector *headers)
SOL_API int sol_flow_packet_get_irange (const struct sol_flow_packet *packet, struct sol_irange *irange)
SOL_API int sol_flow_packet_get_irange_value (const struct sol_flow_packet *packet, int32_t *value)
SOL_API int sol_flow_packet_get_json_array (const struct sol_flow_packet *packet, struct sol_blob **value)
SOL_API int sol_flow_packet_get_json_object (const struct sol_flow_packet *packet, struct sol_blob **value)
SOL_API int sol_flow_packet_get_location (const struct sol_flow_packet *packet, struct sol_location *location)
SOL_API int sol_flow_packet_get_rgb (const struct sol_flow_packet *packet, struct sol_rgb *rgb)
SOL_API int sol_flow_packet_get_rgb_components (const struct sol_flow_packet *packet, uint32_t *red, uint32_t *green, uint32_t *blue)
SOL_API int sol_flow_packet_get_string (const struct sol_flow_packet *packet, const char **value)
SOL_API int sol_flow_packet_get_timestamp (const struct sol_flow_packet *packet, struct timespec *timestamp)
SOL_API const struct
sol_flow_packet_type * sol_flow_packet_get_type (const struct sol_flow_packet *packet)
SOL_API bool sol_flow_packet_is_composed_type (const struct sol_flow_packet_type *type)
SOL_API struct sol_flow_packet * sol_flow_packet_new (const struct sol_flow_packet_type *type, const void *value)
SOL_API struct sol_flow_packet * sol_flow_packet_new_blob (const struct sol_blob *blob)
SOL_API struct sol_flow_packet * sol_flow_packet_new_boolean (bool boolean)
SOL_API struct sol_flow_packet * sol_flow_packet_new_byte (unsigned char byte)
SOL_API struct sol_flow_packet * sol_flow_packet_new_direction_vector (const struct sol_direction_vector *direction_vector)
SOL_API struct sol_flow_packet * sol_flow_packet_new_direction_vector_components (double x, double y, double z)
SOL_API struct sol_flow_packet * sol_flow_packet_new_drange (const struct sol_drange *drange)
SOL_API struct sol_flow_packet * sol_flow_packet_new_drange_value (double value)
SOL_API struct sol_flow_packet * sol_flow_packet_new_empty (void)
SOL_API struct sol_flow_packet * sol_flow_packet_new_error (int code, const char *msg)
SOL_API struct sol_flow_packet * sol_flow_packet_new_http_response (int response_code, const char *url, const char *content_type, const struct sol_blob *content, const struct sol_vector *cookies, const struct sol_vector *headers)
SOL_API struct sol_flow_packet * sol_flow_packet_new_irange (const struct sol_irange *irange)
SOL_API struct sol_flow_packet * sol_flow_packet_new_irange_value (int32_t value)
SOL_API struct sol_flow_packet * sol_flow_packet_new_json_array (const struct sol_blob *json_array)
SOL_API struct sol_flow_packet * sol_flow_packet_new_json_object (const struct sol_blob *json_object)
SOL_API struct sol_flow_packet * sol_flow_packet_new_location (const struct sol_location *location)
SOL_API struct sol_flow_packet * sol_flow_packet_new_rgb (const struct sol_rgb *rgb)
SOL_API struct sol_flow_packet * sol_flow_packet_new_rgb_components (uint32_t red, uint32_t green, uint32_t blue)
SOL_API struct sol_flow_packet * sol_flow_packet_new_string (const char *value)
SOL_API struct sol_flow_packet * sol_flow_packet_new_string_slice (struct sol_str_slice slice)
SOL_API struct sol_flow_packet * sol_flow_packet_new_string_take (char *value)
SOL_API struct sol_flow_packet * sol_flow_packet_new_timestamp (const struct timespec *timestamp)
SOL_API const struct
sol_flow_packet_type * sol_flow_packet_type_composed_new (const struct sol_flow_packet_type **types)
void sol_flow_packet_type_composed_shutdown (void)
Variables
SOL_API const struct
sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_ANY = &_SOL_FLOW_PACKET_TYPE_ANY
SOL_API const struct
sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_BLOB = &_SOL_FLOW_PACKET_TYPE_BLOB
SOL_API const struct
sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_BOOLEAN = &_SOL_FLOW_PACKET_TYPE_BOOLEAN
SOL_API const struct
sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_BYTE = &_SOL_FLOW_PACKET_TYPE_BYTE
SOL_API const struct
sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_DIRECTION_VECTOR = &_SOL_FLOW_PACKET_TYPE_DIRECTION_VECTOR
SOL_API const struct
sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_DRANGE = &_SOL_FLOW_PACKET_TYPE_DRANGE
SOL_API const struct
sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_EMPTY = &_SOL_FLOW_PACKET_TYPE_EMPTY
SOL_API const struct
sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_ERROR = &_SOL_FLOW_PACKET_TYPE_ERROR
SOL_API const struct
sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_HTTP_RESPONSE = &_SOL_FLOW_PACKET_TYPE_HTTP_RESPONSE
SOL_API const struct
sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_IRANGE = &_SOL_FLOW_PACKET_TYPE_IRANGE
SOL_API const struct
sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_JSON_ARRAY = &_SOL_FLOW_PACKET_TYPE_JSON_ARRAY
SOL_API const struct
sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_JSON_OBJECT = &_SOL_FLOW_PACKET_TYPE_JSON_OBJECT
SOL_API const struct
sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_LOCATION = &_SOL_FLOW_PACKET_TYPE_LOCATION
SOL_API const struct
sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_RGB = &_SOL_FLOW_PACKET_TYPE_RGB
SOL_API const struct
sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_STRING = &_SOL_FLOW_PACKET_TYPE_STRING
SOL_API const struct
sol_flow_packet_type * SOL_FLOW_PACKET_TYPE_TIMESTAMP = &_SOL_FLOW_PACKET_TYPE_TIMESTAMP
Macro Definition Documentation
#define SOL_FLOW_PACKET_CHECK (packet, _type, ...)
Value:
do {                                                \
        if (unlikely(!(packet))) {                      \
            SOL_WRN("" # packet "== NULL");              \
            return __VA_ARGS__;                         \
        }                                               \
        if (unlikely((packet)->type != _type)) {        \
            SOL_WRN("" # packet "->type != " # _type);   \
            return __VA_ARGS__;                         \
        }                                               \
    } while (0)
Referenced by sol_flow_packet_get_blob(), sol_flow_packet_get_boolean(), sol_flow_packet_get_byte(), sol_flow_packet_get_direction_vector(), sol_flow_packet_get_direction_vector_components(), sol_flow_packet_get_drange(), sol_flow_packet_get_drange_value(), sol_flow_packet_get_error(), sol_flow_packet_get_http_response(), sol_flow_packet_get_irange(), sol_flow_packet_get_irange_value(), sol_flow_packet_get_json_array(), sol_flow_packet_get_json_object(), sol_flow_packet_get_location(), sol_flow_packet_get_rgb(), sol_flow_packet_get_rgb_components(), sol_flow_packet_get_string(), and sol_flow_packet_get_timestamp().
Function Documentation
SOL_API void sol_flow_packet_del (struct sol_flow_packet * packet)
References sol_flow_packet_type::dispose, sol_flow_packet_type::get_constant, SOL_NULL_CHECK, and sol_flow_packet::type.
Referenced by sol_flow_packet_new(), sol_flow_packet_new_string_take(), and sol_flow_send_packet().
SOL_API struct sol_flow_packet* sol_flow_packet_dup (const struct sol_flow_packet * packet)
References sol_flow_packet::data, sol_flow_packet_type::data_size, sol_flow_packet_get(), sol_flow_packet_get_type(), sol_flow_packet_new(), SOL_INT_CHECK_GOTO, and SOL_NULL_CHECK.
SOL_API int sol_flow_packet_get (const struct sol_flow_packet * packet, void * output)
References sol_flow_packet_type::get, SOL_NULL_CHECK, and sol_flow_packet::type.
Referenced by sol_flow_packet_dup(), sol_flow_packet_get_blob(), sol_flow_packet_get_boolean(), sol_flow_packet_get_byte(), sol_flow_packet_get_composed_members(), sol_flow_packet_get_direction_vector(), sol_flow_packet_get_direction_vector_components(), sol_flow_packet_get_drange(), sol_flow_packet_get_drange_value(), sol_flow_packet_get_error(), sol_flow_packet_get_http_response(), sol_flow_packet_get_irange(), sol_flow_packet_get_irange_value(), sol_flow_packet_get_json_array(), sol_flow_packet_get_json_object(), sol_flow_packet_get_location(), sol_flow_packet_get_rgb(), sol_flow_packet_get_rgb_components(), sol_flow_packet_get_string(), sol_flow_packet_get_timestamp(), sol_flower_power_get_packet(), sol_flower_power_sensor_get_packet(), and sol_flower_power_sensor_get_packet_components().
SOL_API int sol_flow_packet_get_blob (const struct sol_flow_packet * packet, struct sol_blob ** value)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
Referenced by blob_validator_process(), process_subprocess_in_process(), string_b16encode_blob(), and string_b64encode_blob().
SOL_API int sol_flow_packet_get_boolean (const struct sol_flow_packet * packet, bool * boolean)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
Referenced by gtk_label_in_process(), gtk_led_in_process(), gtk_pwm_viewer_enable_process(), sequence_process(), and test_result_process().
SOL_API int sol_flow_packet_get_byte (const struct sol_flow_packet * packet, unsigned char * byte)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
Referenced by byte_validator_process(), gtk_label_in_process(), and gtk_led_7seg_segments_process().
SOL_API int sol_flow_packet_get_composed_members (const struct sol_flow_packet * packet, struct sol_flow_packet *** children, uint16_t * len)
References sol_flow_packet_type::name, sol_flow_packet_get(), sol_flow_packet_is_composed_type(), SOL_NULL_CHECK, SOL_WRN, and sol_flow_packet::type.
SOL_API int sol_flow_packet_get_composed_members_len (const struct sol_flow_packet_type * type, uint16_t * len)
References sol_flow_packet_type::name, SOL_ERR, sol_flow_packet_is_composed_type(), and SOL_NULL_CHECK.
SOL_API int sol_flow_packet_get_direction_vector (const struct sol_flow_packet * packet, struct sol_direction_vector * direction_vector)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
SOL_API int sol_flow_packet_get_direction_vector_components (const struct sol_flow_packet * packet, double * x, double * y, double * z)
References SOL_FLOW_PACKET_CHECK, sol_flow_packet_get(), sol_direction_vector::x, sol_direction_vector::y, and sol_direction_vector::z.
SOL_API int sol_flow_packet_get_drange (const struct sol_flow_packet * packet, struct sol_drange * drange)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
Referenced by float_validator_process().
SOL_API int sol_flow_packet_get_drange_value (const struct sol_flow_packet * packet, double * value)
References SOL_FLOW_PACKET_CHECK, sol_flow_packet_get(), SOL_NULL_CHECK, and sol_drange::val.
SOL_API int sol_flow_packet_get_error (const struct sol_flow_packet * packet, int * code, const char ** msg)
References error_data::code, error_data::msg, SOL_FLOW_PACKET_CHECK, sol_flow_packet_get(), and SOL_INT_CHECK.
SOL_API int sol_flow_packet_get_http_response (const struct sol_flow_packet * packet, int * response_code, const char ** url, const char ** content_type, const struct sol_blob ** content, struct sol_vector * cookies, struct sol_vector * headers)
References http_response::code, http_response::content, http_response::content_type, http_response::cookies, http_response::headers, SOL_FLOW_PACKET_CHECK, sol_flow_packet_get(), SOL_FLOW_PACKET_TYPE_HTTP_RESPONSE, SOL_INT_CHECK, and http_response::url.
SOL_API int sol_flow_packet_get_irange (const struct sol_flow_packet * packet, struct sol_irange * irange)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
Referenced by int_validator_process().
SOL_API int sol_flow_packet_get_irange_value (const struct sol_flow_packet * packet, int32_t * value)
References SOL_FLOW_PACKET_CHECK, sol_flow_packet_get(), SOL_NULL_CHECK, and sol_irange::val.
Referenced by gtk_label_in_process(), gtk_led_7seg_value_process(), gtk_led_in_process(), gtk_pwm_viewer_duty_cycle_process(), gtk_pwm_viewer_period_process(), process_subprocess_signal_process(), set_string_regexp_index(), and set_string_regexp_max_match().
SOL_API int sol_flow_packet_get_json_array (const struct sol_flow_packet * packet, struct sol_blob ** value)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
SOL_API int sol_flow_packet_get_json_object (const struct sol_flow_packet * packet, struct sol_blob ** value)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
SOL_API int sol_flow_packet_get_location (const struct sol_flow_packet * packet, struct sol_location * location)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
SOL_API int sol_flow_packet_get_rgb (const struct sol_flow_packet * packet, struct sol_rgb * rgb)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
Referenced by gtk_led_in_process().
SOL_API int sol_flow_packet_get_rgb_components (const struct sol_flow_packet * packet, uint32_t * red, uint32_t * green, uint32_t * blue)
References sol_rgb::blue, sol_rgb::green, sol_rgb::red, SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
SOL_API int sol_flow_packet_get_string (const struct sol_flow_packet * packet, const char ** value)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
Referenced by gtk_label_in_process(), set_string_regexp_pattern(), string_b16decode(), string_b16encode_string(), string_b64decode(), string_b64encode_string(), string_is_empty(), string_regexp_replace(), string_regexp_search(), and string_validator_process().
SOL_API int sol_flow_packet_get_timestamp (const struct sol_flow_packet * packet, struct timespec * timestamp)
References SOL_FLOW_PACKET_CHECK, and sol_flow_packet_get().
SOL_API const struct sol_flow_packet_type* sol_flow_packet_get_type (const struct sol_flow_packet * packet)
References SOL_NULL_CHECK, and sol_flow_packet::type.
Referenced by gtk_label_in_process(), gtk_led_in_process(), gtk_pwm_viewer_duty_cycle_process(), gtk_pwm_viewer_enable_process(), gtk_pwm_viewer_period_process(), sol_flow_packet_dup(), sol_flower_power_get_packet(), sol_flower_power_sensor_get_packet(), and sol_flower_power_sensor_get_packet_components().
SOL_API bool sol_flow_packet_is_composed_type (const struct sol_flow_packet_type * type)
References sol_flow_packet_type::init, and SOL_NULL_CHECK.
Referenced by sol_flow_packet_get_composed_members(), and sol_flow_packet_get_composed_members_len().
SOL_API struct sol_flow_packet* sol_flow_packet_new (const struct sol_flow_packet_type * type, const void * value)
References sol_flow_packet_type::api_version, sol_flow_packet_type::get_constant, sol_flow_packet_type::name, sol_flow_packet_del(), SOL_FLOW_PACKET_TYPE_ANY, SOL_FLOW_PACKET_TYPE_API_VERSION, SOL_NULL_CHECK, SOL_WRN, and unlikely.
Referenced by sol_flow_packet_dup(), sol_flow_packet_new_blob(), sol_flow_packet_new_boolean(), sol_flow_packet_new_byte(), sol_flow_packet_new_direction_vector(), sol_flow_packet_new_direction_vector_components(), sol_flow_packet_new_drange(), sol_flow_packet_new_drange_value(), sol_flow_packet_new_empty(), sol_flow_packet_new_error(), sol_flow_packet_new_http_response(), sol_flow_packet_new_irange(), sol_flow_packet_new_irange_value(), sol_flow_packet_new_json_array(), sol_flow_packet_new_json_object(), sol_flow_packet_new_location(), sol_flow_packet_new_rgb(), sol_flow_packet_new_rgb_components(), sol_flow_packet_new_string(), sol_flow_packet_new_timestamp(), sol_flow_send_composed_packet(), sol_flower_power_new_packet(), sol_flower_power_sensor_new_packet(), and sol_flower_power_sensor_new_packet_components().
SOL_API struct sol_flow_packet* sol_flow_packet_new_blob (const struct sol_blob * blob)
References sol_flow_packet_new(), and SOL_NULL_CHECK.
SOL_API struct sol_flow_packet* sol_flow_packet_new_boolean (bool boolean)
References sol_flow_packet_new().
SOL_API struct sol_flow_packet* sol_flow_packet_new_byte (unsigned char byte)
References sol_flow_packet_new().
SOL_API struct sol_flow_packet* sol_flow_packet_new_direction_vector (const struct sol_direction_vector * direction_vector)
References sol_flow_packet_new().
SOL_API struct sol_flow_packet* sol_flow_packet_new_direction_vector_components (double x, double y, double z)
References sol_flow_packet_new(), sol_direction_vector::x, sol_direction_vector::y, and sol_direction_vector::z.
Referenced by sol_flow_send_direction_vector_components_packet().
SOL_API struct sol_flow_packet* sol_flow_packet_new_drange (const struct sol_drange * drange)
References sol_flow_packet_new().
SOL_API struct sol_flow_packet* sol_flow_packet_new_drange_value (double value)
References SOL_DRANGE_INIT_VALUE, and sol_flow_packet_new().
SOL_API struct sol_flow_packet* sol_flow_packet_new_empty (void)
References sol_flow_packet_new().
Referenced by sol_flow_send_empty_packet().
SOL_API struct sol_flow_packet* sol_flow_packet_new_error (int code, const char * msg)
References error_data::code, error_data::msg, and sol_flow_packet_new().
Referenced by sol_flow_send_error_packet().
SOL_API struct sol_flow_packet* sol_flow_packet_new_http_response (int response_code, const char * url, const char * content_type, const struct sol_blob * content, const struct sol_vector * cookies, const struct sol_vector * headers)
References http_response::code, http_response::content, http_response::content_type, http_response::cookies, http_response::headers, sol_flow_packet_new(), SOL_FLOW_PACKET_TYPE_HTTP_RESPONSE, and http_response::url.
Referenced by sol_flow_send_http_response_packet().
SOL_API struct sol_flow_packet* sol_flow_packet_new_irange (const struct sol_irange * irange)
References sol_flow_packet_new().
SOL_API struct sol_flow_packet* sol_flow_packet_new_irange_value (int32_t value)
References sol_flow_packet_new(), and SOL_IRANGE_INIT_VALUE.
SOL_API struct sol_flow_packet* sol_flow_packet_new_json_array (const struct sol_blob * json_array)
References sol_flow_packet_new(), and SOL_NULL_CHECK.
SOL_API struct sol_flow_packet* sol_flow_packet_new_json_object (const struct sol_blob * json_object)
References sol_flow_packet_new(), and SOL_NULL_CHECK.
SOL_API struct sol_flow_packet* sol_flow_packet_new_location (const struct sol_location * location)
References sol_flow_packet_new().
SOL_API struct sol_flow_packet* sol_flow_packet_new_rgb (const struct sol_rgb * rgb)
References sol_flow_packet_new().
SOL_API struct sol_flow_packet* sol_flow_packet_new_rgb_components (uint32_t red, uint32_t green, uint32_t blue)
References sol_rgb::blue, sol_rgb::green, sol_rgb::red, sol_rgb::red_max, and sol_flow_packet_new().
Referenced by sol_flow_send_rgb_components_packet().
SOL_API struct sol_flow_packet* sol_flow_packet_new_string (const char * value)
References sol_flow_packet_new().
SOL_API struct sol_flow_packet* sol_flow_packet_new_string_slice (struct sol_str_slice slice)
References sol_str_slice::data, sol_str_slice::len, and sol_flow_packet_new_string_take().
SOL_API struct sol_flow_packet* sol_flow_packet_new_string_take (char * value)
References sol_flow_packet_del(), and SOL_WRN.
Referenced by sol_flow_packet_new_string_slice(), and sol_flow_send_string_take_packet().
SOL_API struct sol_flow_packet* sol_flow_packet_new_timestamp (const struct timespec * timestamp)
References sol_flow_packet_new().
SOL_API const struct sol_flow_packet_type* sol_flow_packet_type_composed_new (const struct sol_flow_packet_type ** types)
References sol_flow_packet_type::api_version, sol_flow_packet_type::data_size, sol_flow_packet_type::dispose, sol_flow_packet_type::init, sol_flow_packet_composed_type::members, sol_flow_packet_composed_type::members_len, sol_flow_packet_type::name, sol_flow_packet_composed_type::self, sol_buffer_append_slice(), sol_buffer_steal(), SOL_FLOW_PACKET_TYPE_API_VERSION, SOL_INT_CHECK_GOTO, SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, sol_ptr_vector_append(), and SOL_PTR_VECTOR_FOREACH_IDX.
void sol_flow_packet_type_composed_shutdown (void)
References sol_flow_packet_composed_type::members, sol_flow_packet_type::name, sol_flow_packet_composed_type::self, and SOL_PTR_VECTOR_FOREACH_IDX.
Referenced by sol_flow_shutdown().
Variable Documentation
SOL_API const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_ANY = &_SOL_FLOW_PACKET_TYPE_ANY
Referenced by sol_flow_packet_new().
SOL_API const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_BLOB = &_SOL_FLOW_PACKET_TYPE_BLOB
SOL_API const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_BOOLEAN = &_SOL_FLOW_PACKET_TYPE_BOOLEAN
Referenced by gtk_label_in_process(), gtk_led_in_process(), and gtk_pwm_viewer_enable_process().
SOL_API const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_BYTE = &_SOL_FLOW_PACKET_TYPE_BYTE
Referenced by gtk_label_in_process().
SOL_API const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_DIRECTION_VECTOR = &_SOL_FLOW_PACKET_TYPE_DIRECTION_VECTOR
SOL_API const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_DRANGE = &_SOL_FLOW_PACKET_TYPE_DRANGE
SOL_API const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_EMPTY = &_SOL_FLOW_PACKET_TYPE_EMPTY
Referenced by gtk_label_in_process().
SOL_API const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_ERROR = &_SOL_FLOW_PACKET_TYPE_ERROR
Referenced by sol_flow_node_type_get_port_out().
SOL_API const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_HTTP_RESPONSE = &_SOL_FLOW_PACKET_TYPE_HTTP_RESPONSE
Referenced by sol_flow_packet_get_http_response(), and sol_flow_packet_new_http_response().
SOL_API const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_IRANGE = &_SOL_FLOW_PACKET_TYPE_IRANGE
Referenced by gtk_label_in_process(), gtk_led_in_process(), gtk_pwm_viewer_duty_cycle_process(), and gtk_pwm_viewer_period_process().
SOL_API const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_JSON_ARRAY = &_SOL_FLOW_PACKET_TYPE_JSON_ARRAY
SOL_API const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_JSON_OBJECT = &_SOL_FLOW_PACKET_TYPE_JSON_OBJECT
SOL_API const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_LOCATION = &_SOL_FLOW_PACKET_TYPE_LOCATION
SOL_API const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_RGB = &_SOL_FLOW_PACKET_TYPE_RGB
Referenced by gtk_led_in_process().
SOL_API const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_STRING = &_SOL_FLOW_PACKET_TYPE_STRING
Referenced by gtk_label_in_process().
SOL_API const struct sol_flow_packet_type* SOL_FLOW_PACKET_TYPE_TIMESTAMP = &_SOL_FLOW_PACKET_TYPE_TIMESTAMP