Soletta: src/lib/common/sol-event-handler-contiki.h File Reference
sol-event-handler-contiki.h File Reference
#include <stdbool.h>
#include <contiki.h>
Functions
bool sol_mainloop_contiki_event_handler_add (const process_event_t *ev, const process_data_t ev_data, void(*cb)(void *user_data, process_event_t ev, process_data_t ev_data), const void *data)
bool sol_mainloop_contiki_event_handler_del (const process_event_t *ev, const process_data_t ev_data, void(*cb)(void *user_data, process_event_t ev, process_data_t ev_data), const void *data)
Function Documentation
bool sol_mainloop_contiki_event_handler_add (const process_event_t * ev, const process_data_t ev_data, void(*)(void *user_data, process_event_t ev, process_data_t ev_data) cb, const void * data)
References sol_event_handler_contiki::cb, sol_event_handler_contiki::delete_me, sol_event_handler_contiki::ev, sol_event_handler_contiki::ev_data, sol_ptr_vector_append(), and sol_event_handler_contiki::user_data.
Referenced by sol_gpio_open_raw().
bool sol_mainloop_contiki_event_handler_del (const process_event_t * ev, const process_data_t ev_data, void(*)(void *user_data, process_event_t ev, process_data_t ev_data) cb, const void * data)
References sol_event_handler_contiki::cb, sol_event_handler_contiki::delete_me, sol_event_handler_contiki::ev, sol_event_handler_contiki::ev_data, SOL_PTR_VECTOR_FOREACH_IDX, and sol_event_handler_contiki::user_data.
Referenced by sol_gpio_close().