Soletta: src/shared/sol-util-file.h File Reference
sol-util-file.h File Reference
#include "sol-macros.h"
#include "sol-buffer.h"
#include <dirent.h>
#include <sys/types.h>
#include <stdarg.h>
#include <stdbool.h>
Macros
#define CHUNK_SIZE 4096
#define SOL_UTIL_MAX_READ_ATTEMPTS 10
Functions
int sol_util_fd_set_flag (int fd, int flag) SOL_ATTR_WARN_UNUSED_RESULT
ssize_t sol_util_fill_buffer (const int fd, struct sol_buffer *buffer, const size_t size)
int sol_util_get_rootdir (char *out, size_t size) SOL_ATTR_WARN_UNUSED_RESULT
bool sol_util_iterate_dir (const char *path, bool(*iterate_dir_cb)(void *data, const char *dir_path, struct dirent *ent), const void *data)
char * sol_util_load_file_fd_string (const int fd, size_t *size) SOL_ATTR_WARN_UNUSED_RESULT
int int int int struct sol_buffer * sol_util_load_file_raw (const int fd) SOL_ATTR_WARN_UNUSED_RESULT
char * sol_util_load_file_string (const char *filename, size_t *size) SOL_ATTR_WARN_UNUSED_RESULT
int int int sol_util_read_file (const char *path, const char *fmt,...) SOL_ATTR_SCANF(2
int int int int sol_util_vread_file (const char *path, const char *fmt, va_list args) SOL_ATTR_SCANF(2
int int sol_util_vwrite_file (const char *path, const char *fmt, va_list args) SOL_ATTR_PRINTF(2
int sol_util_write_file (const char *path, const char *fmt,...) SOL_ATTR_PRINTF(2
Macro Definition Documentation
#define CHUNK_SIZE 4096
Referenced by sol_util_load_file_raw().
#define SOL_UTIL_MAX_READ_ATTEMPTS 10
Referenced by sol_util_fill_buffer().
Function Documentation
int sol_util_fd_set_flag (int fd, int flag)
References sol_buffer::flags.
Referenced by process_subprocess_open().
ssize_t sol_util_fill_buffer (const int fd, struct sol_buffer * buffer, const size_t size)
Fills buffer with data read from file fd
Data read will be appended to the end of used buffer (i.e. buffer->used). If one wants data to be inserted at beginning of buffer, then one must call sol_buffer_reset() on buffer before calling sol_util_fill_buffer.
By using this function to fill the buffer, one doesn't need to care about EAGAIN or EINTR being returned by read() raw call.
References sol_buffer::capacity, sol_buffer::data, sol_buffer::flags, sol_buffer_ensure(), SOL_BUFFER_FLAGS_NO_NUL_BYTE, SOL_NULL_CHECK, SOL_UTIL_MAX_READ_ATTEMPTS, SOL_WRN, and sol_buffer::used.
Referenced by sol_efivars_read_raw(), sol_fs_read_raw(), and sol_util_load_file_raw().
int sol_util_get_rootdir (char * out, size_t size)
Referenced by sol_lib_loader_new_in_rootdir().
bool sol_util_iterate_dir (const char * path, bool(*)(void *data, const char *dir_path, struct dirent *ent) iterate_dir_cb, const void * data)
References SOL_NULL_CHECK, sol_util_strerrora, and SOL_WRN.
Referenced by sol_i2c_create_device().
char* sol_util_load_file_fd_string (const int fd, size_t * size)
References sol_buffer::data, sol_buffer::flags, sol_buffer_ensure_nul_byte(), SOL_BUFFER_FLAGS_DEFAULT, sol_buffer_steal(), and sol_util_load_file_raw().
Referenced by sol_efivars_read_raw(), sol_fs_read_raw(), and sol_util_load_file_string().
int int int int struct sol_buffer* sol_util_load_file_raw (const int fd)
References CHUNK_SIZE, sol_buffer::flags, SOL_BUFFER_FLAGS_NO_NUL_BYTE, SOL_NULL_CHECK, and sol_util_fill_buffer().
Referenced by sol_file_reader_open(), and sol_util_load_file_fd_string().
char* sol_util_load_file_string (const char * filename, size_t * size)
References sol_util_load_file_fd_string().
int int int sol_util_read_file (const char * path, const char * fmt, ...)
int int int int sol_util_vread_file (const char * path, const char * fmt, va_list args)
int int sol_util_vwrite_file (const char * path, const char * fmt, va_list args)
int sol_util_write_file (const char * path, const char * fmt, ...)