Soletta: src/lib/flow/sol-flow-parser-dynamic.c File Reference
sol-flow-parser-dynamic.c File Reference
#include "sol-flow-internal.h"
#include "sol-lib-loader.h"
Functions
const struct sol_flow_metatype * get_dynamic_metatype (const struct sol_str_slice name)
void loaded_metatype_cache_shutdown (void)
Function Documentation
const struct sol_flow_metatype* get_dynamic_metatype (const struct sol_str_slice name)
References sol_str_slice::data, sol_str_slice::len, SOL_INT_CHECK, sol_lib_load(), sol_lib_loader_new_in_rootdir(), and SOL_NULL_CHECK.
Referenced by sol_flow_metatype_get_generate_code_end_func(), sol_flow_metatype_get_generate_code_start_func(), sol_flow_metatype_get_generate_code_type_func(), and sol_flow_metatype_get_ports_description_func().
void loaded_metatype_cache_shutdown (void)
References sol_lib_loader_del().
Referenced by sol_flow_shutdown().