Soletta: src/lib/crypto/sol-message-digest-impl-linux-kcapi.c File Reference
sol-message-digest-impl-linux-kcapi.c File Reference
#include <assert.h>
#include <errno.h>
#include <fcntl.h>
#include <linux/if_alg.h>
#include <linux/netlink.h>
#include <linux/rtnetlink.h>
#include <sys/socket.h>
#include <unistd.h>
#include "sol-message-digest-common.h"
#include "sol-crypto.h"
#include "sol-util.h"
#include "sol-vector.h"
Data Structures
struct crypto_report_hash
struct crypto_user_alg
struct sol_message_digest_algorithm_info
Macros
#define AF_ALG 38
#define CR_RTA(x) ((struct rtattr *)(((char *)(x)) + NLMSG_ALIGN(sizeof(struct crypto_user_alg))))
#define CRYPTO_MAX_ALG_NAME 64 /* from kernel */
#define CRYPTO_MAX_NAME CRYPTO_MAX_ALG_NAME
#define CRYPTO_MSG_MAX (__CRYPTO_MSG_MAX - 1)
#define CRYPTOCFGA_MAX (__CRYPTOCFGA_MAX - 1)
#define SOL_ALG 279
Enumerations
enum {
CRYPTO_MSG_BASE = 0x10, CRYPTO_MSG_NEWALG = 0x10, CRYPTO_MSG_DELALG, CRYPTO_MSG_UPDATEALG,
CRYPTO_MSG_GETALG, CRYPTO_MSG_DELRNG
}
enum crypto_attr_type_t {
CRYPTOCFGA_UNSPEC, CRYPTOCFGA_PRIORITY_VAL, CRYPTOCFGA_REPORT_LARVAL, CRYPTOCFGA_REPORT_HASH,
CRYPTOCFGA_REPORT_BLKCIPHER, CRYPTOCFGA_REPORT_AEAD, CRYPTOCFGA_REPORT_COMPRESS, CRYPTOCFGA_REPORT_RNG,
CRYPTOCFGA_REPORT_CIPHER, CRYPTOCFGA_REPORT_AKCIPHER
}
Functions
int sol_message_digest_init (void)
SOL_API struct sol_message_digest * sol_message_digest_new (const struct sol_message_digest_config *config)
void sol_message_digest_shutdown (void)
Macro Definition Documentation
#define AF_ALG 38
Referenced by sol_message_digest_new().
#define CR_RTA (x) ((struct rtattr *)(((char *)(x)) + NLMSG_ALIGN(sizeof(struct crypto_user_alg))))
#define CRYPTO_MAX_ALG_NAME 64 /* from kernel */
Referenced by sol_message_digest_init().
#define CRYPTO_MAX_NAME CRYPTO_MAX_ALG_NAME
#define CRYPTO_MSG_MAX (__CRYPTO_MSG_MAX - 1)
#define CRYPTOCFGA_MAX (__CRYPTOCFGA_MAX - 1)
#define SOL_ALG 279
Referenced by sol_message_digest_new().
Enumeration Type Documentation
anonymous enum
Enumerator
CRYPTO_MSG_BASE
CRYPTO_MSG_NEWALG
CRYPTO_MSG_DELALG
CRYPTO_MSG_UPDATEALG
CRYPTO_MSG_GETALG
CRYPTO_MSG_DELRNG
enum crypto_attr_type_t
Enumerator
CRYPTOCFGA_UNSPEC
CRYPTOCFGA_PRIORITY_VAL
CRYPTOCFGA_REPORT_LARVAL
CRYPTOCFGA_REPORT_HASH
CRYPTOCFGA_REPORT_BLKCIPHER
CRYPTOCFGA_REPORT_AEAD
CRYPTOCFGA_REPORT_COMPRESS
CRYPTOCFGA_REPORT_RNG
CRYPTOCFGA_REPORT_CIPHER
CRYPTOCFGA_REPORT_AKCIPHER
Function Documentation
int sol_message_digest_init (void)
References CRYPTO_MAX_ALG_NAME, and sol_message_digest_common_init().
void sol_message_digest_shutdown (void)
References sol_message_digest_common_shutdown(), and sol_vector_clear().