Soletta: src/lib/common/include/sol-glib-integration.h File Reference
sol-glib-integration.h File Reference
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <sol-mainloop.h>
#include <sol-log.h>
#include <sol-vector.h>
Data Structures
struct _sol_glib_integration_fd_handler
struct _sol_glib_integration_source_data
Functions
static unsigned int _sol_glib_integration_align_power2 (unsigned int u)
static gushort _sol_glib_integration_fd_flags_to_gpoll_events (uint32_t sol_flags)
static void _sol_glib_integration_fd_handler_del (struct _sol_glib_integration_fd_handler *h)
static uint32_t _sol_glib_integration_gpoll_events_to_fd_flags (gushort gpoll_events)
static gboolean _sol_glib_integration_gsource_cb (gpointer user_data)
static gboolean _sol_glib_integration_gsource_check (GSource *source)
static gboolean _sol_glib_integration_gsource_dispatch (GSource *source, GSourceFunc cb, gpointer user_data)
static gboolean _sol_glib_integration_gsource_prepare (GSource *source, gint *timeout)
static bool _sol_glib_integration_on_source_fd (void *data, int fd, uint32_t active_flags)
static bool _sol_glib_integration_source_acquire (struct _sol_glib_integration_source_data *mdata)
static bool _sol_glib_integration_source_check (void *data)
static void _sol_glib_integration_source_dispatch (void *data)
static void _sol_glib_integration_source_dispose (void *data)
static struct _sol_glib_integration_fd_handler * _sol_glib_integration_source_fd_handler_data_find (struct _sol_glib_integration_source_data *mdata, int fd)
static void _sol_glib_integration_source_fd_handlers_adjust (struct _sol_glib_integration_source_data *mdata)
static bool _sol_glib_integration_source_get_next_timeout (void *data, struct timespec *ts)
static GPollFD * _sol_glib_integration_source_gpollfd_find (struct _sol_glib_integration_source_data *mdata, int fd)
static bool _sol_glib_integration_source_prepare (void *data)
static void _sol_glib_integration_source_release (struct _sol_glib_integration_source_data *mdata)
static bool sol_glib_integration (void)
Variables
static GSourceFuncs _sol_glib_integration_gsource_funcs
static const struct sol_mainloop_source_type _sol_glib_integration_source_type
Detailed Description
This file is to be included by GMainLoop users. It will make sure Glib's main loop is usable with Soletta in the case of Soletta being compiled with glib as mainloop or any other such as POSIX.
Include this file and call sol_glib_integration().
Function Documentation
static unsigned int _sol_glib_integration_align_power2 (unsigned int u) inline static
Referenced by _sol_glib_integration_source_prepare().
static gushort _sol_glib_integration_fd_flags_to_gpoll_events (uint32_t sol_flags) static
Referenced by _sol_glib_integration_on_source_fd().
static void _sol_glib_integration_fd_handler_del (struct _sol_glib_integration_fd_handler * h) static
References _sol_glib_integration_fd_handler::watch.
Referenced by _sol_glib_integration_source_dispose(), and _sol_glib_integration_source_fd_handlers_adjust().
static uint32_t _sol_glib_integration_gpoll_events_to_fd_flags (gushort gpoll_events) static
Referenced by _sol_glib_integration_source_fd_handlers_adjust().
static gboolean _sol_glib_integration_gsource_cb (gpointer user_data) static
Referenced by sol_glib_integration().
static gboolean _sol_glib_integration_gsource_check (GSource * source) static
static gboolean _sol_glib_integration_gsource_dispatch (GSource * source, GSourceFunc cb, gpointer user_data) static
static gboolean _sol_glib_integration_gsource_prepare (GSource * source, gint * timeout) static
static bool _sol_glib_integration_on_source_fd (void * data, int fd, uint32_t active_flags) static
References _sol_glib_integration_fd_flags_to_gpoll_events(), _sol_glib_integration_source_gpollfd_find(), _sol_glib_integration_fd_handler::mdata, and SOL_NULL_CHECK.
Referenced by _sol_glib_integration_source_fd_handlers_adjust().
static bool _sol_glib_integration_source_acquire (struct _sol_glib_integration_source_data * mdata) static
References _sol_glib_integration_source_data::gsource, and SOL_WRN.
Referenced by _sol_glib_integration_source_check(), _sol_glib_integration_source_dispatch(), and _sol_glib_integration_source_prepare().
static bool _sol_glib_integration_source_check (void * data) static
References _sol_glib_integration_source_acquire(), _sol_glib_integration_source_release(), _sol_glib_integration_source_data::fds, _sol_glib_integration_source_data::gsource, _sol_glib_integration_source_data::max_prio, and _sol_glib_integration_source_data::n_poll.
static void _sol_glib_integration_source_dispatch (void * data) static
References _sol_glib_integration_source_acquire(), _sol_glib_integration_source_release(), and _sol_glib_integration_source_data::gsource.
static void _sol_glib_integration_source_dispose (void * data) static
References _sol_glib_integration_fd_handler_del(), _sol_glib_integration_source_data::fds, _sol_glib_integration_source_data::gsource, _sol_glib_integration_source_data::handlers, sol_ptr_vector_clear(), and SOL_PTR_VECTOR_FOREACH_REVERSE_IDX.
static struct _sol_glib_integration_fd_handler* _sol_glib_integration_source_fd_handler_data_find (struct _sol_glib_integration_source_data * mdata, int fd) static
References _sol_glib_integration_fd_handler::fd, _sol_glib_integration_source_data::handlers, and SOL_PTR_VECTOR_FOREACH_IDX.
Referenced by _sol_glib_integration_source_fd_handlers_adjust().
static void _sol_glib_integration_source_fd_handlers_adjust (struct _sol_glib_integration_source_data * mdata) static
References _sol_glib_integration_fd_handler_del(), _sol_glib_integration_gpoll_events_to_fd_flags(), _sol_glib_integration_on_source_fd(), _sol_glib_integration_source_fd_handler_data_find(), _sol_glib_integration_source_gpollfd_find(), _sol_glib_integration_fd_handler::events, _sol_glib_integration_fd_handler::fd, _sol_glib_integration_source_data::fds, _sol_glib_integration_source_data::handlers, _sol_glib_integration_fd_handler::mdata, _sol_glib_integration_source_data::n_poll, SOL_DBG, SOL_INT_CHECK_GOTO, SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, sol_ptr_vector_append(), sol_ptr_vector_del(), SOL_PTR_VECTOR_FOREACH_REVERSE_IDX, and _sol_glib_integration_fd_handler::watch.
Referenced by _sol_glib_integration_source_prepare().
static bool _sol_glib_integration_source_get_next_timeout (void * data, struct timespec * ts) static
References _sol_glib_integration_source_data::timeout.
static GPollFD* _sol_glib_integration_source_gpollfd_find (struct _sol_glib_integration_source_data * mdata, int fd) static
References _sol_glib_integration_source_data::fds, and _sol_glib_integration_source_data::n_poll.
Referenced by _sol_glib_integration_on_source_fd(), and _sol_glib_integration_source_fd_handlers_adjust().
static bool _sol_glib_integration_source_prepare (void * data) static
References _sol_glib_integration_align_power2(), _sol_glib_integration_source_acquire(), _sol_glib_integration_source_fd_handlers_adjust(), _sol_glib_integration_source_release(), _sol_glib_integration_source_data::fds, _sol_glib_integration_source_data::gsource, _sol_glib_integration_source_data::max_prio, _sol_glib_integration_source_data::n_fds, _sol_glib_integration_source_data::n_poll, SOL_NULL_CHECK_GOTO, and _sol_glib_integration_source_data::timeout.
static void _sol_glib_integration_source_release (struct _sol_glib_integration_source_data * mdata) static
References _sol_glib_integration_source_data::gsource.
Referenced by _sol_glib_integration_source_check(), _sol_glib_integration_source_dispatch(), and _sol_glib_integration_source_prepare().
static bool sol_glib_integration (void) static
References _sol_glib_integration_gsource_cb(), _sol_glib_integration_gsource_funcs, _sol_glib_integration_source_data::fds, _sol_glib_integration_source_data::handlers, _sol_glib_integration_source_data::max_prio, _sol_glib_integration_source_data::n_fds, _sol_glib_integration_source_data::n_poll, SOL_DBG, sol_init(), SOL_INT_CHECK_GOTO, sol_mainloop_source_new(), SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, sol_ptr_vector_init(), SOL_WRN, and _sol_glib_integration_source_data::timeout.
Variable Documentation
GSourceFuncs _sol_glib_integration_gsource_funcs static
Initial value:
= {
    .prepare = _sol_glib_integration_gsource_prepare,
    .check = _sol_glib_integration_gsource_check,
    .dispatch = _sol_glib_integration_gsource_dispatch,
}
Referenced by sol_glib_integration().
const struct sol_mainloop_source_type _sol_glib_integration_source_type static
Initial value:
= {
    .api_version = SOL_MAINLOOP_SOURCE_TYPE_API_VERSION,
    .prepare = _sol_glib_integration_source_prepare,
    .get_next_timeout = _sol_glib_integration_source_get_next_timeout,
    .check = _sol_glib_integration_source_check,
    .dispatch = _sol_glib_integration_source_dispatch,
    .dispose = _sol_glib_integration_source_dispose
}