Soletta: src/lib/common/include/sol-mainloop-contiki.h File Reference
sol-mainloop-contiki.h File Reference
#include <contiki.h>
#include <stdbool.h>
Functions
void sol_mainloop_contiki_event_set (process_event_t ev, process_data_t data)
bool sol_mainloop_contiki_iter (void)
Function Documentation
void sol_mainloop_contiki_event_set (process_event_t ev, process_data_t data)
bool sol_mainloop_contiki_iter (void)
References sol_mainloop_common_idler_process(), sol_mainloop_common_loop_check(), and sol_mainloop_common_timeout_process().