Soletta: src/lib/flow/sol-flow-composed.c File Reference
sol-flow-composed.c File Reference
#include <string.h>
#include <alloca.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <ctype.h>
#include "sol-str-slice.h"
#include "sol-vector.h"
#include "sol-util.h"
#include "sol-flow-packet.h"
#include "sol-types.h"
#include "sol-flow-composed.h"
#include "sol-log.h"
#include "sol-str-table.h"
Data Structures
struct composed_node_data
struct composed_node_port_type
struct composed_node_type
Macros
#define DELIM ("|")
#define INPUT_PORT_NAME ("IN")
#define OUTPUT_PORT_NAME ("OUT")
Functions
int composed_metatype_constructor_generate_code_end (struct sol_buffer *out, const struct sol_str_slice name, const struct sol_str_slice contents)
int composed_metatype_constructor_generate_code_start (struct sol_buffer *out, const struct sol_str_slice name, const struct sol_str_slice contents)
int composed_metatype_constructor_generate_code_type (struct sol_buffer *out, const struct sol_str_slice name, const struct sol_str_slice contents)
int composed_metatype_constructor_get_ports_description (const struct sol_str_slice contents, struct sol_vector *in, struct sol_vector *out)
int composed_metatype_splitter_generate_code_end (struct sol_buffer *out, const struct sol_str_slice name, const struct sol_str_slice contents)
int composed_metatype_splitter_generate_code_start (struct sol_buffer *out, const struct sol_str_slice name, const struct sol_str_slice contents)
int composed_metatype_splitter_generate_code_type (struct sol_buffer *out, const struct sol_str_slice name, const struct sol_str_slice contents)
int composed_metatype_splitter_get_ports_description (const struct sol_str_slice contents, struct sol_vector *in, struct sol_vector *out)
int create_composed_constructor_type (const struct sol_flow_metatype_context *ctx, struct sol_flow_node_type **type)
int create_composed_splitter_type (const struct sol_flow_metatype_context *ctx, struct sol_flow_node_type **type)
Macro Definition Documentation
#define DELIM ("|")
#define INPUT_PORT_NAME ("IN")
#define OUTPUT_PORT_NAME ("OUT")
Function Documentation
int composed_metatype_constructor_generate_code_end (struct sol_buffer * out, const struct sol_str_slice name, const struct sol_str_slice contents)
Referenced by sol_flow_metatype_get_generate_code_end_func().
int composed_metatype_constructor_generate_code_start (struct sol_buffer * out, const struct sol_str_slice name, const struct sol_str_slice contents)
References SOL_INT_CHECK, and SOL_NULL_CHECK.
Referenced by sol_flow_metatype_get_generate_code_start_func().
int composed_metatype_constructor_generate_code_type (struct sol_buffer * out, const struct sol_str_slice name, const struct sol_str_slice contents)
Referenced by sol_flow_metatype_get_generate_code_type_func().
int composed_metatype_constructor_get_ports_description (const struct sol_str_slice contents, struct sol_vector * in, struct sol_vector * out)
Referenced by sol_flow_metatype_get_ports_description_func().
int composed_metatype_splitter_generate_code_end (struct sol_buffer * out, const struct sol_str_slice name, const struct sol_str_slice contents)
Referenced by sol_flow_metatype_get_generate_code_end_func().
int composed_metatype_splitter_generate_code_start (struct sol_buffer * out, const struct sol_str_slice name, const struct sol_str_slice contents)
References SOL_NULL_CHECK.
Referenced by sol_flow_metatype_get_generate_code_start_func().
int composed_metatype_splitter_generate_code_type (struct sol_buffer * out, const struct sol_str_slice name, const struct sol_str_slice contents)
Referenced by sol_flow_metatype_get_generate_code_type_func().
int composed_metatype_splitter_get_ports_description (const struct sol_str_slice contents, struct sol_vector * in, struct sol_vector * out)
Referenced by sol_flow_metatype_get_ports_description_func().
int create_composed_constructor_type (const struct sol_flow_metatype_context * ctx, struct sol_flow_node_type ** type)
int create_composed_splitter_type (const struct sol_flow_metatype_context * ctx, struct sol_flow_node_type ** type)