Soletta: src/lib/parsers/sol-json.c File Reference
sol-json.c File Reference
#include <ctype.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "sol-json.h"
#include "sol-log.h"
#include "sol-util.h"
#include <float.h>
#include <math.h>
Macros
#define MAX_BYTES_UNICODE 3
#define STR_DOUBLE_LEN 64
Functions
SOL_API size_t sol_json_calculate_escaped_string_len (const char *str)
SOL_API int sol_json_double_to_str (const double value, char *buf, size_t len)
SOL_API char * sol_json_escape_string (const char *str, char *buf, size_t len)
SOL_API bool sol_json_is_valid_type (struct sol_json_scanner *scanner, enum sol_json_type type)
SOL_API bool sol_json_scanner_get_dict_pair (struct sol_json_scanner *scanner, struct sol_json_token *key, struct sol_json_token *value)
SOL_API bool sol_json_scanner_next (struct sol_json_scanner *scanner, struct sol_json_token *token)
SOL_API bool sol_json_scanner_skip_over (struct sol_json_scanner *scanner, struct sol_json_token *token)
SOL_API int sol_json_serialize_boolean (struct sol_buffer *buffer, bool val)
SOL_API int sol_json_serialize_double (struct sol_buffer *buffer, double val)
SOL_API int sol_json_serialize_int32 (struct sol_buffer *buffer, int32_t val)
SOL_API int sol_json_serialize_int64 (struct sol_buffer *buffer, int64_t val)
SOL_API int sol_json_serialize_string (struct sol_buffer *buffer, const char *str)
SOL_API int sol_json_serialize_uint32 (struct sol_buffer *buffer, uint32_t val)
SOL_API int sol_json_serialize_uint64 (struct sol_buffer *buffer, uint64_t val)
SOL_API int sol_json_token_get_double (const struct sol_json_token *token, double *value)
SOL_API int sol_json_token_get_int64 (const struct sol_json_token *token, int64_t *value)
SOL_API int sol_json_token_get_uint64 (const struct sol_json_token *token, uint64_t *value)
SOL_API int sol_json_token_get_unescaped_string (const struct sol_json_token *token, struct sol_buffer *buffer)
SOL_API char * sol_json_token_get_unescaped_string_copy (const struct sol_json_token *value)
Macro Definition Documentation
#define MAX_BYTES_UNICODE 3
Referenced by sol_json_token_get_unescaped_string().
#define STR_DOUBLE_LEN 64
Referenced by sol_json_serialize_double().
Function Documentation
SOL_API char* sol_json_escape_string (const char * str, char * buf, size_t len)
References SOL_NULL_CHECK.
Referenced by sol_json_serialize_string().
SOL_API bool sol_json_scanner_get_dict_pair (struct sol_json_scanner * scanner, struct sol_json_token * key, struct sol_json_token * value)
References sol_json_scanner::current, SOL_ERR, sol_json_scanner_next(), sol_json_scanner_skip_over(), SOL_JSON_TYPE_PAIR_SEP, SOL_JSON_TYPE_STRING, sol_json_token::start, and start.
SOL_API bool sol_json_scanner_next (struct sol_json_scanner * scanner, struct sol_json_token * token)
References sol_json_scanner::current, sol_json_token::end, sol_json_scanner::mem_end, SOL_ERR, SOL_JSON_TYPE_ARRAY_END, SOL_JSON_TYPE_ARRAY_START, SOL_JSON_TYPE_ELEMENT_SEP, SOL_JSON_TYPE_FALSE, SOL_JSON_TYPE_NULL, SOL_JSON_TYPE_NUMBER, SOL_JSON_TYPE_OBJECT_END, SOL_JSON_TYPE_OBJECT_START, SOL_JSON_TYPE_PAIR_SEP, SOL_JSON_TYPE_STRING, SOL_JSON_TYPE_TRUE, SOL_JSON_TYPE_UNKNOWN, and sol_json_token::start.
Referenced by sol_json_is_valid_type(), sol_json_scanner_get_dict_pair(), and sol_json_scanner_skip_over().
SOL_API bool sol_json_scanner_skip_over (struct sol_json_scanner * scanner, struct sol_json_token * token)
References sol_json_scanner::current, sol_json_token::end, sol_json_scanner_next(), SOL_JSON_TYPE_ARRAY_END, SOL_JSON_TYPE_ARRAY_START, SOL_JSON_TYPE_ELEMENT_SEP, SOL_JSON_TYPE_FALSE, SOL_JSON_TYPE_NULL, SOL_JSON_TYPE_NUMBER, SOL_JSON_TYPE_OBJECT_END, SOL_JSON_TYPE_OBJECT_START, SOL_JSON_TYPE_PAIR_SEP, SOL_JSON_TYPE_STRING, SOL_JSON_TYPE_TRUE, SOL_JSON_TYPE_UNKNOWN, and unlikely.
Referenced by sol_json_is_valid_type(), and sol_json_scanner_get_dict_pair().
SOL_API int sol_json_serialize_string (struct sol_buffer * buffer, const char * str)
References sol_buffer_append_char(), sol_buffer_ensure(), SOL_INT_CHECK, sol_json_calculate_escaped_string_len(), sol_json_escape_string(), SOL_NULL_CHECK, and sol_buffer::used.
SOL_API int sol_json_token_get_double (const struct sol_json_token * token, double * value)
References SOL_DBG, sol_util_strtodn(), and sol_json_token::start.
SOL_API int sol_json_token_get_int64 (const struct sol_json_token * token, int64_t * value)
References sol_json_token::end, SOL_JSON_TYPE_NUMBER, SOL_NULL_CHECK, SOL_WRN, and sol_json_token::start.
SOL_API int sol_json_token_get_uint64 (const struct sol_json_token * token, uint64_t * value)
References sol_json_token::end, SOL_DBG, SOL_JSON_TYPE_NUMBER, SOL_NULL_CHECK, SOL_WRN, and sol_json_token::start.