Soletta: src/lib/common/include/sol-pin-mux.h File Reference
sol-pin-mux.h File Reference
#include <stdint.h>
#include "sol-gpio.h"
Enumerations
enum sol_io_protocol {
SOL_IO_AIO = 0x01, SOL_IO_GPIO = 0x02, SOL_IO_I2C = 0x04, SOL_IO_PWM = 0x08,
SOL_IO_SPI = 0x10, SOL_IO_UART = 0x20
}
Functions
int sol_pin_mux_map (const char *label, const enum sol_io_protocol prot,...)
bool sol_pin_mux_select_mux (const char *board)
int sol_pin_mux_setup_aio (const int device, const int pin)
int sol_pin_mux_setup_gpio (const int pin, const enum sol_gpio_direction dir)
int sol_pin_mux_setup_i2c (const uint8_t bus)
int sol_pin_mux_setup_pwm (const int device, const int channel)
Enumeration Type Documentation
enum sol_io_protocol
Enumerator
SOL_IO_AIO
SOL_IO_GPIO
SOL_IO_I2C
SOL_IO_PWM
SOL_IO_SPI
SOL_IO_UART
Function Documentation
int sol_pin_mux_map (const char * label, const enum sol_io_protocol prot, ...)
Maps a pin label to the parameters necessary so it works on the desired protocol.
Find if a given pin labeled 'label' is capable of operate on protocol 'prot' and return the parameters needed to setup the protocol.
Parameters
label The label of the pin as see on the board
prot Protocol on which the pin should operate
Returns
'0' on success, error code (always negative) otherwise.
References sol_pin_mux::pin_map.
Referenced by sol_aio_open_by_label(), sol_gpio_open_by_label(), and sol_pwm_open_by_label().
bool sol_pin_mux_select_mux (const char * board)
Select Pin Multiplexer instructions of a given board.
Searches(and activate if found) for pin multiplexing instructions of the given board. Built-in Pin Multiplexers have priority over modules.
Parameters
board The board name being used
Returns
'true' on success, 'false' otherwise.
References sol_pin_mux::init, sol_pin_mux::plat_name, sol_pin_mux::shutdown, and streq.
Referenced by sol_pin_mux_init().
int sol_pin_mux_setup_aio (const int device, const int pin)
Setup the given pin to operate as Analog I/O.
If a pin multiplexer is loaded (from a successfully call to sol_pin_mux_select_mux), execute the instructions needed to configure 'device'/'pin' pair to operate as Analog I/O.
Parameters
device the aio device number.
pin the aio pin number.
Returns
'0' on success, error code (always negative) otherwise.
References sol_pin_mux::aio.
Referenced by sol_aio_open().
int sol_pin_mux_setup_gpio (const int pin, const enum sol_gpio_direction dir)
Setup the given pin to operate as GPIO in the given direction (in or out).
If a pin multiplexer is loaded (from a successfully call to sol_pin_mux_select_mux), execute the instructions needed to configure 'pin' to operate as GPIO in direction 'dir'.
Parameters
pin the gpio pin number.
dir direction (in or out) that the pin should operate.
Returns
'0' on success, error code (always negative) otherwise.
References sol_pin_mux::gpio.
Referenced by sol_gpio_open().
int sol_pin_mux_setup_i2c (const uint8_t bus)
Setup the pins used of the given i2c bus number to operate in I2C mode.
If a pin multiplexer is loaded (from a successfully call to sol_pin_mux_select_mux), execute the instructions needed to configure the pins used by the given i2c bus to operate in I2C mode.
Parameters
bus the i2c bus number.
Returns
'0' on success, error code (always negative) otherwise.
References sol_pin_mux::i2c.
Referenced by sol_i2c_open().
int sol_pin_mux_setup_pwm (const int device, const int channel)
Setup the given pin to operate as PWM.
If a pin multiplexer is loaded (from a successfully call to sol_pin_mux_select_mux), execute the instructions needed to configure 'device'/'channel' pair to operate as PWM.
Parameters
device the pwm device number.
channel the channel number on device.
Returns
'0' on success, error code (always negative) otherwise.
References sol_pin_mux::pwm.
Referenced by sol_pwm_open().