Soletta: src/lib/common/sol-bus.c File Reference
sol-bus.c File Reference
#include <errno.h>
#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include <systemd/sd-bus.h>
#include <systemd/sd-event.h>
#include "sol-bus.h"
#include "sol-mainloop.h"
#include "sol-platform-impl.h"
#include "sol-util.h"
#include "sol-vector.h"
Data Structures
struct ctx
struct property_table
struct source_ctx
Functions
void sol_bus_close (void)
sd_bus * sol_bus_get (void(*bus_initialized)(sd_bus *bus))
int sol_bus_log_callback (sd_bus_message *reply, void *userdata, sd_bus_error *ret_error)
int sol_bus_map_cached_properties (sd_bus *bus, const char *dest, const char *path, const char *iface, const struct sol_bus_properties property_table[], void(*changed)(void *data, uint64_t mask), const void *data)
int sol_bus_unmap_cached_properties (const struct sol_bus_properties property_table[], const void *data)
Function Documentation
void sol_bus_close (void)
References ctx::bus, source_ctx::event, ctx::exiting, property_table::getall_slot, ctx::mainloop_source, property_table::match_slot, ctx::ping, ctx::property_tables, sol_mainloop_source_del(), sol_mainloop_source_get_data(), and SOL_PTR_VECTOR_FOREACH_IDX.
Referenced by sol_platform_impl_shutdown().
sd_bus* sol_bus_get (void(*)(sd_bus *bus) bus_initialized)
References ctx::bus, ctx::mainloop_source, ctx::property_tables, SOL_INT_CHECK_GOTO, sol_quit(), and SOL_WRN.
Referenced by sol_platform_impl_add_service_monitor(), and sol_platform_impl_get_state().
int sol_bus_log_callback (sd_bus_message * reply, void * userdata, sd_bus_error * ret_error)
References SOL_WRN.
int sol_bus_map_cached_properties (sd_bus * bus, const char * dest, const char * path, const char * iface, const struct sol_bus_properties property_table[], void(*)(void *data, uint64_t mask) changed, const void * data)
References property_table::changed, property_table::data, property_table::getall_slot, property_table::match_slot, sol_bus_properties::member, property_table::properties, ctx::property_tables, SOL_INT_CHECK, SOL_INT_CHECK_GOTO, SOL_NULL_CHECK, and sol_ptr_vector_append().
int sol_bus_unmap_cached_properties (const struct sol_bus_properties property_table[], const void * data)
References property_table::data, property_table::getall_slot, property_table::match_slot, property_table::properties, ctx::property_tables, SOL_NULL_CHECK, and SOL_PTR_VECTOR_FOREACH_IDX.
Referenced by sol_platform_impl_del_service_monitor().