Soletta: src/lib/flow/sol-flow-parser.c File Reference
sol-flow-parser.c File Reference
#include <errno.h>
#include "sol-arena.h"
#include "sol-buffer.h"
#include "sol-fbp.h"
#include "sol-flow-builder.h"
#include "sol-flow-internal.h"
#include "sol-flow-metatype.h"
#include "sol-flow-parser.h"
#include "sol-flow-resolver.h"
#include "sol-log.h"
#include "sol-util.h"
#include "sol-vector.h"
#include "sol-flow-composed.h"
#include "sol-flow-metatype-builtins-gen.h"
Data Structures
struct declared_type
struct metatype_context_internal
struct metatype_context_with_buf
struct parse_state
struct sol_flow_parser
Macros
#define SOL_FLOW_PARSER_CLIENT_API_CHECK(client, expected,...)
Functions
SOL_API
sol_flow_metatype_generate_code_func sol_flow_metatype_get_generate_code_end_func (const struct sol_str_slice name)
SOL_API
sol_flow_metatype_generate_code_func sol_flow_metatype_get_generate_code_start_func (const struct sol_str_slice name)
SOL_API
sol_flow_metatype_generate_code_func sol_flow_metatype_get_generate_code_type_func (const struct sol_str_slice name)
SOL_API
sol_flow_metatype_ports_description_func sol_flow_metatype_get_ports_description_func (const struct sol_str_slice name)
SOL_API struct sol_flow_node_type * sol_flow_parse_buffer (struct sol_flow_parser *parser, const char *buf, size_t len, const char *filename)
SOL_API struct sol_flow_node_type * sol_flow_parse_buffer_metatype (struct sol_flow_parser *parser, const char *metatype, const char *buf, size_t len, const char *filename)
SOL_API struct sol_flow_node_type * sol_flow_parse_string (struct sol_flow_parser *parser, const char *cstr, const char *filename)
SOL_API struct sol_flow_node_type * sol_flow_parse_string_metatype (struct sol_flow_parser *parser, const char *metatype, const char *str, const char *filename)
SOL_API int sol_flow_parser_del (struct sol_flow_parser *parser)
SOL_API struct sol_flow_parser * sol_flow_parser_new (const struct sol_flow_parser_client *client, const struct sol_flow_resolver *resolver)
Macro Definition Documentation
#define SOL_FLOW_PARSER_CLIENT_API_CHECK (client, expected, ...)
Value:
do {                                                                \
        if ((client)->api_version != (expected)) {                      \
            SOL_WRN("Invalid " # client " %p API version(%lu), "         \
                "expected " # expected "(%lu)",                     \
                (client), (client)->api_version, (expected));       \
            return __VA_ARGS__;                                         \
        }                                                               \
    } while (0)
Referenced by sol_flow_parser_new().
Function Documentation
SOL_API sol_flow_metatype_generate_code_func sol_flow_metatype_get_generate_code_end_func (const struct sol_str_slice name)
References composed_metatype_constructor_generate_code_end(), composed_metatype_splitter_generate_code_end(), sol_flow_metatype::generate_type_end, and get_dynamic_metatype().
SOL_API sol_flow_metatype_generate_code_func sol_flow_metatype_get_generate_code_start_func (const struct sol_str_slice name)
References composed_metatype_constructor_generate_code_start(), composed_metatype_splitter_generate_code_start(), sol_flow_metatype::generate_type_start, and get_dynamic_metatype().
SOL_API sol_flow_metatype_generate_code_func sol_flow_metatype_get_generate_code_type_func (const struct sol_str_slice name)
References composed_metatype_constructor_generate_code_type(), composed_metatype_splitter_generate_code_type(), sol_flow_metatype::generate_type_body, and get_dynamic_metatype().
SOL_API sol_flow_metatype_ports_description_func sol_flow_metatype_get_ports_description_func (const struct sol_str_slice name)
References composed_metatype_constructor_get_ports_description(), composed_metatype_splitter_get_ports_description(), get_dynamic_metatype(), and sol_flow_metatype::ports_description.
SOL_API struct sol_flow_node_type* sol_flow_parse_buffer (struct sol_flow_parser * parser, const char * buf, size_t len, const char * filename)
References sol_str_slice::data, sol_flow_node_type_del(), SOL_INT_CHECK, SOL_NULL_CHECK, sol_ptr_vector_append(), and sol_flow_parser::types.
Referenced by runner_new_from_file(), sol_flow_parse_buffer_metatype(), and sol_flow_parse_string().
SOL_API struct sol_flow_node_type* sol_flow_parse_buffer_metatype (struct sol_flow_parser * parser, const char * metatype, const char * buf, size_t len, const char * filename)
References metatype_context_internal::base, metatype_context_with_buf::base, metatype_context_with_buf::buf, sol_flow_metatype_context::contents, metatype_context_with_buf::filename, metatype_context_with_buf::len, sol_flow_metatype_context::name, sol_flow_metatype_context::read_file, SOL_ERR, sol_flow_parse_buffer(), SOL_INT_CHECK, SOL_NULL_CHECK, and streq.
Referenced by sol_flow_parse_string_metatype().
SOL_API struct sol_flow_node_type* sol_flow_parse_string (struct sol_flow_parser * parser, const char * cstr, const char * filename)
References sol_flow_parse_buffer().
SOL_API struct sol_flow_node_type* sol_flow_parse_string_metatype (struct sol_flow_parser * parser, const char * metatype, const char * str, const char * filename)
References sol_flow_parse_buffer_metatype(), and SOL_NULL_CHECK.
SOL_API int sol_flow_parser_del (struct sol_flow_parser * parser)
References sol_flow_node_type_del(), SOL_NULL_CHECK, SOL_PTR_VECTOR_FOREACH_REVERSE_IDX, and sol_flow_parser::types.
Referenced by runner_del().
SOL_API struct sol_flow_parser* sol_flow_parser_new (const struct sol_flow_parser_client * client, const struct sol_flow_resolver * resolver)
References sol_flow_parser::builtins_resolver, sol_flow_parser::client, sol_flow_parser::resolver, sol_flow_get_builtins_resolver(), sol_flow_get_default_resolver(), SOL_FLOW_PARSER_CLIENT_API_CHECK, SOL_FLOW_PARSER_CLIENT_API_VERSION, and sol_flow_parser::types.
Referenced by runner_new_from_file().