Soletta: src/lib/common/sol-platform.c File Reference
sol-platform.c File Reference
#include <errno.h>
#include <stdbool.h>
#include <stdlib.h>
#include <ctype.h>
#include "sol-platform-impl.h"
#include "sol-log-internal.h"
#include "sol-macros.h"
#include "sol-monitors.h"
#include "sol-platform.h"
#include "sol-util.h"
Data Structures
struct ctx
struct service_monitor
Macros
#define SOL_BOARD_NAME_ENVVAR "SOL_BOARD_NAME"
Functions
SOL_LOG_INTERNAL_DECLARE (_sol_platform_log_domain,"platform")
SOL_API int sol_platform_add_service_monitor (void(*cb)(void *data, const char *service, enum sol_platform_service_state state), const char *service, const void *data)
SOL_API int sol_platform_add_state_monitor (void(*cb)(void *data, enum sol_platform_state state), const void *data)
SOL_API int sol_platform_del_service_monitor (void(*cb)(void *data, const char *service, enum sol_platform_service_state state), const char *service, const void *data)
SOL_API int sol_platform_del_state_monitor (void(*cb)(void *data, enum sol_platform_state state), const void *data)
SOL_API const char * sol_platform_get_board_name (void)
SOL_API const char * sol_platform_get_machine_id (void)
SOL_API const char * sol_platform_get_os_version (void)
SOL_API const char * sol_platform_get_serial_number (void)
SOL_API enum
sol_platform_service_state sol_platform_get_service_state (const char *service)
SOL_API int sol_platform_get_state (void)
SOL_API const char * sol_platform_get_sw_version (void)
void sol_platform_inform_service_monitors (const char *service, enum sol_platform_service_state state)
void sol_platform_inform_state_monitors (enum sol_platform_state state)
int sol_platform_init (void)
SOL_API int sol_platform_restart_service (const char *service)
SOL_API int sol_platform_set_target (const char *target)
void sol_platform_shutdown (void)
SOL_API int sol_platform_start_service (const char *service)
SOL_API int sol_platform_stop_service (const char *service)
Macro Definition Documentation
#define SOL_BOARD_NAME_ENVVAR "SOL_BOARD_NAME"
Referenced by sol_platform_get_board_name().
Function Documentation
SOL_LOG_INTERNAL_DECLARE (_sol_platform_log_domain , "platform")
void sol_platform_inform_service_monitors (const char * service, enum sol_platform_service_state state)
References service_monitor::base, sol_monitors_entry::cb, sol_monitors_entry::data, service_monitor::service, ctx::service_monitors, SOL_MONITORS_WALK, service_monitor::state, and streq.
Referenced by sol_platform_linux_micro_inform_service_state().
void sol_platform_inform_state_monitors (enum sol_platform_state state)
References sol_monitors_entry::cb, sol_monitors_entry::data, SOL_MONITORS_WALK, and ctx::state_monitors.
int sol_platform_init (void)
References ctx::service_monitors, SOL_LOG_DOMAIN, sol_log_domain_init_level(), sol_monitors_init_custom(), sol_platform_impl_init(), and ctx::state_monitors.
Referenced by sol_init().
void sol_platform_shutdown (void)
References ctx::service_monitors, sol_monitors_clear(), sol_platform_impl_shutdown(), and ctx::state_monitors.
Referenced by sol_init(), and sol_shutdown().