Soletta: src/lib/flow/include/sol-flow-builder.h File Reference
sol-flow-builder.h File Reference
#include <stdbool.h>
#include "sol-flow.h"
Functions
int sol_flow_builder_add_node (struct sol_flow_builder *builder, const char *name, const struct sol_flow_node_type *type, const struct sol_flow_node_options *option)
int sol_flow_builder_add_node_by_type (struct sol_flow_builder *builder, const char *name, const char *type_name, const char *const *options_strv)
int sol_flow_builder_connect (struct sol_flow_builder *builder, const char *src_name, const char *src_port_name, int src_port_idx, const char *dst_name, const char *dst_port_name, int dst_port_idx)
int sol_flow_builder_connect_by_index (struct sol_flow_builder *builder, const char *src_name, uint16_t src_port_index, const char *dst_name, uint16_t dst_port_index)
int sol_flow_builder_del (struct sol_flow_builder *builder)
int sol_flow_builder_export_in_port (struct sol_flow_builder *builder, const char *node_name, const char *port_name, int port_idx, const char *exported_name)
int sol_flow_builder_export_option (struct sol_flow_builder *builder, const char *node_name, const char *option_name, const char *exported_name)
int sol_flow_builder_export_out_port (struct sol_flow_builder *builder, const char *node_name, const char *port_name, int port_idx, const char *exported_name)
struct sol_flow_node_type * sol_flow_builder_get_node_type (struct sol_flow_builder *builder)
struct sol_flow_builder * sol_flow_builder_new (void)
void sol_flow_builder_set_resolver (struct sol_flow_builder *builder, const struct sol_flow_resolver *resolver)
int sol_flow_builder_set_type_description (struct sol_flow_builder *builder, const char *name, const char *category, const char *description, const char *author, const char *url, const char *license, const char *version)
Function Documentation
int sol_flow_builder_add_node (struct sol_flow_builder * builder, const char * name, const struct sol_flow_node_type * type, const struct sol_flow_node_options * option)
Referenced by startup().
int sol_flow_builder_add_node_by_type (struct sol_flow_builder * builder, const char * name, const char * type_name, const char *const * options_strv)
Referenced by startup().
int sol_flow_builder_connect (struct sol_flow_builder * builder, const char * src_name, const char * src_port_name, int src_port_idx, const char * dst_name, const char * dst_port_name, int dst_port_idx)
Referenced by startup().
int sol_flow_builder_connect_by_index (struct sol_flow_builder * builder, const char * src_name, uint16_t src_port_index, const char * dst_name, uint16_t dst_port_index)
int sol_flow_builder_del (struct sol_flow_builder * builder)
Referenced by shutdown(), and startup().
int sol_flow_builder_export_in_port (struct sol_flow_builder * builder, const char * node_name, const char * port_name, int port_idx, const char * exported_name)
int sol_flow_builder_export_option (struct sol_flow_builder * builder, const char * node_name, const char * option_name, const char * exported_name)
int sol_flow_builder_export_out_port (struct sol_flow_builder * builder, const char * node_name, const char * port_name, int port_idx, const char * exported_name)
struct sol_flow_node_type* sol_flow_builder_get_node_type (struct sol_flow_builder * builder)
Referenced by startup().
struct sol_flow_builder* sol_flow_builder_new (void)
Referenced by startup().
void sol_flow_builder_set_resolver (struct sol_flow_builder * builder, const struct sol_flow_resolver * resolver)
int sol_flow_builder_set_type_description (struct sol_flow_builder * builder, const char * name, const char * category, const char * description, const char * author, const char * url, const char * license, const char * version)