Soletta: src/lib/io/include/sol-i2c.h File Reference
sol-i2c.h File Reference
These routines are used for I2C access under Soletta.
#include <stdbool.h>
#include <stdint.h>
#include <sys/types.h>
#include <sol-macros.h>
#include <sol-buffer.h>
enum sol_i2c_speed {
SOL_I2C_SPEED_10KBIT = 0, SOL_I2C_SPEED_100KBIT, SOL_I2C_SPEED_400KBIT, SOL_I2C_SPEED_1MBIT,
SOL_I2C_SPEED_3MBIT_400KBIT
}
struct sol_i2c * sol_i2c_open_raw (uint8_t bus, enum sol_i2c_speed speed) SOL_ATTR_WARN_UNUSED_RESULT
struct sol_i2c * sol_i2c_open (uint8_t bus, enum sol_i2c_speed speed) SOL_ATTR_WARN_UNUSED_RESULT
void sol_i2c_close (struct sol_i2c *i2c)
void sol_i2c_close_raw (struct sol_i2c *i2c)
bool sol_i2c_set_slave_address (struct sol_i2c *i2c, uint8_t slave_address)
uint8_t sol_i2c_get_slave_address (struct sol_i2c *i2c)
struct sol_i2c_pending * sol_i2c_write_quick (struct sol_i2c *i2c, bool rw, void(*write_quick_cb)(void *cb_data, struct sol_i2c *i2c, ssize_t status), const void *cb_data)
struct sol_i2c_pending * sol_i2c_read (struct sol_i2c *i2c, uint8_t *data, size_t count, void(*read_cb)(void *cb_data, struct sol_i2c *i2c, uint8_t *data, ssize_t status), const void *cb_data)
struct sol_i2c_pending * sol_i2c_write (struct sol_i2c *i2c, uint8_t *data, size_t count, void(*write_cb)(void *cb_data, struct sol_i2c *i2c, uint8_t *data, ssize_t status), const void *cb_data)
struct sol_i2c_pending * sol_i2c_read_register (struct sol_i2c *i2c, uint8_t reg, uint8_t *data, size_t count, void(*read_reg_cb)(void *cb_data, struct sol_i2c *i2c, uint8_t reg, uint8_t *data, ssize_t status), const void *cb_data)
struct sol_i2c_pending * sol_i2c_write_register (struct sol_i2c *i2c, uint8_t reg, const uint8_t *data, size_t count, void(*write_reg_cb)(void *cb_data, struct sol_i2c *i2c, uint8_t reg, uint8_t *data, ssize_t status), const void *cb_data)
struct sol_i2c_pending * sol_i2c_read_register_multiple (struct sol_i2c *i2c, uint8_t reg, uint8_t *values, size_t count, uint8_t times, void(*read_reg_multiple_cb)(void *cb_data, struct sol_i2c *i2c, uint8_t reg, uint8_t *data, ssize_t status), const void *cb_data)
bool sol_i2c_busy (struct sol_i2c *i2c)
uint8_t sol_i2c_bus_get (const struct sol_i2c *i2c)
void sol_i2c_pending_cancel (struct sol_i2c *i2c, struct sol_i2c_pending *pending)
Detailed Description
These routines are used for I2C access under Soletta.
Enumeration Type Documentation
enum sol_i2c_speed
Enumerator
SOL_I2C_SPEED_10KBIT
SOL_I2C_SPEED_100KBIT
SOL_I2C_SPEED_400KBIT
SOL_I2C_SPEED_1MBIT
SOL_I2C_SPEED_3MBIT_400KBIT
Function Documentation
uint8_t sol_i2c_bus_get (const struct sol_i2c * i2c)
Get the I2C bus id
Parameters
i2c The I2C bus handle
Returns
the bus id
References sol_i2c::bus, sol_i2c::dev, and SOL_NULL_CHECK.
Referenced by am2315_open(), and sol_i2c_open().
bool sol_i2c_busy (struct sol_i2c * i2c)
Return true if I2C bus is busy, processing another operation. This function should be called before call any other I2C function.
Parameters
i2c The I2C bus handle
Returns
true is busy or false if idle
References sol_i2c::async, SOL_NULL_CHECK, and sol_i2c::timeout.
void sol_i2c_close (struct sol_i2c * i2c)
Close an I2C bus.
Parameters
i2c bus The I2C bus handle to close
References sol_i2c_shared::i2c, sol_i2c_shared::refcount, sol_i2c_close_raw(), SOL_NULL_CHECK, sol_vector_del(), and SOL_VECTOR_FOREACH_IDX.
Referenced by am2315_close(), am2315_open(), and sol_i2c_open().
void sol_i2c_close_raw (struct sol_i2c * i2c)
Close an I2C bus.
Parameters
i2c bus The I2C bus handle to close
Note
This call will not remove this I2C handle from cache. Use sol_i2c_close() for that.
References sol_i2c::async, sol_i2c::dev, sol_i2c_pending_cancel(), SOL_NULL_CHECK, and sol_i2c::timeout.
Referenced by sol_i2c_close().
uint8_t sol_i2c_get_slave_address (struct sol_i2c * i2c)
Get the (slave) device address set on an I2C bus (to deliver I2C commands)
Parameters
i2c bus The I2C bus handle
Returns
The slave device address set on bus. 0x0 means bus was not set to any device yet
References sol_i2c::addr, sol_i2c::slave_address, and SOL_NULL_CHECK.
struct sol_i2c* sol_i2c_open (uint8_t bus, enum sol_i2c_speed speed)
Open an I2C bus.
Parameters
bus The I2C bus number to open
speed The speed to open I2C bus bus at
Returns
A new I2C bus handle
Note
This call will attempt to make pin muxing operations underneath, for the given platform that the code is running in. Use sol_i2c_open_raw() if you want to skip any pin mux operation.
The same I2C bus is shared between every user, so only the first one opening the bus will be able to set the bus speed, if some I2C slave device need to work in lower speed you need to change it on every other user of the bus.
References sol_i2c_shared::i2c, sol_i2c_shared::refcount, SOL_ERR, sol_i2c_bus_get(), sol_i2c_close(), sol_i2c_open_raw(), SOL_LOG_INTERNAL_INIT_ONCE, SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, sol_pin_mux_setup_i2c(), sol_vector_append(), and SOL_VECTOR_FOREACH_IDX.
Referenced by am2315_open().
struct sol_i2c* sol_i2c_open_raw (uint8_t bus, enum sol_i2c_speed speed)
Open an I2C bus.
Parameters
bus The I2C bus number to open
speed The speed to open I2C bus bus at
Returns
A new I2C bus handle
Note
This call won't attempt to make any pin muxing operations underneath. Use sol_i2c_open() for that, also this will not cache this I2C or try get an previous cached I2C handle.
References sol_i2c::bus, sol_i2c::dev, sol_i2c::plain_i2c, SOL_LOG_INTERNAL_INIT_ONCE, SOL_NULL_CHECK, and SOL_WRN.
Referenced by sol_i2c_open().
void sol_i2c_pending_cancel (struct sol_i2c * i2c, struct sol_i2c_pending * pending)
Cancel a pending operation.
Parameters
i2c the I2C bus handle
pending the operation handle
References sol_i2c::async, i2c_create_device::dev_name, i2c_create_device::dev_number, sol_i2c::dispatch, i2c_create_device::result, i2c_create_device::result_path, SOL_API, SOL_NULL_CHECK, sol_timeout_del(), sol_util_strerrora, sol_util_write_file(), sol_worker_thread_cancel(), SOL_WRN, strstartswith, SYSFS_I2C_NEW_DEVICE, and sol_i2c::timeout.
Referenced by am2315_close(), and sol_i2c_close_raw().
struct sol_i2c_pending* sol_i2c_read (struct sol_i2c * i2c, uint8_t * data, size_t count, void(*)(void *cb_data, struct sol_i2c *i2c, uint8_t *data, ssize_t status) read_cb, const void * cb_data)
Perform successive asynchronous I2C byte read operations, with no specified register
This makes count read byte I2C operations on the device bus is set to operate on, at no specific register. Some devices are so simple that this interface is enough. For others, it is a shorthand if you want to read the same register as in the previous I2C command.
Parameters
i2c bus The I2C bus handle
data The output buffer for the read operation
count The bytes count for the read operation
read_cb The callback to be called when operation finish, the status parameter should be equal to count in case of success
cb_data The first parameter of callback
Note
Caller should guarantee that data will not be freed until callback is called. Also there is no transfer queue, calling this function when there is another I2C operation running will return false.
Returns
pending handle if operation was started otherwise a NULL pointer
References sol_worker_thread_spec::api_version, sol_i2c::async, BUSY_CHECK, sol_i2c::cb_data, sol_i2c::count, sol_i2c::data, sol_i2c::dev, sol_i2c::dispatch, sol_i2c::read_write_cb, SOL_EXP_CHECK, SOL_INT_CHECK, SOL_NULL_CHECK, sol_timeout_add(), sol_worker_thread_new(), SOL_WORKER_THREAD_SPEC_API_VERSION, sol_i2c::status, and sol_i2c::timeout.
struct sol_i2c_pending* sol_i2c_read_register (struct sol_i2c * i2c, uint8_t reg, uint8_t * data, size_t count, void(*)(void *cb_data, struct sol_i2c *i2c, uint8_t reg, uint8_t *data, ssize_t status) read_reg_cb, const void * cb_data)
Perform a asynchronous I2C read operation on a given device register
Parameters
i2c bus The I2C bus handle
reg The I2C register for the read operation
data The output buffer for the read operation
count The bytes count for the read operation
read_reg_cb The callback to be called when operation finish, the status parameter should be equal to count in case of success
cb_data The first parameter of callback
Note
Caller should guarantee that data will not be freed until callback is called. Also there is no transfer queue, calling this function when there is another I2C operation running will return false.
Returns
pending handle if operation was started otherwise a NULL pointer
References sol_worker_thread_spec::api_version, sol_i2c::async, BUSY_CHECK, sol_i2c::cb_data, sol_i2c::count, sol_i2c::data, sol_i2c::dev, sol_i2c::dispatch, sol_i2c::read_write_reg_cb, sol_i2c::reg, SOL_EXP_CHECK, SOL_INT_CHECK, SOL_NULL_CHECK, sol_timeout_add(), sol_worker_thread_new(), SOL_WORKER_THREAD_SPEC_API_VERSION, sol_i2c::status, and sol_i2c::timeout.
struct sol_i2c_pending* sol_i2c_read_register_multiple (struct sol_i2c * i2c, uint8_t reg, uint8_t * values, size_t count, uint8_t times, void(*)(void *cb_data, struct sol_i2c *i2c, uint8_t reg, uint8_t *data, ssize_t status) read_reg_multiple_cb, const void * cb_data)
Asynchronous read of an arbitrary number of bytes from a register in repeated bursts of a given length (that start always on the provided register address)
This is so because a lot of devices will, after a read operation, update its register values with new data to be read on subsequent operations, until the total data length the user requested is read. If the device has the auto-increment feature, sol_i2c_read_register() might be a better call than this function.
This will issue multiple I2C read/write transactions with the first (write) message specifying the register to operate on and the second (read) message specifying the length (always len per read) and the destination of the read operation.
Parameters
i2c bus The I2C bus handle
reg The register to start reading from
values Where to store the read bytes
count The size of a single read block
times How many reads of size len to perform (on success, len * times bytes will be read)
read_reg_multiple_cb The callback to be called when operation finish, the status parameter should be equal to count in case of success
cb_data The first parameter of callback
Note
Caller should guarantee that data will not be freed until callback is called. Also there is no transfer queue, calling this function when there is another I2C operation running will return false.
Returns
pending handle if operation was started otherwise a NULL pointer
References sol_worker_thread_spec::api_version, sol_i2c::async, BUSY_CHECK, sol_i2c::cb_data, sol_i2c::count, sol_i2c::data, sol_i2c::dev, sol_i2c::dispatch, sol_i2c::read_write_reg_cb, sol_i2c::reg, SOL_EXP_CHECK, SOL_INT_CHECK, SOL_NULL_CHECK, sol_timeout_add(), sol_worker_thread_new(), SOL_WORKER_THREAD_SPEC_API_VERSION, sol_i2c::status, sol_i2c::timeout, and sol_i2c::times.
bool sol_i2c_set_slave_address (struct sol_i2c * i2c, uint8_t slave_address)
Set a (slave) device address on a I2C bus to deliver commands to.
All other I2C functions, after this call, will act on the given slave_address device address. Since other I2C calls might happen in between your own ones, though, it's highly advisable that you issue this call before using any of the I2C read/write functions.
Parameters
i2c bus The I2C bus handle
slave_address The slave device address to deliver commands to
Returns
true on success, false otherwise.
References sol_i2c::addr, sol_i2c::async, sol_i2c::bus, BUSY_CHECK, sol_i2c::dev, sol_i2c::slave_address, SOL_EXP_CHECK, SOL_NULL_CHECK, SOL_WRN, and sol_i2c::timeout.
struct sol_i2c_pending* sol_i2c_write (struct sol_i2c * i2c, uint8_t * data, size_t count, void(*)(void *cb_data, struct sol_i2c *i2c, uint8_t *data, ssize_t status) write_cb, const void * cb_data)
Perform successive asynchronous I2C byte write operations, with no specified register
This makes count write byte I2C operations on the device bus is set to operate on, at no specific register. Some devices are so simple that this interface is enough. For others, it is a shorthand if you want to write the same register as in the previous I2C command.
Parameters
i2c bus The I2C bus handle
data The output buffer for the write operation
count The bytes count for the write operation
write_cb The callback to be called when operation finish, the status parameter should be equal to count in case of success
cb_data The first parameter of callback
Note
Caller should guarantee that data will not be freed until callback is called. Also there is no transfer queue, calling this function when there is another I2C operation running will return false.
Returns
pending handle if operation was started otherwise a NULL pointer
References sol_worker_thread_spec::api_version, sol_i2c::async, BUSY_CHECK, sol_i2c::cb_data, sol_i2c::count, sol_i2c::data, sol_i2c::dev, sol_i2c::dispatch, sol_i2c::read_write_cb, SOL_EXP_CHECK, SOL_INT_CHECK, SOL_NULL_CHECK, sol_timeout_add(), sol_worker_thread_new(), SOL_WORKER_THREAD_SPEC_API_VERSION, sol_i2c::status, and sol_i2c::timeout.
struct sol_i2c_pending* sol_i2c_write_quick (struct sol_i2c * i2c, bool rw, void(*)(void *cb_data, struct sol_i2c *i2c, ssize_t status) write_quick_cb, const void * cb_data)
Perform a I2C write quick operation
This sends a single bit to a device (command designed to turn on and off simple devices)
Parameters
i2c The I2C bus handle
rw The value to write
write_quick_cb The callback to be issued when the operation finishes. The status parameter should be equal to one in case of success
cb_data Data to be passed to write_quick_cb
Returns
pending handle if operation was started otherwise a NULL pointer
References sol_worker_thread_spec::api_version, sol_i2c::async, BUSY_CHECK, sol_i2c::cb_data, sol_i2c::data, sol_i2c::dev, sol_i2c::dispatch, SOL_CRI, SOL_INT_CHECK, SOL_NULL_CHECK, sol_timeout_add(), sol_worker_thread_new(), SOL_WORKER_THREAD_SPEC_API_VERSION, sol_i2c::status, sol_i2c::timeout, and sol_i2c::write_quick_cb.
struct sol_i2c_pending* sol_i2c_write_register (struct sol_i2c * i2c, uint8_t reg, const uint8_t * data, size_t count, void(*)(void *cb_data, struct sol_i2c *i2c, uint8_t reg, uint8_t *data, ssize_t status) write_reg_cb, const void * cb_data)
Perform a asynchronous I2C write operation on a given device register
Parameters
i2c bus The I2C bus handle
reg The I2C register for the write operation
data The output buffer for the write operation
count The bytes count for the write operation
write_reg_cb The callback to be called when operation finish, the status parameter should be equal to count in case of success
cb_data The first parameter of callback
Note
Caller should guarantee that data will not be freed until callback is called. Also there is no transfer queue, calling this function when there is another I2C operation running will return false.
Returns
pending handle if operation was started otherwise a NULL pointer
References sol_worker_thread_spec::api_version, sol_i2c::async, BUSY_CHECK, sol_i2c::cb_data, sol_i2c::count, sol_i2c::data, sol_i2c::dev, sol_i2c::dispatch, sol_i2c::read_write_reg_cb, sol_i2c::reg, SOL_EXP_CHECK, SOL_INT_CHECK, SOL_NULL_CHECK, sol_timeout_add(), sol_worker_thread_new(), SOL_WORKER_THREAD_SPEC_API_VERSION, sol_i2c::status, and sol_i2c::timeout.