Soletta: src/lib/common/sol-mainloop-impl-contiki.c File Reference
sol-mainloop-impl-contiki.c File Reference
#include <contiki.h>
#include <lib/sensors.h>
#include "sol-event-handler-contiki.h"
#include "sol-mainloop-common.h"
#include "sol-mainloop-contiki.h"
#include "sol-mainloop-impl.h"
#include "sol-vector.h"
Data Structures
struct sol_event_handler_contiki
Macros
#define DEFAULT_USLEEP_TIME 10000
#define DEFAULT_USLEEP_TIME_TICKS (CLOCK_SECOND * DEFAULT_USLEEP_TIME) / NSEC_PER_SEC
Functions
bool sol_mainloop_contiki_event_handler_add (const process_event_t *ev, const process_data_t ev_data, void(*cb)(void *user_data, process_event_t ev, process_data_t ev_data), const void *data)
bool sol_mainloop_contiki_event_handler_del (const process_event_t *ev, const process_data_t ev_data, void(*cb)(void *user_data, process_event_t ev, process_data_t ev_data), const void *data)
void sol_mainloop_contiki_event_set (process_event_t ev, process_data_t data)
bool sol_mainloop_contiki_iter (void)
void sol_mainloop_impl_iter (void)
void sol_mainloop_impl_lock (void)
bool sol_mainloop_impl_main_thread_check (void)
void sol_mainloop_impl_main_thread_notify (void)
int sol_mainloop_impl_platform_init (void)
void sol_mainloop_impl_platform_shutdown (void)
void sol_mainloop_impl_run (void)
void sol_mainloop_impl_unlock (void)
Macro Definition Documentation
#define DEFAULT_USLEEP_TIME 10000
#define DEFAULT_USLEEP_TIME_TICKS (CLOCK_SECOND * DEFAULT_USLEEP_TIME) / NSEC_PER_SEC
Function Documentation
bool sol_mainloop_contiki_event_handler_add (const process_event_t * ev, const process_data_t ev_data, void(*)(void *user_data, process_event_t ev, process_data_t ev_data) cb, const void * data)
References sol_event_handler_contiki::cb, sol_event_handler_contiki::delete_me, sol_event_handler_contiki::ev, sol_event_handler_contiki::ev_data, sol_ptr_vector_append(), and sol_event_handler_contiki::user_data.
Referenced by sol_gpio_open_raw().
bool sol_mainloop_contiki_event_handler_del (const process_event_t * ev, const process_data_t ev_data, void(*)(void *user_data, process_event_t ev, process_data_t ev_data) cb, const void * data)
References sol_event_handler_contiki::cb, sol_event_handler_contiki::delete_me, sol_event_handler_contiki::ev, sol_event_handler_contiki::ev_data, SOL_PTR_VECTOR_FOREACH_IDX, and sol_event_handler_contiki::user_data.
Referenced by sol_gpio_close().
void sol_mainloop_contiki_event_set (process_event_t ev, process_data_t data)
bool sol_mainloop_contiki_iter (void)
References sol_mainloop_common_idler_process(), sol_mainloop_common_loop_check(), and sol_mainloop_common_timeout_process().
void sol_mainloop_impl_iter (void)
void sol_mainloop_impl_lock (void)
bool sol_mainloop_impl_main_thread_check (void)
Referenced by sol_mainloop_impl_run().
void sol_mainloop_impl_main_thread_notify (void)
int sol_mainloop_impl_platform_init (void)
void sol_mainloop_impl_platform_shutdown (void)
References sol_mainloop_common_source_shutdown(), and SOL_PTR_VECTOR_FOREACH_IDX.
void sol_mainloop_impl_run (void)
References SOL_ERR, sol_mainloop_common_loop_set(), and sol_mainloop_impl_main_thread_check().
void sol_mainloop_impl_unlock (void)