Soletta: src/lib/common/sol-mainloop-common.c File Reference
sol-mainloop-common.c File Reference
#include <stdbool.h>
#include <stdlib.h>
#include <unistd.h>
#include "sol-vector.h"
#include "sol-mainloop-impl.h"
#include "sol-mainloop-common.h"
Data Structures
struct sol_mainloop_source_common
Macros
#define IDLER_ACUM idler_vector
#define IDLER_PROCESS idler_vector
#define SOURCE_ACUM source_vector
#define SOURCE_PROCESS source_vector
#define TIMEOUT_ACUM timeout_vector
#define TIMEOUT_PROCESS timeout_vector
#define timeout_vector_update(...) do { } while (0)
Functions
struct sol_idler_common * sol_mainloop_common_idler_first (void)
void sol_mainloop_common_idler_process (void)
bool sol_mainloop_common_loop_check (void)
void sol_mainloop_common_loop_set (bool val)
bool sol_mainloop_common_source_check (void)
void sol_mainloop_common_source_dispatch (void)
bool sol_mainloop_common_source_get_next_timeout (struct timespec *timeout)
bool sol_mainloop_common_source_prepare (void)
void sol_mainloop_common_source_shutdown (void)
void sol_mainloop_common_timeout_process (void)
bool sol_mainloop_common_timespec_first (struct timespec *ts)
void * sol_mainloop_impl_idle_add (bool(*cb)(void *data), const void *data)
bool sol_mainloop_impl_idle_del (void *handle)
int sol_mainloop_impl_init (void)
void sol_mainloop_impl_quit (void)
void sol_mainloop_impl_run (void)
void sol_mainloop_impl_shutdown (void)
void sol_mainloop_impl_source_del (void *handle)
void * sol_mainloop_impl_source_get_data (const void *handle)
void * sol_mainloop_impl_source_new (const struct sol_mainloop_source_type *type, const void *data)
void * sol_mainloop_impl_timeout_add (unsigned int timeout_ms, bool(*cb)(void *data), const void *data)
bool sol_mainloop_impl_timeout_del (void *handle)
Macro Definition Documentation
#define IDLER_ACUM idler_vector
Referenced by sol_mainloop_common_idler_process().
#define IDLER_PROCESS idler_vector
Referenced by sol_mainloop_common_idler_process().
#define SOURCE_ACUM source_vector
Referenced by sol_mainloop_common_source_check(), sol_mainloop_common_source_dispatch(), and sol_mainloop_common_source_prepare().
#define SOURCE_PROCESS source_vector
Referenced by sol_mainloop_common_source_check(), sol_mainloop_common_source_dispatch(), and sol_mainloop_common_source_prepare().
#define TIMEOUT_ACUM timeout_vector
Referenced by sol_mainloop_common_timeout_process().
#define TIMEOUT_PROCESS timeout_vector
Referenced by sol_mainloop_common_timeout_process().
#define timeout_vector_update (...) do { } while (0)
Referenced by sol_mainloop_common_timeout_process().
Function Documentation
struct sol_idler_common* sol_mainloop_common_idler_first (void)
References sol_idler_common::idler_deleted, SOL_PTR_VECTOR_FOREACH_IDX, and sol_idler_common::status.
void sol_mainloop_common_idler_process (void)
References sol_idler_common::cb, sol_idler_common::data, IDLER_ACUM, sol_idler_common::idler_deleted, IDLER_PROCESS, sol_idler_common::idler_ready, sol_idler_common::idler_ready_on_next_iteration, sol_mainloop_common_loop_check(), sol_mainloop_common_timeout_process(), sol_mainloop_impl_lock(), sol_mainloop_impl_unlock(), SOL_PTR_VECTOR_FOREACH_IDX, and sol_idler_common::status.
Referenced by sol_mainloop_contiki_iter(), and sol_mainloop_impl_iter().
bool sol_mainloop_common_loop_check (void)
Referenced by sol_mainloop_common_idler_process(), sol_mainloop_common_source_check(), sol_mainloop_common_source_dispatch(), sol_mainloop_common_source_prepare(), sol_mainloop_common_timeout_process(), sol_mainloop_contiki_iter(), sol_mainloop_impl_iter(), and sol_mainloop_impl_run().
void sol_mainloop_common_loop_set (bool val)
Referenced by sol_mainloop_impl_quit(), and sol_mainloop_impl_run().
bool sol_mainloop_common_source_check (void)
References sol_mainloop_source_type::check, sol_mainloop_source_common::data, sol_mainloop_source_common::ready, sol_mainloop_source_common::remove_me, sol_mainloop_common_loop_check(), sol_mainloop_impl_lock(), sol_mainloop_impl_unlock(), SOL_PTR_VECTOR_FOREACH_IDX, SOURCE_ACUM, SOURCE_PROCESS, and sol_mainloop_source_common::type.
void sol_mainloop_common_source_dispatch (void)
References sol_mainloop_source_common::data, sol_mainloop_source_type::dispatch, sol_mainloop_source_common::ready, sol_mainloop_source_common::remove_me, sol_mainloop_common_loop_check(), sol_mainloop_impl_lock(), sol_mainloop_impl_unlock(), SOL_PTR_VECTOR_FOREACH_IDX, SOURCE_ACUM, SOURCE_PROCESS, and sol_mainloop_source_common::type.
bool sol_mainloop_common_source_get_next_timeout (struct timespec * timeout)
References sol_mainloop_impl_lock(), and sol_mainloop_impl_unlock().
bool sol_mainloop_common_source_prepare (void)
References sol_mainloop_source_common::data, sol_mainloop_source_type::prepare, sol_mainloop_source_common::ready, sol_mainloop_source_common::remove_me, sol_mainloop_common_loop_check(), sol_mainloop_impl_lock(), sol_mainloop_impl_unlock(), SOL_PTR_VECTOR_FOREACH_IDX, SOURCE_ACUM, SOURCE_PROCESS, and sol_mainloop_source_common::type.
void sol_mainloop_common_source_shutdown (void)
References sol_mainloop_source_common::data, sol_mainloop_source_type::dispose, sol_mainloop_source_common::remove_me, SOL_PTR_VECTOR_FOREACH_IDX, and sol_mainloop_source_common::type.
Referenced by sol_mainloop_impl_platform_shutdown().
void sol_mainloop_common_timeout_process (void)
References sol_timeout_common::cb, sol_timeout_common::data, sol_timeout_common::expire, sol_timeout_common::remove_me, sol_mainloop_common_loop_check(), sol_mainloop_impl_lock(), sol_mainloop_impl_unlock(), sol_ptr_vector_insert_sorted(), sol_util_timespec_get_current(), sol_timeout_common::timeout, TIMEOUT_ACUM, TIMEOUT_PROCESS, and timeout_vector_update.
Referenced by sol_mainloop_common_idler_process(), sol_mainloop_contiki_iter(), and sol_mainloop_impl_iter().
bool sol_mainloop_common_timespec_first (struct timespec * ts)
References sol_timeout_common::expire, and sol_util_timespec_get_current().
void* sol_mainloop_impl_idle_add (bool(*)(void *data) cb, const void * data)
Referenced by sol_idle_add().
bool sol_mainloop_impl_idle_del (void * handle)
Referenced by sol_idle_del().
int sol_mainloop_impl_init (void)
Referenced by sol_init().
void sol_mainloop_impl_quit (void)
Referenced by sol_quit_with_code().
void sol_mainloop_impl_run (void)
Referenced by sol_run().
void sol_mainloop_impl_shutdown (void)
Referenced by sol_init(), and sol_shutdown().
void sol_mainloop_impl_source_del (void * handle)
Referenced by sol_mainloop_source_del().
void* sol_mainloop_impl_source_get_data (const void * handle)
Referenced by sol_mainloop_source_get_data().
void* sol_mainloop_impl_source_new (const struct sol_mainloop_source_type * type, const void * data)
Referenced by sol_mainloop_source_new().
void* sol_mainloop_impl_timeout_add (unsigned int timeout_ms, bool(*)(void *data) cb, const void * data)
Referenced by sol_timeout_add().
bool sol_mainloop_impl_timeout_del (void * handle)
Referenced by sol_timeout_del().