Soletta: src/shared/sol-util.c File Reference
sol-util.c File Reference
#include <errno.h>
#include <float.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include "sol-buffer.h"
#include "sol-util.h"
#include "sol-log.h"
#include "sol-random.h"
#include "sol-str-slice.h"
Data Structures
struct sol_uuid
Macros
#define CREATE_SLICE(_str, _len)
Functions
SOL_API ssize_t sol_util_base16_decode (void *buf, size_t buflen, const struct sol_str_slice slice, enum sol_decode_case decode_case)
SOL_API ssize_t sol_util_base16_encode (void *buf, size_t buflen, const struct sol_str_slice slice, bool uppercase)
SOL_API ssize_t sol_util_base64_decode (void *buf, size_t buflen, const struct sol_str_slice slice, const char base64_map[static 65])
SOL_API ssize_t sol_util_base64_encode (void *buf, size_t buflen, const struct sol_str_slice slice, const char base64_map[static 65])
void * sol_util_memdup (const void *data, size_t len)
SOL_API int sol_util_replace_str_if_changed (char **str, const char *new_str)
struct sol_vector sol_util_str_split (const struct sol_str_slice slice, const char *delim, size_t maxsplit)
char * sol_util_strerror (int errnum, char *buf, size_t buflen)
double sol_util_strtodn (const char *nptr, char **endptr, ssize_t len, bool use_locale)
SOL_API int32_t sol_util_unicode_code_from_utf8 (const uint8_t *buf, size_t buf_len, uint8_t *bytes_read)
SOL_API int8_t sol_util_utf8_from_unicode_code (uint8_t *buf, size_t buf_len, uint32_t unicode_code)
int sol_util_uuid_gen (bool upcase, bool with_hyphens, char id[static 37])
Macro Definition Documentation
#define CREATE_SLICE (_str, _len)
Value:
do { \
        s = sol_vector_append(&v); \
        if (!s) \
            goto err; \
        s->data = _str; \
        s->len = _len; \
    } while (0)
Referenced by sol_util_str_split().
Function Documentation
SOL_API ssize_t sol_util_base16_decode (void * buf, size_t buflen, const struct sol_str_slice slice, enum sol_decode_case decode_case)
Decode the binary slice from base16 (hexadecimal).
Note
no trailing null '\0' is added!
Parameters
buf a buffer of size buflen that is big enough to hold the decoded string.
buflen the number of bytes available in buffer. Must be large enough to contain the decoded slice, that is: slice.len / 2.
slice the slice to decode, it must be a set of 0-9 or letters A-F (if uppercase) or a-f, otherwise decode fails.
decode_case if SOL_DECODE_UPERCASE, uppercase letters ABCDEF are used, if SOL_DECODE_LOWERCASE, lowercase abcdef are used instead. If SOL_DECODE_BOTH both, lowercase and uppercase, letters can be used.
Returns
the number of bytes written or -errno if failed.
References sol_str_slice::data, sol_str_slice::len, SOL_DECODE_BOTH, SOL_DECODE_UPERCASE, SOL_INT_CHECK, SOL_NULL_CHECK, SOL_WRN, and unlikely.
Referenced by sol_buffer_append_from_base16(), sol_buffer_insert_from_base16(), and sol_json_token_get_unescaped_string().
SOL_API ssize_t sol_util_base16_encode (void * buf, size_t buflen, const struct sol_str_slice slice, bool uppercase)
Encode the binary slice to base16 (hexadecimal).
Note
no trailing null '\0' is added!
Parameters
buf a buffer of size buflen that is big enough to hold the encoded string.
buflen the number of bytes available in buffer. Must be large enough to contain the encoded slice, that is: slice.len * 2
slice the slice to encode, it may contain null-bytes (\0), the whole size of the slice will be used (slice.len).
uppercase if true, uppercase letters ABCDEF are used, otherwise lowercase abcdef are used instead.
Returns
the number of bytes written or -errno if failed.
References sol_str_slice::data, sol_str_slice::len, SOL_INT_CHECK, and SOL_NULL_CHECK.
Referenced by sol_buffer_append_as_base16(), and sol_buffer_insert_as_base16().
SOL_API ssize_t sol_util_base64_decode (void * buf, size_t buflen, const struct sol_str_slice slice, const char base64_map[static 65])
Decode the binary slice from base64 using the given map.
https://en.wikipedia.org/wiki/Base64
Note
no trailing null '\0' is added!
Parameters
buf a buffer of size buflen that is big enough to hold the decoded string.
buflen the number of bytes available in buffer. Must be large enough to contain the decoded slice, that is: (slice.len / 4) * 3
slice the slice to decode, it must be composed solely of the base64_map characters or it will fail.
base64_map the map to use. The last char is used as the padding character if slice length is not multiple of 3 bytes.
Returns
the number of bytes written or -errno if failed.
References sol_str_slice::data, sol_str_slice::len, SOL_INT_CHECK, and SOL_NULL_CHECK.
Referenced by sol_buffer_append_from_base64(), and sol_buffer_insert_from_base64().
SOL_API ssize_t sol_util_base64_encode (void * buf, size_t buflen, const struct sol_str_slice slice, const char base64_map[static 65])
Encode the binary slice to base64 using the given map.
https://en.wikipedia.org/wiki/Base64
Note
no trailing null '\0' is added!
Parameters
buf a buffer of size buflen that is big enough to hold the encoded string.
buflen the number of bytes available in buffer. Must be large enough to contain the encoded slice, that is: (slice.len / 3 + 1) * 4
slice the slice to encode, it may contain null-bytes (\0), the whole size of the slice will be used (slice.len).
base64_map the map to use. The last char is used as the padding character if slice length is not multiple of 3 bytes.
Returns
the number of bytes written or -errno if failed.
References sol_str_slice::data, sol_str_slice::len, SOL_INT_CHECK, and SOL_NULL_CHECK.
Referenced by sol_buffer_append_as_base64(), and sol_buffer_insert_as_base64().
void* sol_util_memdup (const void * data, size_t len)
Referenced by sol_buffer_copy(), sol_oic_client_find_resource(), and sol_oic_client_get_server_info().
SOL_API int sol_util_replace_str_if_changed (char ** str, const char * new_str)
References SOL_NULL_CHECK.
struct sol_vector sol_util_str_split (const struct sol_str_slice slice, const char * delim, size_t maxsplit)
Return a list of the words in a given string slice, using a given delimiter string. If maxsplit is given, at most that number of splits are done (thus, the list will have at most maxsplit+1 elements). If maxsplit is zero, then there is no limit on the number of splits (all possible splits are made).
Parameters
slice The string slice to divide in sub-strings (in array of slices form)
delim The delimiter string to divide slice based on
maxsplit The maximum number of splits to make on slice. If it's 0, than make as many splits as it can.
Returns
A vector of string slices with the splitted words, on success, or NULL, otherwise.
References CREATE_SLICE, sol_vector::len, sol_vector_clear(), and SOL_VECTOR_INIT.
Referenced by sol_iio_address_device(), and string_generator_open().
char* sol_util_strerror (int errnum, char * buf, size_t buflen)
double sol_util_strtodn (const char * nptr, char ** endptr, ssize_t len, bool use_locale)
Wrapper over strtod() that consumes up to len bytes and may not use a locale.
This variation of strtod() will work with buffers that are not null-terminated.
It also offers a way to skip the currently set locale, forcing plain "C". This is required to parse numbers in formats that require '.' as the decimal point while the current locale may use ',' such as in pt_BR.
All the formats accepted by strtod() are accepted and the behavior should be the same, including using information from LC_NUMERIC if locale is configured and use_locale is true.
Parameters
nptr the string containing the number to convert.
endptr if non-NULL, it will contain the last character used in the conversion. If no conversion was done, endptr is nptr.
use_locale if true, then current locale is used, if false then "C" locale is forced.
len use at most this amount of bytes of nptr. If -1, assumes nptr has a trailing NUL and calculate the string length.
Returns
the converted value, if any. The converted value may be NAN, INF (positive or negative). See the strtod(3) documentation for the details.
References SOL_WRN, streq, streqn, strndupa, and unlikely.
Referenced by float_generator_open(), float_validator_open(), and sol_json_token_get_double().
SOL_API int32_t sol_util_unicode_code_from_utf8 (const uint8_t * buf, size_t buf_len, uint8_t * bytes_read)
Convert a utf-8 character to unicode code.
Parameters
buf Buffer with the utf-8 representation of the unicode character.
buf_len The buffer length
bytes_read Optional pointer to variable to write number of bytes read from buf.
Returns
The code from unicode table of the character in 'buf' or a negative number on error.
References SOL_INT_CHECK, SOL_NULL_CHECK, and SOL_WRN.
SOL_API int8_t sol_util_utf8_from_unicode_code (uint8_t * buf, size_t buf_len, uint32_t unicode_code)
Convert from unicode code to utf-8 string.
Write at string buf the bytes needed to represent the unicode charater informed as utf-8. One to four characters will be written on success. No character is written on error.
Note
no trailing null '\0' is added!
Parameters
buf Buffer to write the utf-8 representation of the unicode character
buf_len The buffer length
unicode_code Code from unicode table of the character to be converted
Returns
The number of bytes written in 'buf' or a negative number on error.
References SOL_INT_CHECK, and SOL_NULL_CHECK.
Referenced by sol_json_token_get_unescaped_string().
int sol_util_uuid_gen (bool upcase, bool with_hyphens, char id[static 37])
Generates a new universally unique identifier (UUID), in string form, which is 16 bytes-long (128 bits) long and conforms to v4 UUIDs (generated from random—or pseudo-random—numbers).
Parameters
upcase Whether to generate the UUID in upcase or not
with_hyphens Format the resulting UUID string with hyphens (e.g. "de305d54-75b4-431b-adb2-eb6b9e546014") or without them.
id Where to store the generated id. It's 37 bytes in lenght so it accomodates the maximum lenght case – 2 * 16 (chars) + 4 (hyphens) + 1 (\0)
Returns
0 on success, negative error code otherwise.
References ARRAY_SIZE, sol_uuid::bytes, SOL_BUFFER_FLAGS_MEMORY_NOT_OWNED, sol_buffer_insert_slice(), SOL_INT_CHECK, SOL_INT_CHECK_GOTO, and SOL_STR_SLICE_LITERAL.
Referenced by string_uuid_gen().