Soletta: src/lib/flow/include/sol-flow-metatype.h File Reference
sol-flow-metatype.h File Reference
#include "sol-flow.h"
#include "sol-str-slice.h"
#include "sol-buffer.h"
#include "sol-vector.h"
#include <stdbool.h>
Data Structures
struct sol_flow_metatype
struct sol_flow_metatype_context
struct sol_flow_metatype_port_description
Macros
#define SOL_FLOW_METATYPE(_NAME, decl...)
#define SOL_FLOW_METATYPE_API_VERSION (1)
Typedefs
typedef int(* sol_flow_metatype_create_type_func)(const struct sol_flow_metatype_context *, struct sol_flow_node_type **)
typedef int(* sol_flow_metatype_generate_code_func)(struct sol_buffer *, const struct sol_str_slice, const struct sol_str_slice)
typedef int(* sol_flow_metatype_ports_description_func)(const struct sol_str_slice, struct sol_vector *, struct sol_vector *)
Functions
sol_flow_metatype_generate_code_func sol_flow_metatype_get_generate_code_end_func (const struct sol_str_slice)
sol_flow_metatype_generate_code_func sol_flow_metatype_get_generate_code_start_func (const struct sol_str_slice)
sol_flow_metatype_generate_code_func sol_flow_metatype_get_generate_code_type_func (const struct sol_str_slice)
sol_flow_metatype_ports_description_func sol_flow_metatype_get_ports_description_func (const struct sol_str_slice)
Macro Definition Documentation
#define SOL_FLOW_METATYPE (_NAME, decl...)
Value:
const struct sol_flow_metatype SOL_FLOW_METATYPE_ ## _NAME = { \
        .api_version = SOL_FLOW_METATYPE_API_VERSION, \
        decl \
    }
#define SOL_FLOW_METATYPE_API_VERSION (1)
Typedef Documentation
typedef int(* sol_flow_metatype_create_type_func)(const struct sol_flow_metatype_context *, struct sol_flow_node_type **)
typedef int(* sol_flow_metatype_generate_code_func)(struct sol_buffer *, const struct sol_str_slice, const struct sol_str_slice)
typedef int(* sol_flow_metatype_ports_description_func)(const struct sol_str_slice, struct sol_vector *, struct sol_vector *)
Function Documentation
sol_flow_metatype_generate_code_func sol_flow_metatype_get_generate_code_end_func (const struct sol_str_slice)
References composed_metatype_constructor_generate_code_end(), composed_metatype_splitter_generate_code_end(), sol_flow_metatype::generate_type_end, and get_dynamic_metatype().
sol_flow_metatype_generate_code_func sol_flow_metatype_get_generate_code_start_func (const struct sol_str_slice)
References composed_metatype_constructor_generate_code_start(), composed_metatype_splitter_generate_code_start(), sol_flow_metatype::generate_type_start, and get_dynamic_metatype().
sol_flow_metatype_generate_code_func sol_flow_metatype_get_generate_code_type_func (const struct sol_str_slice)
References composed_metatype_constructor_generate_code_type(), composed_metatype_splitter_generate_code_type(), sol_flow_metatype::generate_type_body, and get_dynamic_metatype().
sol_flow_metatype_ports_description_func sol_flow_metatype_get_ports_description_func (const struct sol_str_slice)
References composed_metatype_constructor_get_ports_description(), composed_metatype_splitter_get_ports_description(), get_dynamic_metatype(), and sol_flow_metatype::ports_description.