Soletta: src/lib/common/sol-log-impl-linux.c File Reference
sol-log-impl-linux.c File Reference
#include <ctype.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <syslog.h>
#include "sol-str-table.h"
#include "sol-log-impl.h"
#include "sol-util.h"
Macros
#define SPEC(str, storage, parse)
Functions
void sol_log_impl_domain_init_level (struct sol_log_domain *domain)
int sol_log_impl_init (void)
bool sol_log_impl_lock (void)
void sol_log_impl_print_function_stderr (void *data, const struct sol_log_domain *domain, uint8_t message_level, const char *file, const char *function, int line, const char *format, va_list args)
void sol_log_impl_shutdown (void)
void sol_log_impl_unlock (void)
SOL_API void sol_log_print_function_file (void *data, const struct sol_log_domain *domain, uint8_t message_level, const char *file, const char *function, int line, const char *format, va_list args)
SOL_API void sol_log_print_function_journal (void *data, const struct sol_log_domain *domain, uint8_t message_level, const char *file, const char *function, int line, const char *format, va_list args)
SOL_API void sol_log_print_function_syslog (void *data, const struct sol_log_domain *domain, uint8_t message_level, const char *file, const char *function, int line, const char *format, va_list args)
Macro Definition Documentation
#define SPEC (str, storage, parse)
Value:
{ str, sizeof(str) - 1, storage, parse \
    }
Function Documentation
void sol_log_impl_domain_init_level (struct sol_log_domain * domain)
References _global_domain, sol_log_domain::level, sol_log_domain::name, and sol_str_table_lookup.
int sol_log_impl_init (void)
References _abort_level, _global_domain, _print_function, _print_function_data, _show_colors, _show_file, _show_function, _show_line, sol_log_domain::level, sol_log_print_function_journal(), sol_log_print_function_stderr(), sol_log_print_function_syslog(), and streq.
bool sol_log_impl_lock (void)
void sol_log_impl_print_function_stderr (void * data, const struct sol_log_domain * domain, uint8_t message_level, const char * file, const char * function, int line, const char * format, va_list args)
References _show_colors, _show_file, _show_function, _show_line, sol_log_domain::color, name, sol_log_domain::name, SOL_LOG_COLOR_HIGH, SOL_LOG_COLOR_RESET, sol_log_get_level_color(), and sol_log_level_to_str().
void sol_log_impl_shutdown (void)
void sol_log_impl_unlock (void)
SOL_API void sol_log_print_function_file (void * data, const struct sol_log_domain * domain, uint8_t message_level, const char * file, const char * function, int line, const char * format, va_list args)
References _show_file, _show_function, _show_line, name, sol_log_domain::name, and sol_log_level_to_str().
SOL_API void sol_log_print_function_journal (void * data, const struct sol_log_domain * domain, uint8_t message_level, const char * file, const char * function, int line, const char * format, va_list args)
References sol_log_print_function_syslog().
Referenced by sol_log_impl_init().
SOL_API void sol_log_print_function_syslog (void * data, const struct sol_log_domain * domain, uint8_t message_level, const char * file, const char * function, int line, const char * format, va_list args)
Referenced by sol_log_impl_init(), and sol_log_print_function_journal().