Soletta: src/lib/comms/sol-http-client-impl-curl.c File Reference
sol-http-client-impl-curl.c File Reference
#include <curl/curl.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/socket.h>
#include <unistd.h>
#include "sol-arena.h"
#include "sol-buffer.h"
#include "sol-http-client.h"
#include "sol-log.h"
#include "sol-mainloop.h"
#include "sol-str-slice.h"
#include "sol-util.h"
#include "sol-vector.h"
Data Structures
struct curl_http_method_opt
struct sol_http_client_connection
Functions
SOL_API void sol_http_client_connection_cancel (struct sol_http_client_connection *pending)
int sol_http_client_init (void)
SOL_API struct
sol_http_client_connection * sol_http_client_request (enum sol_http_method method, const char *base_uri, const struct sol_http_param *params, void(*cb)(void *data, const struct sol_http_client_connection *connection, struct sol_http_response *response), const void *data)
void sol_http_client_shutdown (void)
Function Documentation
int sol_http_client_init (void)
References SOL_NULL_CHECK_GOTO.
Referenced by sol_comms_init().
SOL_API struct sol_http_client_connection* sol_http_client_request (enum sol_http_method method, const char * base_uri, const struct sol_http_param * params, void(*)(void *data, const struct sol_http_client_connection *connection, struct sol_http_response *response) cb, const void * data)
References curl_http_method_opt::args, sol_http_client_connection::curl, curl_http_method_opt::enabled, curl_http_method_opt::method, sol_http_param::params, curl_http_method_opt::request_name, sol_arena_del(), sol_arena_new(), SOL_HTTP_METHOD_CONNECT, SOL_HTTP_METHOD_DELETE, SOL_HTTP_METHOD_GET, SOL_HTTP_METHOD_HEAD, SOL_HTTP_METHOD_INVALID, SOL_HTTP_METHOD_OPTIONS, SOL_HTTP_METHOD_PATCH, SOL_HTTP_METHOD_POST, SOL_HTTP_METHOD_PUT, SOL_HTTP_METHOD_TRACE, SOL_HTTP_PARAM_ALLOW_REDIR, SOL_HTTP_PARAM_AUTH_BASIC, SOL_HTTP_PARAM_COOKIE, SOL_HTTP_PARAM_HEADER, SOL_HTTP_PARAM_POST_DATA, SOL_HTTP_PARAM_POST_FIELD, SOL_HTTP_PARAM_QUERY_PARAM, SOL_HTTP_PARAM_TIMEOUT, SOL_HTTP_PARAM_VERBOSE, SOL_VECTOR_FOREACH_IDX, SOL_VECTOR_INIT, SOL_WRN, strstartswith, sol_http_param_value::type, and sol_http_param_value::value.
void sol_http_client_shutdown (void)
References SOL_PTR_VECTOR_FOREACH_IDX, and sol_timeout_del().
Referenced by sol_comms_shutdown().
Variable Documentation
struct sol_ptr_vector connections
CURLM* multi
struct sol_timeout* multi_perform_timeout
int ref
Referenced by mux_shutdown().
long timeout_ms
Referenced by ppoll().