Soletta: src/lib/comms/sol-oic-cbor.h File Reference
sol-oic-cbor.h File Reference
#include "cbor.h"
#include "sol-coap.h"
#include "sol-oic-common.h"
#include "sol-vector.h"
Macros
#define SOL_OIC_KEY_BITMAP "bm"
#define SOL_OIC_KEY_DEVICE_ID "sid"
#define SOL_OIC_KEY_FIRMWARE_VER "mnfv"
#define SOL_OIC_KEY_HREF "href"
#define SOL_OIC_KEY_HW_VER "mnhw"
#define SOL_OIC_KEY_INTERFACES "if"
#define SOL_OIC_KEY_MANUF_DATE "mndt"
#define SOL_OIC_KEY_MANUF_NAME "mnmn"
#define SOL_OIC_KEY_MANUF_URL "mnml"
#define SOL_OIC_KEY_MODEL_NUM "mnmo"
#define SOL_OIC_KEY_OS_VER "mnos"
#define SOL_OIC_KEY_PLATFORM_ID "pi"
#define SOL_OIC_KEY_PLATFORM_VER "mnpv"
#define SOL_OIC_KEY_POLICY "p"
#define SOL_OIC_KEY_PROPERTIES "prop"
#define SOL_OIC_KEY_REPRESENTATION "rep"
#define SOL_OIC_KEY_RESOURCE_TYPES "rt"
#define SOL_OIC_KEY_SUPPORT_URL "mnsl"
#define SOL_OIC_KEY_SYSTEM_TIME "st"
Enumerations
enum sol_oic_payload_type { SOL_OIC_PAYLOAD_DISCOVERY = 1, SOL_OIC_PAYLOAD_PLATFORM = 3, SOL_OIC_PAYLOAD_REPRESENTATION = 4 }
Functions
CborError sol_oic_decode_cbor_repr (struct sol_coap_packet *pkt, struct sol_vector *reprs)
CborError sol_oic_decode_cbor_repr_map (CborValue *map, struct sol_vector *reprs)
CborError sol_oic_encode_cbor_repr (struct sol_coap_packet *pkt, const char *href, const struct sol_vector *reprs)
bool sol_oic_pkt_has_cbor_content (const struct sol_coap_packet *pkt)
Macro Definition Documentation
#define SOL_OIC_KEY_BITMAP "bm"
#define SOL_OIC_KEY_DEVICE_ID "sid"
#define SOL_OIC_KEY_FIRMWARE_VER "mnfv"
#define SOL_OIC_KEY_HREF "href"
Referenced by sol_oic_encode_cbor_repr().
#define SOL_OIC_KEY_HW_VER "mnhw"
#define SOL_OIC_KEY_INTERFACES "if"
#define SOL_OIC_KEY_MANUF_DATE "mndt"
#define SOL_OIC_KEY_MANUF_NAME "mnmn"
#define SOL_OIC_KEY_MANUF_URL "mnml"
#define SOL_OIC_KEY_MODEL_NUM "mnmo"
#define SOL_OIC_KEY_OS_VER "mnos"
#define SOL_OIC_KEY_PLATFORM_ID "pi"
#define SOL_OIC_KEY_PLATFORM_VER "mnpv"
#define SOL_OIC_KEY_POLICY "p"
#define SOL_OIC_KEY_PROPERTIES "prop"
#define SOL_OIC_KEY_REPRESENTATION "rep"
Referenced by sol_oic_decode_cbor_repr(), and sol_oic_encode_cbor_repr().
#define SOL_OIC_KEY_RESOURCE_TYPES "rt"
#define SOL_OIC_KEY_SUPPORT_URL "mnsl"
#define SOL_OIC_KEY_SYSTEM_TIME "st"
Enumeration Type Documentation
enum sol_oic_payload_type
Enumerator
SOL_OIC_PAYLOAD_DISCOVERY
SOL_OIC_PAYLOAD_PLATFORM
SOL_OIC_PAYLOAD_REPRESENTATION
Function Documentation
CborError sol_oic_decode_cbor_repr (struct sol_coap_packet * pkt, struct sol_vector * reprs)
References sol_coap_packet_get_payload(), sol_oic_decode_cbor_repr_map(), SOL_OIC_KEY_REPRESENTATION, and SOL_OIC_PAYLOAD_REPRESENTATION.
CborError sol_oic_decode_cbor_repr_map (CborValue * map, struct sol_vector * reprs)
References sol_str_slice::data, sol_oic_repr_field::key, sol_str_slice::len, SOL_ERR, SOL_OIC_REPR_TYPE_BOOLEAN, SOL_OIC_REPR_TYPE_BYTE_STRING, SOL_OIC_REPR_TYPE_DOUBLE, SOL_OIC_REPR_TYPE_FLOAT, SOL_OIC_REPR_TYPE_HALF_FLOAT, SOL_OIC_REPR_TYPE_INT, SOL_OIC_REPR_TYPE_TEXT_STRING, sol_vector_append(), sol_oic_repr_field::type, sol_oic_repr_field::v_boolean, sol_oic_repr_field::v_double, sol_oic_repr_field::v_float, sol_oic_repr_field::v_int, sol_oic_repr_field::v_slice, and sol_oic_repr_field::v_voidptr.
Referenced by sol_oic_decode_cbor_repr().
CborError sol_oic_encode_cbor_repr (struct sol_coap_packet * pkt, const char * href, const struct sol_vector * reprs)
References sol_str_slice::data, sol_oic_repr_field::key, sol_str_slice::len, sol_coap_packet_get_payload(), sol_coap_packet_set_payload_used(), SOL_OIC_KEY_HREF, SOL_OIC_KEY_REPRESENTATION, SOL_OIC_PAYLOAD_REPRESENTATION, SOL_OIC_REPR_TYPE_BOOLEAN, SOL_OIC_REPR_TYPE_BYTE_STRING, SOL_OIC_REPR_TYPE_DOUBLE, SOL_OIC_REPR_TYPE_FLOAT, SOL_OIC_REPR_TYPE_HALF_FLOAT, SOL_OIC_REPR_TYPE_INT, SOL_OIC_REPR_TYPE_SIMPLE, SOL_OIC_REPR_TYPE_TEXT_STRING, SOL_OIC_REPR_TYPE_UINT, SOL_VECTOR_FOREACH_IDX, SOL_WRN, sol_oic_repr_field::type, sol_oic_repr_field::v_boolean, sol_oic_repr_field::v_double, sol_oic_repr_field::v_float, sol_oic_repr_field::v_int, sol_oic_repr_field::v_simple, sol_oic_repr_field::v_slice, sol_oic_repr_field::v_uint, and sol_oic_repr_field::v_voidptr.
Referenced by sol_oic_notify_observers().
bool sol_oic_pkt_has_cbor_content (const struct sol_coap_packet * pkt)
References SOL_COAP_CONTENTTYPE_APPLICATION_CBOR, sol_coap_find_first_option(), and SOL_COAP_OPTION_CONTENT_FORMAT.