Soletta: src/lib/flow/sol-flow.c File Reference
sol-flow.c File Reference
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include "sol-flow-internal.h"
#include "sol-flow-resolver.h"
#include "sol-util.h"
Macros
#define SOL_FLOW_SEND_PACKET(_type)
Functions
int sol_flow_init (void)
SOL_API void sol_flow_node_del (struct sol_flow_node *node)
void sol_flow_node_fini (struct sol_flow_node *node)
SOL_API const char * sol_flow_node_get_id (const struct sol_flow_node *node)
SOL_API const struct
sol_flow_node * sol_flow_node_get_parent (const struct sol_flow_node *node)
SOL_API void * sol_flow_node_get_private_data (const struct sol_flow_node *node)
SOL_API const struct
sol_flow_node_type * sol_flow_node_get_type (const struct sol_flow_node *node)
int sol_flow_node_init (struct sol_flow_node *node, struct sol_flow_node *parent, const char *name, const struct sol_flow_node_type *type, const struct sol_flow_node_options *options)
SOL_API struct sol_flow_node * sol_flow_node_new (struct sol_flow_node *parent, const char *id, const struct sol_flow_node_type *type, const struct sol_flow_node_options *options)
SOL_API void sol_flow_node_type_del (struct sol_flow_node_type *type)
SOL_API const struct
sol_flow_port_type_in * sol_flow_node_type_get_port_in (const struct sol_flow_node_type *type, uint16_t port)
SOL_API const struct
sol_flow_port_type_out * sol_flow_node_type_get_port_out (const struct sol_flow_node_type *type, uint16_t port)
SOL_API int sol_flow_send_blob_packet (struct sol_flow_node *src, uint16_t src_port, const struct sol_blob *value)
SOL_API int sol_flow_send_boolean_packet (struct sol_flow_node *src, uint16_t src_port, unsigned char value)
SOL_API int sol_flow_send_byte_packet (struct sol_flow_node *src, uint16_t src_port, unsigned char value)
SOL_API int sol_flow_send_composed_packet (struct sol_flow_node *src, uint16_t src_port, const struct sol_flow_packet_type *composed_type, struct sol_flow_packet **children)
SOL_API int sol_flow_send_direction_vector_components_packet (struct sol_flow_node *src, uint16_t src_port, double x, double y, double z)
SOL_API int sol_flow_send_direction_vector_packet (struct sol_flow_node *src, uint16_t src_port, const struct sol_direction_vector *value)
SOL_API int sol_flow_send_drange_packet (struct sol_flow_node *src, uint16_t src_port, const struct sol_drange *value)
SOL_API int sol_flow_send_drange_value_packet (struct sol_flow_node *src, uint16_t src_port, double value)
SOL_API int sol_flow_send_empty_packet (struct sol_flow_node *src, uint16_t src_port)
SOL_API int sol_flow_send_error_packet (struct sol_flow_node *src, int code, const char *msg_fmt,...)
SOL_API int sol_flow_send_error_packet_errno (struct sol_flow_node *src, int code)
SOL_API int sol_flow_send_error_packet_str (struct sol_flow_node *src, int code, const char *str)
SOL_API int sol_flow_send_http_response_packet (struct sol_flow_node *src, uint16_t src_port, int response_code, const char *url, const char *content_type, const struct sol_blob *content, const struct sol_vector *cookies, const struct sol_vector *headers)
SOL_API int sol_flow_send_irange_packet (struct sol_flow_node *src, uint16_t src_port, const struct sol_irange *value)
SOL_API int sol_flow_send_irange_value_packet (struct sol_flow_node *src, uint16_t src_port, int32_t value)
SOL_API int sol_flow_send_json_array_packet (struct sol_flow_node *src, uint16_t src_port, const struct sol_blob *value)
SOL_API int sol_flow_send_json_object_packet (struct sol_flow_node *src, uint16_t src_port, const struct sol_blob *value)
SOL_API int sol_flow_send_location_packet (struct sol_flow_node *src, uint16_t src_port, const struct sol_location *value)
SOL_API int sol_flow_send_packet (struct sol_flow_node *src, uint16_t src_port, struct sol_flow_packet *packet)
SOL_API int sol_flow_send_rgb_components_packet (struct sol_flow_node *src, uint16_t src_port, uint32_t red, uint32_t green, uint32_t blue)
SOL_API int sol_flow_send_rgb_packet (struct sol_flow_node *src, uint16_t src_port, const struct sol_rgb *value)
SOL_API int sol_flow_send_string_packet (struct sol_flow_node *src, uint16_t src_port, const char *value)
SOL_API int sol_flow_send_string_slice_packet (struct sol_flow_node *src, uint16_t src_port, const struct sol_str_slice value)
SOL_API int sol_flow_send_string_take_packet (struct sol_flow_node *src, uint16_t src_port, char *value)
SOL_API int sol_flow_send_timestamp_packet (struct sol_flow_node *src, uint16_t src_port, const struct timespec *value)
void sol_flow_shutdown (void)
SOL_LOG_INTERNAL_DECLARE (_sol_flow_log_domain,"flow")
Variables
const struct sol_flow_node_options sol_flow_node_options_empty
Macro Definition Documentation
#define SOL_FLOW_SEND_PACKET (_type)
Value:
do { \
        struct sol_flow_packet *out_packet; \
 \
        out_packet = sol_flow_packet_new_ ## _type(value); \
        SOL_NULL_CHECK(out_packet, -ENOMEM); \
 \
        return sol_flow_send_packet(src, src_port, out_packet); \
    } while (0)
Referenced by sol_flow_send_blob_packet(), sol_flow_send_boolean_packet(), sol_flow_send_byte_packet(), sol_flow_send_direction_vector_packet(), sol_flow_send_drange_packet(), sol_flow_send_drange_value_packet(), sol_flow_send_irange_packet(), sol_flow_send_irange_value_packet(), sol_flow_send_json_array_packet(), sol_flow_send_json_object_packet(), sol_flow_send_location_packet(), sol_flow_send_rgb_packet(), sol_flow_send_string_packet(), sol_flow_send_string_slice_packet(), and sol_flow_send_timestamp_packet().
Function Documentation
int sol_flow_init (void)
References SOL_LOG_DOMAIN, and sol_log_domain_init_level().
Referenced by sol_init().
void sol_flow_node_fini (struct sol_flow_node * node)
References sol_flow_node_type::close, sol_flow_node::data, sol_flow_node_type::data_size, sol_flow_node::id, sol_flow_node::parent, sol_flow_node_container_type::remove, SOL_FLOW_NODE_CHECK, and sol_flow_node::type.
Referenced by sol_flow_node_del().
int sol_flow_node_init (struct sol_flow_node * node, struct sol_flow_node * parent, const char * name, const struct sol_flow_node_type * type, const struct sol_flow_node_options * options)
References sol_flow_node_container_type::add, sol_flow_node::data, sol_flow_node_type::data_size, sol_flow_node::id, sol_flow_node_type::init_type, sol_flow_node_type::open, sol_flow_node::parent, sol_flow_node_container_type::remove, SOL_FLOW_NODE_OPTIONS_API_CHECK, SOL_FLOW_NODE_OPTIONS_API_VERSION, SOL_FLOW_NODE_TYPE_API_CHECK, SOL_FLOW_NODE_TYPE_API_VERSION, SOL_FLOW_NODE_TYPE_IS_CONTAINER_CHECK, SOL_NULL_CHECK, sol_util_strerrora, SOL_WRN, and sol_flow_node::type.
Referenced by sol_flow_node_new().
SOL_API int sol_flow_send_error_packet (struct sol_flow_node * src, int code, const char * msg_fmt, ...)
References SOL_FLOW_NODE_PORT_ERROR, sol_flow_packet_new_error(), sol_flow_send_packet(), SOL_NULL_CHECK, and SOL_WRN.
Referenced by sol_flow_send_error_packet_errno(), and sol_flow_send_error_packet_str().
void sol_flow_shutdown (void)
References loaded_metatype_cache_shutdown(), and sol_flow_packet_type_composed_shutdown().
Referenced by sol_init(), and sol_shutdown().
SOL_LOG_INTERNAL_DECLARE (_sol_flow_log_domain , "flow")
Variable Documentation
const struct sol_flow_node_options sol_flow_node_options_empty
Initial value:
= {
    .api_version = SOL_FLOW_NODE_OPTIONS_API_VERSION,
    .sub_api = 0,
}
Referenced by sol_flow_node_new(), and sol_flow_node_options_new().