Soletta: src/lib/io/sol-i2c-impl-linux.c File Reference
sol-i2c-impl-linux.c File Reference
#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <linux/i2c-dev.h>
#include <linux/i2c.h>
#include <dirent.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdint.h>
#include <sys/ioctl.h>
#include <sys/stat.h>
#include <errno.h>
#include "sol-log-internal.h"
#include "sol-i2c.h"
#include "sol-macros.h"
#include "sol-mainloop.h"
#include "sol-util.h"
Data Structures
struct i2c_create_device
struct sol_i2c
Macros
#define BUSY_CHECK(i2c, ret) SOL_EXP_CHECK(i2c->async.timeout, ret);
#define SOL_LOG_DOMAIN &_log_domain
#define SYSFS_DEVICES_PATH_RAW "/sys/devices/%s"
#define SYSFS_I2C_NEW_DEVICE "%s/%s/new_device"
Functions
SOL_API uint8_t sol_i2c_bus_get (const struct sol_i2c *i2c)
SOL_API bool sol_i2c_busy (struct sol_i2c *i2c)
SOL_API void sol_i2c_close_raw (struct sol_i2c *i2c)
SOL_API int sol_i2c_create_device (const char *address, const char *dev_name, unsigned int dev_number, struct sol_buffer *result_path)
SOL_API uint8_t sol_i2c_get_slave_address (struct sol_i2c *i2c)
SOL_API struct sol_i2c * sol_i2c_open_raw (uint8_t bus, enum sol_i2c_speed speed)
SOL_API void sol_i2c_pending_cancel (struct sol_i2c *i2c, struct sol_i2c_pending *pending)
SOL_API struct sol_i2c_pending * sol_i2c_read (struct sol_i2c *i2c, uint8_t *values, size_t count, void(*read_cb)(void *cb_data, struct sol_i2c *i2c, uint8_t *data, ssize_t status), const void *cb_data)
SOL_API struct sol_i2c_pending * sol_i2c_read_register (struct sol_i2c *i2c, uint8_t reg, uint8_t *values, size_t count, void(*read_reg_cb)(void *cb_data, struct sol_i2c *i2c, uint8_t reg, uint8_t *data, ssize_t status), const void *cb_data)
SOL_API struct sol_i2c_pending * sol_i2c_read_register_multiple (struct sol_i2c *i2c, uint8_t reg, uint8_t *values, size_t count, uint8_t times, void(*read_reg_multiple_cb)(void *cb_data, struct sol_i2c *i2c, uint8_t reg, uint8_t *data, ssize_t status), const void *cb_data)
SOL_API bool sol_i2c_set_slave_address (struct sol_i2c *i2c, uint8_t slave_address)
SOL_API struct sol_i2c_pending * sol_i2c_write (struct sol_i2c *i2c, uint8_t *values, size_t count, void(*write_cb)(void *cb_data, struct sol_i2c *i2c, uint8_t *data, ssize_t status), const void *cb_data)
SOL_API struct sol_i2c_pending * sol_i2c_write_quick (struct sol_i2c *i2c, bool rw, void(*write_quick_cb)(void *cb_data, struct sol_i2c *i2c, ssize_t status), const void *cb_data)
SOL_API struct sol_i2c_pending * sol_i2c_write_register (struct sol_i2c *i2c, uint8_t reg, const uint8_t *values, size_t count, void(*write_reg_cb)(void *cb_data, struct sol_i2c *i2c, uint8_t reg, uint8_t *data, ssize_t status), const void *cb_data)
SOL_LOG_INTERNAL_DECLARE_STATIC (_log_domain,"i2c")
Macro Definition Documentation
#define BUSY_CHECK (i2c, ret) SOL_EXP_CHECK(i2c->async.timeout, ret);
Referenced by sol_i2c_read(), sol_i2c_read_register(), sol_i2c_read_register_multiple(), sol_i2c_set_slave_address(), sol_i2c_write(), sol_i2c_write_quick(), and sol_i2c_write_register().
#define SOL_LOG_DOMAIN &_log_domain
#define SYSFS_DEVICES_PATH_RAW "/sys/devices/%s"
Referenced by sol_i2c_create_device().
#define SYSFS_I2C_NEW_DEVICE "%s/%s/new_device"
Referenced by sol_i2c_pending_cancel().
Function Documentation
SOL_API uint8_t sol_i2c_bus_get (const struct sol_i2c * i2c)
Get the I2C bus id
Parameters
i2c The I2C bus handle
Returns
the bus id
References sol_i2c::bus, and SOL_NULL_CHECK.
SOL_API bool sol_i2c_busy (struct sol_i2c * i2c)
Return true if I2C bus is busy, processing another operation. This function should be called before call any other I2C function.
Parameters
i2c The I2C bus handle
Returns
true is busy or false if idle
References sol_i2c::async, SOL_NULL_CHECK, and sol_i2c::timeout.
SOL_API void sol_i2c_close_raw (struct sol_i2c * i2c)
Close an I2C bus.
Parameters
i2c bus The I2C bus handle to close
Note
This call will not remove this I2C handle from cache. Use sol_i2c_close() for that.
References sol_i2c::async, sol_i2c::dev, sol_i2c_pending_cancel(), SOL_NULL_CHECK, and sol_i2c::timeout.
SOL_API int sol_i2c_create_device (const char * address, const char * dev_name, unsigned int dev_number, struct sol_buffer * result_path)
References i2c_create_device::dev_name, i2c_create_device::dev_number, i2c_create_device::result, i2c_create_device::result_path, SOL_NULL_CHECK, sol_util_iterate_dir(), SOL_WRN, strstartswith, and SYSFS_DEVICES_PATH_RAW.
SOL_API uint8_t sol_i2c_get_slave_address (struct sol_i2c * i2c)
Get the (slave) device address set on an I2C bus (to deliver I2C commands)
Parameters
i2c bus The I2C bus handle
Returns
The slave device address set on bus. 0x0 means bus was not set to any device yet
References sol_i2c::addr, and SOL_NULL_CHECK.
SOL_API struct sol_i2c* sol_i2c_open_raw (uint8_t bus, enum sol_i2c_speed speed)
Open an I2C bus.
Parameters
bus The I2C bus number to open
speed The speed to open I2C bus bus at
Returns
A new I2C bus handle
Note
This call won't attempt to make any pin muxing operations underneath. Use sol_i2c_open() for that, also this will not cache this I2C or try get an previous cached I2C handle.
References sol_i2c::bus, sol_i2c::dev, sol_i2c::plain_i2c, SOL_LOG_INTERNAL_INIT_ONCE, and SOL_WRN.
SOL_API void sol_i2c_pending_cancel (struct sol_i2c * i2c, struct sol_i2c_pending * pending)
Cancel a pending operation.
Parameters
i2c the I2C bus handle
pending the operation handle
References sol_i2c::async, i2c_create_device::dev_name, i2c_create_device::dev_number, sol_i2c::dispatch, i2c_create_device::result, i2c_create_device::result_path, SOL_API, SOL_NULL_CHECK, sol_timeout_del(), sol_util_strerrora, sol_util_write_file(), sol_worker_thread_cancel(), SOL_WRN, strstartswith, SYSFS_I2C_NEW_DEVICE, and sol_i2c::timeout.
Referenced by sol_i2c_close_raw().
SOL_API struct sol_i2c_pending* sol_i2c_read (struct sol_i2c * i2c, uint8_t * data, size_t count, void(*)(void *cb_data, struct sol_i2c *i2c, uint8_t *data, ssize_t status) read_cb, const void * cb_data)
Perform successive asynchronous I2C byte read operations, with no specified register
This makes count read byte I2C operations on the device bus is set to operate on, at no specific register. Some devices are so simple that this interface is enough. For others, it is a shorthand if you want to read the same register as in the previous I2C command.
Parameters
i2c bus The I2C bus handle
data The output buffer for the read operation
count The bytes count for the read operation
read_cb The callback to be called when operation finish, the status parameter should be equal to count in case of success
cb_data The first parameter of callback
Note
Caller should guarantee that data will not be freed until callback is called. Also there is no transfer queue, calling this function when there is another I2C operation running will return false.
Returns
pending handle if operation was started otherwise a NULL pointer
References sol_worker_thread_spec::api_version, sol_i2c::async, BUSY_CHECK, sol_i2c::cb_data, sol_i2c::count, sol_i2c::data, sol_i2c::dev, sol_i2c::dispatch, sol_i2c::read_write_cb, SOL_INT_CHECK, SOL_NULL_CHECK, sol_timeout_add(), sol_worker_thread_new(), SOL_WORKER_THREAD_SPEC_API_VERSION, sol_i2c::status, and sol_i2c::timeout.
SOL_API struct sol_i2c_pending* sol_i2c_read_register (struct sol_i2c * i2c, uint8_t reg, uint8_t * data, size_t count, void(*)(void *cb_data, struct sol_i2c *i2c, uint8_t reg, uint8_t *data, ssize_t status) read_reg_cb, const void * cb_data)
Perform a asynchronous I2C read operation on a given device register
Parameters
i2c bus The I2C bus handle
reg The I2C register for the read operation
data The output buffer for the read operation
count The bytes count for the read operation
read_reg_cb The callback to be called when operation finish, the status parameter should be equal to count in case of success
cb_data The first parameter of callback
Note
Caller should guarantee that data will not be freed until callback is called. Also there is no transfer queue, calling this function when there is another I2C operation running will return false.
Returns
pending handle if operation was started otherwise a NULL pointer
References sol_worker_thread_spec::api_version, sol_i2c::async, BUSY_CHECK, sol_i2c::cb_data, sol_i2c::count, sol_i2c::data, sol_i2c::dev, sol_i2c::dispatch, sol_i2c::read_write_reg_cb, sol_i2c::reg, SOL_INT_CHECK, SOL_NULL_CHECK, sol_timeout_add(), sol_worker_thread_new(), SOL_WORKER_THREAD_SPEC_API_VERSION, sol_i2c::status, and sol_i2c::timeout.
SOL_API struct sol_i2c_pending* sol_i2c_read_register_multiple (struct sol_i2c * i2c, uint8_t reg, uint8_t * values, size_t count, uint8_t times, void(*)(void *cb_data, struct sol_i2c *i2c, uint8_t reg, uint8_t *data, ssize_t status) read_reg_multiple_cb, const void * cb_data)
Asynchronous read of an arbitrary number of bytes from a register in repeated bursts of a given length (that start always on the provided register address)
This is so because a lot of devices will, after a read operation, update its register values with new data to be read on subsequent operations, until the total data length the user requested is read. If the device has the auto-increment feature, sol_i2c_read_register() might be a better call than this function.
This will issue multiple I2C read/write transactions with the first (write) message specifying the register to operate on and the second (read) message specifying the length (always len per read) and the destination of the read operation.
Parameters
i2c bus The I2C bus handle
reg The register to start reading from
values Where to store the read bytes
count The size of a single read block
times How many reads of size len to perform (on success, len * times bytes will be read)
read_reg_multiple_cb The callback to be called when operation finish, the status parameter should be equal to count in case of success
cb_data The first parameter of callback
Note
Caller should guarantee that data will not be freed until callback is called. Also there is no transfer queue, calling this function when there is another I2C operation running will return false.
Returns
pending handle if operation was started otherwise a NULL pointer
References sol_worker_thread_spec::api_version, sol_i2c::async, BUSY_CHECK, sol_i2c::cb_data, sol_i2c::count, sol_i2c::data, sol_i2c::dev, sol_i2c::dispatch, sol_i2c::read_write_reg_cb, sol_i2c::reg, SOL_INT_CHECK, SOL_NULL_CHECK, sol_timeout_add(), sol_worker_thread_new(), SOL_WORKER_THREAD_SPEC_API_VERSION, sol_i2c::status, sol_i2c::timeout, and sol_i2c::times.
SOL_API bool sol_i2c_set_slave_address (struct sol_i2c * i2c, uint8_t slave_address)
Set a (slave) device address on a I2C bus to deliver commands to.
All other I2C functions, after this call, will act on the given slave_address device address. Since other I2C calls might happen in between your own ones, though, it's highly advisable that you issue this call before using any of the I2C read/write functions.
Parameters
i2c bus The I2C bus handle
slave_address The slave device address to deliver commands to
Returns
true on success, false otherwise.
References sol_i2c::addr, sol_i2c::bus, BUSY_CHECK, sol_i2c::dev, SOL_NULL_CHECK, and SOL_WRN.
SOL_API struct sol_i2c_pending* sol_i2c_write (struct sol_i2c * i2c, uint8_t * data, size_t count, void(*)(void *cb_data, struct sol_i2c *i2c, uint8_t *data, ssize_t status) write_cb, const void * cb_data)
Perform successive asynchronous I2C byte write operations, with no specified register
This makes count write byte I2C operations on the device bus is set to operate on, at no specific register. Some devices are so simple that this interface is enough. For others, it is a shorthand if you want to write the same register as in the previous I2C command.
Parameters
i2c bus The I2C bus handle
data The output buffer for the write operation
count The bytes count for the write operation
write_cb The callback to be called when operation finish, the status parameter should be equal to count in case of success
cb_data The first parameter of callback
Note
Caller should guarantee that data will not be freed until callback is called. Also there is no transfer queue, calling this function when there is another I2C operation running will return false.
Returns
pending handle if operation was started otherwise a NULL pointer
References sol_worker_thread_spec::api_version, sol_i2c::async, BUSY_CHECK, sol_i2c::cb_data, sol_i2c::count, sol_i2c::data, sol_i2c::dev, sol_i2c::dispatch, sol_i2c::read_write_cb, SOL_INT_CHECK, SOL_NULL_CHECK, sol_timeout_add(), sol_worker_thread_new(), SOL_WORKER_THREAD_SPEC_API_VERSION, sol_i2c::status, and sol_i2c::timeout.
SOL_API struct sol_i2c_pending* sol_i2c_write_quick (struct sol_i2c * i2c, bool rw, void(*)(void *cb_data, struct sol_i2c *i2c, ssize_t status) write_quick_cb, const void * cb_data)
Perform a I2C write quick operation
This sends a single bit to a device (command designed to turn on and off simple devices)
Parameters
i2c The I2C bus handle
rw The value to write
write_quick_cb The callback to be issued when the operation finishes. The status parameter should be equal to one in case of success
cb_data Data to be passed to write_quick_cb
Returns
pending handle if operation was started otherwise a NULL pointer
References sol_worker_thread_spec::api_version, sol_i2c::async, BUSY_CHECK, sol_i2c::cb_data, sol_i2c::data, sol_i2c::dev, sol_i2c::dispatch, SOL_INT_CHECK, SOL_NULL_CHECK, sol_timeout_add(), sol_worker_thread_new(), SOL_WORKER_THREAD_SPEC_API_VERSION, sol_i2c::status, sol_i2c::timeout, and sol_i2c::write_quick_cb.
SOL_API struct sol_i2c_pending* sol_i2c_write_register (struct sol_i2c * i2c, uint8_t reg, const uint8_t * data, size_t count, void(*)(void *cb_data, struct sol_i2c *i2c, uint8_t reg, uint8_t *data, ssize_t status) write_reg_cb, const void * cb_data)
Perform a asynchronous I2C write operation on a given device register
Parameters
i2c bus The I2C bus handle
reg The I2C register for the write operation
data The output buffer for the write operation
count The bytes count for the write operation
write_reg_cb The callback to be called when operation finish, the status parameter should be equal to count in case of success
cb_data The first parameter of callback
Note
Caller should guarantee that data will not be freed until callback is called. Also there is no transfer queue, calling this function when there is another I2C operation running will return false.
Returns
pending handle if operation was started otherwise a NULL pointer
References sol_worker_thread_spec::api_version, sol_i2c::async, BUSY_CHECK, sol_i2c::cb_data, sol_i2c::count, sol_i2c::data, sol_i2c::dev, sol_i2c::dispatch, sol_i2c::read_write_reg_cb, sol_i2c::reg, SOL_INT_CHECK, SOL_NULL_CHECK, sol_timeout_add(), sol_worker_thread_new(), SOL_WORKER_THREAD_SPEC_API_VERSION, sol_i2c::status, and sol_i2c::timeout.
SOL_LOG_INTERNAL_DECLARE_STATIC (_log_domain , "i2c")