Soletta: src/lib/io/sol-i2c-common.c File Reference
sol-i2c-common.c File Reference
#include <stdlib.h>
#include "sol-log-internal.h"
#include "sol-i2c.h"
#include "sol-vector.h"
Data Structures
struct sol_i2c_shared
Macros
#define SOL_LOG_DOMAIN &_log_domain
Functions
SOL_API void sol_i2c_close (struct sol_i2c *i2c)
SOL_API struct sol_i2c * sol_i2c_open (uint8_t bus, enum sol_i2c_speed speed)
SOL_LOG_INTERNAL_DECLARE_STATIC (_log_domain,"i2c")
Macro Definition Documentation
#define SOL_LOG_DOMAIN &_log_domain
Function Documentation
SOL_API void sol_i2c_close (struct sol_i2c * i2c)
Close an I2C bus.
Parameters
i2c bus The I2C bus handle to close
References sol_i2c_shared::i2c, sol_i2c_shared::refcount, sol_i2c_close_raw(), SOL_NULL_CHECK, sol_vector_del(), and SOL_VECTOR_FOREACH_IDX.
Referenced by am2315_close(), am2315_open(), and sol_i2c_open().
SOL_API struct sol_i2c* sol_i2c_open (uint8_t bus, enum sol_i2c_speed speed)
Open an I2C bus.
Parameters
bus The I2C bus number to open
speed The speed to open I2C bus bus at
Returns
A new I2C bus handle
Note
This call will attempt to make pin muxing operations underneath, for the given platform that the code is running in. Use sol_i2c_open_raw() if you want to skip any pin mux operation.
The same I2C bus is shared between every user, so only the first one opening the bus will be able to set the bus speed, if some I2C slave device need to work in lower speed you need to change it on every other user of the bus.
References sol_i2c_shared::i2c, sol_i2c_shared::refcount, SOL_ERR, sol_i2c_bus_get(), sol_i2c_close(), sol_i2c_open_raw(), SOL_LOG_INTERNAL_INIT_ONCE, SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, sol_pin_mux_setup_i2c(), sol_vector_append(), and SOL_VECTOR_FOREACH_IDX.
Referenced by am2315_open().
SOL_LOG_INTERNAL_DECLARE_STATIC (_log_domain , "i2c")