Soletta: src/lib/common/sol-worker-thread.c File Reference
sol-worker-thread.c File Reference
#include <stdbool.h>
#include <stdlib.h>
#include "sol-util.h"
#include "sol-macros.h"
#include "sol-worker-thread.h"
#include "sol-worker-thread-impl.h"
Functions
SOL_LOG_INTERNAL_DECLARE (_sol_worker_thread_log_domain,"worker-thread")
SOL_API void sol_worker_thread_cancel (struct sol_worker_thread *thread)
SOL_API bool sol_worker_thread_cancel_check (const struct sol_worker_thread *thread)
SOL_API void sol_worker_thread_feedback (struct sol_worker_thread *thread)
SOL_API struct sol_worker_thread * sol_worker_thread_new (const struct sol_worker_thread_spec *spec)
Function Documentation
SOL_LOG_INTERNAL_DECLARE (_sol_worker_thread_log_domain , "worker-thread")
SOL_API void sol_worker_thread_cancel (struct sol_worker_thread * thread)
Cancel a worker thread.
The cancel function will inform the thread it should stop working, there is no preemptive cancellation – both setup(), iterate() and cleanup() (see sol_worker_thread_new()) will be executed and take the time they need, meanwhile this function will block waiting. After this function is called no further calls to iterate() will be done.
If sol_worker_thread_new() was provided with a cancel() function, then that function will be called prior to any cancellation work. You may use that function to schedule work cancellation in more fine grained fashion in your own code.
Note
this function must be called from the main thread.
Parameters
thread a valid worker thread handle.
See Also
sol_worker_thread_new()
References SOL_NULL_CHECK, and sol_worker_thread_impl_cancel().
Referenced by sol_i2c_pending_cancel(), and sol_spi_close().
SOL_API bool sol_worker_thread_cancel_check (const struct sol_worker_thread * thread)
Check if a worker thread has been marked as cancelled.
Note
this function may be called from both main and worker thread.
Parameters
thread a valid worker thread handle.
Returns
true if worker thread is marked cancelled or false otherwise.
See Also
sol_worker_thread_cancel()
References SOL_NULL_CHECK, and sol_worker_thread_impl_cancel_check().
SOL_API void sol_worker_thread_feedback (struct sol_worker_thread * thread)
Schedule feedback from the worker to the main thread.
This function will schedule a call to feedback() function given to sol_worker_thread_new(). This call is not guaranteed to be executed and multiple calls to sol_worker_thread_feedback() will not queue, a single one will be done. If queuing is to be done, then do it on your own using locks and a list/array in the data context.
When feedback() is called from the main thread there is no locking of data and the worker thread may be executing both setup(), iterate() or cleanup().
Note
this function must be called from the worker thread.
Parameters
thread a valid worker thread handle.
See Also
sol_worker_thread_new()
References SOL_NULL_CHECK, and sol_worker_thread_impl_feedback().
SOL_API struct sol_worker_thread* sol_worker_thread_new (const struct sol_worker_thread_spec * spec)
Create and run a worker thread.
Worker threads are meant to do processing that is hard to split and play nice with cooperative workloads used by the main loop (sol_idle_add(), sol_timeout_add() and sol_fd_add()). Usually this is due blocking operating system calls or third party libraries that don't allow work to be segmented.
Worker threads shouldn't impact the main thread while they execute, but this comes at the trade off of code complexity and synchronization issues. If both the worker thread and the main thread may operate on the same data simultaneously, then it may result in partial reads and writes leading to inconsistent results if locks are not properly done. The best approach is to have the worker thread to operate on its own exclusive data and after it's finished deliver that data to users from within finished callback. If this pattern cannot be used, then employ locks to segments of data that may result into race conditions.
Note
this function must be called from the main thread.
Parameters
spec worker thread specification with functions and context data to be used.
Returns
newly allocated worker thread handle on success or NULL on errors.
See Also
sol_worker_thread_spec
sol_worker_thread_cancel()
sol_worker_thread_feedback()
sol_idle_add()
References sol_worker_thread_spec::api_version, sol_worker_thread_spec::iterate, SOL_NULL_CHECK, sol_worker_thread_impl_new(), SOL_WORKER_THREAD_SPEC_API_VERSION, SOL_WRN, and unlikely.
Referenced by sol_i2c_read(), sol_i2c_read_register(), sol_i2c_read_register_multiple(), sol_i2c_write(), sol_i2c_write_quick(), sol_i2c_write_register(), and sol_spi_transfer().