Soletta: src/lib/crypto/sol-message-digest-common.h File Reference
sol-message-digest-common.h File Reference
#include "sol-log-internal.h"
#include "sol-message-digest.h"
Data Structures
struct sol_message_digest_common_new_params
struct sol_message_digest_common_ops
Macros
#define SOL_LOG_DOMAIN &_sol_message_digest_common_log_domain
Functions
void * sol_message_digest_common_get_context (const struct sol_message_digest *handle)
int sol_message_digest_common_init (void)
struct sol_message_digest * sol_message_digest_common_new (const struct sol_message_digest_common_new_params params)
void sol_message_digest_common_shutdown (void)
Variables
struct sol_log_domain _sol_message_digest_common_log_domain
Macro Definition Documentation
#define SOL_LOG_DOMAIN &_sol_message_digest_common_log_domain
Function Documentation
void* sol_message_digest_common_get_context (const struct sol_message_digest * handle)
int sol_message_digest_common_init (void)
References SOL_LOG_INTERNAL_INIT_ONCE.
Referenced by sol_message_digest_init().
struct sol_message_digest* sol_message_digest_common_new (const struct sol_message_digest_common_new_params params)
This function creates the base handle.
If it fails, then params.ops->cleanup() is NOT called, one may need to do extra cleanups if needed.
Parameters
params the set of parameters is specified as a struct to avoid mistakes. Se its documentation for each parameter purpose and behavior.
newly allocated handle or NULL on error, with errno set.
References sol_message_digest_config::algorithm, sol_message_digest_common_ops::cleanup, config, sol_message_digest_common_new_params::config, sol_message_digest_common_new_params::context_size, sol_message_digest_common_new_params::context_template, sol_message_digest::data, sol_message_digest_config::data, sol_message_digest::digest_size, sol_message_digest_common_new_params::digest_size, sol_message_digest_common_ops::feed, sol_message_digest::on_digest_ready, sol_message_digest_config::on_digest_ready, sol_message_digest::on_feed_done, sol_message_digest_config::on_feed_done, sol_message_digest::ops, sol_message_digest_common_new_params::ops, sol_message_digest::pending_feed, sol_message_digest_common_ops::read_digest, sol_message_digest::refcnt, SOL_DBG, SOL_INT_CHECK, SOL_NULL_CHECK, and sol_vector_init().
Referenced by sol_message_digest_new().
void sol_message_digest_common_shutdown (void)
Referenced by sol_message_digest_shutdown().
Variable Documentation
struct sol_log_domain _sol_message_digest_common_log_domain