Soletta: src/bin/sol-fbp-generator/main.c File Reference
main.c File Reference
#include <assert.h>
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <libgen.h>
#include <stdio.h>
#include <sys/stat.h>
#include <unistd.h>
#include "sol-arena.h"
#include "sol-buffer.h"
#include "sol-conffile.h"
#include "sol-fbp-internal-log.h"
#include "sol-fbp.h"
#include "sol-file-reader.h"
#include "sol-flow-static.h"
#include "sol-mainloop.h"
#include "sol-missing.h"
#include "sol-str-slice.h"
#include "sol-util.h"
#include "sol-flow-metatype.h"
#include "type-store.h"
Data Structures
struct declared_fbp_type
struct declared_metatype
struct declared_metatype_control
struct exported_option
struct exported_option_description
struct fbp_data
struct generate_context
struct node_data
struct sol_type_default_value
struct type_to_init
Typedefs
typedef void(* handle_func)(const struct sol_fbp_meta *meta, const char *field, const struct sol_str_slice option, uint16_t index, const char *opt_name, const char *fbp_file)
Functions
int main (int argc, char *argv[])
SOL_ATTR_PRINTF (1, 2)
Typedef Documentation
typedef void(* handle_func)(const struct sol_fbp_meta *meta, const char *field, const struct sol_str_slice option, uint16_t index, const char *opt_name, const char *fbp_file)
Function Documentation
int main (int argc, char * argv[])
References declared_metatype::c_name, option_description::data_type, fbp_data::declared_fbp_types, fbp_data::declared_meta_types, exported_option_description::description, fbp_data::exported_options, fbp_data::exported_options_symbol, fbp_data::graph, option_description::name, sol_fbp_graph::nodes, exported_option::options, sol_arena_del(), sol_arena_new(), SOL_ERR, sol_fbp_graph_fini(), sol_file_reader_close(), sol_init(), SOL_PTR_VECTOR_FOREACH_IDX, sol_shutdown(), sol_util_strerrora, sol_vector_clear(), SOL_VECTOR_FOREACH_IDX, sol_vector_init(), fbp_data::store, type_store_del(), type_store_new(), and sol_fbp_node::user_data.
SOL_ATTR_PRINTF (1 , 2)
References sol_buffer_append_vprintf().
Variable Documentation
const char* conf_file
const char* export_symbol
char* fbp_basename
struct sol_ptr_vector fbp_search_paths
struct sol_ptr_vector json_files
const char* output_file