Soletta: src/lib/comms/sol-socket-impl-linux.c File Reference
sol-socket-impl-linux.c File Reference
#include <netinet/in.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include "sol-log.h"
#include "sol-mainloop.h"
#include "sol-network.h"
#include "sol-util.h"
#include "sol-socket.h"
Data Structures
struct sol_socket
Functions
SOL_API int sol_socket_bind (struct sol_socket *s, const struct sol_network_link_addr *addr)
SOL_API void sol_socket_del (struct sol_socket *s)
SOL_API int sol_socket_join_group (struct sol_socket *s, int ifindex, const struct sol_network_link_addr *group)
SOL_API struct sol_socket * sol_socket_new (int domain, enum sol_socket_type type, int protocol)
SOL_API int sol_socket_recvmsg (struct sol_socket *s, void *buf, size_t len, struct sol_network_link_addr *cliaddr)
SOL_API int sol_socket_sendmsg (struct sol_socket *s, const void *buf, size_t len, const struct sol_network_link_addr *cliaddr)
SOL_API int sol_socket_set_on_read (struct sol_socket *s, bool(*cb)(void *data, struct sol_socket *s), void *data)
SOL_API int sol_socket_set_on_write (struct sol_socket *s, bool(*cb)(void *data, struct sol_socket *s), void *data)
Function Documentation
SOL_API int sol_socket_bind (struct sol_socket * s, const struct sol_network_link_addr * addr)
Referenced by sol_coap_server_new().
SOL_API void sol_socket_del (struct sol_socket * s)
Referenced by sol_coap_server_new().
SOL_API int sol_socket_join_group (struct sol_socket * s, int ifindex, const struct sol_network_link_addr * group)
SOL_API struct sol_socket* sol_socket_new (int domain, enum sol_socket_type type, int protocol)
Referenced by sol_coap_server_new().
SOL_API int sol_socket_recvmsg (struct sol_socket * s, void * buf, size_t len, struct sol_network_link_addr * cliaddr)
SOL_API int sol_socket_sendmsg (struct sol_socket * s, const void * buf, size_t len, const struct sol_network_link_addr * cliaddr)
SOL_API int sol_socket_set_on_read (struct sol_socket * s, bool(*)(void *data, struct sol_socket *s) cb, void * data)
Referenced by sol_coap_server_new().
SOL_API int sol_socket_set_on_write (struct sol_socket * s, bool(*)(void *data, struct sol_socket *s) cb, void * data)