Soletta: src/samples/http/static-files.c File Reference
static-files.c File Reference
HTTP Static files server.
#include <getopt.h>
#include <stdio.h>
#include <string.h>
#include "sol-mainloop.h"
#include "sol-http.h"
#include "sol-http-server.h"
Functions
static void shutdown_server (void)
SOL_MAIN_DEFAULT (startup_server, shutdown_server)
static void startup_server (void)
Variables
static struct sol_http_server * server
Detailed Description
HTTP Static files server.
Sample static files server. The path used to look for the files should be given as argument when launching this sample. To see the usage help, -h or –help.
Function Documentation
static void shutdown_server (void) static
References sol_http_server_del().
SOL_MAIN_DEFAULT (startup_server , shutdown_server)
static void startup_server (void) static
References sol_argc(), sol_argv(), sol_http_server_add_dir(), sol_http_server_new(), and sol_quit_with_code().
Variable Documentation
struct sol_http_server* server static