Soletta: src/modules/flow/string/string-uuid.h File Reference
string-uuid.h File Reference
#include "sol-flow.h"
Data Structures
struct string_uuid_data
Functions
int string_uuid_gen (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int string_uuid_open (struct sol_flow_node *node, void *data, const struct sol_flow_node_options *options)
Function Documentation
int string_uuid_gen (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References sol_flow_send_string_packet(), SOL_INT_CHECK, sol_util_uuid_gen(), string_uuid_data::upcase, and string_uuid_data::with_hyphens.
Referenced by string_uuid_open().
int string_uuid_open (struct sol_flow_node * node, void * data, const struct sol_flow_node_options * options)
References string_uuid_data::node, SOL_FLOW_NODE_OPTIONS_SUB_API_CHECK, string_uuid_gen(), string_uuid_data::upcase, and string_uuid_data::with_hyphens.