Soletta: src/modules/flow/string/string-regexp.h File Reference
string-regexp.h File Reference
#include "sol-flow.h"
Data Structures
struct string_regexp_replace_data
struct string_regexp_search_data
Functions
int set_string_regexp_index (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int set_string_regexp_max_match (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int set_string_regexp_pattern (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int set_string_regexp_replace_max_match (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int set_string_regexp_replace_pattern (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int set_string_regexp_replace_to (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int string_regexp_replace (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
void string_regexp_replace_close (struct sol_flow_node *node, void *data)
int string_regexp_replace_open (struct sol_flow_node *node, void *data, const struct sol_flow_node_options *options)
int string_regexp_search (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
void string_regexp_search_close (struct sol_flow_node *node, void *data)
int string_regexp_search_open (struct sol_flow_node *node, void *data, const struct sol_flow_node_options *options)
Function Documentation
int set_string_regexp_index (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References string_regexp_search_data::index, sol_flow_packet_get_irange_value(), sol_flow_send_error_packet(), SOL_INT_CHECK, and SOL_WRN.
int set_string_regexp_max_match (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References string_regexp_search_data::max_regexp_search, sol_flow_packet_get_irange_value(), sol_flow_send_error_packet(), SOL_INT_CHECK, and SOL_WRN.
int set_string_regexp_pattern (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References string_regexp_search_data::node, string_regexp_search_data::regexp, sol_flow_packet_get_string(), sol_flow_send_error_packet(), and SOL_INT_CHECK.
int set_string_regexp_replace_max_match (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
int set_string_regexp_replace_pattern (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
int set_string_regexp_replace_to (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
int string_regexp_replace (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References string_regexp_replace_data::forward_on_no_match, string_regexp_replace_data::max_regexp_replace, string_regexp_replace_data::node, string_regexp_replace_data::orig_string, string_regexp_replace_data::regexp, sol_buffer_append_slice(), sol_buffer_ensure(), sol_flow_packet_get_string(), sol_flow_send_error_packet(), sol_flow_send_string_packet(), sol_flow_send_string_slice_packet(), SOL_INT_CHECK, SOL_INT_CHECK_GOTO, SOL_STR_SLICE_STR, and sol_buffer::used.
void string_regexp_replace_close (struct sol_flow_node * node, void * data)
References string_regexp_replace_data::orig_string, string_regexp_replace_data::regexp, and string_regexp_replace_data::to_regexp.
int string_regexp_replace_open (struct sol_flow_node * node, void * data, const struct sol_flow_node_options * options)
References string_regexp_replace_data::forward_on_no_match, string_regexp_replace_data::max_regexp_replace, string_regexp_replace_data::node, string_regexp_replace_data::regexp, SOL_FLOW_NODE_OPTIONS_SUB_API_CHECK, SOL_WRN, and string_regexp_replace_data::to_regexp.
int string_regexp_search (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References sol_flow_packet_get_string(), sol_flow_send_error_packet(), SOL_INT_CHECK, and string_regexp_search_data::string.
void string_regexp_search_close (struct sol_flow_node * node, void * data)
References string_regexp_search_data::regexp, sol_vector_clear(), string_regexp_search_data::string, and string_regexp_search_data::substrings.
int string_regexp_search_open (struct sol_flow_node * node, void * data, const struct sol_flow_node_options * options)
References string_regexp_search_data::index, string_regexp_search_data::max_regexp_search, string_regexp_search_data::node, string_regexp_search_data::regexp, SOL_FLOW_NODE_OPTIONS_SUB_API_CHECK, sol_vector_init(), SOL_WRN, and string_regexp_search_data::substrings.