Soletta: src/modules/flow/string/string-common.h File Reference
string-common.h File Reference
#include "sol-flow.h"
Data Structures
struct string_b16_data
struct string_b16decode_data
struct string_b64_data
struct string_b64decode_data
Functions
int string_b16_open (struct sol_flow_node *node, void *data, const struct sol_flow_node_options *options)
int string_b16decode (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int string_b16decode_port_connect (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id)
int string_b16decode_port_disconnect (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id)
int string_b16encode_blob (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int string_b16encode_string (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
void string_b64_close (struct sol_flow_node *node, void *data)
int string_b64_open (struct sol_flow_node *node, void *data, const struct sol_flow_node_options *options)
int string_b64decode (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int string_b64decode_port_connect (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id)
int string_b64decode_port_disconnect (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id)
int string_b64encode_blob (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int string_b64encode_string (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int string_is_empty (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
Function Documentation
int string_b16_open (struct sol_flow_node * node, void * data, const struct sol_flow_node_options * options)
References SOL_FLOW_NODE_OPTIONS_SUB_API_CHECK, and string_b16_data::uppercase.
int string_b16decode (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References string_b16decode_data::blob_conns, sol_blob_new(), SOL_BLOB_TYPE_DEFAULT, sol_blob_unref(), sol_buffer_append_from_base16(), sol_buffer_steal(), SOL_DECODE_LOWERCASE, SOL_DECODE_UPERCASE, sol_flow_packet_get_string(), sol_flow_send_blob_packet(), sol_flow_send_error_packet(), sol_flow_send_string_packet(), sol_flow_send_string_take_packet(), SOL_INT_CHECK, SOL_INT_CHECK_GOTO, SOL_NULL_CHECK_GOTO, sol_util_strerrora, string_b16decode_data::string_conns, and string_b16decode_data::uppercase.
int string_b16decode_port_connect (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id)
References string_b16decode_data::blob_conns, and string_b16decode_data::string_conns.
int string_b16decode_port_disconnect (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id)
References string_b16decode_data::blob_conns, and string_b16decode_data::string_conns.
int string_b16encode_blob (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References sol_blob::mem, sol_blob::size, sol_buffer_append_as_base16(), sol_buffer_steal(), sol_flow_packet_get_blob(), sol_flow_send_error_packet(), sol_flow_send_string_take_packet(), SOL_INT_CHECK, SOL_INT_CHECK_GOTO, sol_util_strerrora, and string_b16_data::uppercase.
int string_b16encode_string (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References sol_buffer_append_as_base16(), sol_buffer_steal(), sol_flow_packet_get_string(), sol_flow_send_error_packet(), sol_flow_send_string_take_packet(), SOL_INT_CHECK, SOL_INT_CHECK_GOTO, sol_util_strerrora, and string_b16_data::uppercase.
void string_b64_close (struct sol_flow_node * node, void * data)
References string_b64_data::base64_map, and SOL_BASE64_MAP.
int string_b64_open (struct sol_flow_node * node, void * data, const struct sol_flow_node_options * options)
References string_b64_data::base64_map, SOL_BASE64_MAP, SOL_FLOW_NODE_OPTIONS_SUB_API_CHECK, SOL_WRN, and streq.
int string_b64decode (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References string_b64decode_data::base64_map, string_b64decode_data::blob_conns, sol_blob_new(), SOL_BLOB_TYPE_DEFAULT, sol_blob_unref(), sol_buffer_append_from_base64(), sol_buffer_steal(), sol_flow_packet_get_string(), sol_flow_send_blob_packet(), sol_flow_send_error_packet(), sol_flow_send_string_packet(), sol_flow_send_string_take_packet(), SOL_INT_CHECK, SOL_INT_CHECK_GOTO, SOL_NULL_CHECK_GOTO, sol_util_strerrora, and string_b64decode_data::string_conns.
int string_b64decode_port_connect (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id)
References string_b64decode_data::blob_conns, and string_b64decode_data::string_conns.
int string_b64decode_port_disconnect (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id)
References string_b64decode_data::blob_conns, and string_b64decode_data::string_conns.
int string_b64encode_blob (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References string_b64_data::base64_map, sol_blob::mem, sol_blob::size, sol_buffer_append_as_base64(), sol_buffer_steal(), sol_flow_packet_get_blob(), sol_flow_send_error_packet(), sol_flow_send_string_take_packet(), SOL_INT_CHECK, SOL_INT_CHECK_GOTO, and sol_util_strerrora.
int string_b64encode_string (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References string_b64_data::base64_map, sol_buffer_append_as_base64(), sol_buffer_steal(), sol_flow_packet_get_string(), sol_flow_send_error_packet(), sol_flow_send_string_take_packet(), SOL_INT_CHECK, SOL_INT_CHECK_GOTO, and sol_util_strerrora.
int string_is_empty (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References sol_flow_packet_get_string(), sol_flow_send_boolean_packet(), and SOL_INT_CHECK.