Soletta: sol_message_digest_common_ops Struct Reference
sol_message_digest_common_ops Struct Reference
#include <sol-message-digest-common.h>
Data Fields
void(* cleanup)(struct sol_message_digest *handle)
ssize_t(* feed)(struct sol_message_digest *handle, const void *mem, size_t len, bool is_last)
ssize_t(* read_digest)(struct sol_message_digest *handle, void *mem, size_t len)
Detailed Description
Operations to use with the common message digest implementation.
Field Documentation
void(* sol_message_digest_common_ops::cleanup)(struct sol_message_digest *handle)
Cleanup any remaining resources before the handle is deleted.
This functions is called from the main thread.
Referenced by sol_message_digest_common_new().
ssize_t(* sol_message_digest_common_ops::feed)(struct sol_message_digest *handle, const void *mem, size_t len, bool is_last)
Feed the algorithm with more data (mem of len bytes).
This function is called from a thread if defined(PTHREAD) && defined(WORKER_THREAD), and in such case care may be needed depending on the platform.
It is guaranteed that the same handle is not called from different worker thread, both feed and read_digest are called from the same worker thread, while cleanup is called from the main thread once the worker thread is already finalized.
If this function returns less then the requested amount of bytes (len), then it is called again with a new mem adapted (offset) to the remaining location and reduced len, so it would do partial feeds.
Parameters
handle the message digest handle feeding the algorithm.
mem the pointer to memory to be feed.
len the size in bytes of memory to be feed.
is_last if this is the last chunk to be feed.
Returns
number of bytes fed or -errno.
Referenced by sol_message_digest_common_new().
ssize_t(* sol_message_digest_common_ops::read_digest)(struct sol_message_digest *handle, void *mem, size_t len)
Read the digest from the message.
This function is called from a thread if defined(PTHREAD) && defined(WORKER_THREAD), and in such case care may be needed depending on the platform.
It is guaranteed that the same handle is not called from different worker thread, both feed and read_digest are called from the same worker thread, while cleanup is called from the main thread once the worker thread is already finalized.
If this function returns less then the requested amount of bytes (len), then it is called again with a new mem adapted (offset) to the remaining location and reduced len, so it would do partial reads. The initial call will always be enough to hold the whole digest as specified in digest_size;
Parameters
handle the message digest handle reading the hash.
mem the pointer to memory to store the digest.
len the size in bytes of memory to store the digest.
Returns
number of bytes fed or -errno.
Referenced by sol_message_digest_common_new().
The documentation for this struct was generated from the following file:
src/lib/crypto/sol-message-digest-common.h