Soletta: sol_random_impl Struct Reference
sol_random_impl Struct Reference
Data Fields
uint32_t(* generate_uint32)(struct sol_random *engine)
bool(* init)(struct sol_random *engine, uint64_t seed)
void(* shutdown)(struct sol_random *engine)
size_t struct_size
Field Documentation
uint32_t(* sol_random_impl::generate_uint32)(struct sol_random *engine)
Referenced by sol_random_fill_buffer().
bool(* sol_random_impl::init)(struct sol_random *engine, uint64_t seed)
Referenced by sol_random_new().
void(* sol_random_impl::shutdown)(struct sol_random *engine)
Referenced by sol_random_del().
size_t sol_random_impl::struct_size
Referenced by sol_random_new().
The documentation for this struct was generated from the following file:
src/shared/sol-random.c