Soletta™ Framework: my_stream_api_config Struct Reference
my_stream_api_config Struct Reference
[stream config]
Data Fields
size_t data_buffer_size
size_t feed_size
ssize_t(* on_data)(void *user_data, struct my_stream_api_handle *handle, const struct sol_buffer *buf)
void(* on_feed_done)(void *user_data, struct my_stream_api_handle *handle, struct sol_blob *blob, int status)
const void * user_data
Detailed Description
[stream config]
Examples:
/src/samples/design_patterns/stream_sample.c.
Field Documentation
size_t my_stream_api_config::data_buffer_size
Examples:
/src/samples/design_patterns/stream_sample.c.
Referenced by my_stream_api_new().
size_t my_stream_api_config::feed_size
Examples:
/src/samples/design_patterns/stream_sample.c.
Referenced by my_stream_api_new().
ssize_t(* my_stream_api_config::on_data)(void *user_data, struct my_stream_api_handle *handle, const struct sol_buffer *buf)
Examples:
/src/samples/design_patterns/stream_sample.c.
Referenced by my_stream_api_new(), and startup().
void(* my_stream_api_config::on_feed_done)(void *user_data, struct my_stream_api_handle *handle, struct sol_blob *blob, int status)
Examples:
/src/samples/design_patterns/stream_sample.c.
Referenced by my_stream_api_new(), and startup().
const void* my_stream_api_config::user_data
Examples:
/src/samples/design_patterns/stream_sample.c.
Referenced by my_stream_api_new().
The documentation for this struct was generated from the following file:
src/samples/design_patterns/stream_sample.c