Soletta: sol_pin_mux Struct Reference
sol_pin_mux Struct Reference
#include <sol-pin-mux-modules.h>
Data Fields
int(* aio)(const int device, const int pin)
unsigned long int api_version
int(* gpio)(const int pin, const enum sol_gpio_direction dir)
int(* i2c)(const uint8_t bus)
int(* init)(void)
int(* pin_map)(const char *label, const enum sol_io_protocol prot, va_list args)
const char * plat_name
int(* pwm)(const int device, const int channel)
void(* shutdown)(void)
Field Documentation
int(* sol_pin_mux::aio)(const int device, const int pin)
Referenced by sol_pin_mux_setup_aio().
unsigned long int sol_pin_mux::api_version
API version
int(* sol_pin_mux::gpio)(const int pin, const enum sol_gpio_direction dir)
Referenced by sol_pin_mux_setup_gpio().
int(* sol_pin_mux::i2c)(const uint8_t bus)
Referenced by sol_pin_mux_setup_i2c().
int(* sol_pin_mux::init)(void)
Referenced by sol_pin_mux_select_mux().
int(* sol_pin_mux::pin_map)(const char *label, const enum sol_io_protocol prot, va_list args)
Referenced by sol_pin_mux_map().
const char* sol_pin_mux::plat_name
Name this multiplexer target platform
Referenced by sol_pin_mux_select_mux().
int(* sol_pin_mux::pwm)(const int device, const int channel)
Referenced by sol_pin_mux_setup_pwm().
void(* sol_pin_mux::shutdown)(void)
Referenced by sol_pin_mux_select_mux(), and sol_pin_mux_shutdown().
The documentation for this struct was generated from the following file:
src/lib/common/include/sol-pin-mux-modules.h