Soletta: sol_socket_class Struct Reference
sol_socket_class Struct Reference
Data Fields
int(* bind)(struct sol_socket *s, const struct sol_network_link_addr *addr)
void(* delete)(struct sol_socket *s)
int(* join_group)(struct sol_socket *s, kernel_pid_t iface, const struct sol_network_link_addr *group)
int(* recvmsg)(struct sol_socket *s, void *buf, size_t len, struct sol_network_link_addr *addr)
gnrc_pktsnip_t *(* sendmsg)(struct sol_socket *s, const void *buf, size_t len, const struct sol_network_link_addr *addr)
gnrc_nettype_t type
Field Documentation
int(* sol_socket_class::bind)(struct sol_socket *s, const struct sol_network_link_addr *addr)
Referenced by sol_socket_bind().
void(* sol_socket_class::delete)(struct sol_socket *s)
Referenced by sol_socket_del().
int(* sol_socket_class::join_group)(struct sol_socket *s, kernel_pid_t iface, const struct sol_network_link_addr *group)
Referenced by sol_socket_join_group().
int(* sol_socket_class::recvmsg)(struct sol_socket *s, void *buf, size_t len, struct sol_network_link_addr *addr)
Referenced by sol_socket_recvmsg().
gnrc_pktsnip_t*(* sol_socket_class::sendmsg)(struct sol_socket *s, const void *buf, size_t len, const struct sol_network_link_addr *addr)
Referenced by sol_socket_sendmsg().
gnrc_nettype_t sol_socket_class::type
Referenced by sol_socket_bind(), sol_socket_del(), and sol_socket_sendmsg().
The documentation for this struct was generated from the following file:
src/lib/comms/sol-socket-impl-riot.c