Soletta: src/modules/flow/process/subprocess.c File Reference
subprocess.c File Reference
#include "common.h"
#include "sol-platform-linux.h"
#include "sol-util.h"
#include "sol-util-file.h"
#include <fcntl.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <unistd.h>
Data Structures
struct write_data
Functions
void process_subprocess_close (struct sol_flow_node *node, void *data)
int process_subprocess_in_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int process_subprocess_open (struct sol_flow_node *node, void *data, const struct sol_flow_node_options *options)
int process_subprocess_signal_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int process_subprocess_start_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int process_subprocess_stop_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
Function Documentation
void process_subprocess_close (struct sol_flow_node * node, void * data)
References write_data::blob, subprocess_data::command, subprocess_data::err, subprocess_data::fork_run, subprocess_data::in, subprocess_data::out, subprocess_data::pipes, sol_blob_unref(), sol_platform_linux_fork_run_stop(), sol_vector_clear(), SOL_VECTOR_FOREACH_IDX, subprocess_data::watches, and subprocess_data::write_data.
int process_subprocess_in_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References write_data::blob, subprocess_data::fork_run, sol_vector::len, write_data::offset, subprocess_data::out, subprocess_data::pipes, sol_blob_ref(), sol_blob_unref(), sol_flow_packet_get_blob(), SOL_INT_CHECK, SOL_NULL_CHECK, sol_vector_append(), sol_vector_del(), subprocess_data::watches, and subprocess_data::write_data.
int process_subprocess_open (struct sol_flow_node * node, void * data, const struct sol_flow_node_options * options)
References subprocess_data::command, subprocess_data::err, subprocess_data::fork_run, subprocess_data::in, subprocess_data::node, subprocess_data::out, subprocess_data::pipes, SOL_INT_CHECK_GOTO, SOL_NULL_CHECK_GOTO, sol_platform_linux_fork_run(), sol_util_fd_set_flag(), sol_vector_init(), SOL_WRN, subprocess_data::watches, and subprocess_data::write_data.
int process_subprocess_signal_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References subprocess_data::fork_run, sol_flow_packet_get_irange_value(), SOL_INT_CHECK, SOL_NULL_CHECK, and sol_platform_linux_fork_run_send_signal().
int process_subprocess_start_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References subprocess_data::err, subprocess_data::fork_run, subprocess_data::in, SOL_NULL_CHECK_GOTO, sol_platform_linux_fork_run(), and subprocess_data::watches.
int process_subprocess_stop_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References subprocess_data::fork_run, and sol_platform_linux_fork_run_send_signal().