Soletta: src/bin/sol-fbp-generator/type-store.c File Reference
type-store.c File Reference
#include <errno.h>
#include <stdio.h>
#include "sol-json.h"
#include "sol-log.h"
#include "sol-missing.h"
#include "sol-str-slice.h"
#include "sol-util.h"
#include "sol-vector.h"
#include "type-store.h"
Data Structures
struct decoder
struct type_store
Macros
#define CONST_SLICE(NAME, VALUE) static const struct sol_str_slice NAME = SOL_STR_SLICE_LITERAL(VALUE)
Functions
CONST_SLICE (NAME_SLICE,"name")
CONST_SLICE (SYMBOL_SLICE,"symbol")
CONST_SLICE (OPTIONS_SYMBOL_SLICE,"options_symbol")
CONST_SLICE (IN_PORTS_SLICE,"in_ports")
CONST_SLICE (OUT_PORTS_SLICE,"out_ports")
CONST_SLICE (DATA_TYPE_SLICE,"data_type")
CONST_SLICE (ARRAY_SIZE_SLICE,"array_size")
CONST_SLICE (BASE_PORT_IDX_SLICE,"base_port_idx")
CONST_SLICE (OPTIONS_SLICE,"options")
CONST_SLICE (MEMBERS_SLICE,"members")
CONST_SLICE (DEFAULT_SLICE,"default")
CONST_SLICE (VAL_SLICE,"val")
CONST_SLICE (MIN_SLICE,"min")
CONST_SLICE (MAX_SLICE,"max")
CONST_SLICE (STEP_SLICE,"step")
CONST_SLICE (RED_SLICE,"red")
CONST_SLICE (RED_MAX_SLICE,"red_max")
CONST_SLICE (GREEN_SLICE,"green")
CONST_SLICE (GREEN_MAX_SLICE,"green_max")
CONST_SLICE (BLUE_SLICE,"blue")
CONST_SLICE (BLUE_MAX_SLICE,"blue_max")
CONST_SLICE (X_SLICE,"x")
CONST_SLICE (Y_SLICE,"y")
CONST_SLICE (Z_SLICE,"z")
bool type_store_add_type (struct type_store *store, const struct type_description *type)
bool type_store_copy_option_description (struct option_description *dst, const struct option_description *src, const struct sol_str_slice opt_name)
void type_store_del (struct type_store *store)
struct type_description * type_store_find (struct type_store *store, const char *name)
struct type_store * type_store_new (void)
void type_store_print (struct type_store *store)
bool type_store_read_from_json (struct type_store *store, struct sol_str_slice input)
Macro Definition Documentation
#define CONST_SLICE (NAME, VALUE) static const struct sol_str_slice NAME = SOL_STR_SLICE_LITERAL(VALUE)
Function Documentation
CONST_SLICE (NAME_SLICE , "name")
CONST_SLICE (SYMBOL_SLICE , "symbol")
CONST_SLICE (OPTIONS_SYMBOL_SLICE , "options_symbol")
CONST_SLICE (IN_PORTS_SLICE , "in_ports")
CONST_SLICE (OUT_PORTS_SLICE , "out_ports")
CONST_SLICE (DATA_TYPE_SLICE , "data_type")
CONST_SLICE (ARRAY_SIZE_SLICE , "array_size")
CONST_SLICE (BASE_PORT_IDX_SLICE , "base_port_idx")
CONST_SLICE (OPTIONS_SLICE , "options")
CONST_SLICE (MEMBERS_SLICE , "members")
CONST_SLICE (DEFAULT_SLICE , "default")
CONST_SLICE (VAL_SLICE , "val")
CONST_SLICE (MIN_SLICE , "min")
CONST_SLICE (MAX_SLICE , "max")
CONST_SLICE (STEP_SLICE , "step")
CONST_SLICE (RED_SLICE , "red")
CONST_SLICE (RED_MAX_SLICE , "red_max")
CONST_SLICE (GREEN_SLICE , "green")
CONST_SLICE (GREEN_MAX_SLICE , "green_max")
CONST_SLICE (BLUE_SLICE , "blue")
CONST_SLICE (BLUE_MAX_SLICE , "blue_max")
CONST_SLICE (X_SLICE , "x")
CONST_SLICE (Y_SLICE , "y")
CONST_SLICE (Z_SLICE , "z")
bool type_store_add_type (struct type_store * store, const struct type_description * type)
References port_description::array_size, port_description::base_port_idx, port_description::data_type, option_description::data_type, option_description::default_value, option_description::default_value_type, type_description::generated_options, type_description::in_ports, sol_vector::len, port_description::name, option_description::name, type_description::name, OPTION_VALUE_TYPE_STRING, type_description::options, type_description::options_symbol, type_description::out_ports, SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, sol_vector_append(), sol_vector_clear(), sol_vector_del(), SOL_VECTOR_FOREACH_IDX, sol_vector_init(), option_description::string, type_description::symbol, type_store_copy_option_description(), and type_store::types.
bool type_store_copy_option_description (struct option_description * dst, const struct option_description * src, const struct sol_str_slice opt_name)
References sol_str_slice::data, option_description::data_type, option_description::default_value, option_description::default_value_type, option_description::direction_vector, sol_str_slice::len, option_description::name, OPTION_VALUE_TYPE_DIRECTION_VECTOR, OPTION_VALUE_TYPE_NONE, OPTION_VALUE_TYPE_RGB, OPTION_VALUE_TYPE_SPEC_RANGE, OPTION_VALUE_TYPE_STRING, OPTION_VALUE_TYPE_UNPARSED_JSON, option_description::rgb, SOL_NULL_CHECK_GOTO, option_description::spec_range, option_description::string, and option_description::token.
Referenced by type_store_add_type().
void type_store_del (struct type_store * store)
References sol_vector_clear(), SOL_VECTOR_FOREACH_IDX, and type_store::types.
Referenced by main().
struct type_description* type_store_find (struct type_store * store, const char * name)
References type_description::name, SOL_VECTOR_FOREACH_IDX, streq, and type_store::types.
struct type_store* type_store_new (void)
References sol_vector_init(), and type_store::types.
Referenced by main().
void type_store_print (struct type_store * store)
References SOL_VECTOR_FOREACH_IDX, and type_store::types.
bool type_store_read_from_json (struct type_store * store, struct sol_str_slice input)
References sol_vector::len, SOL_JSON_TYPE_ARRAY_END, SOL_JSON_TYPE_ARRAY_START, SOL_JSON_TYPE_ELEMENT_SEP, SOL_JSON_TYPE_OBJECT_END, SOL_JSON_TYPE_OBJECT_START, SOL_JSON_TYPE_PAIR_SEP, SOL_JSON_TYPE_STRING, sol_vector_append(), sol_vector_del(), and type_store::types.