Soletta: src/lib/comms/coap.h File Reference
coap.h File Reference
#include <endian.h>
Data Structures
struct coap_header
struct option_context
struct sol_coap_option_value
struct sol_coap_packet
Macros
#define COAP_MARKER 0xFF
#define COAP_UDP_MTU (576)
#define COAP_VERSION 1
Functions
int coap_find_options (const struct sol_coap_packet *pkt, uint16_t code, struct sol_coap_option_value *vec, uint16_t veclen)
int coap_get_header_len (const struct sol_coap_packet *pkt)
struct sol_coap_packet * coap_new_packet (struct sol_coap_packet *old)
int coap_option_encode (struct option_context *context, uint16_t code, const void *value, uint16_t len)
int coap_packet_parse (struct sol_coap_packet *pkt)
int coap_parse_option (const struct sol_coap_packet *pkt, struct option_context *context, uint8_t **value, uint16_t *vlen)
Macro Definition Documentation
#define COAP_MARKER 0xFF
Referenced by coap_parse_option(), and sol_coap_packet_get_payload().
#define COAP_UDP_MTU (576)
Referenced by coap_packet_parse(), and sol_coap_packet_new().
#define COAP_VERSION 1
Referenced by sol_coap_packet_new().
Function Documentation
int coap_find_options (const struct sol_coap_packet * pkt, uint16_t code, struct sol_coap_option_value * vec, uint16_t veclen)
References sol_coap_packet::buf, option_context::buf, option_context::buflen, coap_get_header_len(), coap_parse_option(), option_context::delta, sol_coap_packet::payload, SOL_INT_CHECK, SOL_NULL_CHECK, sol_coap_packet::used, and option_context::used.
Referenced by sol_coap_find_first_option(), and sol_coap_send_packet_with_reply().
int coap_get_header_len (const struct sol_coap_packet * pkt)
References sol_coap_packet::buf, sol_coap_packet::payload, sol_coap_packet::size, and coap_header::tkl.
Referenced by coap_find_options(), coap_packet_parse(), and sol_coap_add_option().
struct sol_coap_packet* coap_new_packet (struct sol_coap_packet * old)
int coap_option_encode (struct option_context * context, uint16_t code, const void * value, uint16_t len)
References option_context::buf, option_context::buflen, and option_context::delta.
Referenced by sol_coap_add_option().
int coap_packet_parse (struct sol_coap_packet * pkt)
References sol_coap_packet::buf, coap_get_header_len(), COAP_UDP_MTU, sol_coap_packet::payload, sol_coap_packet::size, SOL_NULL_CHECK, sol_coap_packet::start, and sol_coap_packet::used.
int coap_parse_option (const struct sol_coap_packet * pkt, struct option_context * context, uint8_t ** value, uint16_t * vlen)
References option_context::buf, option_context::buflen, COAP_MARKER, option_context::delta, and option_context::used.
Referenced by coap_find_options(), and sol_coap_add_option().