Soletta: Data types
Data types
Data Structures
struct sol_arena
struct sol_buffer
struct sol_list
struct sol_str_table
struct sol_vector
Macros
#define SOL_BUFFER_EMPTY (struct sol_buffer){.data = NULL, .size = 0 }
Functions
int sol_buffer_copy_slice (struct sol_buffer *buf, struct sol_str_slice slice)
int sol_buffer_ensure (struct sol_buffer *buf, unsigned int min_size)
int sol_buffer_resize (struct sol_buffer *buf, unsigned int new_size)
int sol_str_slice_to_int (const struct sol_str_slice s, int *value)
#define SOL_STR_STATIC_ASSERT_LITERAL(_s) ("" _s)
#define SOL_STR_SLICE_LITERAL(_s) { sizeof(SOL_STR_STATIC_ASSERT_LITERAL(_s)) - 1, _s }
#define SOL_STR_SLICE_STR(_s, _len) (struct sol_str_slice){.len = _len, .data = _s }
#define SOL_STR_SLICE_EMPTY { .len = 0, .data = "" }
#define SOL_STR_SLICE_PRINT(_s) (int)(_s).len, (_s).data
Detailed Description
Macro Definition Documentation
#define SOL_BUFFER_EMPTY (struct sol_buffer){.data = NULL, .size = 0 }
#define SOL_STR_SLICE_EMPTY { .len = 0, .data = "" }
#define SOL_STR_SLICE_LITERAL (_s) { sizeof(SOL_STR_STATIC_ASSERT_LITERAL(_s)) - 1, _s }
#define SOL_STR_SLICE_PRINT (_s) (int)(_s).len, (_s).data
#define SOL_STR_SLICE_STR (_s, _len) (struct sol_str_slice){.len = _len, .data = _s }
#define SOL_STR_STATIC_ASSERT_LITERAL (_s) ("" _s)
Function Documentation
int sol_buffer_copy_slice (struct sol_buffer * buf, struct sol_str_slice slice)
References sol_buffer::data, sol_str_slice::len, and sol_buffer_ensure().
int sol_buffer_ensure (struct sol_buffer * buf, unsigned int min_size)
References sol_buffer::size, and sol_buffer_resize().
Referenced by sol_buffer_copy_slice().
int sol_buffer_resize (struct sol_buffer * buf, unsigned int new_size)
References sol_buffer::data, and sol_buffer::size.
Referenced by sol_buffer_ensure().
int sol_str_slice_to_int (const struct sol_str_slice s, int * value)
References sol_str_slice::data, sol_str_slice::len, and strndupa.