Soletta: Communication Libraries
Communication Libraries
Data Structures
struct sol_network_link
struct sol_network_link_addr
struct sol_oic_client
Macros
#define SOL_INET_ADDR_STRLEN 48
Enumerations
enum sol_network_event { SOL_NETWORK_LINK_ADDED, SOL_NETWORK_LINK_REMOVED, SOL_NETWORK_LINK_CHANGED }
enum sol_network_link_flags {
SOL_NETWORK_LINK_UP = 1 << 0, SOL_NETWORK_LINK_BROADCAST = 1 << 1, SOL_NETWORK_LINK_LOOPBACK = 1 << 2, SOL_NETWORK_LINK_MULTICAST = 1 << 3,
SOL_NETWORK_LINK_RUNNING = 1 << 4
}
Functions
const char * sol_network_addr_to_str (const struct sol_network_link_addr *addr, char *buf, socklen_t len)
const struct sol_vector * sol_network_get_available_links (void)
bool sol_network_init (void)
bool sol_network_link_addr_eq (const struct sol_network_link_addr *a, const struct sol_network_link_addr *b)
char * sol_network_link_get_name (const struct sol_network_link *link)
bool sol_network_link_up (unsigned int link_index)
void sol_network_shutdown (void)
bool sol_network_subscribe_events (void(*cb)(void *data, const struct sol_network_link *link, enum sol_network_event event), const void *data)
bool sol_network_unsubscribe_events (void(*cb)(void *data, const struct sol_network_link *link, enum sol_network_event event), const void *data)
enum sol_coap_option_num_t {
SOL_COAP_OPTION_IF_MATCH = 1, SOL_COAP_OPTION_URI_HOST = 3, SOL_COAP_OPTION_ETAG = 4, SOL_COAP_OPTION_IF_NONE_MATCH = 5,
SOL_COAP_OPTION_OBSERVE = 6, SOL_COAP_OPTION_URI_PORT = 7, SOL_COAP_OPTION_LOCATION_PATH = 8, SOL_COAP_OPTION_URI_PATH = 11,
SOL_COAP_OPTION_CONTENT_FORMAT = 12, SOL_COAP_OPTION_MAX_AGE = 14, SOL_COAP_OPTION_URI_QUERY = 15, SOL_COAP_OPTION_ACCEPT = 17,
SOL_COAP_OPTION_LOCATION_QUERY = 20, SOL_COAP_OPTION_PROXY_URI = 35, SOL_COAP_OPTION_PROXY_SCHEME = 39
}
bool sol_oic_server_init (int port)
void sol_oic_server_release (void)
struct sol_oic_device_definition * sol_oic_server_get_definition (struct sol_str_slice endpoint, struct sol_str_slice resource_type_prefix)
struct sol_oic_device_definition * sol_oic_server_register_definition (struct sol_str_slice endpoint, struct sol_str_slice resource_type_prefix, enum sol_coap_flags flags)
bool sol_oic_server_unregister_definition (const struct sol_oic_device_definition *definition)
struct sol_coap_resource * sol_oic_device_definition_register_resource_type (struct sol_oic_device_definition *definition, const struct sol_oic_resource_type *resource_type, void *handler_data, enum sol_coap_flags flags)
bool sol_oic_notify_observers (struct sol_coap_resource *resource, uint8_t *msg, uint16_t msg_len)
#define OIC_DEVICE_NAME "Soletta OIC Device"
#define OIC_DEVICE_RESOURCE_TYPE "oc.core"
#define OIC_DEVICE_ID "soletta0"
#define OIC_MANUFACTURER_NAME "Custom"
#define OIC_MANUFACTORER_MODEL "Custom"
#define OIC_MANUFACTORER_DATE "2015-01-01"
#define OIC_INTERFACE_VERSION "1.0"
#define OIC_PLATFORM_VERSION "1.0"
#define OIC_FIRMWARE_VERSION "1.0"
#define OIC_SUPPORT_LINK "http://solettaproject.org/support/"
#define OIC_LOCATION "Unknown"
#define OIC_EPI ""
Detailed Description
Macro Definition Documentation
#define OIC_DEVICE_ID "soletta0"
#define OIC_DEVICE_NAME "Soletta OIC Device"
#define OIC_DEVICE_RESOURCE_TYPE "oc.core"
#define OIC_EPI ""
#define OIC_FIRMWARE_VERSION "1.0"
#define OIC_INTERFACE_VERSION "1.0"
#define OIC_LOCATION "Unknown"
#define OIC_MANUFACTORER_DATE "2015-01-01"
#define OIC_MANUFACTORER_MODEL "Custom"
#define OIC_MANUFACTURER_NAME "Custom"
#define OIC_PLATFORM_VERSION "1.0"
#define OIC_SUPPORT_LINK "http://solettaproject.org/support/"
#define SOL_INET_ADDR_STRLEN 48
Referenced by sol_coap_packet_send_notification(), and sol_coap_send_packet_with_reply().
Enumeration Type Documentation
enum sol_coap_option_num_t
Enumerator
SOL_COAP_OPTION_IF_MATCH
SOL_COAP_OPTION_URI_HOST
SOL_COAP_OPTION_ETAG
SOL_COAP_OPTION_IF_NONE_MATCH
SOL_COAP_OPTION_OBSERVE
SOL_COAP_OPTION_URI_PORT
SOL_COAP_OPTION_LOCATION_PATH
SOL_COAP_OPTION_URI_PATH
SOL_COAP_OPTION_CONTENT_FORMAT
SOL_COAP_OPTION_MAX_AGE
SOL_COAP_OPTION_URI_QUERY
SOL_COAP_OPTION_ACCEPT
SOL_COAP_OPTION_LOCATION_QUERY
SOL_COAP_OPTION_PROXY_URI
SOL_COAP_OPTION_PROXY_SCHEME
enum sol_network_event
Enumerator
SOL_NETWORK_LINK_ADDED
SOL_NETWORK_LINK_REMOVED
SOL_NETWORK_LINK_CHANGED
enum sol_network_link_flags
Enumerator
SOL_NETWORK_LINK_UP
SOL_NETWORK_LINK_BROADCAST
SOL_NETWORK_LINK_LOOPBACK
SOL_NETWORK_LINK_MULTICAST
SOL_NETWORK_LINK_RUNNING
Function Documentation
const char* sol_network_addr_to_str (const struct sol_network_link_addr * addr, char * buf, socklen_t len)
References sol_network_link_addr::addr, sol_network_link_addr::family, and SOL_NULL_CHECK.
Referenced by sol_coap_packet_send_notification(), and sol_coap_send_packet_with_reply().
const struct sol_vector* sol_network_get_available_links (void)
References sol_network::links, and SOL_NULL_CHECK.
Referenced by sol_coap_server_new().
bool sol_network_init (void)
References sol_network_link_addr::addr, sol_network_link::addrs, sol_network_link::api_version, sol_network::callbacks, sol_network::count, sol_network_link_addr::family, sol_network::fd, sol_network_link::flags, sol_network_link_addr::in6, sol_network_link::index, sol_network::links, sol_network::nl_addr, sol_network::nl_socket, sol_network::seq, SOCK_CLOEXEC, sol_fd_add(), SOL_FD_FLAGS_ERR, SOL_FD_FLAGS_HUP, SOL_FD_FLAGS_IN, SOL_LOG_INTERNAL_INIT_ONCE, SOL_NETWORK_LINK_API_VERSION, SOL_NETWORK_LINK_UP, SOL_NULL_CHECK, sol_vector_append(), sol_vector_init(), and SOL_WRN.
Referenced by sol_coap_server_new().
bool sol_network_link_addr_eq (const struct sol_network_link_addr * a, const struct sol_network_link_addr * b)
References sol_network_link_addr::addr, sol_network_link_addr::family, sol_network_link_addr::in, sol_network_link_addr::in6, and SOL_WRN.
char* sol_network_link_get_name (const struct sol_network_link * link)
References sol_network_link::api_version, sol_network_link::index, SOL_NULL_CHECK, SOL_WRN, and unlikely.
Referenced by sol_coap_server_new().
bool sol_network_link_up (unsigned int link_index)
References ADD_RTATTR, IFLA_INET6_ADDR_GEN_MODE, IN6_ADDR_GEN_MODE_EUI64, sol_network::nl_socket, sol_network::seq, SOL_API, SOL_NULL_CHECK, and SOL_WRN.
void sol_network_shutdown (void)
References sol_network_link_addr::addr, sol_network_link::addrs, sol_network::callbacks, sol_network::count, sol_network::fd, sol_network::links, sol_network::nl_socket, sol_fd_del(), sol_vector_clear(), sol_vector_del(), SOL_VECTOR_FOREACH_IDX, and SOL_VECTOR_FOREACH_REVERSE_IDX.
bool sol_network_subscribe_events (void(*)(void *data, const struct sol_network_link *link, enum sol_network_event event) cb, const void * data)
References sol_network::callbacks, callback::cb, callback::data, SOL_NULL_CHECK, and sol_vector_append().
Referenced by sol_coap_server_new().
bool sol_network_unsubscribe_events (void(*)(void *data, const struct sol_network_link *link, enum sol_network_event event) cb, const void * data)
References sol_network::callbacks, callback::cb, callback::data, SOL_NULL_CHECK, sol_vector_del(), and SOL_VECTOR_FOREACH_IDX.
struct sol_coap_resource* sol_oic_device_definition_register_resource_type (struct sol_oic_device_definition * definition, const struct sol_oic_resource_type * resource_type, void * handler_data, enum sol_coap_flags flags)
References sol_oic_resource_type::api_version, resource_type_data::data, sol_coap_resource::delete, sol_oic_resource_type::endpoint, sol_coap_resource::flags, sol_coap_resource::get, sol_oic_resource_type::iface, sol_coap_resource::iface, sol_vector::len, OIC_SERVER_CHECK, sol_coap_resource::post, sol_coap_resource::put, resource_type_data::resource, resource_type_data::resource_type, sol_oic_resource_type::resource_type, sol_coap_resource::resource_type, sol_oic_device_definition::resource_types, sol_oic_server::server, sol_coap_server_register_resource(), SOL_NULL_CHECK, SOL_OIC_RESOURCE_TYPE_API_VERSION, sol_util_memdup(), sol_vector_append(), sol_vector_del(), SOL_WRN, and unlikely.
bool sol_oic_notify_observers (struct sol_coap_resource * resource, uint8_t * msg, uint16_t msg_len)
References sol_coap_resource::path, sol_coap_packet::payload, sol_oic_server::server, sol_coap_header_set_code(), sol_coap_packet_get_payload(), sol_coap_packet_notification_new(), sol_coap_packet_send_notification(), sol_coap_packet_set_payload_used(), sol_coap_packet_unref(), SOL_COAP_RSPCODE_CONTENT, SOL_COAP_RSPCODE_INTERNAL_ERROR, and SOL_NULL_CHECK.
struct sol_oic_device_definition* sol_oic_server_get_definition (struct sol_str_slice endpoint, struct sol_str_slice resource_type_prefix)
References sol_oic_server::device_definitions, sol_oic_device_definition::endpoint, OIC_SERVER_CHECK, sol_oic_device_definition::resource_type_prefix, and SOL_VECTOR_FOREACH_IDX.
Referenced by sol_oic_server_register_definition().
bool sol_oic_server_init (int port)
References sol_oic_server::device_definitions, sol_oic_server::information, sol_oic_server::refcnt, sol_oic_server::server, sol_coap_server_new(), sol_coap_server_register_resource(), SOL_LOG_INTERNAL_INIT_ONCE, SOL_NULL_CHECK, and sol_vector_init().
Referenced by main().
struct sol_oic_device_definition* sol_oic_server_register_definition (struct sol_str_slice endpoint, struct sol_str_slice resource_type_prefix, enum sol_coap_flags flags)
References sol_oic_server::device_definitions, sol_oic_device_definition::endpoint, sol_coap_resource::flags, sol_coap_resource::get, sol_vector::len, OIC_SERVER_CHECK, sol_oic_device_definition::resource, sol_coap_resource::resource_type, sol_oic_device_definition::resource_type_prefix, sol_oic_device_definition::resource_types, sol_oic_server::server, sol_coap_server_register_resource(), SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, sol_oic_server_get_definition(), sol_vector_append(), sol_vector_del(), and sol_vector_init().
void sol_oic_server_release (void)
References sol_oic_server::device_definitions, sol_oic_server::information, OIC_SERVER_CHECK, sol_oic_server::refcnt, sol_oic_server::server, sol_coap_server_unref(), and sol_vector_clear().
Referenced by main().
bool sol_oic_server_unregister_definition (const struct sol_oic_device_definition * definition)
References sol_oic_server::device_definitions, sol_oic_device_definition::endpoint, OIC_SERVER_CHECK, sol_oic_device_definition::resource, sol_oic_device_definition::resource_type_prefix, SOL_NULL_CHECK, sol_vector_del(), and SOL_VECTOR_FOREACH_REVERSE_IDX.