Soletta: Platform
Platform
Macros
#define CHUNK_MAX_TIME_NS (20 * (NSEC_PER_MSEC))
#define CHUNK_READ_MAX (10 * (CHUNK_READ_SIZE))
#define CHUNK_READ_SIZE 1024
#define SOL_PLATFORM_TARGET_DEFAULT "default"
#define SOL_PLATFORM_TARGET_EMERGENCY "emergency"
#define SOL_PLATFORM_TARGET_POWEROFF "poweroff"
#define SOL_PLATFORM_TARGET_REBOOT "reboot"
#define SOL_PLATFORM_TARGET_RESCUE "rescue"
#define SOL_PLATFORM_TARGET_SUSPEND "suspend"
Enumerations
enum sol_platform_service_state {
SOL_PLATFORM_SERVICE_STATE_ACTIVE, SOL_PLATFORM_SERVICE_STATE_RELOADING, SOL_PLATFORM_SERVICE_STATE_INACTIVE, SOL_PLATFORM_SERVICE_STATE_FAILED,
SOL_PLATFORM_SERVICE_STATE_ACTIVATING, SOL_PLATFORM_SERVICE_STATE_DEACTIVATING, SOL_PLATFORM_SERVICE_STATE_UNKNOWN = -1
}
enum sol_platform_state {
SOL_PLATFORM_STATE_INITIALIZING, SOL_PLATFORM_STATE_RUNNING, SOL_PLATFORM_STATE_DEGRADED, SOL_PLATFORM_STATE_MAINTENANCE,
SOL_PLATFORM_STATE_STOPPING, SOL_PLATFORM_STATE_UNKNOWN = -1
}
Functions
int sol_platform_add_service_monitor (void(*cb)(void *data, const char *service, enum sol_platform_service_state state), const char *service, const void *data)
int sol_platform_add_state_monitor (void(*cb)(void *data, enum sol_platform_state state), const void *data)
int sol_platform_del_service_monitor (void(*cb)(void *data, const char *service, enum sol_platform_service_state state), const char *service, const void *data)
int sol_platform_del_state_monitor (void(*cb)(void *data, enum sol_platform_state state), const void *data)
const char * sol_platform_get_name (void)
enum sol_platform_service_state sol_platform_get_service_state (const char *service)
int sol_platform_get_state (void)
int sol_platform_restart_service (const char *service)
int sol_platform_set_target (const char *target)
int sol_platform_start_service (const char *service)
int sol_platform_stop_service (const char *service)
Detailed Description
Macro Definition Documentation
#define CHUNK_MAX_TIME_NS (20 * (NSEC_PER_MSEC))
#define CHUNK_READ_MAX (10 * (CHUNK_READ_SIZE))
#define CHUNK_READ_SIZE 1024
#define SOL_PLATFORM_TARGET_DEFAULT "default"
Referenced by sol_platform_impl_set_target().
#define SOL_PLATFORM_TARGET_EMERGENCY "emergency"
Referenced by sol_platform_impl_set_target().
#define SOL_PLATFORM_TARGET_POWEROFF "poweroff"
Referenced by sol_platform_impl_set_target().
#define SOL_PLATFORM_TARGET_REBOOT "reboot"
Referenced by sol_platform_impl_set_target().
#define SOL_PLATFORM_TARGET_RESCUE "rescue"
Referenced by sol_platform_impl_set_target().
#define SOL_PLATFORM_TARGET_SUSPEND "suspend"
Referenced by sol_platform_impl_set_target().
Enumeration Type Documentation
enum sol_platform_service_state
Enumerator
SOL_PLATFORM_SERVICE_STATE_ACTIVE
SOL_PLATFORM_SERVICE_STATE_RELOADING
SOL_PLATFORM_SERVICE_STATE_INACTIVE
SOL_PLATFORM_SERVICE_STATE_FAILED
SOL_PLATFORM_SERVICE_STATE_ACTIVATING
SOL_PLATFORM_SERVICE_STATE_DEACTIVATING
SOL_PLATFORM_SERVICE_STATE_UNKNOWN
enum sol_platform_state
Enumerator
SOL_PLATFORM_STATE_INITIALIZING
SOL_PLATFORM_STATE_RUNNING
SOL_PLATFORM_STATE_DEGRADED
SOL_PLATFORM_STATE_MAINTENANCE
SOL_PLATFORM_STATE_STOPPING
SOL_PLATFORM_STATE_UNKNOWN
Function Documentation
int sol_platform_add_service_monitor (void(*)(void *data, const char *service, enum sol_platform_service_state state) cb, const char * service, const void * data)
References service_monitor::service, ctx::service_monitors, SOL_INT_CHECK_GOTO, sol_monitors_del(), SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, sol_platform_impl_add_service_monitor(), SOL_PLATFORM_SERVICE_STATE_UNKNOWN, and service_monitor::state.
int sol_platform_add_state_monitor (void(*)(void *data, enum sol_platform_state state) cb, const void * data)
References sol_monitors_entry::cb, SOL_NULL_CHECK, and ctx::state_monitors.
Referenced by main().
int sol_platform_del_service_monitor (void(*)(void *data, const char *service, enum sol_platform_service_state state) cb, const char * service, const void * data)
References service_monitor::base, sol_monitors_entry::cb, sol_monitors_entry::data, service_monitor::service, ctx::service_monitors, sol_monitors_del(), SOL_MONITORS_WALK, SOL_NULL_CHECK, and streq.
int sol_platform_del_state_monitor (void(*)(void *data, enum sol_platform_state state) cb, const void * data)
References sol_monitors_entry::cb, sol_monitors_del(), sol_monitors_find(), SOL_NULL_CHECK, and ctx::state_monitors.
Referenced by main().
const char* sol_platform_get_name (void)
References sol_platform_detect(), sol_platform_invalid_name(), and SOL_PLATFORM_NAME_ENVVAR.
Referenced by sol_pin_mux_init().
enum sol_platform_service_state sol_platform_get_service_state (const char * service)
References SOL_PLATFORM_SERVICE_STATE_UNKNOWN, and service_monitor::state.
int sol_platform_get_state (void)
References sol_platform_impl_get_state().
Referenced by main().
int sol_platform_restart_service (const char * service)
References SOL_NULL_CHECK, and sol_platform_impl_restart_service().
int sol_platform_set_target (const char * target)
References SOL_NULL_CHECK, and sol_platform_impl_set_target().
int sol_platform_start_service (const char * service)
References SOL_NULL_CHECK, and sol_platform_impl_start_service().
int sol_platform_stop_service (const char * service)
References SOL_NULL_CHECK, and sol_platform_impl_stop_service().