Soletta: I/O
I/O
Data Structures
struct sol_gpio_config
Enumerations
enum sol_gpio_direction { SOL_GPIO_DIR_UNDEFINED = -1, SOL_GPIO_DIR_OUT = 0, SOL_GPIO_DIR_IN = 1 }
enum sol_gpio_drive { SOL_GPIO_DRIVE_NONE = 0, SOL_GPIO_DRIVE_PULL_UP, SOL_GPIO_DRIVE_PULL_DOWN }
enum sol_gpio_edge { SOL_GPIO_EDGE_NONE = 0, SOL_GPIO_EDGE_RISING, SOL_GPIO_EDGE_FALLING, SOL_GPIO_EDGE_BOTH }
Functions
void sol_gpio_close (struct sol_gpio *gpio)
struct sol_gpio * sol_gpio_open (int pin, const struct sol_gpio_config *config) SOL_ATTR_WARN_UNUSED_RESULT
struct sol_gpio * sol_gpio_open_raw (int pin, const struct sol_gpio_config *config) SOL_ATTR_WARN_UNUSED_RESULT
int sol_gpio_read (struct sol_gpio *gpio)
bool sol_gpio_write (struct sol_gpio *gpio, bool value)
Detailed Description
These routines are used for general I/O access under Solleta (namely GPIO, PWM, SPI, UART and I2C).
Enumeration Type Documentation
enum sol_gpio_direction
Enumerator
SOL_GPIO_DIR_UNDEFINED
SOL_GPIO_DIR_OUT
SOL_GPIO_DIR_IN
enum sol_gpio_drive
Enumerator
SOL_GPIO_DRIVE_NONE
SOL_GPIO_DRIVE_PULL_UP
SOL_GPIO_DRIVE_PULL_DOWN
enum sol_gpio_edge
Enumerator
SOL_GPIO_EDGE_NONE
SOL_GPIO_EDGE_RISING
SOL_GPIO_EDGE_FALLING
SOL_GPIO_EDGE_BOTH
Function Documentation
void sol_gpio_close (struct sol_gpio * gpio)
References sol_gpio::fd_watch, sol_gpio::fp, sol_gpio::int_handler, sol_gpio::irq, sol_gpio::owned, sol_gpio::pin, sol_fd_del(), sol_interrupt_scheduler_gpio_stop(), SOL_NULL_CHECK, sol_timeout_del(), and sol_gpio::timer.
Referenced by sol_gpio_open(), and sol_gpio_open_raw().
struct sol_gpio* sol_gpio_open (int pin, const struct sol_gpio_config * config)
References sol_gpio_config::dir, SOL_ERR, sol_gpio_close(), sol_gpio_open_raw(), SOL_LOG_INTERNAL_INIT_ONCE, SOL_NULL_CHECK, and sol_pin_mux_setup_gpio().
struct sol_gpio* sol_gpio_open_raw (int pin, const struct sol_gpio_config * config)
References sol_gpio::active_low, sol_gpio_config::active_low, sol_gpio_config::api_version, sol_gpio::cb, sol_gpio::data, sol_gpio_config::dir, sol_gpio_config::drive_mode, GPIO_BASE, sol_gpio_config::in, sol_gpio::int_handler, sol_gpio::irq, sol_gpio_config::out, sol_gpio::owned, sol_gpio::pin, sol_gpio_close(), SOL_GPIO_CONFIG_API_VERSION, SOL_GPIO_DIR_OUT, SOL_GPIO_DRIVE_NONE, SOL_GPIO_DRIVE_PULL_DOWN, SOL_GPIO_DRIVE_PULL_UP, SOL_GPIO_EDGE_BOTH, SOL_GPIO_EDGE_FALLING, SOL_GPIO_EDGE_NONE, SOL_GPIO_EDGE_RISING, sol_gpio_write(), sol_interrupt_scheduler_gpio_init_int(), SOL_LOG_INTERNAL_INIT_ONCE, SOL_NULL_CHECK, SOL_WRN, and unlikely.
Referenced by sol_gpio_open().
int sol_gpio_read (struct sol_gpio * gpio)
References sol_gpio::active_low, sol_gpio::fp, sol_gpio::pin, SOL_NULL_CHECK, and SOL_WRN.
bool sol_gpio_write (struct sol_gpio * gpio, bool value)
References sol_gpio::active_low, sol_gpio::fp, sol_gpio::pin, and SOL_NULL_CHECK.
Referenced by sol_gpio_open_raw().