Soletta: src/modules/flow/gtk/gtk.c File Reference
gtk.c File Reference
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include "common.h"
#include "gtk-gen.h"
#include "sol-mainloop.h"
#include "sol-util.h"
#include "sol-vector.h"
#include "byte-editor.h"
#include "label.h"
#include "led.h"
#include "pushbutton.h"
#include "pwm-editor.h"
#include "pwm-viewer.h"
#include "rgb-editor.h"
#include "slider.h"
#include "spinbutton.h"
#include "toggle.h"
#include "window.h"
#include "gtk-gen.c"
Data Structures
struct gtk_state
Functions
void gtk_close (struct sol_flow_node *node, void *data)
int gtk_open (struct sol_flow_node *node, void *data, int(*setup_cb)(struct gtk_common_data *mdata, const struct sol_flow_node_options *options), const struct sol_flow_node_options *options)
SOL_LOG_INTERNAL_DECLARE (_gtk_log_domain,"flow-gtk")
Function Documentation
void gtk_close (struct sol_flow_node * node, void * data)
References gtk_state::nodes, gtk_common_data::widget, gtk_state::window, and window_del_widget().
int gtk_open (struct sol_flow_node * node, void * data, int(*)(struct gtk_common_data *mdata, const struct sol_flow_node_options *options) setup_cb, const struct sol_flow_node_options * options)
References gtk_common_data::node, gtk_state::nodes, sol_flow_node_get_id(), SOL_NULL_CHECK, gtk_common_data::widget, gtk_state::window, and window_add_widget().
SOL_LOG_INTERNAL_DECLARE (_gtk_log_domain , "flow-gtk")