Soletta: src/modules/flow/gtk/common.h File Reference
common.h File Reference
#include <errno.h>
#include <gtk/gtk.h>
#include "sol-log-internal.h"
#include "sol-flow.h"
#include "sol-util.h"
Data Structures
struct gtk_common_data
Macros
#define DEFINE_DEFAULT_CLOSE(NAME)
#define DEFINE_DEFAULT_HEADER(NAME)
#define DEFINE_DEFAULT_OPEN(NAME)
#define DEFINE_DEFAULT_OPEN_CLOSE(NAME)
#define SOL_LOG_DOMAIN &_gtk_log_domain
Functions
void gtk_close (struct sol_flow_node *node, void *data)
int gtk_open (struct sol_flow_node *node, void *data, int(*setup_cb)(struct gtk_common_data *mdata, const struct sol_flow_node_options *options), const struct sol_flow_node_options *options)
Variables
struct sol_log_domain _gtk_log_domain
Macro Definition Documentation
#define DEFINE_DEFAULT_CLOSE (NAME)
Value:
void                                                   \
    gtk_ ## NAME ## _close(struct sol_flow_node *node, void *data) \
    {                                                             \
        return gtk_close(node, data);                             \
    }
#define DEFINE_DEFAULT_HEADER (NAME)
Value:
int gtk_ ## NAME ## _open(struct sol_flow_node *node, void *data,       \
    const struct sol_flow_node_options *options); \
    void gtk_ ## NAME ## _close(struct sol_flow_node *node, void *data);
#define DEFINE_DEFAULT_OPEN (NAME)
Value:
int                                                      \
    gtk_ ## NAME ## _open(struct sol_flow_node *node, void *data,    \
    const struct sol_flow_node_options *options)             \
    {                                                               \
        return gtk_open(node, data, NAME ## _setup, options);       \
    }
#define DEFINE_DEFAULT_OPEN_CLOSE (NAME)
Value:
DEFINE_DEFAULT_OPEN(NAME);          \
    DEFINE_DEFAULT_CLOSE(NAME);
#define SOL_LOG_DOMAIN &_gtk_log_domain
Function Documentation
void gtk_close (struct sol_flow_node * node, void * data)
References gtk_state::nodes, gtk_common_data::widget, gtk_state::window, and window_del_widget().
int gtk_open (struct sol_flow_node * node, void * data, int(*)(struct gtk_common_data *mdata, const struct sol_flow_node_options *options) setup_cb, const struct sol_flow_node_options * options)
References gtk_common_data::node, gtk_state::nodes, sol_flow_node_get_id(), SOL_NULL_CHECK, gtk_common_data::widget, gtk_state::window, and window_add_widget().
Variable Documentation
struct sol_log_domain _gtk_log_domain