Soletta: src/modules/flow/gtk/led.c File Reference
led.c File Reference
#include <math.h>
#include "led.h"
#include "gtk-gen.h"
#include "sol-types.h"
Macros
#define LED_VIEW_DIMENSION (50)
#define RGB_VALUE_MAX (255)
Functions
DEFINE_DEFAULT_OPEN_CLOSE (led)
int gtk_led_in_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
Macro Definition Documentation
#define LED_VIEW_DIMENSION (50)
#define RGB_VALUE_MAX (255)
Referenced by gtk_led_in_process().
Function Documentation
DEFINE_DEFAULT_OPEN_CLOSE (led)
int gtk_led_in_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References gtk_led_data::b, gtk_led_data::base, sol_rgb::blue, gtk_led_data::g, sol_rgb::green, gtk_led_data::on, gtk_led_data::r, sol_rgb::red, RGB_VALUE_MAX, sol_flow_packet_get_boolean(), sol_flow_packet_get_irange_value(), sol_flow_packet_get_rgb(), sol_flow_packet_get_type(), SOL_FLOW_PACKET_TYPE_BOOLEAN, SOL_FLOW_PACKET_TYPE_IRANGE, SOL_FLOW_PACKET_TYPE_RGB, SOL_INT_CHECK, sol_rgb_set_max(), SOL_WRN, and gtk_common_data::widget.