Soletta: src/modules/flow/process/common.h File Reference
common.h File Reference
#include "sol-log-internal.h"
#include "process-gen.h"
#include "sol-mainloop.h"
#include "sol-flow-internal.h"
Data Structures
struct subprocess_data
Macros
#define SOL_LOG_DOMAIN &_process_log_domain
Functions
void process_log_init (void)
void process_stderr_close (struct sol_flow_node *node, void *data)
int process_stderr_closed_connect (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id)
int process_stderr_in_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int process_stderr_open (struct sol_flow_node *node, void *data, const struct sol_flow_node_options *options)
int process_stdin_closed_connect (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id)
int process_stdin_closed_disconnect (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id)
int process_stdin_out_connect (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id)
int process_stdin_out_disconnect (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id)
void process_stdout_close (struct sol_flow_node *node, void *data)
int process_stdout_closed_connect (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id)
int process_stdout_in_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int process_stdout_open (struct sol_flow_node *node, void *data, const struct sol_flow_node_options *options)
void process_subprocess_close (struct sol_flow_node *node, void *data)
int process_subprocess_in_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int process_subprocess_open (struct sol_flow_node *node, void *data, const struct sol_flow_node_options *options)
int process_subprocess_signal_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int process_subprocess_start_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
int process_subprocess_stop_process (struct sol_flow_node *node, void *data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet *packet)
Variables
struct sol_log_domain _process_log_domain
Macro Definition Documentation
#define SOL_LOG_DOMAIN &_process_log_domain
Function Documentation
void process_log_init (void)
void process_stderr_close (struct sol_flow_node * node, void * data)
int process_stderr_closed_connect (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id)
int process_stderr_in_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
int process_stderr_open (struct sol_flow_node * node, void * data, const struct sol_flow_node_options * options)
int process_stdin_closed_connect (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id)
References stdin_monitor::closeds, and sol_flow_send_boolean_packet().
int process_stdin_closed_disconnect (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id)
References stdin_monitor::closeds.
int process_stdin_out_connect (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id)
References stdin_monitor::chunks.
int process_stdin_out_disconnect (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id)
References stdin_monitor::chunks.
void process_stdout_close (struct sol_flow_node * node, void * data)
int process_stdout_closed_connect (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id)
int process_stdout_in_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
int process_stdout_open (struct sol_flow_node * node, void * data, const struct sol_flow_node_options * options)
void process_subprocess_close (struct sol_flow_node * node, void * data)
References write_data::blob, subprocess_data::command, subprocess_data::fork_run, subprocess_data::pipes, sol_blob_unref(), sol_fd_del(), sol_platform_linux_fork_run_stop(), sol_vector_clear(), SOL_VECTOR_FOREACH_IDX, subprocess_data::stderr, subprocess_data::stdin, subprocess_data::stdout, subprocess_data::watches, and subprocess_data::write_data.
int process_subprocess_in_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References write_data::blob, subprocess_data::fork_run, sol_vector::len, write_data::offset, subprocess_data::pipes, sol_blob_ref(), sol_blob_unref(), sol_fd_add(), SOL_FD_FLAGS_OUT, sol_flow_packet_get_blob(), SOL_INT_CHECK, SOL_NULL_CHECK, sol_vector_append(), sol_vector_del(), subprocess_data::stdout, subprocess_data::watches, and subprocess_data::write_data.
int process_subprocess_open (struct sol_flow_node * node, void * data, const struct sol_flow_node_options * options)
References subprocess_data::command, subprocess_data::fork_run, subprocess_data::node, subprocess_data::pipes, sol_fd_del(), SOL_INT_CHECK_GOTO, SOL_NULL_CHECK_GOTO, sol_platform_linux_fork_run(), sol_util_fd_set_flag(), sol_vector_init(), SOL_WRN, subprocess_data::stderr, subprocess_data::stdin, subprocess_data::stdout, subprocess_data::watches, and subprocess_data::write_data.
int process_subprocess_signal_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References subprocess_data::fork_run, sol_flow_packet_get_irange_value(), SOL_INT_CHECK, SOL_NULL_CHECK, and sol_platform_linux_fork_run_get_pid().
int process_subprocess_start_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References subprocess_data::fork_run, sol_fd_del(), SOL_NULL_CHECK_GOTO, sol_platform_linux_fork_run(), subprocess_data::stderr, subprocess_data::stdin, and subprocess_data::watches.
int process_subprocess_stop_process (struct sol_flow_node * node, void * data, uint16_t port, uint16_t conn_id, const struct sol_flow_packet * packet)
References subprocess_data::fork_run, and sol_platform_linux_fork_run_get_pid().
Variable Documentation
struct sol_log_domain _process_log_domain