Soletta: src/bin/sol-fbp-runner/runner.h File Reference
runner.h File Reference
Functions
void runner_del (struct runner *r)
struct runner * runner_new (const char *filename, bool provide_sim_nodes)
int runner_run (struct runner *r)
Function Documentation
void runner_del (struct runner * r)
References runner::basename, runner::builder, runner::dirname, runner::parser, runner::root, sol_flow_builder_del(), sol_flow_node_del(), and sol_flow_parser_del().
Referenced by runner_new().
struct runner* runner_new (const char * filename, bool provide_sim_nodes)
References sol_flow_parser_client::api_version, runner::basename, sol_flow_parser_client::data, runner::dirname, runner::file_readers, filename, runner::filename, runner::parser, runner::parser_client, sol_flow_parser_client::read_file, runner::root_type, runner_del(), sol_flow_parse_buffer(), SOL_FLOW_PARSER_CLIENT_API_VERSION, sol_flow_parser_new(), and SOL_NULL_CHECK.
int runner_run (struct runner * r)
References runner::filename, runner::root, runner::root_type, and sol_flow_node_new().