Soletta: src/lib/flow/include/sol-flow-static.h File Reference
sol-flow-static.h File Reference
#include "sol-flow.h"
Data Structures
struct sol_flow_static_conn_spec
struct sol_flow_static_node_spec
struct sol_flow_static_port_spec
struct sol_flow_static_spec
Macros
#define SOL_FLOW_STATIC_API_VERSION (1)
#define SOL_FLOW_STATIC_CONN_SPEC_GUARD { .src = UINT16_MAX }
#define SOL_FLOW_STATIC_NODE_SPEC_GUARD { }
#define SOL_FLOW_STATIC_PORT_SPEC_GUARD { .node = UINT16_MAX }
Functions
struct sol_flow_node * sol_flow_static_get_node (struct sol_flow_node *node, uint16_t index)
struct sol_flow_node * sol_flow_static_new (struct sol_flow_node *parent, const struct sol_flow_static_node_spec nodes[], const struct sol_flow_static_conn_spec conns[])
struct sol_flow_node_type * sol_flow_static_new_type (const struct sol_flow_static_spec *spec)
Macro Definition Documentation
#define SOL_FLOW_STATIC_API_VERSION (1)
Referenced by sol_flow_builder_get_node_type(), sol_flow_static_new(), and sol_flow_static_new_type().
#define SOL_FLOW_STATIC_CONN_SPEC_GUARD { .src = UINT16_MAX }
#define SOL_FLOW_STATIC_NODE_SPEC_GUARD { }
#define SOL_FLOW_STATIC_PORT_SPEC_GUARD { .node = UINT16_MAX }
Function Documentation
struct sol_flow_node* sol_flow_static_get_node (struct sol_flow_node * node, uint16_t index)
Get a container node's children node by index
Parameters
node The node to get the child node from
index The index of the child node in node (position in the sol_flow_static_node_spec array)
Returns
The child node of node with the given index or NULL, on errors.
References EBADR, flow_static_type::node_count, flow_static_data::nodes, sol_flow_node_get_private_data(), SOL_FLOW_STATIC_TYPE_CHECK, SOL_NULL_CHECK, and sol_flow_node::type.
struct sol_flow_node* sol_flow_static_new (struct sol_flow_node * parent, const struct sol_flow_static_node_spec nodes[], const struct sol_flow_static_conn_spec conns[])
Creates a new "static flow" node.
Nodes should be created in the sol_main_callbacks::startup function, and at least the root one must be a "static flow" node. This function will create one of those "by hand", if all the child nodes and connections are provided.
Parameters
parent The parent node. Pass NULL if you're creating the root node of the flow.
nodes A SOL_FLOW_STATIC_PORT_SPEC_GUARD terminated array of node specification structs
conns A SOL_FLOW_STATIC_CONN_SPEC_GUARD terminated array of port connections of the nodes declared in nodes. This array must be sorted by node index and port indexes.
For a higher level construct to get your root static flow node, consider using sol_flow_builder_new() family of functions.
See Also
sol_flow_new(), sol_flow_builder_get_node_type() and sol_flow_static_new_type().
Returns
A new node instance on success, otherwise NULL.
References sol_flow_static_spec::api_version, flow_static_type::base, sol_flow_node_container_type::base, sol_flow_static_spec::conns, sol_flow_static_spec::nodes, flow_static_type::owned_by_node, sol_flow_node_new(), sol_flow_node_type_del(), SOL_FLOW_STATIC_API_VERSION, and sol_flow_static_new_type().
struct sol_flow_node_type* sol_flow_static_new_type (const struct sol_flow_static_spec * spec)
Creates a new "static flow" (container) type.
This allows one to create a static flow type "by hand" and fine- tune it. Exported input/output ports may be declared, as well as options forwarding.
Parameters
spec A specification of the type to be created. The data inside the spec is assumed to still be valid until the type is deleted.
Returns
A new container node type on success, otherwise NULL.
References sol_flow_static_spec::api_version, flow_static_type::base, sol_flow_node_container_type::base, SOL_FLOW_STATIC_API_VERSION, SOL_NULL_CHECK, and SOL_WRN.
Referenced by sol_flow_builder_get_node_type(), and sol_flow_static_new().