Soletta: src/lib/common/sol-platform-linux-common.c File Reference
sol-platform-linux-common.c File Reference
#include <errno.h>
#include <signal.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>
#include "sol-mainloop.h"
#include "sol-platform-impl.h"
#include "sol-platform-linux.h"
#include "sol-platform.h"
#include "sol-vector.h"
#include "sol-util.h"
Data Structures
struct sol_platform_linux_fork_run
Functions
SOL_API struct
sol_platform_linux_fork_run * sol_platform_linux_fork_run (void(*on_fork)(void *data), void(*on_child_exit)(void *data, uint64_t pid, int status), const void *data)
SOL_API pid_t sol_platform_linux_fork_run_get_pid (const struct sol_platform_linux_fork_run *handle)
SOL_API void sol_platform_linux_fork_run_stop (struct sol_platform_linux_fork_run *handle)
Function Documentation
SOL_API struct sol_platform_linux_fork_run* sol_platform_linux_fork_run (void(*)(void *data) on_fork, void(*)(void *data, uint64_t pid, int status) on_child_exit, const void * data)
References sol_platform_linux_fork_run::data, sol_platform_linux_fork_run::on_child_exit, sol_platform_linux_fork_run::pid, sol_child_watch_add(), sol_child_watch_del(), SOL_INT_CHECK_GOTO, SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, sol_ptr_vector_append(), sol_util_strerrora, SOL_WRN, and sol_platform_linux_fork_run::watch.
Referenced by process_subprocess_open(), and process_subprocess_start_process().
SOL_API pid_t sol_platform_linux_fork_run_get_pid (const struct sol_platform_linux_fork_run * handle)
References sol_platform_linux_fork_run::pid, and SOL_NULL_CHECK.
Referenced by process_subprocess_signal_process(), and process_subprocess_stop_process().
SOL_API void sol_platform_linux_fork_run_stop (struct sol_platform_linux_fork_run * handle)
References sol_platform_linux_fork_run::data, sol_platform_linux_fork_run::on_child_exit, sol_platform_linux_fork_run::pid, sol_child_watch_del(), SOL_NULL_CHECK, SOL_PTR_VECTOR_FOREACH_IDX, and sol_platform_linux_fork_run::watch.
Referenced by process_subprocess_close().