Soletta: src/shared/sol-file-reader.h File Reference
sol-file-reader.h File Reference
#include "sol-str-slice.h"
Functions
void sol_file_reader_close (struct sol_file_reader *fr)
struct sol_str_slice sol_file_reader_get_all (const struct sol_file_reader *fr)
const struct stat * sol_file_reader_get_stat (const struct sol_file_reader *fr)
struct sol_file_reader * sol_file_reader_open (const char *filename)
Function Documentation
void sol_file_reader_close (struct sol_file_reader * fr)
References sol_file_reader::contents, sol_file_reader::mmapped, and sol_file_reader::st.
Referenced by main(), and sol_platform_detect().
struct sol_str_slice sol_file_reader_get_all (const struct sol_file_reader * fr)
References sol_str_slice::len.
const struct stat* sol_file_reader_get_stat (const struct sol_file_reader * fr)
References sol_file_reader::st.
struct sol_file_reader* sol_file_reader_open (const char * filename)
References sol_file_reader::contents, sol_file_reader::mmapped, sol_util_load_file_raw(), and sol_file_reader::st.
Referenced by main().