Soletta: src/shared/sol-util-linux.c File Reference
sol-util-linux.c File Reference
#include "sol-util-linux.h"
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>
Functions
int sol_util_fd_set_flag (int fd, int flag)
int sol_util_get_rootdir (char *out, size_t size)
void * sol_util_load_file_raw (const int fd, size_t *size)
char * sol_util_load_file_string (const char *filename, size_t *size)
int sol_util_read_file (const char *path, const char *fmt,...)
int sol_util_vread_file (const char *path, const char *fmt, va_list args)
int sol_util_vwrite_file (const char *path, const char *fmt, va_list args)
int sol_util_write_file (const char *path, const char *fmt,...)
Function Documentation
int sol_util_fd_set_flag (int fd, int flag)
Referenced by process_subprocess_open().
int sol_util_get_rootdir (char * out, size_t size)
References strndupa.
void* sol_util_load_file_raw (const int fd, size_t * size)
References CHUNK_SIZE.
Referenced by sol_file_reader_open(), and sol_util_load_file_string().
char* sol_util_load_file_string (const char * filename, size_t * size)
References sol_util_load_file_raw().
int sol_util_read_file (const char * path, const char * fmt, ...)
References sol_util_vread_file().
int sol_util_vread_file (const char * path, const char * fmt, va_list args)
Referenced by sol_util_read_file().
int sol_util_vwrite_file (const char * path, const char * fmt, va_list args)
Referenced by sol_util_write_file().
int sol_util_write_file (const char * path, const char * fmt, ...)
References sol_util_vwrite_file().