Soletta: src/lib/common/sol-platform-detect.c File Reference
sol-platform-detect.c File Reference
#include <errno.h>
#include <regex.h>
#include <stdio.h>
#include <unistd.h>
#include "sol-log-internal.h"
#include "sol-file-reader.h"
#include "sol-json.h"
#include "sol-platform-detect.h"
#include "sol-str-slice.h"
#include "sol-util.h"
#include "sol-vector.h"
Macros
#define PLATFORM_JSON "/platform_detect.json"
#define SOL_LOG_DOMAIN &_log_domain
Functions
SOL_LOG_INTERNAL_DECLARE_STATIC (_log_domain,"platform-detect")
char * sol_platform_detect (void)
bool sol_platform_invalid_name (const char *name)
Macro Definition Documentation
#define PLATFORM_JSON "/platform_detect.json"
Referenced by sol_platform_detect().
#define SOL_LOG_DOMAIN &_log_domain
Function Documentation
SOL_LOG_INTERNAL_DECLARE_STATIC (_log_domain , "platform-detect")
char* sol_platform_detect (void)
References sol_json_token::end, PLATFORM_JSON, sol_file_reader_close(), SOL_INF, SOL_JSON_SCANNER_ARRAY_LOOP, SOL_JSON_SCANNER_OBJECT_LOOP, SOL_JSON_SCANNER_OBJECT_LOOP_NEST, SOL_JSON_TOKEN_STR_LITERAL_EQ, SOL_JSON_TYPE_ARRAY_START, SOL_JSON_TYPE_OBJECT_START, SOL_JSON_TYPE_STRING, and sol_json_token::start.
Referenced by sol_platform_get_name().
bool sol_platform_invalid_name (const char * name)
Referenced by sol_platform_get_name().