Soletta: src/shared/sol-monitors.h File Reference
sol-monitors.h File Reference
#include <errno.h>
#include "sol-vector.h"
Data Structures
struct sol_monitors
struct sol_monitors_entry
Macros
#define __SOL_MONITORS_WALK(ms, itrvar, idx, executed)
#define __SOL_MONITORS_WALK_AND_CALLBACK(ms, e, i)
#define _SOL_MONITORS_WALK(ms, itrvar, idx, executed) __SOL_MONITORS_WALK(ms, itrvar, idx, _SOL_MONITORS_WALK_VAR(executed))
#define _SOL_MONITORS_WALK_AND_CALLBACK(ms, e, i) __SOL_MONITORS_WALK_AND_CALLBACK(ms, _SOL_MONITORS_WALK_VAR(e), _SOL_MONITORS_WALK_VAR(i))
#define _SOL_MONITORS_WALK_VAR(X) walk__var__ ## X
#define SOL_MONITORS_INIT(CLEANUP) SOL_MONITORS_INIT_CUSTOM(struct sol_monitors_entry, CLEANUP)
#define SOL_MONITORS_INIT_CUSTOM(TYPE, CLEANUP)
#define SOL_MONITORS_WALK(ms, itrvar, idx) _SOL_MONITORS_WALK(ms, itrvar, idx, __COUNTER__)
#define SOL_MONITORS_WALK_AND_CALLBACK(ms) _SOL_MONITORS_WALK_AND_CALLBACK(ms, __COUNTER__, __COUNTER__)
Typedefs
typedef void(* sol_monitors_cb_t)(const void *)
typedef void(* sol_monitors_cleanup_func_t)(const struct sol_monitors *, const struct sol_monitors_entry *)
Functions
void sol_monitors_clear (struct sol_monitors *ms)
int sol_monitors_del (struct sol_monitors *ms, uint16_t i)
void sol_monitors_end_walk (struct sol_monitors *ms)
int sol_monitors_find (const struct sol_monitors *ms, sol_monitors_cb_t cb, const void *data)
void sol_monitors_init_custom (struct sol_monitors *ms, uint16_t elem_size, sol_monitors_cleanup_func_t cleanup)
Macro Definition Documentation
#define __SOL_MONITORS_WALK (ms, itrvar, idx, executed)
Value:
for (bool executed = ({ sol_monitors_begin_walk(ms); false; });      \
        !executed;                                                     \
        executed = ({ sol_monitors_end_walk(ms); true; }))              \
        SOL_VECTOR_FOREACH_IDX (&(ms)->entries, itrvar, idx)
#define __SOL_MONITORS_WALK_AND_CALLBACK (ms, e, i)
Value:
do {                                                \
        struct sol_monitors_entry *e;                     \
        uint16_t i;                                     \
        SOL_MONITORS_WALK (ms, e, i)                      \
            if (e->cb) e->cb(e->data);                  \
    } while (0)
#define _SOL_MONITORS_WALK (ms, itrvar, idx, executed) __SOL_MONITORS_WALK(ms, itrvar, idx, _SOL_MONITORS_WALK_VAR(executed))
#define _SOL_MONITORS_WALK_AND_CALLBACK (ms, e, i) __SOL_MONITORS_WALK_AND_CALLBACK(ms, _SOL_MONITORS_WALK_VAR(e), _SOL_MONITORS_WALK_VAR(i))
#define _SOL_MONITORS_WALK_VAR (X) walk__var__ ## X
#define SOL_MONITORS_INIT (CLEANUP) SOL_MONITORS_INIT_CUSTOM(struct sol_monitors_entry, CLEANUP)
#define SOL_MONITORS_INIT_CUSTOM (TYPE, CLEANUP)
Value:
{                                                       \
        .entries = SOL_VECTOR_INIT(TYPE),                    \
        .walking = 0,                                       \
        .pending_deletion = 0,                              \
        .cleanup = CLEANUP,                                 \
    }
#define SOL_MONITORS_WALK (ms, itrvar, idx) _SOL_MONITORS_WALK(ms, itrvar, idx, __COUNTER__)
Referenced by sol_platform_del_service_monitor(), sol_platform_inform_service_monitors(), and sol_platform_inform_state_monitors().
#define SOL_MONITORS_WALK_AND_CALLBACK (ms) _SOL_MONITORS_WALK_AND_CALLBACK(ms, __COUNTER__, __COUNTER__)
Typedef Documentation
typedef void(* sol_monitors_cb_t)(const void *)
typedef void(* sol_monitors_cleanup_func_t)(const struct sol_monitors *, const struct sol_monitors_entry *)
Function Documentation
void sol_monitors_clear (struct sol_monitors * ms)
References sol_monitors_entry::cb, sol_monitors::cleanup, sol_monitors::entries, sol_vector::len, sol_monitors::pending_deletion, sol_vector_clear(), and sol_monitors::walking.
Referenced by sol_platform_shutdown().
int sol_monitors_del (struct sol_monitors * ms, uint16_t i)
References sol_monitors_entry::cb, sol_monitors::cleanup, sol_monitors::entries, sol_monitors::pending_deletion, and sol_monitors::walking.
Referenced by sol_platform_add_service_monitor(), sol_platform_del_service_monitor(), and sol_platform_del_state_monitor().
void sol_monitors_end_walk (struct sol_monitors * ms)
References sol_monitors::walking.
int sol_monitors_find (const struct sol_monitors * ms, sol_monitors_cb_t cb, const void * data)
References sol_monitors_entry::cb, sol_monitors_entry::data, sol_monitors::entries, and sol_vector::len.
Referenced by sol_platform_del_state_monitor().
void sol_monitors_init_custom (struct sol_monitors * ms, uint16_t elem_size, sol_monitors_cleanup_func_t cleanup)
References sol_monitors::cleanup, sol_monitors::entries, sol_monitors::pending_deletion, sol_vector_init(), and sol_monitors::walking.
Referenced by sol_platform_init().