Soletta: src/lib/common/sol-mainloop.c File Reference
sol-mainloop.c File Reference
#include <stdlib.h>
#include "sol-mainloop-impl.h"
#include "sol-macros.h"
#include "sol-util.h"
Functions
SOL_API int sol_argc (void)
SOL_API void sol_args_set (int argc, char *argv[])
SOL_API char ** sol_argv (void)
int sol_blob_init (void)
void sol_blob_shutdown (void)
SOL_API struct sol_child_watch * sol_child_watch_add (uint64_t pid, void(*cb)(void *data, uint64_t pid, int status), const void *data)
SOL_API bool sol_child_watch_del (struct sol_child_watch *handle)
SOL_API struct sol_fd * sol_fd_add (int fd, unsigned int flags, bool(*cb)(void *data, int fd, unsigned int active_flags), const void *data)
SOL_API bool sol_fd_del (struct sol_fd *handle)
SOL_API struct sol_idle * sol_idle_add (bool(*cb)(void *data), const void *data)
SOL_API bool sol_idle_del (struct sol_idle *handle)
SOL_API int sol_init (void)
SOL_LOG_INTERNAL_DECLARE (_sol_mainloop_log_domain,"mainloop")
SOL_API int sol_mainloop_default_main (const struct sol_main_callbacks *callbacks, int argc, char *argv[])
int sol_platform_init (void)
void sol_platform_shutdown (void)
SOL_API void sol_quit (void)
SOL_API void sol_quit_with_code (int return_code)
SOL_API int sol_run (void)
SOL_API void sol_shutdown (void)
SOL_API struct sol_timeout * sol_timeout_add (unsigned int timeout_ms, bool(*cb)(void *data), const void *data)
SOL_API bool sol_timeout_del (struct sol_timeout *handle)
Function Documentation
int sol_blob_init (void)
References SOL_LOG_DOMAIN, and sol_log_domain_init_level().
Referenced by sol_init().
void sol_blob_shutdown (void)
Referenced by sol_init(), and sol_shutdown().
SOL_LOG_INTERNAL_DECLARE (_sol_mainloop_log_domain , "mainloop")
int sol_platform_init (void)
References ctx::service_monitors, SOL_LOG_DOMAIN, sol_log_domain_init_level(), sol_monitors_init_custom(), sol_platform_impl_init(), and ctx::state_monitors.
Referenced by sol_init().
void sol_platform_shutdown (void)
References ctx::service_monitors, sol_monitors_clear(), sol_platform_impl_shutdown(), and ctx::state_monitors.
Referenced by sol_init(), and sol_shutdown().