Soletta: src/lib/comms/include/sol-coap.h File Reference
sol-coap.h File Reference
Routines to handle CoAP protocol. The Constrained Application Protocol (CoAP) is a specialized web transfer protocol for use with constrained nodes and constrained (e.g., low-power, lossy) networks.
#include <sol-network.h>
#include <sol-str-slice.h>
Data Structures
struct sol_coap_resource
Macros
#define SOL_COAP_RESOURCE_API_VERSION (1)
#define SOL_COAP_REQUEST_MASK 0x07
#define MAKE_RSPCODE(clas, det) ((clas << 5) | (det))
enum sol_coap_option_num_t {
SOL_COAP_OPTION_IF_MATCH = 1, SOL_COAP_OPTION_URI_HOST = 3, SOL_COAP_OPTION_ETAG = 4, SOL_COAP_OPTION_IF_NONE_MATCH = 5,
SOL_COAP_OPTION_OBSERVE = 6, SOL_COAP_OPTION_URI_PORT = 7, SOL_COAP_OPTION_LOCATION_PATH = 8, SOL_COAP_OPTION_URI_PATH = 11,
SOL_COAP_OPTION_CONTENT_FORMAT = 12, SOL_COAP_OPTION_MAX_AGE = 14, SOL_COAP_OPTION_URI_QUERY = 15, SOL_COAP_OPTION_ACCEPT = 17,
SOL_COAP_OPTION_LOCATION_QUERY = 20, SOL_COAP_OPTION_PROXY_URI = 35, SOL_COAP_OPTION_PROXY_SCHEME = 39
}
enum sol_coap_method_t { SOL_COAP_METHOD_GET = 1, SOL_COAP_METHOD_POST = 2, SOL_COAP_METHOD_PUT = 3, SOL_COAP_METHOD_DELETE = 4 }
enum sol_coap_msgtype_t { SOL_COAP_TYPE_CON = 0, SOL_COAP_TYPE_NONCON = 1, SOL_COAP_TYPE_ACK = 2, SOL_COAP_TYPE_RESET = 3 }
enum sol_coap_responsecode_t {
SOL_COAP_RSPCODE_OK = MAKE_RSPCODE(2, 0), SOL_COAP_RSPCODE_CREATED = MAKE_RSPCODE(2, 1), SOL_COAP_RSPCODE_DELETED = MAKE_RSPCODE(2, 2), SOL_COAP_RSPCODE_VALID = MAKE_RSPCODE(2, 3),
SOL_COAP_RSPCODE_CHANGED = MAKE_RSPCODE(2, 4), SOL_COAP_RSPCODE_CONTENT = MAKE_RSPCODE(2, 5), SOL_COAP_RSPCODE_BAD_REQUEST = MAKE_RSPCODE(4, 0), SOL_COAP_RSPCODE_UNAUTHORIZED = MAKE_RSPCODE(4, 1),
SOL_COAP_RSPCODE_BAD_OPTION = MAKE_RSPCODE(4, 2), SOL_COAP_RSPCODE_FORBIDDEN = MAKE_RSPCODE(4, 3), SOL_COAP_RSPCODE_NOT_FOUND = MAKE_RSPCODE(4, 4), SOL_COAP_RSPCODE_NOT_ALLOWED = MAKE_RSPCODE(4, 5),
SOL_COAP_RSPCODE_NOT_ACCEPTABLE = MAKE_RSPCODE(4, 6), SOL_COAP_RSPCODE_PRECONDITION_FAILED = MAKE_RSPCODE(4, 12), SOL_COAP_RSPCODE_REQUEST_TOO_LARGE = MAKE_RSPCODE(4, 13), SOL_COAP_RSPCODE_INTERNAL_ERROR = MAKE_RSPCODE(5, 0),
SOL_COAP_RSPCODE_NOT_IMPLEMENTED = MAKE_RSPCODE(5, 1), SOL_COAP_RSPCODE_BAD_GATEWAY = MAKE_RSPCODE(5, 2), SOL_COAP_RSPCODE_SERVICE_UNAVAILABLE = MAKE_RSPCODE(5, 3), SOL_COAP_RSPCODE_GATEWAY_TIMEOUT = MAKE_RSPCODE(5, 4),
SOL_COAP_RSPCODE_PROXYING_NOT_SUPPORTED = MAKE_RSPCODE(5, 5)
}
enum sol_coap_content_type_t { SOL_COAP_CONTENTTYPE_NONE = -1, SOL_COAP_CONTENTTYPE_TEXT_PLAIN = 0, SOL_COAP_CONTENTTYPE_APPLICATION_LINKFORMAT = 40, SOL_COAP_CONTENTTYPE_APPLICATION_JSON = 50 }
enum sol_coap_flags { SOL_COAP_FLAGS_NONE = 0, SOL_COAP_FLAGS_WELL_KNOWN = (1 << 1), SOL_COAP_FLAGS_OC_CORE = (1 << 2), SOL_COAP_FLAGS_OBSERVABLE = (1 << 3) }
uint8_t sol_coap_header_get_ver (const struct sol_coap_packet *pkt)
uint8_t sol_coap_header_get_type (const struct sol_coap_packet *pkt)
uint8_t * sol_coap_header_get_token (const struct sol_coap_packet *pkt, uint8_t *len)
uint8_t sol_coap_header_get_code (const struct sol_coap_packet *pkt)
uint16_t sol_coap_header_get_id (const struct sol_coap_packet *pkt)
void sol_coap_header_set_ver (struct sol_coap_packet *pkt, uint8_t ver)
void sol_coap_header_set_type (struct sol_coap_packet *pkt, uint8_t type)
bool sol_coap_header_set_token (struct sol_coap_packet *pkt, uint8_t *token, uint8_t tokenlen)
void sol_coap_header_set_code (struct sol_coap_packet *pkt, uint8_t code)
void sol_coap_header_set_id (struct sol_coap_packet *pkt, uint16_t id)
struct sol_coap_server * sol_coap_server_new (int port)
struct sol_coap_server * sol_coap_server_ref (struct sol_coap_server *server)
void sol_coap_server_unref (struct sol_coap_server *server)
struct sol_coap_packet * sol_coap_packet_new (struct sol_coap_packet *old)
struct sol_coap_packet * sol_coap_packet_request_new (sol_coap_method_t method, sol_coap_msgtype_t type)
struct sol_coap_packet * sol_coap_packet_notification_new (struct sol_coap_server *server, struct sol_coap_resource *resource)
struct sol_coap_packet * sol_coap_packet_ref (struct sol_coap_packet *pkt)
void sol_coap_packet_unref (struct sol_coap_packet *pkt)
int sol_coap_packet_get_buf (struct sol_coap_packet *pkt, uint8_t **buf, uint16_t *len)
int sol_coap_packet_get_payload (struct sol_coap_packet *pkt, uint8_t **buf, uint16_t *len)
int sol_coap_packet_set_payload_used (struct sol_coap_packet *pkt, uint16_t len)
bool sol_coap_packet_has_payload (struct sol_coap_packet *pkt)
int sol_coap_add_option (struct sol_coap_packet *pkt, uint16_t code, const void *value, uint16_t len)
int sol_coap_packet_add_uri_path_option (struct sol_coap_packet *pkt, const char *uri)
const void * sol_coap_find_first_option (struct sol_coap_packet *pkt, uint16_t code, uint16_t *len)
int sol_coap_send_packet (struct sol_coap_server *server, struct sol_coap_packet *pkt, const struct sol_network_link_addr *cliaddr)
int sol_coap_send_packet_with_reply (struct sol_coap_server *server, struct sol_coap_packet *pkt, const struct sol_network_link_addr *cliaddr, int(*reply_cb)(struct sol_coap_packet *req, const struct sol_network_link_addr *cliaddr, void *data), void *data)
int sol_coap_packet_send_notification (struct sol_coap_server *server, struct sol_coap_resource *resource, struct sol_coap_packet *pkt)
bool sol_coap_server_register_resource (struct sol_coap_server *server, const struct sol_coap_resource *resource, void *data)
int sol_coap_uri_path_to_buf (const struct sol_str_slice path[], uint8_t *buf, size_t buflen)
Detailed Description
Routines to handle CoAP protocol. The Constrained Application Protocol (CoAP) is a specialized web transfer protocol for use with constrained nodes and constrained (e.g., low-power, lossy) networks.
Macro Definition Documentation
#define MAKE_RSPCODE (clas, det) ((clas << 5) | (det))
#define SOL_COAP_REQUEST_MASK 0x07
#define SOL_COAP_RESOURCE_API_VERSION (1)
Enumeration Type Documentation
enum sol_coap_content_type_t
Enumerator
SOL_COAP_CONTENTTYPE_NONE
SOL_COAP_CONTENTTYPE_TEXT_PLAIN
SOL_COAP_CONTENTTYPE_APPLICATION_LINKFORMAT
SOL_COAP_CONTENTTYPE_APPLICATION_JSON
enum sol_coap_flags
Enumerator
SOL_COAP_FLAGS_NONE
SOL_COAP_FLAGS_WELL_KNOWN
SOL_COAP_FLAGS_OC_CORE
SOL_COAP_FLAGS_OBSERVABLE
enum sol_coap_method_t
Enumerator
SOL_COAP_METHOD_GET
SOL_COAP_METHOD_POST
SOL_COAP_METHOD_PUT
SOL_COAP_METHOD_DELETE
enum sol_coap_msgtype_t
Enumerator
SOL_COAP_TYPE_CON
SOL_COAP_TYPE_NONCON
SOL_COAP_TYPE_ACK
SOL_COAP_TYPE_RESET
enum sol_coap_responsecode_t
Enumerator
SOL_COAP_RSPCODE_OK
SOL_COAP_RSPCODE_CREATED
SOL_COAP_RSPCODE_DELETED
SOL_COAP_RSPCODE_VALID
SOL_COAP_RSPCODE_CHANGED
SOL_COAP_RSPCODE_CONTENT
SOL_COAP_RSPCODE_BAD_REQUEST
SOL_COAP_RSPCODE_UNAUTHORIZED
SOL_COAP_RSPCODE_BAD_OPTION
SOL_COAP_RSPCODE_FORBIDDEN
SOL_COAP_RSPCODE_NOT_FOUND
SOL_COAP_RSPCODE_NOT_ALLOWED
SOL_COAP_RSPCODE_NOT_ACCEPTABLE
SOL_COAP_RSPCODE_PRECONDITION_FAILED
SOL_COAP_RSPCODE_REQUEST_TOO_LARGE
SOL_COAP_RSPCODE_INTERNAL_ERROR
SOL_COAP_RSPCODE_NOT_IMPLEMENTED
SOL_COAP_RSPCODE_BAD_GATEWAY
SOL_COAP_RSPCODE_SERVICE_UNAVAILABLE
SOL_COAP_RSPCODE_GATEWAY_TIMEOUT
SOL_COAP_RSPCODE_PROXYING_NOT_SUPPORTED
Function Documentation
int sol_coap_add_option (struct sol_coap_packet * pkt, uint16_t code, const void * value, uint16_t len)
References sol_coap_packet::buf, option_context::buf, option_context::buflen, coap_get_header_len(), coap_option_encode(), coap_parse_option(), option_context::delta, sol_coap_packet::payload, sol_coap_packet::size, SOL_NULL_CHECK, SOL_WRN, sol_coap_packet::start, sol_coap_packet::used, and option_context::used.
Referenced by main(), sol_coap_packet_add_uri_path_option(), sol_coap_packet_notification_new(), and sol_oic_client_find_resource().
const void* sol_coap_find_first_option (struct sol_coap_packet * pkt, uint16_t code, uint16_t * len)
References coap_find_options(), sol_coap_option_value::len, SOL_NULL_CHECK, and sol_coap_option_value::value.
uint8_t sol_coap_header_get_code (const struct sol_coap_packet * pkt)
References sol_coap_packet::buf, coap_header::code, SOL_COAP_METHOD_DELETE, SOL_COAP_METHOD_GET, SOL_COAP_METHOD_POST, SOL_COAP_METHOD_PUT, SOL_COAP_RSPCODE_BAD_GATEWAY, SOL_COAP_RSPCODE_BAD_OPTION, SOL_COAP_RSPCODE_BAD_REQUEST, SOL_COAP_RSPCODE_CHANGED, SOL_COAP_RSPCODE_CONTENT, SOL_COAP_RSPCODE_CREATED, SOL_COAP_RSPCODE_DELETED, SOL_COAP_RSPCODE_FORBIDDEN, SOL_COAP_RSPCODE_GATEWAY_TIMEOUT, SOL_COAP_RSPCODE_INTERNAL_ERROR, SOL_COAP_RSPCODE_NOT_ACCEPTABLE, SOL_COAP_RSPCODE_NOT_ALLOWED, SOL_COAP_RSPCODE_NOT_FOUND, SOL_COAP_RSPCODE_NOT_IMPLEMENTED, SOL_COAP_RSPCODE_OK, SOL_COAP_RSPCODE_PRECONDITION_FAILED, SOL_COAP_RSPCODE_PROXYING_NOT_SUPPORTED, SOL_COAP_RSPCODE_REQUEST_TOO_LARGE, SOL_COAP_RSPCODE_SERVICE_UNAVAILABLE, SOL_COAP_RSPCODE_UNAUTHORIZED, SOL_COAP_RSPCODE_VALID, and SOL_WRN.
Referenced by sol_coap_packet_send_notification().
uint16_t sol_coap_header_get_id (const struct sol_coap_packet * pkt)
References sol_coap_packet::buf, and coap_header::id.
Referenced by sol_coap_packet_new(), and sol_coap_send_packet_with_reply().
uint8_t* sol_coap_header_get_token (const struct sol_coap_packet * pkt, uint8_t * len)
References sol_coap_packet::buf, and coap_header::tkl.
Referenced by sol_coap_packet_new(), sol_coap_packet_send_notification(), and sol_coap_send_packet_with_reply().
uint8_t sol_coap_header_get_type (const struct sol_coap_packet * pkt)
References sol_coap_packet::buf, and coap_header::type.
Referenced by sol_coap_packet_send_notification().
uint8_t sol_coap_header_get_ver (const struct sol_coap_packet * pkt)
References sol_coap_packet::buf, and coap_header::ver.
void sol_coap_header_set_code (struct sol_coap_packet * pkt, uint8_t code)
References sol_coap_packet::buf, and coap_header::code.
Referenced by sol_coap_packet_request_new(), sol_coap_packet_send_notification(), and sol_oic_notify_observers().
void sol_coap_header_set_id (struct sol_coap_packet * pkt, uint16_t id)
References sol_coap_packet::buf, and coap_header::id.
Referenced by sol_coap_packet_new(), sol_coap_packet_request_new(), and sol_oic_client_find_resource().
bool sol_coap_header_set_token (struct sol_coap_packet * pkt, uint8_t * token, uint8_t tokenlen)
References sol_coap_packet::buf, sol_coap_packet::payload, sol_coap_packet::size, coap_header::tkl, and sol_coap_packet::used.
Referenced by main(), sol_coap_packet_new(), and sol_coap_packet_send_notification().
void sol_coap_header_set_type (struct sol_coap_packet * pkt, uint8_t type)
References sol_coap_packet::buf, and coap_header::type.
Referenced by sol_coap_packet_notification_new(), sol_coap_packet_request_new(), and sol_coap_packet_send_notification().
void sol_coap_header_set_ver (struct sol_coap_packet * pkt, uint8_t ver)
References sol_coap_packet::buf, and coap_header::ver.
Referenced by sol_coap_packet_new().
int sol_coap_packet_add_uri_path_option (struct sol_coap_packet * pkt, const char * uri)
References sol_coap_add_option(), SOL_COAP_OPTION_URI_PATH, SOL_NULL_CHECK, and SOL_WRN.
Referenced by sol_oic_client_find_resource().
int sol_coap_packet_get_buf (struct sol_coap_packet * pkt, uint8_t ** buf, uint16_t * len)
References sol_coap_packet::buf, and SOL_NULL_CHECK.
int sol_coap_packet_get_payload (struct sol_coap_packet * pkt, uint8_t ** buf, uint16_t * len)
References sol_coap_packet::buf, COAP_MARKER, sol_coap_packet::payload, sol_coap_packet::size, SOL_INT_CHECK, SOL_NULL_CHECK, sol_coap_packet::start, and sol_coap_packet::used.
Referenced by sol_oic_notify_observers().
bool sol_coap_packet_has_payload (struct sol_coap_packet * pkt)
References sol_coap_packet::payload, sol_coap_packet::size, SOL_NULL_CHECK, sol_coap_packet::start, and sol_coap_packet::used.
struct sol_coap_packet* sol_coap_packet_new (struct sol_coap_packet * old)
References COAP_UDP_MTU, COAP_VERSION, sol_coap_packet::payload, sol_coap_packet::refcnt, sol_coap_packet::size, sol_coap_header_get_id(), sol_coap_header_get_token(), sol_coap_header_set_id(), sol_coap_header_set_token(), sol_coap_header_set_ver(), SOL_NULL_CHECK, coap_header::tkl, and sol_coap_packet::used.
Referenced by sol_coap_packet_notification_new(), sol_coap_packet_request_new(), and sol_coap_packet_send_notification().
struct sol_coap_packet* sol_coap_packet_notification_new (struct sol_coap_server * server, struct sol_coap_resource * resource)
References resource_context::age, COAP_RESOURCE_CHECK_API, sol_coap_add_option(), sol_coap_header_set_type(), SOL_COAP_OPTION_OBSERVE, sol_coap_packet_new(), SOL_COAP_TYPE_NONCON, and SOL_NULL_CHECK.
Referenced by sol_oic_notify_observers().
struct sol_coap_packet* sol_coap_packet_ref (struct sol_coap_packet * pkt)
References sol_coap_packet::refcnt, and SOL_NULL_CHECK.
struct sol_coap_packet* sol_coap_packet_request_new (sol_coap_method_t method, sol_coap_msgtype_t type)
References sol_coap_header_set_code(), sol_coap_header_set_id(), sol_coap_header_set_type(), sol_coap_packet_new(), and SOL_NULL_CHECK.
Referenced by main(), and sol_oic_client_find_resource().
int sol_coap_packet_send_notification (struct sol_coap_server * server, struct sol_coap_resource * resource, struct sol_coap_packet * pkt)
References sol_coap_packet::buf, resource_observer::cliaddr, COAP_RESOURCE_CHECK_API, resource_context::observers, sol_coap_packet::payload, sol_coap_header_get_code(), sol_coap_header_get_token(), sol_coap_header_get_type(), sol_coap_header_set_code(), sol_coap_header_set_token(), sol_coap_header_set_type(), sol_coap_packet_new(), sol_coap_packet_unref(), SOL_INET_ADDR_STRLEN, sol_network_addr_to_str(), SOL_NULL_CHECK, SOL_PTR_VECTOR_FOREACH_IDX, SOL_WRN, coap_header::tkl, resource_observer::tkl, resource_observer::token, and sol_coap_packet::used.
Referenced by sol_oic_notify_observers().
int sol_coap_packet_set_payload_used (struct sol_coap_packet * pkt, uint16_t len)
References sol_coap_packet::payload, sol_coap_packet::size, SOL_INT_CHECK, SOL_NULL_CHECK, sol_coap_packet::start, and sol_coap_packet::used.
Referenced by sol_oic_notify_observers().
void sol_coap_packet_unref (struct sol_coap_packet * pkt)
References sol_coap_packet::refcnt, and SOL_NULL_CHECK.
Referenced by main(), sol_coap_packet_send_notification(), sol_coap_send_packet_with_reply(), sol_oic_client_find_resource(), and sol_oic_notify_observers().
int sol_coap_send_packet (struct sol_coap_server * server, struct sol_coap_packet * pkt, const struct sol_network_link_addr * cliaddr)
References sol_coap_send_packet_with_reply().
int sol_coap_send_packet_with_reply (struct sol_coap_server * server, struct sol_coap_packet * pkt, const struct sol_network_link_addr * cliaddr, int(*)(struct sol_coap_packet *req, const struct sol_network_link_addr *cliaddr, void *data) reply_cb, void * data)
References pending_reply::cb, coap_find_options(), pending_reply::data, pending_reply::id, sol_coap_option_value::len, pending_reply::observing, sol_coap_server::pending, sol_coap_header_get_id(), sol_coap_header_get_token(), SOL_COAP_OPTION_OBSERVE, sol_coap_packet_unref(), SOL_INET_ADDR_STRLEN, SOL_INT_CHECK_GOTO, sol_network_addr_to_str(), sol_ptr_vector_append(), sol_util_strerrora, SOL_WRN, pending_reply::tkl, pending_reply::token, and sol_coap_option_value::value.
Referenced by main(), sol_coap_send_packet(), and sol_oic_client_find_resource().
struct sol_coap_server* sol_coap_server_new (int port)
References sol_coap_server::contexts, sol_network_link_addr::family, sol_coap_server::fd, sol_coap_server::outgoing, sol_coap_server::pending, sol_coap_server::read_watch, sol_coap_server::refcnt, SOCK_CLOEXEC, SOL_DBG, sol_fd_add(), SOL_FD_FLAGS_IN, SOL_LOG_INTERNAL_INIT_ONCE, sol_network_get_available_links(), sol_network_init(), sol_network_link_get_name(), sol_network_subscribe_events(), SOL_NULL_CHECK_GOTO, sol_socket_bind(), sol_util_strerrora, SOL_VECTOR_FOREACH_IDX, sol_vector_init(), and SOL_WRN.
Referenced by main(), and sol_oic_server_init().
struct sol_coap_server* sol_coap_server_ref (struct sol_coap_server * server)
References sol_coap_server::refcnt, and SOL_NULL_CHECK.
bool sol_coap_server_register_resource (struct sol_coap_server * server, const struct sol_coap_resource * resource, void * data)
References resource_context::age, COAP_RESOURCE_CHECK_API, sol_coap_server::contexts, resource_context::data, resource_context::observers, resource_context::resource, SOL_NULL_CHECK, and sol_vector_append().
Referenced by main(), sol_oic_device_definition_register_resource_type(), sol_oic_server_init(), and sol_oic_server_register_definition().
void sol_coap_server_unref (struct sol_coap_server * server)
References sol_coap_server::refcnt, and SOL_NULL_CHECK.
Referenced by main(), and sol_oic_server_release().
int sol_coap_uri_path_to_buf (const struct sol_str_slice path[], uint8_t * buf, size_t buflen)
References sol_str_slice::data, sol_str_slice::len, and SOL_NULL_CHECK.