Soletta: src/lib/common/sol-platform-impl.h File Reference
sol-platform-impl.h File Reference
#include "sol-log-internal.h"
#include "sol-platform.h"
Macros
#define SOL_LOG_DOMAIN &_sol_platform_log_domain
Functions
int sol_platform_impl_add_service_monitor (const char *service) SOL_ATTR_NONNULL(1)
int sol_platform_impl_del_service_monitor (const char *service) SOL_ATTR_NONNULL(1)
int sol_platform_impl_get_state (void)
int sol_platform_impl_init (void)
int sol_platform_impl_restart_service (const char *service) SOL_ATTR_NONNULL(1)
int sol_platform_impl_set_target (const char *target) SOL_ATTR_NONNULL(1)
void sol_platform_impl_shutdown (void)
int sol_platform_impl_start_service (const char *service) SOL_ATTR_NONNULL(1)
int sol_platform_impl_stop_service (const char *service) SOL_ATTR_NONNULL(1)
void sol_platform_inform_service_monitors (const char *service, enum sol_platform_service_state state)
void sol_platform_inform_state_monitors (enum sol_platform_state state)
Variables
struct sol_log_domain _sol_platform_log_domain
Macro Definition Documentation
#define SOL_LOG_DOMAIN &_sol_platform_log_domain
Function Documentation
int sol_platform_impl_add_service_monitor (const char * service)
References service::properties, service::service, ctx::services, service::slot, sol_bus_get(), SOL_CRI, SOL_INT_CHECK_GOTO, SOL_NULL_CHECK, SOL_PLATFORM_SERVICE_STATE_UNKNOWN, SOL_PLATFORM_STATE_STOPPING, sol_ptr_vector_append(), SOL_WRN, and service::state.
Referenced by sol_platform_add_service_monitor().
int sol_platform_impl_del_service_monitor (const char * service)
References service::service, ctx::services, service::slot, sol_bus_unmap_cached_properties(), SOL_CRI, SOL_NULL_CHECK, SOL_PLATFORM_STATE_STOPPING, SOL_PTR_VECTOR_FOREACH_IDX, SOL_WRN, and streq.
int sol_platform_impl_get_state (void)
References ctx::properties, sol_bus_get(), SOL_NULL_CHECK, SOL_PLATFORM_STATE_RUNNING, SOL_PLATFORM_STATE_STOPPING, SOL_PLATFORM_STATE_UNKNOWN, SOL_WRN, and ctx::system_state.
Referenced by sol_platform_get_state().
int sol_platform_impl_init (void)
References ctx::services, SOL_INT_CHECK, SOL_PLATFORM_STATE_INITIALIZING, and SOL_PLATFORM_STATE_RUNNING.
Referenced by sol_platform_init().
int sol_platform_impl_restart_service (const char * service)
References SOL_CRI, SOL_DBG, SOL_INT_CHECK, SOL_PLATFORM_SERVICE_STATE_ACTIVATING, SOL_PLATFORM_SERVICE_STATE_DEACTIVATING, SOL_PLATFORM_SERVICE_STATE_RELOADING, SOL_PLATFORM_STATE_STOPPING, and SOL_WRN.
Referenced by sol_platform_restart_service().
int sol_platform_impl_set_target (const char * target)
References SOL_CRI, SOL_PLATFORM_STATE_STOPPING, SOL_PLATFORM_TARGET_DEFAULT, SOL_PLATFORM_TARGET_EMERGENCY, SOL_PLATFORM_TARGET_POWEROFF, SOL_PLATFORM_TARGET_REBOOT, SOL_PLATFORM_TARGET_RESCUE, SOL_PLATFORM_TARGET_SUSPEND, sol_quit(), SOL_STR_TABLE_ITEM, sol_str_table_lookup_fallback(), SOL_WRN, streq, TARGET_PARAM_ISOLATE, and TARGET_PARAM_REPLACE_IRREVERSIBLY.
Referenced by sol_platform_set_target().
void sol_platform_impl_shutdown (void)
References ctx::services, sol_bus_close(), and SOL_PLATFORM_STATE_STOPPING.
Referenced by sol_platform_shutdown().
int sol_platform_impl_start_service (const char * service)
References SOL_CRI, SOL_DBG, SOL_PLATFORM_SERVICE_STATE_ACTIVATING, SOL_PLATFORM_STATE_STOPPING, and SOL_WRN.
Referenced by sol_platform_start_service().
int sol_platform_impl_stop_service (const char * service)
References SOL_CRI, SOL_DBG, SOL_PLATFORM_SERVICE_STATE_DEACTIVATING, SOL_PLATFORM_STATE_STOPPING, and SOL_WRN.
Referenced by sol_platform_stop_service().
void sol_platform_inform_service_monitors (const char * service, enum sol_platform_service_state state)
References service_monitor::base, sol_monitors_entry::cb, sol_monitors_entry::data, service_monitor::service, ctx::service_monitors, SOL_MONITORS_WALK, service_monitor::state, and streq.
Referenced by sol_platform_linux_micro_inform_service_state().
void sol_platform_inform_state_monitors (enum sol_platform_state state)
References sol_monitors_entry::cb, sol_monitors_entry::data, SOL_MONITORS_WALK, and ctx::state_monitors.
Variable Documentation
struct sol_log_domain _sol_platform_log_domain