Soletta: src/lib/io/include/sol-pwm.h File Reference
sol-pwm.h File Reference
These routines are used for PWM access under Solleta.
#include <stdbool.h>
#include <stdint.h>
Data Structures
struct sol_pwm_config
Macros
#define SOL_PWM_CONFIG_API_VERSION (1)
enum sol_pwm_alignment { SOL_PWM_ALIGNMENT_LEFT, SOL_PWM_ALIGNMENT_RIGHT, SOL_PWM_ALIGNMENT_CENTER }
enum sol_pwm_polarity { SOL_PWM_POLARITY_NORMAL, SOL_PWM_POLARITY_INVERSED }
struct sol_pwm * sol_pwm_open (int device, int channel, const struct sol_pwm_config *config)
struct sol_pwm * sol_pwm_open_raw (int device, int channel, const struct sol_pwm_config *config)
void sol_pwm_close (struct sol_pwm *pwm)
bool sol_pwm_set_enabled (struct sol_pwm *pwm, bool enable)
bool sol_pwm_get_enabled (const struct sol_pwm *pwm)
bool sol_pwm_set_period (struct sol_pwm *pwm, uint32_t period_ns)
int32_t sol_pwm_get_period (const struct sol_pwm *pwm)
bool sol_pwm_set_duty_cycle (struct sol_pwm *pwm, uint32_t duty_cycle_ns)
int32_t sol_pwm_get_duty_cycle (const struct sol_pwm *pwm)
Detailed Description
These routines are used for PWM access under Solleta.
Macro Definition Documentation
#define SOL_PWM_CONFIG_API_VERSION (1)
Referenced by sol_pwm_open_raw().
Enumeration Type Documentation
enum sol_pwm_alignment
Enumerator
SOL_PWM_ALIGNMENT_LEFT
SOL_PWM_ALIGNMENT_RIGHT
SOL_PWM_ALIGNMENT_CENTER
enum sol_pwm_polarity
Enumerator
SOL_PWM_POLARITY_NORMAL
SOL_PWM_POLARITY_INVERSED
Function Documentation
void sol_pwm_close (struct sol_pwm * pwm)
References sol_pwm::channel, sol_pwm::dev, sol_pwm::device, sol_pwm::duty_cycle, sol_pwm::owned, sol_pwm::period, SOL_NULL_CHECK, sol_pwm_set_duty_cycle(), sol_pwm_set_enabled(), and sol_pwm_set_period().
Referenced by sol_pwm_open().
int32_t sol_pwm_get_duty_cycle (const struct sol_pwm * pwm)
References sol_pwm::channel, sol_pwm::device, sol_pwm::duty_cycle, SOL_NULL_CHECK, and SOL_WRN.
bool sol_pwm_get_enabled (const struct sol_pwm * pwm)
References sol_pwm::channel, sol_pwm::device, sol_pwm::enable, SOL_NULL_CHECK, and SOL_WRN.
int32_t sol_pwm_get_period (const struct sol_pwm * pwm)
References sol_pwm::channel, sol_pwm::device, sol_pwm::period, SOL_NULL_CHECK, and SOL_WRN.
struct sol_pwm* sol_pwm_open (int device, int channel, const struct sol_pwm_config * config)
References SOL_LOG_INTERNAL_INIT_ONCE, sol_pin_mux_setup_pwm(), sol_pwm_close(), sol_pwm_open_raw(), and SOL_WRN.
struct sol_pwm* sol_pwm_open_raw (int device, int channel, const struct sol_pwm_config * config)
References sol_pwm_config::alignment, sol_pwm_config::api_version, sol_pwm::channel, sol_pwm::dev, sol_pwm::device, sol_pwm_config::duty_cycle_ns, sol_pwm_config::enabled, sol_pwm::owned, sol_pwm_config::period_ns, sol_pwm::phase, PWM_BASE, SOL_LOG_INTERNAL_INIT_ONCE, SOL_NULL_CHECK, SOL_PWM_CONFIG_API_VERSION, sol_pwm_set_duty_cycle(), sol_pwm_set_enabled(), sol_pwm_set_period(), SOL_WRN, and unlikely.
Referenced by sol_pwm_open().
bool sol_pwm_set_duty_cycle (struct sol_pwm * pwm, uint32_t duty_cycle_ns)
References sol_pwm::channel, sol_pwm::dev, sol_pwm::device, sol_pwm::duty_cycle, sol_pwm::period, RESOLUTION, SOL_INT_CHECK, SOL_NULL_CHECK, and SOL_WRN.
Referenced by sol_pwm_close(), and sol_pwm_open_raw().
bool sol_pwm_set_enabled (struct sol_pwm * pwm, bool enable)
References sol_pwm::channel, sol_pwm::dev, sol_pwm::device, sol_pwm::enable, SOL_NULL_CHECK, and SOL_WRN.
Referenced by sol_pwm_close(), and sol_pwm_open_raw().
bool sol_pwm_set_period (struct sol_pwm * pwm, uint32_t period_ns)
References sol_pwm::channel, sol_pwm::dev, sol_pwm::device, NSEC_PER_SEC, sol_pwm::period, sol_pwm::phase, RESOLUTION, SOL_NULL_CHECK, and SOL_WRN.
Referenced by sol_pwm_close(), and sol_pwm_open_raw().