Soletta: src/bin/sol-fbp-runner/main.c File Reference
main.c File Reference
#include <stdbool.h>
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include "sol-flow-buildopts.h"
#include "sol-log.h"
#include "sol-mainloop.h"
#include "runner.h"
Functions
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
References sol_idle_add(), sol_init(), sol_run(), and sol_shutdown().
Variable Documentation
bool check_only
const char* filename
Referenced by runner_new().
bool provide_sim_nodes