Soletta: src/shared/sol-fbp-internal-log.c File Reference
sol-fbp-internal-log.c File Reference
#include <errno.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include "sol-fbp-internal-log.h"
#include "sol-util.h"
Macros
#define SOL_LOG_DOMAIN &sol_fbp_log_domain
Functions
void sol_fbp_init_log_domain (void)
SOL_LOG_INTERNAL_DECLARE (sol_fbp_log_domain,"fbp")
Macro Definition Documentation
#define SOL_LOG_DOMAIN &sol_fbp_log_domain
Function Documentation
void sol_fbp_init_log_domain (void)
References SOL_LOG_INTERNAL_INIT_ONCE.
Referenced by sol_fbp_graph_init(), sol_fbp_parse(), and sol_fbp_scanner_init().
SOL_LOG_INTERNAL_DECLARE (sol_fbp_log_domain , "fbp")