Soletta: src/lib/comms/sol-oic-server.c File Reference
sol-oic-server.c File Reference
#include <errno.h>
#include <netinet/in.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include "sol-log-internal.h"
#include "sol-vector.h"
#include "sol-str-slice.h"
#include "sol-util.h"
#include "sol-oic-server.h"
#include "sol-json.h"
#include "sol-coap.h"
Data Structures
struct resource_type_data
struct sol_oic_device_definition
struct sol_oic_server
struct sol_oic_server_information
Macros
#define APPEND_KEY_VALUE(k, v)
#define DEFINE_RESOURCE_TYPE_CALLBACK_FOR_METHOD(method, expect_payload)
#define OIC_SERVER_CHECK(ret)
#define SOL_LOG_DOMAIN &_sol_oic_server_log_domain
Functions
SOL_LOG_INTERNAL_DECLARE (_sol_oic_server_log_domain,"oic-server")
SOL_API struct sol_coap_resource * sol_oic_device_definition_register_resource_type (struct sol_oic_device_definition *definition, const struct sol_oic_resource_type *resource_type, void *handler_data, enum sol_coap_flags flags)
SOL_API bool sol_oic_notify_observers (struct sol_coap_resource *resource, uint8_t *msg, uint16_t msg_len)
SOL_API struct
sol_oic_device_definition * sol_oic_server_get_definition (struct sol_str_slice endpoint, struct sol_str_slice resource_type_prefix)
SOL_API bool sol_oic_server_init (int port)
SOL_API struct
sol_oic_device_definition * sol_oic_server_register_definition (struct sol_str_slice endpoint, struct sol_str_slice resource_type_prefix, enum sol_coap_flags flags)
SOL_API void sol_oic_server_release (void)
SOL_API bool sol_oic_server_unregister_definition (const struct sol_oic_device_definition *definition)
Macro Definition Documentation
#define APPEND_KEY_VALUE (k, v)
Value:
do {                                    \
        uint16_t r;                             \
        r = _append_json_key_value(payload, payload_size, payload_len, k,   \
            sol_str_slice_from_str(oic_server.information->v));     \
        if (!r) goto no_memory;                     \
        payload += (r - payload_len);                   \
        payload_len = r;                            \
    } while (0)
#define DEFINE_RESOURCE_TYPE_CALLBACK_FOR_METHOD (method, expect_payload)
Value:
static int                                                                               \
    _sol_oic_resource_type_ ## method(const struct sol_coap_resource *resource,                  \
    struct sol_coap_packet *req, const struct sol_network_link_addr *cliaddr, void *data)  \
    {                                                                                        \
        struct resource_type_data *res = data;                                               \
        return _sol_oic_resource_type_handle(res->resource_type->method.handle,               \
            req, cliaddr, res, expect_payload);                                              \
    }
#define OIC_SERVER_CHECK (ret)
Value:
do {                                                    \
        if (oic_server.refcnt == 0) {                       \
            SOL_WRN("OIC API used before initialization");   \
            return ret;                                     \
        }                                                   \
    } while (0)
Referenced by sol_oic_device_definition_register_resource_type(), sol_oic_server_get_definition(), sol_oic_server_register_definition(), sol_oic_server_release(), and sol_oic_server_unregister_definition().
#define SOL_LOG_DOMAIN &_sol_oic_server_log_domain
Function Documentation
SOL_LOG_INTERNAL_DECLARE (_sol_oic_server_log_domain , "oic-server")
SOL_API struct sol_coap_resource* sol_oic_device_definition_register_resource_type (struct sol_oic_device_definition * definition, const struct sol_oic_resource_type * resource_type, void * handler_data, enum sol_coap_flags flags)
References sol_oic_resource_type::api_version, resource_type_data::data, sol_coap_resource::delete, sol_oic_resource_type::endpoint, sol_coap_resource::flags, sol_coap_resource::get, sol_oic_resource_type::iface, sol_coap_resource::iface, sol_vector::len, OIC_SERVER_CHECK, sol_coap_resource::post, sol_coap_resource::put, resource_type_data::resource, resource_type_data::resource_type, sol_oic_resource_type::resource_type, sol_coap_resource::resource_type, sol_oic_device_definition::resource_types, sol_oic_server::server, sol_coap_server_register_resource(), SOL_NULL_CHECK, SOL_OIC_RESOURCE_TYPE_API_VERSION, sol_util_memdup(), sol_vector_append(), sol_vector_del(), SOL_WRN, and unlikely.
SOL_API bool sol_oic_notify_observers (struct sol_coap_resource * resource, uint8_t * msg, uint16_t msg_len)
References sol_coap_resource::path, sol_coap_packet::payload, sol_oic_server::server, sol_coap_header_set_code(), sol_coap_packet_get_payload(), sol_coap_packet_notification_new(), sol_coap_packet_send_notification(), sol_coap_packet_set_payload_used(), sol_coap_packet_unref(), SOL_COAP_RSPCODE_CONTENT, SOL_COAP_RSPCODE_INTERNAL_ERROR, and SOL_NULL_CHECK.
SOL_API struct sol_oic_device_definition* sol_oic_server_get_definition (struct sol_str_slice endpoint, struct sol_str_slice resource_type_prefix)
References sol_oic_server::device_definitions, sol_oic_device_definition::endpoint, OIC_SERVER_CHECK, sol_oic_device_definition::resource_type_prefix, and SOL_VECTOR_FOREACH_IDX.
Referenced by sol_oic_server_register_definition().
SOL_API bool sol_oic_server_init (int port)
References sol_oic_server::device_definitions, sol_oic_server::information, sol_oic_server::refcnt, sol_oic_server::server, sol_coap_server_new(), sol_coap_server_register_resource(), SOL_LOG_INTERNAL_INIT_ONCE, SOL_NULL_CHECK, and sol_vector_init().
Referenced by main().
SOL_API struct sol_oic_device_definition* sol_oic_server_register_definition (struct sol_str_slice endpoint, struct sol_str_slice resource_type_prefix, enum sol_coap_flags flags)
References sol_oic_server::device_definitions, sol_oic_device_definition::endpoint, sol_coap_resource::flags, sol_coap_resource::get, sol_vector::len, OIC_SERVER_CHECK, sol_oic_device_definition::resource, sol_coap_resource::resource_type, sol_oic_device_definition::resource_type_prefix, sol_oic_device_definition::resource_types, sol_oic_server::server, sol_coap_server_register_resource(), SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, sol_oic_server_get_definition(), sol_vector_append(), sol_vector_del(), and sol_vector_init().
SOL_API void sol_oic_server_release (void)
References sol_oic_server::device_definitions, sol_oic_server::information, OIC_SERVER_CHECK, sol_oic_server::refcnt, sol_oic_server::server, sol_coap_server_unref(), and sol_vector_clear().
Referenced by main().
SOL_API bool sol_oic_server_unregister_definition (const struct sol_oic_device_definition * definition)
References sol_oic_server::device_definitions, sol_oic_device_definition::endpoint, OIC_SERVER_CHECK, sol_oic_device_definition::resource, sol_oic_device_definition::resource_type_prefix, SOL_NULL_CHECK, sol_vector_del(), and SOL_VECTOR_FOREACH_REVERSE_IDX.