Soletta: src/shared/sol-util-linux.h File Reference
sol-util-linux.h File Reference
#include "sol-macros.h"
#include <sys/types.h>
#include <stdarg.h>
Macros
#define CHUNK_SIZE 4096
#define SOL_UTIL_MAX_READ_ATTEMPTS 10
Functions
int sol_util_fd_set_flag (int fd, int flag) SOL_ATTR_WARN_UNUSED_RESULT
int sol_util_get_rootdir (char *out, size_t size) SOL_ATTR_WARN_UNUSED_RESULT
int int int int void * sol_util_load_file_raw (const int fd, size_t *size) SOL_ATTR_WARN_UNUSED_RESULT
char * sol_util_load_file_string (const char *filename, size_t *size) SOL_ATTR_WARN_UNUSED_RESULT
int int int sol_util_read_file (const char *path, const char *fmt,...) SOL_ATTR_SCANF(2
int int int int sol_util_vread_file (const char *path, const char *fmt, va_list args) SOL_ATTR_SCANF(2
int int sol_util_vwrite_file (const char *path, const char *fmt, va_list args) SOL_ATTR_PRINTF(2
int sol_util_write_file (const char *path, const char *fmt,...) SOL_ATTR_PRINTF(2
Macro Definition Documentation
#define CHUNK_SIZE 4096
Referenced by sol_util_load_file_raw().
#define SOL_UTIL_MAX_READ_ATTEMPTS 10
Function Documentation
int sol_util_fd_set_flag (int fd, int flag)
Referenced by process_subprocess_open().
int sol_util_get_rootdir (char * out, size_t size)
References strndupa.
int int int int void* sol_util_load_file_raw (const int fd, size_t * size)
References CHUNK_SIZE.
Referenced by sol_file_reader_open(), and sol_util_load_file_string().
char* sol_util_load_file_string (const char * filename, size_t * size)
References sol_util_load_file_raw().
int int int sol_util_read_file (const char * path, const char * fmt, ...)
int int int int sol_util_vread_file (const char * path, const char * fmt, va_list args)
int int sol_util_vwrite_file (const char * path, const char * fmt, va_list args)
int sol_util_write_file (const char * path, const char * fmt, ...)