Soletta: src/lib/comms/include/sol-oic-client.h File Reference
sol-oic-client.h File Reference
Routines to create clients talking OIC protocol.
#include <stdbool.h>
#include <stdint.h>
#include <sol-coap.h>
#include <sol-network.h>
#include <sol-str-slice.h>
#include <sol-vector.h>
Data Structures
struct sol_oic_client
struct sol_oic_resource
Macros
#define SOL_OIC_CLIENT_API_VERSION (1)
#define SOL_OIC_RESOURCE_API_VERSION (1)
Functions
bool sol_oic_client_find_resource (struct sol_oic_client *client, struct sol_network_link_addr *cliaddr, const char *resource_type, void(*resource_found_cb)(struct sol_oic_client *cli, struct sol_oic_resource *res, void *data), void *data)
bool sol_oic_client_resource_request (struct sol_oic_client *client, struct sol_oic_resource *res, sol_coap_method_t method, uint8_t *payload, size_t payload_len, void(*callback)(struct sol_oic_client *cli, const struct sol_network_link_addr *addr, const struct sol_str_slice *href, const struct sol_str_slice *payload, void *data), void *data)
bool sol_oic_client_resource_set_observable (struct sol_oic_client *client, struct sol_oic_resource *res, void(*callback)(struct sol_oic_client *cli, const struct sol_network_link_addr *addr, const struct sol_str_slice *href, const struct sol_str_slice *payload, void *data), void *data, bool observe)
struct sol_oic_resource * sol_oic_resource_ref (struct sol_oic_resource *r)
void sol_oic_resource_unref (struct sol_oic_resource *r)
Detailed Description
Routines to create clients talking OIC protocol.
Macro Definition Documentation
#define SOL_OIC_CLIENT_API_VERSION (1)
#define SOL_OIC_RESOURCE_API_VERSION (1)
Function Documentation
bool sol_oic_client_find_resource (struct sol_oic_client * client, struct sol_network_link_addr * cliaddr, const char * resource_type, void(*)(struct sol_oic_client *cli, struct sol_oic_resource *res, void *data) resource_found_cb, void * data)
References find_resource_ctx::client, IOTIVITY_NONCON_REQ_MID, OIC_CLIENT_CHECK_API, sol_oic_client::server, sol_coap_add_option(), sol_coap_header_set_id(), SOL_COAP_METHOD_GET, SOL_COAP_OPTION_ACCEPT, SOL_COAP_OPTION_URI_QUERY, sol_coap_packet_add_uri_path_option(), sol_coap_packet_request_new(), sol_coap_packet_unref(), sol_coap_send_packet_with_reply(), SOL_COAP_TYPE_NONCON, SOL_LOG_INTERNAL_INIT_ONCE, SOL_NULL_CHECK, sol_util_memdup(), and SOL_WRN.
Referenced by main().
bool sol_oic_client_resource_request (struct sol_oic_client * client, struct sol_oic_resource * res, sol_coap_method_t method, uint8_t * payload, size_t payload_len, void(*)(struct sol_oic_client *cli, const struct sol_network_link_addr *addr, const struct sol_str_slice *href, const struct sol_str_slice *payload, void *data) callback, void * data)
References OIC_CLIENT_CHECK_API, OIC_RESOURCE_CHECK_API, and SOL_NULL_CHECK.
bool sol_oic_client_resource_set_observable (struct sol_oic_client * client, struct sol_oic_resource * res, void(*)(struct sol_oic_client *cli, const struct sol_network_link_addr *addr, const struct sol_str_slice *href, const struct sol_str_slice *payload, void *data) callback, void * data, bool observe)
References sol_oic_resource::observable, sol_oic_resource::observe, OIC_CLIENT_CHECK_API, OIC_RESOURCE_CHECK_API, SOL_COAP_METHOD_GET, SOL_NULL_CHECK, SOL_WRN, and sol_oic_resource::timeout.
struct sol_oic_resource* sol_oic_resource_ref (struct sol_oic_resource * r)
References OIC_RESOURCE_CHECK_API, sol_oic_resource::refcnt, and SOL_NULL_CHECK.
void sol_oic_resource_unref (struct sol_oic_resource * r)
References sol_oic_resource::interfaces, OIC_RESOURCE_CHECK_API, sol_oic_resource::refcnt, SOL_NULL_CHECK, sol_vector_clear(), and sol_oic_resource::types.