Soletta: src/lib/common/sol-log-impl-riot.c File Reference
sol-log-impl-riot.c File Reference
#include <errno.h>
#include <stdio.h>
#include <string.h>
#include "sol-log-impl.h"
Functions
void sol_log_impl_domain_init_level (struct sol_log_domain *domain)
int sol_log_impl_init (void)
bool sol_log_impl_lock (void)
void sol_log_impl_print_function_stderr (void *data, const struct sol_log_domain *domain, uint8_t message_level, const char *file, const char *function, int line, const char *format, va_list args)
void sol_log_impl_shutdown (void)
void sol_log_impl_unlock (void)
Function Documentation
void sol_log_impl_domain_init_level (struct sol_log_domain * domain)
References _global_domain, sol_log_domain::level, sol_log_domain::name, and sol_str_table_lookup.
int sol_log_impl_init (void)
References _abort_level, _global_domain, _print_function, _print_function_data, _show_colors, _show_file, _show_function, _show_line, sol_log_domain::level, sol_log_print_function_journal(), sol_log_print_function_stderr(), sol_log_print_function_syslog(), and streq.
bool sol_log_impl_lock (void)
void sol_log_impl_print_function_stderr (void * data, const struct sol_log_domain * domain, uint8_t message_level, const char * file, const char * function, int line, const char * format, va_list args)
References _show_colors, _show_file, _show_function, _show_line, sol_log_domain::color, sol_log_domain::name, SOL_LOG_COLOR_HIGH, SOL_LOG_COLOR_RESET, sol_log_get_level_color(), and sol_log_level_to_str().
void sol_log_impl_shutdown (void)
void sol_log_impl_unlock (void)