Soletta: src/shared/sol-monitors.c File Reference
sol-monitors.c File Reference
#include <assert.h>
#include "sol-monitors.h"
Functions
void sol_monitors_clear (struct sol_monitors *ms)
int sol_monitors_del (struct sol_monitors *ms, uint16_t i)
void sol_monitors_end_walk (struct sol_monitors *ms)
int sol_monitors_find (const struct sol_monitors *ms, sol_monitors_cb_t cb, const void *data)
void sol_monitors_init_custom (struct sol_monitors *ms, uint16_t elem_size, sol_monitors_cleanup_func_t cleanup)
Function Documentation
void sol_monitors_clear (struct sol_monitors * ms)
References sol_monitors_entry::cb, sol_monitors::cleanup, sol_monitors::entries, sol_vector::len, sol_monitors::pending_deletion, sol_vector_clear(), and sol_monitors::walking.
Referenced by sol_platform_shutdown().
int sol_monitors_del (struct sol_monitors * ms, uint16_t i)
References sol_monitors_entry::cb, sol_monitors::cleanup, sol_monitors::entries, sol_monitors::pending_deletion, and sol_monitors::walking.
Referenced by sol_platform_add_service_monitor(), sol_platform_del_service_monitor(), and sol_platform_del_state_monitor().
void sol_monitors_end_walk (struct sol_monitors * ms)
References sol_monitors::walking.
int sol_monitors_find (const struct sol_monitors * ms, sol_monitors_cb_t cb, const void * data)
References sol_monitors_entry::cb, sol_monitors_entry::data, sol_monitors::entries, and sol_vector::len.
Referenced by sol_platform_del_state_monitor().
void sol_monitors_init_custom (struct sol_monitors * ms, uint16_t elem_size, sol_monitors_cleanup_func_t cleanup)
References sol_monitors::cleanup, sol_monitors::entries, sol_monitors::pending_deletion, sol_vector_init(), and sol_monitors::walking.
Referenced by sol_platform_init().