Soletta: src/lib/io/sol-pwm-linux.c File Reference
sol-pwm-linux.c File Reference
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include <unistd.h>
#include <time.h>
#include <limits.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <errno.h>
#include "sol-log-internal.h"
#include "sol-pwm.h"
#include "sol-util.h"
Data Structures
struct sol_pwm
Macros
#define EXPORT_STAT_RETRIES 10
#define PWM_BASE "/sys/class/pwm"
#define PWM_PATH(dst, pwm, action) snprintf(dst, sizeof(dst), PWM_BASE "/pwmchip%d/pwm%d/%s", pwm->device, pwm->channel, action);
#define SOL_LOG_DOMAIN &_log_domain
Functions
SOL_LOG_INTERNAL_DECLARE_STATIC (_log_domain,"pwm")
SOL_API void sol_pwm_close (struct sol_pwm *pwm)
SOL_API int32_t sol_pwm_get_duty_cycle (const struct sol_pwm *pwm)
SOL_API bool sol_pwm_get_enabled (const struct sol_pwm *pwm)
SOL_API int32_t sol_pwm_get_period (const struct sol_pwm *pwm)
SOL_API struct sol_pwm * sol_pwm_open_raw (int device, int channel, const struct sol_pwm_config *config)
SOL_API bool sol_pwm_set_duty_cycle (struct sol_pwm *pwm, uint32_t duty_cycle_ns)
SOL_API bool sol_pwm_set_enabled (struct sol_pwm *pwm, bool enable)
SOL_API bool sol_pwm_set_period (struct sol_pwm *pwm, uint32_t period_ns)
Macro Definition Documentation
#define EXPORT_STAT_RETRIES 10
#define PWM_BASE "/sys/class/pwm"
Referenced by sol_pwm_open_raw().
#define PWM_PATH (dst, pwm, action) snprintf(dst, sizeof(dst), PWM_BASE "/pwmchip%d/pwm%d/%s", pwm->device, pwm->channel, action);
#define SOL_LOG_DOMAIN &_log_domain
Function Documentation
SOL_LOG_INTERNAL_DECLARE_STATIC (_log_domain , "pwm")
SOL_API void sol_pwm_close (struct sol_pwm * pwm)
References sol_pwm::channel, sol_pwm::device, sol_pwm::duty_cycle, sol_pwm::owned, sol_pwm::period, SOL_NULL_CHECK, sol_pwm_set_duty_cycle(), sol_pwm_set_enabled(), and sol_pwm_set_period().
SOL_API int32_t sol_pwm_get_duty_cycle (const struct sol_pwm * pwm)
References sol_pwm::channel, sol_pwm::device, sol_pwm::duty_cycle, SOL_NULL_CHECK, and SOL_WRN.
SOL_API bool sol_pwm_get_enabled (const struct sol_pwm * pwm)
References sol_pwm::channel, sol_pwm::device, SOL_NULL_CHECK, and SOL_WRN.
SOL_API int32_t sol_pwm_get_period (const struct sol_pwm * pwm)
References sol_pwm::channel, sol_pwm::device, sol_pwm::period, SOL_NULL_CHECK, and SOL_WRN.
SOL_API struct sol_pwm* sol_pwm_open_raw (int device, int channel, const struct sol_pwm_config * config)
References sol_pwm_config::api_version, sol_pwm::channel, sol_pwm::device, sol_pwm::owned, PWM_BASE, SOL_LOG_INTERNAL_INIT_ONCE, SOL_PWM_CONFIG_API_VERSION, SOL_WRN, and unlikely.
SOL_API bool sol_pwm_set_duty_cycle (struct sol_pwm * pwm, uint32_t duty_cycle_ns)
References sol_pwm::channel, sol_pwm::device, sol_pwm::duty_cycle, SOL_NULL_CHECK, and SOL_WRN.
Referenced by sol_pwm_close().
SOL_API bool sol_pwm_set_enabled (struct sol_pwm * pwm, bool enable)
References sol_pwm::channel, sol_pwm::device, SOL_NULL_CHECK, and SOL_WRN.
Referenced by sol_pwm_close().
SOL_API bool sol_pwm_set_period (struct sol_pwm * pwm, uint32_t period_ns)
References sol_pwm::channel, sol_pwm::device, sol_pwm::period, SOL_NULL_CHECK, and SOL_WRN.
Referenced by sol_pwm_close().