Soletta: src/lib/comms/sol-oic-client.c File Reference
sol-oic-client.c File Reference
#include <arpa/inet.h>
#include <errno.h>
#include <fcntl.h>
#include <netinet/in.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/socket.h>
#include "sol-coap.h"
#include "sol-json.h"
#include "sol-log-internal.h"
#include "sol-mainloop.h"
#include "sol-missing.h"
#include "sol-util.h"
#include "sol-oic-client.h"
Data Structures
struct find_resource_ctx
struct resource_request_ctx
Macros
#define IOTIVITY_CON_REQ_MID 0xd42
#define IOTIVITY_CON_REQ_OBS_MID 0x7d44
#define IOTIVITY_NONCON_REQ_MID 0x7d40
#define OIC_CLIENT_CHECK_API(ptr,...)
#define OIC_RESOURCE_CHECK_API(ptr,...)
#define POLL_OBSERVE_TIMEOUT_MS 10000
Functions
SOL_LOG_INTERNAL_DECLARE (_sol_oic_client_log_domain,"oic-client")
SOL_API bool sol_oic_client_find_resource (struct sol_oic_client *client, struct sol_network_link_addr *cliaddr, const char *resource_type, void(*resource_found_cb)(struct sol_oic_client *cli, struct sol_oic_resource *res, void *data), void *data)
SOL_API bool sol_oic_client_resource_request (struct sol_oic_client *client, struct sol_oic_resource *res, sol_coap_method_t method, uint8_t *payload, size_t payload_len, void(*callback)(struct sol_oic_client *cli, const struct sol_network_link_addr *addr, const struct sol_str_slice *href, const struct sol_str_slice *payload, void *data), void *data)
SOL_API bool sol_oic_client_resource_set_observable (struct sol_oic_client *client, struct sol_oic_resource *res, void(*callback)(struct sol_oic_client *cli, const struct sol_network_link_addr *addr, const struct sol_str_slice *href, const struct sol_str_slice *payload, void *data), void *data, bool observe)
SOL_API struct sol_oic_resource * sol_oic_resource_ref (struct sol_oic_resource *r)
SOL_API void sol_oic_resource_unref (struct sol_oic_resource *r)
Macro Definition Documentation
#define IOTIVITY_CON_REQ_MID 0xd42
#define IOTIVITY_CON_REQ_OBS_MID 0x7d44
#define IOTIVITY_NONCON_REQ_MID 0x7d40
Referenced by sol_oic_client_find_resource().
#define OIC_CLIENT_CHECK_API (ptr, ...)
Value:
do {                                        \
        if (unlikely(ptr->api_version != SOL_OIC_CLIENT_API_VERSION)) { \
            SOL_WRN("Couldn't handle oic client that has unsupported "\
                    "version '%u', expected version is '%u'", \
                    ptr->api_version, SOL_OIC_CLIENT_API_VERSION); \
            return __VA_ARGS__; \
        } \
    } while (0)
Referenced by sol_oic_client_find_resource(), sol_oic_client_resource_request(), and sol_oic_client_resource_set_observable().
#define OIC_RESOURCE_CHECK_API (ptr, ...)
Value:
do {                                        \
        if (unlikely(ptr->api_version != \
                SOL_OIC_RESOURCE_API_VERSION)) { \
            SOL_WRN("Couldn't handle oic client resource that has unsupported "\
                    "version '%u', expected version is '%u'", \
                    ptr->api_version, SOL_OIC_RESOURCE_API_VERSION); \
            return __VA_ARGS__; \
        } \
    } while (0)
Referenced by sol_oic_client_resource_request(), sol_oic_client_resource_set_observable(), sol_oic_resource_ref(), and sol_oic_resource_unref().
#define POLL_OBSERVE_TIMEOUT_MS 10000
Function Documentation
SOL_LOG_INTERNAL_DECLARE (_sol_oic_client_log_domain , "oic-client")
SOL_API bool sol_oic_client_find_resource (struct sol_oic_client * client, struct sol_network_link_addr * cliaddr, const char * resource_type, void(*)(struct sol_oic_client *cli, struct sol_oic_resource *res, void *data) resource_found_cb, void * data)
References find_resource_ctx::client, IOTIVITY_NONCON_REQ_MID, OIC_CLIENT_CHECK_API, sol_oic_client::server, sol_coap_add_option(), sol_coap_header_set_id(), SOL_COAP_METHOD_GET, SOL_COAP_OPTION_ACCEPT, SOL_COAP_OPTION_URI_QUERY, sol_coap_packet_add_uri_path_option(), sol_coap_packet_request_new(), sol_coap_packet_unref(), sol_coap_send_packet_with_reply(), SOL_COAP_TYPE_NONCON, SOL_LOG_INTERNAL_INIT_ONCE, SOL_NULL_CHECK, sol_util_memdup(), and SOL_WRN.
Referenced by main().
SOL_API bool sol_oic_client_resource_request (struct sol_oic_client * client, struct sol_oic_resource * res, sol_coap_method_t method, uint8_t * payload, size_t payload_len, void(*)(struct sol_oic_client *cli, const struct sol_network_link_addr *addr, const struct sol_str_slice *href, const struct sol_str_slice *payload, void *data) callback, void * data)
References OIC_CLIENT_CHECK_API, OIC_RESOURCE_CHECK_API, and SOL_NULL_CHECK.
SOL_API bool sol_oic_client_resource_set_observable (struct sol_oic_client * client, struct sol_oic_resource * res, void(*)(struct sol_oic_client *cli, const struct sol_network_link_addr *addr, const struct sol_str_slice *href, const struct sol_str_slice *payload, void *data) callback, void * data, bool observe)
References sol_oic_resource::observable, sol_oic_resource::observe, OIC_CLIENT_CHECK_API, OIC_RESOURCE_CHECK_API, SOL_COAP_METHOD_GET, SOL_NULL_CHECK, SOL_WRN, and sol_oic_resource::timeout.
SOL_API struct sol_oic_resource* sol_oic_resource_ref (struct sol_oic_resource * r)
References OIC_RESOURCE_CHECK_API, sol_oic_resource::refcnt, and SOL_NULL_CHECK.
SOL_API void sol_oic_resource_unref (struct sol_oic_resource * r)
References sol_oic_resource::interfaces, OIC_RESOURCE_CHECK_API, sol_oic_resource::refcnt, SOL_NULL_CHECK, sol_vector_clear(), and sol_oic_resource::types.