Soletta: src/lib/common/sol-mainloop-impl-riot.c File Reference
sol-mainloop-impl-riot.c File Reference
#include <stdbool.h>
#include <stdlib.h>
#include <unistd.h>
#include <time.h>
#include <riotos/sched.h>
#include <vtimer.h>
#include "sol-mainloop-common.h"
#include "sol-interrupt_scheduler_riot.h"
#include "sol-mainloop-impl.h"
#include "sol-vector.h"
Macros
#define DEFAULT_USLEEP_TIME 10000
#define MSG_BUFFER_SIZE 32
Functions
void * sol_mainloop_impl_child_watch_add (uint64_t pid, void(*cb)(void *data, uint64_t pid, int status), const void *data)
bool sol_mainloop_impl_child_watch_del (void *handle)
void * sol_mainloop_impl_fd_add (int fd, unsigned int flags, bool(*cb)(void *data, int fd, unsigned int active_flags), const void *data)
bool sol_mainloop_impl_fd_del (void *handle)
int sol_mainloop_impl_init (void)
void sol_mainloop_impl_iter (void)
void sol_mainloop_impl_lock (void)
bool sol_mainloop_impl_main_thread_check (void)
void sol_mainloop_impl_main_thread_notify (void)
void sol_mainloop_impl_shutdown (void)
void sol_mainloop_impl_unlock (void)
Macro Definition Documentation
#define DEFAULT_USLEEP_TIME 10000
#define MSG_BUFFER_SIZE 32
Referenced by sol_mainloop_impl_init().
Function Documentation
void* sol_mainloop_impl_child_watch_add (uint64_t pid, void(*)(void *data, uint64_t pid, int status) cb, const void * data)
References child_wrap_data::cb, child_wrap_data::data, SOL_CRI, and SOL_NULL_CHECK.
bool sol_mainloop_impl_child_watch_del (void * handle)
References SOL_CRI.
void* sol_mainloop_impl_fd_add (int fd, unsigned int flags, bool(*)(void *data, int fd, unsigned int active_flags) cb, const void * data)
References fd_wrap_data::cb, fd_wrap_data::data, SOL_CRI, SOL_FD_FLAGS_ERR, SOL_FD_FLAGS_HUP, SOL_FD_FLAGS_IN, SOL_FD_FLAGS_NVAL, SOL_FD_FLAGS_OUT, SOL_FD_FLAGS_PRI, and SOL_NULL_CHECK.
bool sol_mainloop_impl_fd_del (void * handle)
References SOL_CRI.
int sol_mainloop_impl_init (void)
References MSG_BUFFER_SIZE, SOL_CRI, sol_interrupt_scheduler_set_pid(), and sol_mainloop_common_init().
void sol_mainloop_impl_iter (void)
References sol_interrupt_scheduler_process(), sol_mainloop_common_idler_process(), sol_mainloop_common_loop_check(), and sol_mainloop_common_timeout_process().
Referenced by sol_mainloop_impl_run().
void sol_mainloop_impl_lock (void)
Referenced by sol_mainloop_common_idler_process(), sol_mainloop_common_timeout_process(), sol_mainloop_impl_idle_add(), sol_mainloop_impl_idle_del(), sol_mainloop_impl_timeout_add(), and sol_mainloop_impl_timeout_del().
bool sol_mainloop_impl_main_thread_check (void)
Referenced by sol_mainloop_impl_run().
void sol_mainloop_impl_main_thread_notify (void)
Referenced by sol_mainloop_impl_quit().
void sol_mainloop_impl_shutdown (void)
References sol_mainloop_common_shutdown().
void sol_mainloop_impl_unlock (void)
Referenced by sol_mainloop_common_idler_process(), sol_mainloop_common_timeout_process(), sol_mainloop_impl_idle_add(), sol_mainloop_impl_idle_del(), sol_mainloop_impl_timeout_add(), and sol_mainloop_impl_timeout_del().