Soletta: src/lib/common/sol-worker-thread-impl.h File Reference
sol-worker-thread-impl.h File Reference
#include <stdbool.h>
#include "sol-log-internal.h"
#include "sol-worker-thread.h"
Macros
#define SOL_LOG_DOMAIN &_sol_worker_thread_log_domain
Functions
void sol_worker_thread_impl_cancel (void *handle)
bool sol_worker_thread_impl_cancel_check (const void *handle)
void sol_worker_thread_impl_feedback (void *handle)
void * sol_worker_thread_impl_new (const struct sol_worker_thread_spec *spec)
Variables
struct sol_log_domain _sol_worker_thread_log_domain
Macro Definition Documentation
#define SOL_LOG_DOMAIN &_sol_worker_thread_log_domain
Function Documentation
void sol_worker_thread_impl_cancel (void * handle)
References sol_worker_thread_spec::cancel, sol_worker_thread_spec::data, sol_worker_thread_glib::idler, sol_worker_thread_posix::idler, sol_idle_del(), SOL_NULL_CHECK, sol_worker_thread_impl_cancel_check(), SOL_WRN, sol_worker_thread_glib::spec, sol_worker_thread_posix::spec, sol_worker_thread_glib::thread, and sol_worker_thread_posix::thread.
Referenced by sol_worker_thread_cancel().
bool sol_worker_thread_impl_cancel_check (const void * handle)
References sol_worker_thread_glib::cancel, sol_worker_thread_posix::cancel, sol_worker_thread_posix::thread, and sol_worker_thread_glib::thread.
Referenced by sol_worker_thread_cancel_check(), sol_worker_thread_impl_cancel(), and sol_worker_thread_impl_feedback().
void sol_worker_thread_impl_feedback (void * handle)
References sol_worker_thread_spec::feedback, sol_worker_thread_glib::idler, sol_worker_thread_posix::idler, sol_worker_thread_glib::lock, sol_idle_add(), SOL_NULL_CHECK, sol_worker_thread_impl_cancel_check(), SOL_WRN, sol_worker_thread_glib::spec, sol_worker_thread_posix::spec, sol_worker_thread_posix::thread, and sol_worker_thread_glib::thread.
Referenced by sol_worker_thread_feedback().
void* sol_worker_thread_impl_new (const struct sol_worker_thread_spec * spec)
References sol_worker_thread_glib::lock, sol_worker_thread_posix::lock, SOL_INT_CHECK_GOTO, sol_mainloop_posix_signals_block(), sol_mainloop_posix_signals_unblock(), SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, sol_worker_thread_glib::spec, sol_worker_thread_posix::spec, sol_worker_thread_posix::thread, and sol_worker_thread_glib::thread.
Referenced by sol_worker_thread_new().
Variable Documentation
struct sol_log_domain _sol_worker_thread_log_domain