Soletta: src/bin/sol-fbp-to-dot/main.c File Reference
main.c File Reference
#include <errno.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include "sol-log-internal.h"
#include "sol-fbp.h"
#include "sol-file-reader.h"
#include "sol-flow-builder.h"
#include "sol-flow-internal.h"
#include "sol-flow.h"
#include "sol-mainloop.h"
#include "sol-str-slice.h"
#include "sol-str-table.h"
#include "sol-util.h"
#include "sol-vector.h"
Macros
#define SOL_LOG_DOMAIN &_log_domain
Functions
int main (int argc, char *argv[])
SOL_LOG_INTERNAL_DECLARE_STATIC (_log_domain,"flow-to-dot")
Macro Definition Documentation
#define SOL_LOG_DOMAIN &_log_domain
Referenced by sol_flow_init(), sol_init(), sol_pin_mux_init(), and sol_platform_init().
Function Documentation
int main (int argc, char * argv[])
References sol_fbp_graph_fini(), sol_file_reader_close(), sol_file_reader_open(), sol_init(), SOL_LOG_INTERNAL_INIT_ONCE, sol_shutdown(), and sol_util_strerrora.
SOL_LOG_INTERNAL_DECLARE_STATIC (_log_domain , "flow-to-dot")