Soletta: src/lib/comms/sol-coap.c File Reference
sol-coap.c File Reference
#include <arpa/inet.h>
#include <netinet/in.h>
#include <errno.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "sol-log-internal.h"
#include "sol-mainloop.h"
#include "sol-network.h"
#include "sol-socket.h"
#include "sol-str-slice.h"
#include "sol-util.h"
#include "sol-vector.h"
#include "coap.h"
#include "sol-coap.h"
Data Structures
struct outgoing
struct pending_reply
struct resource_context
struct resource_observer
struct sol_coap_server
Macros
#define ACK_TIMEOUT_MS 2345
#define COAP_RESOURCE_CHECK_API(...)
#define IPV4_ALL_COAP_NODES_GROUP "224.0.1.187"
#define IPV6_ALL_COAP_NODES_SCOPE_LOCAL "ff02::fd"
#define IPV6_ALL_COAP_NODES_SCOPE_SITE "ff05::fd"
#define MAX_RETRANSMIT 4
#define OC_CORE_ELEM_JSON_END "}}"
#define OC_CORE_ELEM_JSON_START "{\"href\":\"%s\",\"prop\":{"
#define OC_CORE_JSON_END "]}"
#define OC_CORE_JSON_SEPARATOR ","
#define OC_CORE_JSON_START "{\"oc\":["
#define OC_CORE_PROP_JSON_NUMBER "\"%s\":%d"
#define OC_CORE_PROP_JSON_SLICE "\"%s\":[\"%.*s\"]"
#define OC_CORE_PROP_JSON_STRING "\"%s\":[\"%s\"]"
#define SOL_LOG_DOMAIN &_sol_coap_log_domain
Functions
SOL_API int sol_coap_add_option (struct sol_coap_packet *pkt, uint16_t code, const void *value, uint16_t len)
SOL_API const void * sol_coap_find_first_option (struct sol_coap_packet *pkt, uint16_t code, uint16_t *len)
SOL_API uint8_t sol_coap_header_get_code (const struct sol_coap_packet *pkt)
SOL_API uint16_t sol_coap_header_get_id (const struct sol_coap_packet *pkt)
SOL_API uint8_t * sol_coap_header_get_token (const struct sol_coap_packet *pkt, uint8_t *len)
SOL_API uint8_t sol_coap_header_get_type (const struct sol_coap_packet *pkt)
SOL_API uint8_t sol_coap_header_get_ver (const struct sol_coap_packet *pkt)
SOL_API void sol_coap_header_set_code (struct sol_coap_packet *pkt, uint8_t code)
SOL_API void sol_coap_header_set_id (struct sol_coap_packet *pkt, uint16_t id)
SOL_API bool sol_coap_header_set_token (struct sol_coap_packet *pkt, uint8_t *token, uint8_t tokenlen)
SOL_API void sol_coap_header_set_type (struct sol_coap_packet *pkt, uint8_t type)
SOL_API void sol_coap_header_set_ver (struct sol_coap_packet *pkt, uint8_t ver)
SOL_API int sol_coap_packet_add_uri_path_option (struct sol_coap_packet *pkt, const char *uri)
SOL_API int sol_coap_packet_get_buf (struct sol_coap_packet *pkt, uint8_t **buf, uint16_t *len)
SOL_API int sol_coap_packet_get_payload (struct sol_coap_packet *pkt, uint8_t **buf, uint16_t *len)
SOL_API bool sol_coap_packet_has_payload (struct sol_coap_packet *pkt)
SOL_API struct sol_coap_packet * sol_coap_packet_new (struct sol_coap_packet *old)
SOL_API struct sol_coap_packet * sol_coap_packet_notification_new (struct sol_coap_server *server, struct sol_coap_resource *resource)
SOL_API struct sol_coap_packet * sol_coap_packet_ref (struct sol_coap_packet *pkt)
SOL_API struct sol_coap_packet * sol_coap_packet_request_new (sol_coap_method_t method, sol_coap_msgtype_t type)
SOL_API int sol_coap_packet_send_notification (struct sol_coap_server *server, struct sol_coap_resource *resource, struct sol_coap_packet *pkt)
SOL_API int sol_coap_packet_set_payload_used (struct sol_coap_packet *pkt, uint16_t len)
SOL_API void sol_coap_packet_unref (struct sol_coap_packet *pkt)
SOL_API int sol_coap_send_packet (struct sol_coap_server *server, struct sol_coap_packet *pkt, const struct sol_network_link_addr *cliaddr)
SOL_API int sol_coap_send_packet_with_reply (struct sol_coap_server *server, struct sol_coap_packet *pkt, const struct sol_network_link_addr *cliaddr, int(*reply_cb)(struct sol_coap_packet *req, const struct sol_network_link_addr *cliaddr, void *data), void *data)
SOL_API struct sol_coap_server * sol_coap_server_new (int port)
SOL_API struct sol_coap_server * sol_coap_server_ref (struct sol_coap_server *server)
SOL_API bool sol_coap_server_register_resource (struct sol_coap_server *server, const struct sol_coap_resource *resource, void *data)
SOL_API void sol_coap_server_unref (struct sol_coap_server *server)
SOL_API int sol_coap_uri_path_to_buf (const struct sol_str_slice path[], uint8_t *buf, size_t buflen)
SOL_LOG_INTERNAL_DECLARE (_sol_coap_log_domain,"coap")
Macro Definition Documentation
#define ACK_TIMEOUT_MS 2345
#define COAP_RESOURCE_CHECK_API (...)
Value:
do { \
        if (unlikely(resource->api_version != \
                SOL_COAP_RESOURCE_API_VERSION)) { \
            SOL_WRN("Couldn't handle resource that has unsupported version " \
                    "'%u', expected version is '%u'", \
                    resource->api_version, SOL_COAP_RESOURCE_API_VERSION); \
            return __VA_ARGS__; \
        } \
    } while (0)
Referenced by sol_coap_packet_notification_new(), sol_coap_packet_send_notification(), and sol_coap_server_register_resource().
#define IPV4_ALL_COAP_NODES_GROUP "224.0.1.187"
#define IPV6_ALL_COAP_NODES_SCOPE_LOCAL "ff02::fd"
#define IPV6_ALL_COAP_NODES_SCOPE_SITE "ff05::fd"
#define MAX_RETRANSMIT 4
#define OC_CORE_ELEM_JSON_END "}}"
#define OC_CORE_ELEM_JSON_START "{\"href\":\"%s\",\"prop\":{"
#define OC_CORE_JSON_END "]}"
#define OC_CORE_JSON_SEPARATOR ","
#define OC_CORE_JSON_START "{\"oc\":["
#define OC_CORE_PROP_JSON_NUMBER "\"%s\":%d"
#define OC_CORE_PROP_JSON_SLICE "\"%s\":[\"%.*s\"]"
#define OC_CORE_PROP_JSON_STRING "\"%s\":[\"%s\"]"
#define SOL_LOG_DOMAIN &_sol_coap_log_domain
Function Documentation
SOL_API int sol_coap_add_option (struct sol_coap_packet * pkt, uint16_t code, const void * value, uint16_t len)
References sol_coap_packet::buf, option_context::buf, option_context::buflen, coap_get_header_len(), coap_option_encode(), coap_parse_option(), option_context::delta, sol_coap_packet::payload, sol_coap_packet::size, SOL_NULL_CHECK, SOL_WRN, sol_coap_packet::start, sol_coap_packet::used, and option_context::used.
Referenced by main(), sol_coap_packet_add_uri_path_option(), sol_coap_packet_notification_new(), and sol_oic_client_find_resource().
SOL_API const void* sol_coap_find_first_option (struct sol_coap_packet * pkt, uint16_t code, uint16_t * len)
References coap_find_options(), sol_coap_option_value::len, SOL_NULL_CHECK, and sol_coap_option_value::value.
SOL_API uint8_t sol_coap_header_get_code (const struct sol_coap_packet * pkt)
References sol_coap_packet::buf, coap_header::code, SOL_COAP_METHOD_DELETE, SOL_COAP_METHOD_GET, SOL_COAP_METHOD_POST, SOL_COAP_METHOD_PUT, SOL_COAP_RSPCODE_BAD_GATEWAY, SOL_COAP_RSPCODE_BAD_OPTION, SOL_COAP_RSPCODE_BAD_REQUEST, SOL_COAP_RSPCODE_CHANGED, SOL_COAP_RSPCODE_CONTENT, SOL_COAP_RSPCODE_CREATED, SOL_COAP_RSPCODE_DELETED, SOL_COAP_RSPCODE_FORBIDDEN, SOL_COAP_RSPCODE_GATEWAY_TIMEOUT, SOL_COAP_RSPCODE_INTERNAL_ERROR, SOL_COAP_RSPCODE_NOT_ACCEPTABLE, SOL_COAP_RSPCODE_NOT_ALLOWED, SOL_COAP_RSPCODE_NOT_FOUND, SOL_COAP_RSPCODE_NOT_IMPLEMENTED, SOL_COAP_RSPCODE_OK, SOL_COAP_RSPCODE_PRECONDITION_FAILED, SOL_COAP_RSPCODE_PROXYING_NOT_SUPPORTED, SOL_COAP_RSPCODE_REQUEST_TOO_LARGE, SOL_COAP_RSPCODE_SERVICE_UNAVAILABLE, SOL_COAP_RSPCODE_UNAUTHORIZED, SOL_COAP_RSPCODE_VALID, and SOL_WRN.
Referenced by sol_coap_packet_send_notification().
SOL_API uint16_t sol_coap_header_get_id (const struct sol_coap_packet * pkt)
References sol_coap_packet::buf, and coap_header::id.
Referenced by sol_coap_packet_new(), and sol_coap_send_packet_with_reply().
SOL_API uint8_t* sol_coap_header_get_token (const struct sol_coap_packet * pkt, uint8_t * len)
References sol_coap_packet::buf, and coap_header::tkl.
Referenced by sol_coap_packet_new(), sol_coap_packet_send_notification(), and sol_coap_send_packet_with_reply().
SOL_API uint8_t sol_coap_header_get_type (const struct sol_coap_packet * pkt)
References sol_coap_packet::buf, and coap_header::type.
Referenced by sol_coap_packet_send_notification().
SOL_API uint8_t sol_coap_header_get_ver (const struct sol_coap_packet * pkt)
References sol_coap_packet::buf, and coap_header::ver.
SOL_API void sol_coap_header_set_code (struct sol_coap_packet * pkt, uint8_t code)
References sol_coap_packet::buf, and coap_header::code.
Referenced by sol_coap_packet_request_new(), sol_coap_packet_send_notification(), and sol_oic_notify_observers().
SOL_API void sol_coap_header_set_id (struct sol_coap_packet * pkt, uint16_t id)
References sol_coap_packet::buf, and coap_header::id.
Referenced by sol_coap_packet_new(), sol_coap_packet_request_new(), and sol_oic_client_find_resource().
SOL_API bool sol_coap_header_set_token (struct sol_coap_packet * pkt, uint8_t * token, uint8_t tokenlen)
References sol_coap_packet::buf, sol_coap_packet::payload, sol_coap_packet::size, coap_header::tkl, and sol_coap_packet::used.
Referenced by main(), sol_coap_packet_new(), and sol_coap_packet_send_notification().
SOL_API void sol_coap_header_set_type (struct sol_coap_packet * pkt, uint8_t type)
References sol_coap_packet::buf, and coap_header::type.
Referenced by sol_coap_packet_notification_new(), sol_coap_packet_request_new(), and sol_coap_packet_send_notification().
SOL_API void sol_coap_header_set_ver (struct sol_coap_packet * pkt, uint8_t ver)
References sol_coap_packet::buf, and coap_header::ver.
Referenced by sol_coap_packet_new().
SOL_API int sol_coap_packet_add_uri_path_option (struct sol_coap_packet * pkt, const char * uri)
References sol_coap_add_option(), SOL_COAP_OPTION_URI_PATH, SOL_NULL_CHECK, and SOL_WRN.
Referenced by sol_oic_client_find_resource().
SOL_API int sol_coap_packet_get_buf (struct sol_coap_packet * pkt, uint8_t ** buf, uint16_t * len)
References sol_coap_packet::buf, and SOL_NULL_CHECK.
SOL_API int sol_coap_packet_get_payload (struct sol_coap_packet * pkt, uint8_t ** buf, uint16_t * len)
References sol_coap_packet::buf, COAP_MARKER, sol_coap_packet::payload, sol_coap_packet::size, SOL_INT_CHECK, SOL_NULL_CHECK, sol_coap_packet::start, and sol_coap_packet::used.
Referenced by sol_oic_notify_observers().
SOL_API bool sol_coap_packet_has_payload (struct sol_coap_packet * pkt)
References sol_coap_packet::payload, sol_coap_packet::size, SOL_NULL_CHECK, sol_coap_packet::start, and sol_coap_packet::used.
SOL_API struct sol_coap_packet* sol_coap_packet_new (struct sol_coap_packet * old)
References COAP_UDP_MTU, COAP_VERSION, sol_coap_packet::payload, sol_coap_packet::refcnt, sol_coap_packet::size, sol_coap_header_get_id(), sol_coap_header_get_token(), sol_coap_header_set_id(), sol_coap_header_set_token(), sol_coap_header_set_ver(), SOL_NULL_CHECK, coap_header::tkl, and sol_coap_packet::used.
Referenced by sol_coap_packet_notification_new(), sol_coap_packet_request_new(), and sol_coap_packet_send_notification().
SOL_API struct sol_coap_packet* sol_coap_packet_notification_new (struct sol_coap_server * server, struct sol_coap_resource * resource)
References resource_context::age, COAP_RESOURCE_CHECK_API, sol_coap_add_option(), sol_coap_header_set_type(), SOL_COAP_OPTION_OBSERVE, sol_coap_packet_new(), SOL_COAP_TYPE_NONCON, and SOL_NULL_CHECK.
Referenced by sol_oic_notify_observers().
SOL_API struct sol_coap_packet* sol_coap_packet_ref (struct sol_coap_packet * pkt)
References sol_coap_packet::refcnt, and SOL_NULL_CHECK.
SOL_API struct sol_coap_packet* sol_coap_packet_request_new (sol_coap_method_t method, sol_coap_msgtype_t type)
References sol_coap_header_set_code(), sol_coap_header_set_id(), sol_coap_header_set_type(), sol_coap_packet_new(), and SOL_NULL_CHECK.
Referenced by main(), and sol_oic_client_find_resource().
SOL_API int sol_coap_packet_send_notification (struct sol_coap_server * server, struct sol_coap_resource * resource, struct sol_coap_packet * pkt)
References sol_coap_packet::buf, resource_observer::cliaddr, COAP_RESOURCE_CHECK_API, resource_context::observers, sol_coap_packet::payload, sol_coap_header_get_code(), sol_coap_header_get_token(), sol_coap_header_get_type(), sol_coap_header_set_code(), sol_coap_header_set_token(), sol_coap_header_set_type(), sol_coap_packet_new(), sol_coap_packet_unref(), SOL_INET_ADDR_STRLEN, sol_network_addr_to_str(), SOL_NULL_CHECK, SOL_PTR_VECTOR_FOREACH_IDX, SOL_WRN, coap_header::tkl, resource_observer::tkl, resource_observer::token, and sol_coap_packet::used.
Referenced by sol_oic_notify_observers().
SOL_API int sol_coap_packet_set_payload_used (struct sol_coap_packet * pkt, uint16_t len)
References sol_coap_packet::payload, sol_coap_packet::size, SOL_INT_CHECK, SOL_NULL_CHECK, sol_coap_packet::start, and sol_coap_packet::used.
Referenced by sol_oic_notify_observers().
SOL_API void sol_coap_packet_unref (struct sol_coap_packet * pkt)
References sol_coap_packet::refcnt, and SOL_NULL_CHECK.
Referenced by main(), sol_coap_packet_send_notification(), sol_coap_send_packet_with_reply(), sol_oic_client_find_resource(), and sol_oic_notify_observers().
SOL_API int sol_coap_send_packet (struct sol_coap_server * server, struct sol_coap_packet * pkt, const struct sol_network_link_addr * cliaddr)
References sol_coap_send_packet_with_reply().
SOL_API int sol_coap_send_packet_with_reply (struct sol_coap_server * server, struct sol_coap_packet * pkt, const struct sol_network_link_addr * cliaddr, int(*)(struct sol_coap_packet *req, const struct sol_network_link_addr *cliaddr, void *data) reply_cb, void * data)
References pending_reply::cb, coap_find_options(), pending_reply::data, pending_reply::id, sol_coap_option_value::len, pending_reply::observing, sol_coap_server::pending, sol_coap_header_get_id(), sol_coap_header_get_token(), SOL_COAP_OPTION_OBSERVE, sol_coap_packet_unref(), SOL_INET_ADDR_STRLEN, SOL_INT_CHECK_GOTO, sol_network_addr_to_str(), sol_ptr_vector_append(), sol_util_strerrora, SOL_WRN, pending_reply::tkl, pending_reply::token, and sol_coap_option_value::value.
Referenced by main(), sol_coap_send_packet(), and sol_oic_client_find_resource().
SOL_API struct sol_coap_server* sol_coap_server_new (int port)
References sol_coap_server::contexts, sol_network_link_addr::family, sol_coap_server::fd, sol_coap_server::outgoing, sol_coap_server::pending, sol_coap_server::read_watch, sol_coap_server::refcnt, SOCK_CLOEXEC, SOL_DBG, sol_fd_add(), SOL_FD_FLAGS_IN, SOL_LOG_INTERNAL_INIT_ONCE, sol_network_get_available_links(), sol_network_init(), sol_network_link_get_name(), sol_network_subscribe_events(), SOL_NULL_CHECK_GOTO, sol_socket_bind(), sol_util_strerrora, SOL_VECTOR_FOREACH_IDX, sol_vector_init(), and SOL_WRN.
Referenced by main(), and sol_oic_server_init().
SOL_API struct sol_coap_server* sol_coap_server_ref (struct sol_coap_server * server)
References sol_coap_server::refcnt, and SOL_NULL_CHECK.
SOL_API bool sol_coap_server_register_resource (struct sol_coap_server * server, const struct sol_coap_resource * resource, void * data)
References resource_context::age, COAP_RESOURCE_CHECK_API, sol_coap_server::contexts, resource_context::data, resource_context::observers, resource_context::resource, SOL_NULL_CHECK, and sol_vector_append().
Referenced by main(), sol_oic_device_definition_register_resource_type(), sol_oic_server_init(), and sol_oic_server_register_definition().
SOL_API void sol_coap_server_unref (struct sol_coap_server * server)
References sol_coap_server::refcnt, and SOL_NULL_CHECK.
Referenced by main(), and sol_oic_server_release().
SOL_API int sol_coap_uri_path_to_buf (const struct sol_str_slice path[], uint8_t * buf, size_t buflen)
References sol_str_slice::data, sol_str_slice::len, and SOL_NULL_CHECK.
SOL_LOG_INTERNAL_DECLARE (_sol_coap_log_domain , "coap")