Soletta: src/lib/common/sol-mainloop-impl.h File Reference
sol-mainloop-impl.h File Reference
#include "sol-log-internal.h"
#include "sol-mainloop.h"
Macros
#define SOL_LOG_DOMAIN &_sol_mainloop_log_domain
Functions
void * sol_mainloop_impl_child_watch_add (uint64_t pid, void(*cb)(void *data, uint64_t pid, int status), const void *data)
bool sol_mainloop_impl_child_watch_del (void *handle)
void * sol_mainloop_impl_fd_add (int fd, unsigned int flags, bool(*cb)(void *data, int fd, unsigned int active_flags), const void *data)
bool sol_mainloop_impl_fd_del (void *handle)
void * sol_mainloop_impl_idle_add (bool(*cb)(void *data), const void *data)
bool sol_mainloop_impl_idle_del (void *handle)
int sol_mainloop_impl_init (void)
void sol_mainloop_impl_quit (void)
void sol_mainloop_impl_run (void)
void sol_mainloop_impl_shutdown (void)
void * sol_mainloop_impl_timeout_add (unsigned int timeout_ms, bool(*cb)(void *data), const void *data)
bool sol_mainloop_impl_timeout_del (void *handle)
Variables
struct sol_log_domain _sol_mainloop_log_domain
Macro Definition Documentation
#define SOL_LOG_DOMAIN &_sol_mainloop_log_domain
Function Documentation
void* sol_mainloop_impl_child_watch_add (uint64_t pid, void(*)(void *data, uint64_t pid, int status) cb, const void * data)
References sol_child_watch_posix::cb, child_wrap_data::cb, sol_child_watch_posix::data, child_wrap_data::data, sol_child_watch_posix::pid, sol_child_watch_posix::remove_me, SOL_CRI, SOL_INT_CHECK_GOTO, sol_mainloop_impl_lock(), sol_mainloop_impl_unlock(), SOL_NULL_CHECK, and sol_ptr_vector_append().
Referenced by sol_child_watch_add().
bool sol_mainloop_impl_child_watch_del (void * handle)
References sol_child_watch_posix::remove_me, SOL_CRI, sol_mainloop_impl_lock(), and sol_mainloop_impl_unlock().
Referenced by sol_child_watch_del().
void* sol_mainloop_impl_fd_add (int fd, unsigned int flags, bool(*)(void *data, int fd, unsigned int active_flags) cb, const void * data)
References sol_fd_posix::cb, fd_wrap_data::cb, sol_fd_posix::data, fd_wrap_data::data, sol_fd_posix::fd, sol_fd_posix::flags, sol_fd_posix::invalid, sol_fd_posix::remove_me, SOL_CRI, SOL_FD_FLAGS_ERR, SOL_FD_FLAGS_HUP, SOL_FD_FLAGS_IN, SOL_FD_FLAGS_NVAL, SOL_FD_FLAGS_OUT, SOL_FD_FLAGS_PRI, SOL_INT_CHECK_GOTO, sol_mainloop_impl_lock(), sol_mainloop_impl_unlock(), SOL_NULL_CHECK, and sol_ptr_vector_append().
Referenced by sol_fd_add().
bool sol_mainloop_impl_fd_del (void * handle)
References sol_fd_posix::remove_me, SOL_CRI, sol_mainloop_impl_lock(), and sol_mainloop_impl_unlock().
Referenced by sol_fd_del().
void* sol_mainloop_impl_idle_add (bool(*)(void *data) cb, const void * data)
References sol_idler_common::cb, gsourcefunc_wrap_data::cb, sol_idler_common::data, gsourcefunc_wrap_data::data, sol_idler_common::idler_ready, sol_idler_common::idler_ready_on_next_iteration, SOL_INT_CHECK_GOTO, sol_mainloop_impl_lock(), sol_mainloop_impl_unlock(), SOL_NULL_CHECK, sol_ptr_vector_append(), and sol_idler_common::status.
Referenced by sol_idle_add().
bool sol_mainloop_impl_idle_del (void * handle)
References sol_idler_common::idler_deleted, sol_mainloop_impl_lock(), sol_mainloop_impl_unlock(), and sol_idler_common::status.
Referenced by sol_idle_del().
int sol_mainloop_impl_init (void)
References MSG_BUFFER_SIZE, siginfo_handler::sig, SIGINFO_HANDLER_FOREACH, SIGPROCMASK, SOL_CRI, sol_interrupt_scheduler_set_pid(), sol_mainloop_common_init(), and threads_init.
Referenced by sol_init().
void sol_mainloop_impl_quit (void)
References sol_mainloop_common_loop_set(), and sol_mainloop_impl_main_thread_notify().
Referenced by sol_quit_with_code().
void sol_mainloop_impl_run (void)
References SOL_ERR, sol_mainloop_common_loop_check(), sol_mainloop_common_loop_set(), sol_mainloop_impl_iter(), and sol_mainloop_impl_main_thread_check().
Referenced by sol_run().
void sol_mainloop_impl_shutdown (void)
References siginfo_handler::sig, SIGINFO_HANDLER_FOREACH, SIGPROCMASK, sol_mainloop_common_shutdown(), SOL_PTR_VECTOR_FOREACH_IDX, and threads_shutdown.
Referenced by sol_init(), and sol_shutdown().
void* sol_mainloop_impl_timeout_add (unsigned int timeout_ms, bool(*)(void *data) cb, const void * data)
References sol_timeout_common::cb, gsourcefunc_wrap_data::cb, sol_timeout_common::data, gsourcefunc_wrap_data::data, sol_timeout_common::expire, MSEC_PER_SEC, NSEC_PER_MSEC, sol_timeout_common::remove_me, SOL_INT_CHECK_GOTO, sol_mainloop_impl_lock(), sol_mainloop_impl_unlock(), SOL_NULL_CHECK, sol_ptr_vector_insert_sorted(), sol_util_timespec_get_current(), and sol_timeout_common::timeout.
Referenced by sol_timeout_add().
bool sol_mainloop_impl_timeout_del (void * handle)
References sol_timeout_common::remove_me, sol_mainloop_impl_lock(), and sol_mainloop_impl_unlock().
Referenced by sol_timeout_del().
Variable Documentation
struct sol_log_domain _sol_mainloop_log_domain