Soletta: src/lib/io/include/sol-uart.h File Reference
sol-uart.h File Reference
These routines are used for UART access under Solleta.
#include <stdbool.h>
#include <stdint.h>
Functions
struct sol_uart * sol_uart_open (const char *port_name)
void sol_uart_close (struct sol_uart *uart)
bool sol_uart_set_baud_rate (struct sol_uart *uart, uint32_t baud_rate)
uint32_t sol_uart_get_baud_rate (const struct sol_uart *uart)
bool sol_uart_set_parity_bit (struct sol_uart *uart, bool enable, bool odd_paraty)
bool sol_uart_get_parity_bit_enable (struct sol_uart *uart)
bool sol_uart_get_parity_bit_odd (struct sol_uart *uart)
bool sol_uart_set_data_bits_length (struct sol_uart *uart, uint8_t lenght)
uint8_t sol_uart_get_data_bits_length (struct sol_uart *uart)
bool sol_uart_set_stop_bits_length (struct sol_uart *uart, bool two_bits)
uint8_t sol_uart_get_stop_bits_length (struct sol_uart *uart)
bool sol_uart_set_flow_control (struct sol_uart *uart, bool enable)
bool sol_uart_get_flow_control (struct sol_uart *uart)
bool sol_uart_write (struct sol_uart *uart, const char *tx, unsigned int length, void(*tx_cb)(struct sol_uart *uart, int status, void *data), const void *data)
bool sol_uart_set_rx_callback (struct sol_uart *uart, void(*rx_cb)(struct sol_uart *uart, char read_char, void *data), const void *data)
void sol_uart_del_rx_callback (struct sol_uart *uart)
Detailed Description
These routines are used for UART access under Solleta.
Function Documentation
void sol_uart_close (struct sol_uart * uart)
References sol_uart::async, uart_write_data::buffer, uart_write_data::cb, sol_uart::fd, sol_uart::handler, sol_uart::id, sol_uart::rx_fd_handler, sol_fd_del(), sol_interrupt_scheduler_uart_stop(), SOL_NULL_CHECK, sol_vector_clear(), SOL_VECTOR_FOREACH_IDX, sol_uart::tx_fd_handler, sol_uart::tx_queue, and uart_write_data::user_data.
Referenced by main().
void sol_uart_del_rx_callback (struct sol_uart * uart)
References sol_uart::async, sol_uart::rx_cb, sol_uart::rx_fd_handler, sol_uart::rx_user_data, sol_fd_del(), and SOL_NULL_CHECK.
Referenced by main().
uint32_t sol_uart_get_baud_rate (const struct sol_uart * uart)
References sol_uart::baud_rate, sol_uart::fd, SOL_ERR, and SOL_NULL_CHECK.
uint8_t sol_uart_get_data_bits_length (struct sol_uart * uart)
References SOL_NULL_CHECK.
bool sol_uart_get_flow_control (struct sol_uart * uart)
References SOL_NULL_CHECK.
bool sol_uart_get_parity_bit_enable (struct sol_uart * uart)
References SOL_NULL_CHECK.
bool sol_uart_get_parity_bit_odd (struct sol_uart * uart)
References SOL_NULL_CHECK.
uint8_t sol_uart_get_stop_bits_length (struct sol_uart * uart)
References SOL_NULL_CHECK.
struct sol_uart* sol_uart_open (const char * port_name)
References sol_uart::async, sol_uart::baud_rate, sol_uart::fd, sol_uart::id, SOL_ERR, SOL_INT_CHECK, SOL_LOG_INTERNAL_INIT_ONCE, SOL_NULL_CHECK, sol_vector_init(), and sol_uart::tx_queue.
Referenced by main().
bool sol_uart_set_baud_rate (struct sol_uart * uart, uint32_t baud_rate)
References sol_uart::baud_rate, sol_uart::fd, SOL_ERR, and SOL_NULL_CHECK.
Referenced by main().
bool sol_uart_set_data_bits_length (struct sol_uart * uart, uint8_t lenght)
References sol_uart::fd, REG_SET, SOL_ERR, SOL_INT_CHECK, and SOL_NULL_CHECK.
Referenced by main().
bool sol_uart_set_flow_control (struct sol_uart * uart, bool enable)
References sol_uart::fd, REG_SET, SOL_ERR, and SOL_NULL_CHECK.
bool sol_uart_set_parity_bit (struct sol_uart * uart, bool enable, bool odd_paraty)
References sol_uart::fd, REG_SET, SOL_ERR, and SOL_NULL_CHECK.
bool sol_uart_set_rx_callback (struct sol_uart * uart, void(*)(struct sol_uart *uart, char read_char, void *data) rx_cb, const void * data)
Set a callback to be called every time a character is received on UART.
References sol_uart::async, sol_uart::fd, sol_uart::rx_cb, sol_uart::rx_fd_handler, sol_uart::rx_user_data, SOL_EXP_CHECK, sol_fd_add(), and SOL_NULL_CHECK.
Referenced by main().
bool sol_uart_set_stop_bits_length (struct sol_uart * uart, bool two_bits)
References sol_uart::fd, REG_SET, SOL_ERR, and SOL_NULL_CHECK.
bool sol_uart_write (struct sol_uart * uart, const char * tx, unsigned int length, void(*)(struct sol_uart *uart, int status, void *data) tx_cb, const void * data)
Write X characters on UART without block the execution, when the transmission finish the callback will be called.
References sol_uart::async, uart_write_data::buffer, uart_write_data::cb, sol_uart::fd, sol_uart::id, uart_write_data::index, sol_vector::len, uart_write_data::length, sol_fd_add(), sol_fd_del(), SOL_FD_FLAGS_OUT, SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, sol_vector_append(), sol_vector_del(), sol_uart::tx_fd_handler, sol_uart::tx_queue, uart_write_data::uart, and uart_write_data::user_data.
Referenced by main().