Soletta: src/lib/common/sol-pin-mux.c File Reference
sol-pin-mux.c File Reference
#include <errno.h>
#include <dlfcn.h>
#include <limits.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include "sol-log-internal.h"
#include "sol-util.h"
#include "sol-pin-mux.h"
#include "sol-pin-mux-modules.h"
#include "sol-pin-mux-builtins-gen.h"
#include "sol-platform.h"
Macros
#define BASE "/sys/class/gpio"
#define GPIO_DRIVE_HIZ 3
#define GPIO_DRIVE_PULLDOWN 1
#define GPIO_DRIVE_PULLUP 0
#define GPIO_DRIVE_STRONG 2
Functions
SOL_LOG_INTERNAL_DECLARE (_sol_pin_mux_log_domain,"pin-mux")
int sol_pin_mux_init (void)
SOL_API bool sol_pin_mux_select_mux (const char *_board)
SOL_API int sol_pin_mux_setup_aio (const int device, const int pin)
SOL_API int sol_pin_mux_setup_gpio (const int pin, const enum sol_gpio_direction dir)
SOL_API int sol_pin_mux_setup_i2c (const uint8_t bus)
SOL_API int sol_pin_mux_setup_pwm (const int device, const int channel)
void sol_pin_mux_shutdown (void)
Macro Definition Documentation
#define BASE "/sys/class/gpio"
#define GPIO_DRIVE_HIZ 3
#define GPIO_DRIVE_PULLDOWN 1
#define GPIO_DRIVE_PULLUP 0
#define GPIO_DRIVE_STRONG 2
Function Documentation
SOL_LOG_INTERNAL_DECLARE (_sol_pin_mux_log_domain , "pin-mux")
int sol_pin_mux_init (void)
References SOL_LOG_DOMAIN, sol_log_domain_init_level(), sol_pin_mux_select_mux(), sol_platform_get_name(), and SOL_WRN.
Referenced by sol_init().
SOL_API bool sol_pin_mux_select_mux (const char * board)
Select Pin Multiplexer instructions of a given board.
Searches(and activate if found) for pin multiplexing instructions of the given board. Built-in Pin Multiplexers have priority over modules.
Parameters
board The board name being used
Returns
'true' on success, 'false' otherwise.
References sol_pin_mux::plat_name, and streq.
Referenced by sol_pin_mux_init().
SOL_API int sol_pin_mux_setup_aio (const int device, const int pin)
Setup the given pin to operate as Analog I/O.
If a pin multiplexer is loaded (from a successfully call to sol_pin_mux_select_mux), execute the instructions needed to configure 'device'/'pin' pair to operate as Analog I/O.
Parameters
device the aio device number.
pin the aio pin number.
Returns
'0' on success, error code (always negative) otherwise.
References sol_pin_mux::aio, sol_pin_mux::controllers, sol_pin_mux_controller::len, sol_pin_mux::len, sol_pin_mux_controller::recipe, SOL_PIN_MODE_ANALOG, and SOL_WRN.
SOL_API int sol_pin_mux_setup_gpio (const int pin, const enum sol_gpio_direction dir)
Setup the given pin to operate as GPIO in the given direction (in or out).
If a pin multiplexer is loaded (from a successfully call to sol_pin_mux_select_mux), execute the instructions needed to configure 'pin' to operate as GPIO in direction 'dir'.
Parameters
pin the gpio pin number.
dir direction (in or out) that the pin should operate.
Returns
'0' on success, error code (always negative) otherwise.
References sol_pin_mux::gpio, sol_pin_mux_controller::len, sol_pin_mux_controller::recipe, SOL_GPIO_DIR_OUT, SOL_PIN_MODE_GPIO_INPUT_PULLUP, SOL_PIN_MODE_GPIO_OUTPUT, and SOL_WRN.
Referenced by sol_gpio_open().
SOL_API int sol_pin_mux_setup_i2c (const uint8_t bus)
Setup the pins used of the given i2c bus number to operate in I2C mode.
If a pin multiplexer is loaded (from a successfully call to sol_pin_mux_select_mux), execute the instructions needed to configure the pins used by the given i2c bus to operate in I2C mode.
Parameters
bus the i2c bus number.
Returns
'0' on success, error code (always negative) otherwise.
References sol_pin_mux::i2c, sol_pin_mux::len, sol_pin_mux::recipe, and SOL_PIN_MODE_I2C.
Referenced by sol_i2c_open().
SOL_API int sol_pin_mux_setup_pwm (const int device, const int channel)
Setup the given pin to operate as PWM.
If a pin multiplexer is loaded (from a successfully call to sol_pin_mux_select_mux), execute the instructions needed to configure 'device'/'channel' pair to operate as PWM.
Parameters
device the pwm device number.
channel the channel number on device.
Returns
'0' on success, error code (always negative) otherwise.
References sol_pin_mux::controllers, sol_pin_mux_controller::len, sol_pin_mux::len, sol_pin_mux::pwm, sol_pin_mux_controller::recipe, SOL_PIN_MODE_PWM, and SOL_WRN.
Referenced by sol_pwm_open().
void sol_pin_mux_shutdown (void)
Referenced by sol_init(), and sol_shutdown().