Soletta: src/lib/datatypes/include/sol-vector.h File Reference
sol-vector.h File Reference
These are routines that Solleta provides for its vector implementation.
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
Data Structures
struct sol_ptr_vector
struct sol_vector
#define SOL_VECTOR_INIT(TYPE) { NULL, 0, sizeof(TYPE) }
#define SOL_VECTOR_FOREACH_IDX(vector, itrvar, idx)
#define SOL_VECTOR_FOREACH_REVERSE_IDX(vector, itrvar, idx)
#define SOL_PTR_VECTOR_INIT { { NULL, 0, sizeof(void *) } }
#define SOL_PTR_VECTOR_FOREACH_IDX(vector, itrvar, idx)
#define SOL_PTR_VECTOR_FOREACH_REVERSE_IDX(vector, itrvar, idx)
void sol_vector_init (struct sol_vector *v, uint16_t elem_size)
void * sol_vector_append (struct sol_vector *v)
int sol_vector_del (struct sol_vector *v, uint16_t i)
void sol_vector_clear (struct sol_vector *v)
int sol_ptr_vector_append (struct sol_ptr_vector *pv, void *ptr)
int sol_ptr_vector_set (struct sol_ptr_vector *pv, uint16_t i, void *ptr)
int sol_ptr_vector_insert_sorted (struct sol_ptr_vector *pv, void *ptr, int(*compare_cb)(const void *data1, const void *data2))
Detailed Description
These are routines that Solleta provides for its vector implementation.
Macro Definition Documentation
#define SOL_PTR_VECTOR_FOREACH_IDX (vector, itrvar, idx)
Value:
for (idx = 0; \
        idx < (vector)->base.len && \
        ((itrvar = *(((void **)(vector)->base.data) + idx)), true); \
        idx++)
Referenced by main(), sol_arena_del(), sol_bus_close(), sol_bus_unmap_cached_properties(), sol_coap_packet_send_notification(), sol_flow_builder_del(), sol_mainloop_common_idler_first(), sol_mainloop_common_idler_process(), sol_mainloop_common_shutdown(), sol_mainloop_common_timeout_first(), sol_mainloop_impl_shutdown(), sol_platform_impl_del_service_monitor(), and sol_platform_linux_fork_run_stop().
#define SOL_PTR_VECTOR_FOREACH_REVERSE_IDX (vector, itrvar, idx)
Value:
for (idx = (vector)->base.len - 1; \
        idx != ((typeof(idx)) - 1) && \
        (itrvar = *(((void **)(vector)->base.data) + idx), true); \
        idx--)
Referenced by sol_flow_parser_del().
#define SOL_PTR_VECTOR_INIT { { NULL, 0, sizeof(void *) } }
#define SOL_VECTOR_FOREACH_IDX (vector, itrvar, idx)
Value:
for (idx = 0;                                                       \
        idx < (vector)->len && (itrvar = sol_vector_get((vector), idx), true); \
        idx++)
Referenced by main(), process_subprocess_close(), sol_coap_server_new(), sol_fbp_graph_add_conn(), sol_fbp_graph_add_exported_in_port(), sol_fbp_graph_add_exported_out_port(), sol_fbp_graph_add_in_port(), sol_fbp_graph_add_meta(), sol_fbp_graph_add_node(), sol_fbp_graph_add_out_port(), sol_fbp_graph_declare(), sol_fbp_graph_fini(), sol_fbp_graph_option(), sol_flow_builder_add_node(), sol_flow_builder_del(), sol_network_shutdown(), sol_network_unsubscribe_events(), sol_oic_server_get_definition(), sol_uart_close(), type_store_add_type(), type_store_del(), type_store_find(), and type_store_print().
#define SOL_VECTOR_FOREACH_REVERSE_IDX (vector, itrvar, idx)
Value:
for (idx = (vector)->len - 1;                                       \
        idx != ((typeof(idx)) - 1) && (itrvar = sol_vector_get((vector), idx), true); \
        idx--)
Referenced by sol_network_shutdown(), and sol_oic_server_unregister_definition().
#define SOL_VECTOR_INIT (TYPE) { NULL, 0, sizeof(TYPE) }
Referenced by sol_util_str_split().
Function Documentation
int sol_ptr_vector_append (struct sol_ptr_vector * pv, void * ptr)
References sol_ptr_vector::base, and sol_vector_append().
Referenced by sol_arena_slice_dup_str_n(), sol_arena_slice_sprintf(), sol_arena_strndup(), sol_bus_map_cached_properties(), sol_coap_send_packet_with_reply(), sol_flow_parse_buffer(), sol_mainloop_impl_child_watch_add(), sol_mainloop_impl_fd_add(), sol_mainloop_impl_idle_add(), sol_platform_impl_add_service_monitor(), sol_platform_linux_fork_run(), and sol_ptr_vector_insert_sorted().
int sol_ptr_vector_insert_sorted (struct sol_ptr_vector * pv, void * ptr, int(*)(const void *data1, const void *data2) compare_cb)
References sol_ptr_vector::base, sol_vector::len, and sol_ptr_vector_append().
Referenced by sol_mainloop_common_timeout_process(), and sol_mainloop_impl_timeout_add().
int sol_ptr_vector_set (struct sol_ptr_vector * pv, uint16_t i, void * ptr)
References sol_ptr_vector::base.
void* sol_vector_append (struct sol_vector * v)
References sol_vector::data, sol_vector::elem_size, and sol_vector::len.
Referenced by float_generator_open(), float_validator_open(), int_generator_open(), process_subprocess_in_process(), sol_coap_server_register_resource(), sol_fbp_graph_add_conn(), sol_fbp_graph_add_exported_in_port(), sol_fbp_graph_add_exported_out_port(), sol_fbp_graph_add_in_port(), sol_fbp_graph_add_meta(), sol_fbp_graph_add_node(), sol_fbp_graph_add_out_port(), sol_fbp_graph_declare(), sol_fbp_graph_option(), sol_flow_builder_add_node(), sol_flow_builder_export_option(), sol_network_init(), sol_network_subscribe_events(), sol_oic_device_definition_register_resource_type(), sol_oic_server_register_definition(), sol_ptr_vector_append(), sol_uart_write(), type_store_add_type(), and type_store_read_from_json().
void sol_vector_clear (struct sol_vector * v)
References sol_vector::data, and sol_vector::len.
Referenced by float_generator_close(), float_generator_open(), float_validator_close(), float_validator_open(), int_generator_close(), int_generator_open(), int_validator_close(), main(), process_subprocess_close(), sol_fbp_graph_fini(), sol_flow_builder_del(), sol_monitors_clear(), sol_network_shutdown(), sol_oic_resource_unref(), sol_oic_server_release(), sol_uart_close(), sol_util_str_split(), type_store_add_type(), and type_store_del().
int sol_vector_del (struct sol_vector * v, uint16_t i)
References sol_vector::data, sol_vector::elem_size, and sol_vector::len.
Referenced by process_subprocess_in_process(), sol_flow_builder_export_option(), sol_network_shutdown(), sol_network_unsubscribe_events(), sol_oic_device_definition_register_resource_type(), sol_oic_server_register_definition(), sol_oic_server_unregister_definition(), sol_uart_write(), type_store_add_type(), and type_store_read_from_json().
void sol_vector_init (struct sol_vector * v, uint16_t elem_size)
References sol_vector::data, sol_vector::elem_size, and sol_vector::len.
Referenced by float_generator_open(), float_validator_open(), int_generator_open(), main(), process_subprocess_open(), sol_coap_server_new(), sol_fbp_graph_add_node(), sol_fbp_graph_init(), sol_flow_builder_add_node(), sol_monitors_init_custom(), sol_network_init(), sol_oic_server_init(), sol_oic_server_register_definition(), sol_uart_open(), type_store_add_type(), type_store_new(), and unix_socket_server_new().