Soletta: src/lib/io/sol-pwm-common.c File Reference
sol-pwm-common.c File Reference
#include <stdlib.h>
#include "sol-log-internal.h"
#include "sol-pwm.h"
Macros
#define SOL_LOG_DOMAIN &_log_domain
Functions
SOL_LOG_INTERNAL_DECLARE_STATIC (_log_domain,"pwm")
SOL_API struct sol_pwm * sol_pwm_open (int device, int channel, const struct sol_pwm_config *config)
Macro Definition Documentation
#define SOL_LOG_DOMAIN &_log_domain
Function Documentation
SOL_LOG_INTERNAL_DECLARE_STATIC (_log_domain , "pwm")
SOL_API struct sol_pwm* sol_pwm_open (int device, int channel, const struct sol_pwm_config * config)
References SOL_LOG_INTERNAL_INIT_ONCE, sol_pin_mux_setup_pwm(), sol_pwm_close(), sol_pwm_open_raw(), and SOL_WRN.