Soletta: src/lib/datatypes/sol-arena.c File Reference
sol-arena.c File Reference
#include <errno.h>
#include <stdio.h>
#include "sol-log.h"
#include "sol-arena.h"
#include "sol-util.h"
Data Structures
struct sol_arena
Functions
SOL_API void sol_arena_del (struct sol_arena *arena)
SOL_API struct sol_arena * sol_arena_new (void)
SOL_API int sol_arena_slice_dup (struct sol_arena *arena, struct sol_str_slice *dst, struct sol_str_slice slice)
SOL_API int sol_arena_slice_dup_str (struct sol_arena *arena, struct sol_str_slice *dst, const char *str)
SOL_API int sol_arena_slice_dup_str_n (struct sol_arena *arena, struct sol_str_slice *dst, const char *str, size_t n)
SOL_API int sol_arena_slice_sprintf (struct sol_arena *arena, struct sol_str_slice *dst, const char *fmt,...)
SOL_API char * sol_arena_strdup (struct sol_arena *arena, const char *str)
SOL_API char * sol_arena_strdup_slice (struct sol_arena *arena, const struct sol_str_slice slice)
SOL_API char * sol_arena_strndup (struct sol_arena *arena, const char *str, size_t n)
Function Documentation
SOL_API void sol_arena_del (struct sol_arena * arena)
References SOL_NULL_CHECK, SOL_PTR_VECTOR_FOREACH_IDX, and sol_arena::str_vector.
Referenced by main(), sol_fbp_graph_fini(), and sol_flow_builder_del().
SOL_API struct sol_arena* sol_arena_new (void)
References SOL_NULL_CHECK, and sol_arena::str_vector.
Referenced by main(), and sol_fbp_graph_init().
SOL_API int sol_arena_slice_dup (struct sol_arena * arena, struct sol_str_slice * dst, struct sol_str_slice slice)
References sol_str_slice::data, sol_str_slice::len, and sol_arena_slice_dup_str_n().
SOL_API int sol_arena_slice_dup_str (struct sol_arena * arena, struct sol_str_slice * dst, const char * str)
References sol_arena_slice_dup_str_n(), and SOL_NULL_CHECK.
SOL_API int sol_arena_slice_dup_str_n (struct sol_arena * arena, struct sol_str_slice * dst, const char * str, size_t n)
References sol_str_slice::data, sol_str_slice::len, SOL_INT_CHECK, SOL_NULL_CHECK, sol_ptr_vector_append(), and sol_arena::str_vector.
Referenced by sol_arena_slice_dup(), and sol_arena_slice_dup_str().
SOL_API int sol_arena_slice_sprintf (struct sol_arena * arena, struct sol_str_slice * dst, const char * fmt, ...)
References sol_str_slice::data, sol_str_slice::len, SOL_INT_CHECK, sol_ptr_vector_append(), and sol_arena::str_vector.
Referenced by sol_fbp_graph_add_node().
SOL_API char* sol_arena_strdup (struct sol_arena * arena, const char * str)
References sol_arena_strndup(), and SOL_NULL_CHECK.
Referenced by sol_flow_builder_add_node(), sol_flow_builder_export_option(), and sol_flow_builder_set_type_description().
SOL_API char* sol_arena_strdup_slice (struct sol_arena * arena, const struct sol_str_slice slice)
References sol_str_slice::data, sol_str_slice::len, and sol_arena_strndup().
SOL_API char* sol_arena_strndup (struct sol_arena * arena, const char * str, size_t n)
References SOL_INT_CHECK, SOL_NULL_CHECK, sol_ptr_vector_append(), and sol_arena::str_vector.
Referenced by sol_arena_strdup(), and sol_arena_strdup_slice().