Soletta: sol_flow_node_type Struct Reference
sol_flow_node_type Struct Reference
Flow Based Programming
#include <sol-flow.h>
Data Fields
uint16_t api_version
void(* close)(struct sol_flow_node *node, void *data)
uint16_t data_size
void(* dispose_type)(struct sol_flow_node_type *type)
uint16_t flags
void(* free_options)(const struct sol_flow_node_type *type, struct sol_flow_node_options *opts)
const struct
sol_flow_port_type_in *(* get_port_in)(const struct sol_flow_node_type *type, uint16_t port)
const struct
sol_flow_port_type_out *(* get_port_out)(const struct sol_flow_node_type *type, uint16_t port)
void(* get_ports_counts)(const struct sol_flow_node_type *type, uint16_t *ports_in_count, uint16_t *ports_out_count)
void(* init_type)(void)
struct sol_flow_node_options *(* new_options)(const struct sol_flow_node_type *type, const struct sol_flow_node_options *copy_from)
int(* open)(struct sol_flow_node *node, void *data, const struct sol_flow_node_options *options)
const void * type_data
Field Documentation
uint16_t sol_flow_node_type::api_version
must match SOL_FLOW_NODE_TYPE_API_VERSION at runtime
void(* sol_flow_node_type::close)(struct sol_flow_node *node, void *data)
member function to delete the node
Referenced by sol_flow_node_fini().
uint16_t sol_flow_node_type::data_size
size of the whole sol_flow_node_type derivate
Referenced by sol_flow_node_fini(), sol_flow_node_init(), and sol_flow_node_new().
void(* sol_flow_node_type::dispose_type)(struct sol_flow_node_type *type)
Called as part of sol_flow_node_type_del() to dispose any extra resources associated with the node type.
Referenced by sol_flow_node_type_del().
uint16_t sol_flow_node_type::flags
See Also
sol_flow_node_type_flags
void(* sol_flow_node_type::free_options)(const struct sol_flow_node_type *type, struct sol_flow_node_options *opts)
member function to delete the node options
Referenced by sol_flow_builder_get_node_type(), sol_flow_node_free_options(), sol_flow_node_options_del(), and sol_flow_node_options_new_from_strv().
const struct sol_flow_port_type_in*(* sol_flow_node_type::get_port_in)(const struct sol_flow_node_type *type, uint16_t port)
member function to get the array of the node's input ports
Referenced by sol_flow_node_type_get_port_in().
const struct sol_flow_port_type_out*(* sol_flow_node_type::get_port_out)(const struct sol_flow_node_type *type, uint16_t port)
member function to get the array of the node's output ports
Referenced by sol_flow_node_type_get_port_out().
void(* sol_flow_node_type::get_ports_counts)(const struct sol_flow_node_type *type, uint16_t *ports_in_count, uint16_t *ports_out_count)
member function to get the number of input/output ports of the node
Referenced by sol_flow_builder_connect_by_index(), and sol_flow_node_init().
void(* sol_flow_node_type::init_type)(void)
member function called at least once for each node type, that allows initialization of node-specific data (packet types, logging domains, etc)
Referenced by sol_flow_node_init(), and sol_flow_node_options_new_from_strv().
struct sol_flow_node_options*(* sol_flow_node_type::new_options)(const struct sol_flow_node_type *type, const struct sol_flow_node_options *copy_from)
member function to instantiate new options for the node. If copy_from is not NULL, its members will be copied into the new returned struct
Referenced by sol_flow_builder_get_node_type(), sol_flow_node_get_options(), sol_flow_node_options_copy(), sol_flow_node_options_new_from_strv(), and sol_flow_resolve().
int(* sol_flow_node_type::open)(struct sol_flow_node *node, void *data, const struct sol_flow_node_options *options)
member function to instantiate the node
Referenced by sol_flow_node_init().
const void* sol_flow_node_type::type_data
pointer to per-type user data
Referenced by sol_flow_builder_get_node_type().
The documentation for this struct was generated from the following file:
src/lib/flow/include/sol-flow.h