Soletta: sol_flow_packet_type Struct Reference
sol_flow_packet_type Struct Reference
#include <sol-flow-packet.h>
Data Fields
uint16_t api_version
uint16_t data_size
void(* dispose)(const struct sol_flow_packet_type *packet_type, void *mem)
int(* get)(const struct sol_flow_packet_type *packet_type, const void *mem, void *output)
struct sol_flow_packet *(* get_constant)(const struct sol_flow_packet_type *packet_type, const void *value)
int(* init)(const struct sol_flow_packet_type *packet_type, void *mem, const void *input)
const char * name
Field Documentation
uint16_t sol_flow_packet_type::api_version
Referenced by sol_flow_packet_new().
uint16_t sol_flow_packet_type::data_size
void(* sol_flow_packet_type::dispose)(const struct sol_flow_packet_type *packet_type, void *mem)
Referenced by sol_flow_packet_del().
int(* sol_flow_packet_type::get)(const struct sol_flow_packet_type *packet_type, const void *mem, void *output)
Referenced by sol_flow_packet_get().
struct sol_flow_packet*(* sol_flow_packet_type::get_constant)(const struct sol_flow_packet_type *packet_type, const void *value)
Referenced by sol_flow_packet_del(), and sol_flow_packet_new().
int(* sol_flow_packet_type::init)(const struct sol_flow_packet_type *packet_type, void *mem, const void *input)
const char* sol_flow_packet_type::name
Referenced by sol_flow_packet_new().
The documentation for this struct was generated from the following file:
src/lib/flow/include/sol-flow-packet.h