Soletta: unix_socket Struct Reference
unix_socket Struct Reference
Data Fields
const void * data
void(* data_read_cb)(void *data, int fd)
void(* del)(struct unix_socket *un_socket)
int sock
struct sol_fd * watch
int(* write)(struct unix_socket *un_socket, const void *data, size_t count)
Field Documentation
const void* unix_socket::data
Referenced by unix_socket_client_new(), and unix_socket_server_new().
void(* unix_socket::data_read_cb)(void *data, int fd)
Referenced by unix_socket_client_new(), and unix_socket_server_new().
void(* unix_socket::del)(struct unix_socket *un_socket)
Referenced by unix_socket_client_new(), unix_socket_del(), and unix_socket_server_new().
int unix_socket::sock
Referenced by unix_socket_client_new(), unix_socket_server_new(), and unix_socket_write().
struct sol_fd* unix_socket::watch
Referenced by unix_socket_client_new(), and unix_socket_server_new().
int(* unix_socket::write)(struct unix_socket *un_socket, const void *data, size_t count)
Referenced by unix_socket_client_new(), unix_socket_server_new(), and unix_socket_write().
The documentation for this struct was generated from the following file:
src/modules/flow/unix-socket/unix-socket-impl.c