Soletta: sol_flow_node_container_type Struct Reference
sol_flow_node_container_type Struct Reference
Flow Based Programming
#include <sol-flow.h>
Data Fields
void(* add)(struct sol_flow_node *container, struct sol_flow_node *node)
struct sol_flow_node_type base
void(* remove)(struct sol_flow_node *container, struct sol_flow_node *node)
int(* send)(struct sol_flow_node *container, struct sol_flow_node *source_node, uint16_t source_out_port_idx, struct sol_flow_packet *packet)
Field Documentation
void(* sol_flow_node_container_type::add)(struct sol_flow_node *container, struct sol_flow_node *node)
member function that, if not NULL, is issued when child nodes of of an instance of this type are created
Referenced by sol_flow_node_init().
struct sol_flow_node_type sol_flow_node_container_type::base
base part of the container node
Referenced by sol_flow_static_new(), and sol_flow_static_new_type().
void(* sol_flow_node_container_type::remove)(struct sol_flow_node *container, struct sol_flow_node *node)
member function that, if not NULL, is issued when child nodes of an insance of this type this are deleted
Referenced by sol_flow_node_fini(), and sol_flow_node_init().
int(* sol_flow_node_container_type::send)(struct sol_flow_node *container, struct sol_flow_node *source_node, uint16_t source_out_port_idx, struct sol_flow_packet *packet)
member function issued when a child node sends packets to its output ports
Referenced by sol_flow_send_packet().
The documentation for this struct was generated from the following file:
src/lib/flow/include/sol-flow.h