Soletta: src/bin/sol-fbp-generator/type-store.h File Reference
type-store.h File Reference
#include "sol-json.h"
#include "sol-str-slice.h"
#include "sol-vector.h"
Data Structures
struct option_description
struct option_direction_vector_value
struct option_range_value
struct option_rgb_value
struct port_description
struct type_description
Enumerations
enum option_value_type {
OPTION_VALUE_TYPE_NONE = 0, OPTION_VALUE_TYPE_UNPARSED_JSON, OPTION_VALUE_TYPE_STRING, OPTION_VALUE_TYPE_RANGE,
OPTION_VALUE_TYPE_RGB, OPTION_VALUE_TYPE_DIRECTION_VECTOR
}
Functions
bool type_store_add_type (struct type_store *store, const struct type_description *type)
void type_store_del (struct type_store *store)
struct type_description * type_store_find (struct type_store *store, const char *name)
struct type_store * type_store_new (void)
void type_store_print (struct type_store *store)
bool type_store_read_from_json (struct type_store *store, struct sol_str_slice input)
Enumeration Type Documentation
enum option_value_type
Enumerator
OPTION_VALUE_TYPE_NONE
OPTION_VALUE_TYPE_UNPARSED_JSON
OPTION_VALUE_TYPE_STRING
OPTION_VALUE_TYPE_RANGE
OPTION_VALUE_TYPE_RGB
OPTION_VALUE_TYPE_DIRECTION_VECTOR
Function Documentation
bool type_store_add_type (struct type_store * store, const struct type_description * type)
References port_description::array_size, port_description::base_port_idx, port_description::data_type, option_description::data_type, option_description::default_value, option_description::default_value_type, option_description::direction_vector, type_description::in_ports, sol_vector::len, port_description::name, option_description::name, type_description::name, OPTION_VALUE_TYPE_DIRECTION_VECTOR, OPTION_VALUE_TYPE_NONE, OPTION_VALUE_TYPE_RANGE, OPTION_VALUE_TYPE_RGB, OPTION_VALUE_TYPE_STRING, OPTION_VALUE_TYPE_UNPARSED_JSON, type_description::options, type_description::options_symbol, type_description::out_ports, option_description::range, option_description::rgb, SOL_NULL_CHECK, SOL_NULL_CHECK_GOTO, sol_vector_append(), sol_vector_clear(), sol_vector_del(), SOL_VECTOR_FOREACH_IDX, sol_vector_init(), option_description::string, type_description::symbol, option_description::token, and type_store::types.
void type_store_del (struct type_store * store)
References sol_vector_clear(), SOL_VECTOR_FOREACH_IDX, and type_store::types.
Referenced by main().
struct type_description* type_store_find (struct type_store * store, const char * name)
References type_description::name, SOL_VECTOR_FOREACH_IDX, streq, and type_store::types.
struct type_store* type_store_new (void)
References sol_vector_init(), and type_store::types.
Referenced by main().
void type_store_print (struct type_store * store)
References SOL_VECTOR_FOREACH_IDX, and type_store::types.
bool type_store_read_from_json (struct type_store * store, struct sol_str_slice input)
References sol_vector::len, SOL_JSON_TYPE_ARRAY_END, SOL_JSON_TYPE_ARRAY_START, SOL_JSON_TYPE_ELEMENT_SEP, SOL_JSON_TYPE_OBJECT_END, SOL_JSON_TYPE_OBJECT_START, SOL_JSON_TYPE_PAIR_SEP, SOL_JSON_TYPE_STRING, sol_vector_append(), sol_vector_del(), and type_store::types.